import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import type {PracticeOptionId,PracticePack} from '@edu/contracts';
import {INTERNATIONAL_MATHEMATICS_SLIDES as slides,INTERNATIONAL_MATHEMATICS_LESSONS as lessons,INTERNATIONAL_MATHEMATICS_V1_PAGE_MAP as migration,INTERNATIONAL_MATHEMATICS_DECK_ID as deckId,INTERNATIONAL_MATHEMATICS_VERSION_ID as versionId} from '@edu/course-content/international-mathematics';
// These virtual modules contain an explicit public whitelist, never the authoring bank.
// @ts-expect-error generated public practice module
import packs from 'virtual:public-practice';
import {InternationalMathematicsStage} from '../../apps/teacher-web/src/features/international-mathematics/InternationalMathematicsStage';
import {PracticeSheet} from '../../apps/teacher-web/src/features/ranked-practice/PracticeSheet';
import '../international-mathematics-viewer/style.css';
import './style.css';
const publicPacks=packs as PracticePack[];
const params=new URLSearchParams(location.search),requestedLesson=Math.max(1,Math.min(16,Number(params.get('lesson')??1)));
function restore(){
 const explicit=Number(params.get('page'));if(Number.isInteger(explicit)&&explicit>0)return Math.min(slides.length-1,explicit-1);
 if(params.has('lesson'))return lessons[requestedLesson-1]!.slideStart-1;
 try{const saved=JSON.parse(localStorage.getItem('international-mathematics-reading')??'null');if(saved){const key=saved.slideKey??(saved.version==='release-international-mathematics-jacques-v1'?migration.find(m=>m.v1Index===saved.index)?.slideKey:undefined);const match=slides.findIndex(s=>s.slideKey===key);if(match>=0)return match;if(saved.version===versionId&&saved.index>=1&&saved.index<=slides.length)return saved.index-1;}}catch{/* no saved position */}
 return 0;
}
function App(){
 const [index,setIndex]=useState(restore),[view,setView]=useState(params.get('view')==='practice'?'practice':'slides'),[optional,setOptional]=useState(true),[practiceLesson,setPracticeLesson]=useState(requestedLesson),[choices,setChoices]=useState<Record<string,PracticeOptionId>>({}),[storageError,setStorageError]=useState('');
 const spec=slides[index]!,pack=publicPacks[practiceLesson-1]!,choiceKey=`ranked-practice-offline:${pack.id}:${pack.version}`;
 useEffect(()=>{try{const raw=JSON.parse(localStorage.getItem(choiceKey)??'{}');setChoices(Object.fromEntries(Object.entries(raw).filter(([id,o])=>pack.questions.some(q=>q.id===id)&&['A','B','C','D'].includes(String(o)))) as Record<string,PracticeOptionId>);setStorageError('');}catch{setChoices({});setStorageError('Local storage is unavailable. Keep this page open to retain your choices.');}},[choiceKey]);
 useEffect(()=>{try{localStorage.setItem('international-mathematics-reading',JSON.stringify({version:versionId,slideKey:spec.slideKey,index:index+1}));}catch{/* reading still works */}},[index]);
 const move=(step:number)=>{let n=index+step;while(n>=0&&n<slides.length&&!optional&&slides[n]?.optionalChallenge)n+=step;if(n>=0&&n<slides.length)setIndex(n);};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(view!=='slides'||['INPUT','SELECT','TEXTAREA','BUTTON'].includes((e.target as HTMLElement).tagName))return;if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1);};addEventListener('keydown',key);return()=>removeEventListener('keydown',key);},[index,optional,view]);
 function selectLesson(n:number){setPracticeLesson(n);setIndex(lessons[n-1]!.slideStart-1);}
 function choose(id:string,option:PracticeOptionId){setChoices(old=>{const next={...old,[id]:option};try{localStorage.setItem(choiceKey,JSON.stringify(next));setStorageError('');}catch{setStorageError('Your choice is retained until this page closes; local storage is unavailable.');}return next;});}
 const frame={deckId,versionId,slideId:spec.slideKey,index:index+1,total:slides.length,logicalWidth:1600 as const,logicalHeight:1000 as const,aspectRatio:'16:10' as const,title:spec.title,lessonNumber:spec.lesson,lessonTitle:spec.lessonTitle,section:spec.kicker,summary:spec.question??spec.title};
 return <div className={`viewer practice-offline view-${view}`}><nav className="viewer-nav"><strong>CALCULUS / ECONOMICS + BUSINESS</strong><button aria-pressed={view==='slides'} onClick={()=>{setView('slides');setIndex(lessons[practiceLesson-1]!.slideStart-1);}}>Slides</button><button aria-pressed={view==='practice'} onClick={()=>{setPracticeLesson(spec.lesson);setView('practice');}}>Ranked Practice</button><select aria-label="Lesson" value={view==='practice'?practiceLesson:spec.lesson} onChange={e=>selectLesson(Number(e.target.value))}>{lessons.map(l=><option key={l.number} value={l.number}>{String(l.number).padStart(2,'0')} · {l.title}</option>)}</select>
 {view==='slides'&&<><select aria-label="Teaching hour" value={index+1<=(lessons[spec.lesson-1]!.hourRanges?.[0]?.slideEnd??0)?1:2} onChange={e=>setIndex((lessons[spec.lesson-1]!.hourRanges?.[Number(e.target.value)-1]?.slideStart??1)-1)}>{lessons[spec.lesson-1]!.hourRanges?.map(h=><option key={h.number} value={h.number}>Hour {h.number}</option>)}</select><button disabled={index===0} onClick={()=>move(-1)}>Previous</button><span>{spec.localIndex} / {spec.localTotal}</span><button disabled={index===slides.length-1} onClick={()=>move(1)}>Next</button><label><input type="checkbox" checked={optional} onChange={e=>setOptional(e.target.checked)}/> Optional slides</label></>}
 </nav>{view==='slides'?<main><InternationalMathematicsStage key={spec.slideKey} frame={frame} interaction={null} readOnly={false} playbackMode="offline"/></main>:<main className="offline-practice-main"><section className="ranked-practice"><header className="practice-heading"><span>OFFLINE RANKED PRACTICE</span><h2>Lesson {practiceLesson} · {pack.title}</h2><p>10 single-choice questions · 20 minutes · Rank 4 is optional</p></header><p>Work at your own pace. All questions are available immediately. Choices stay on this device and are never submitted to a live classroom.</p><div className="practice-progress"><strong>Answered {Object.keys(choices).length}/10</strong><span>Saved locally · answers are in the separate teacher book</span></div>{storageError&&<p role="alert">{storageError}</p>}<div className="practice-actions"><a download href={`/documents/lesson-${String(practiceLesson).padStart(2,'0')}-choice-practice.pdf`}>Download worksheet</a><a download href="/documents/combined-choice-workbook.pdf">Combined workbook</a><button onClick={()=>{const blob=new Blob([JSON.stringify({schemaVersion:1,mode:'offline-only',packId:pack.id,packVersion:pack.version,choices},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`lesson-${practiceLesson}-local-choices.json`;a.click();URL.revokeObjectURL(url);}}>Export my local choices</button></div><PracticeSheet pack={pack} choices={choices} locked={false} onChoose={choose}/></section></main>}
 <footer className="viewer-info"><span>1,312 slides · 160 choice questions · English · Jacques 9th ed.</span><a href="/documents/combined-choice-workbook.pdf">Choice workbook</a><a href="/slides/complete-course-student-slides.pdf">Student slides PDF</a></footer></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
