import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.png':'image/png','.svg':'image/svg+xml','.woff2':'font/woff2','.woff':'font/woff','.ttf':'font/ttf','.mp4':'video/mp4','.wav':'audio/wav','.srt':'text/plain; charset=utf-8','.vtt':'text/vtt; charset=utf-8','.pdf':'application/pdf','.md':'text/plain; charset=utf-8'};
let lastRequest=Date.now();
const server=http.createServer((req,res)=>{lastRequest=Date.now();if(req.url==='/__health'){res.writeHead(200,{'Content-Type':'text/plain'});res.end('international-mathematics-ranked-practice-offline-v1');return;}let relative;try{relative=decodeURIComponent(new URL(req.url,'http://localhost').pathname);}catch{res.writeHead(400);res.end();return;}const target=path.resolve(root,'.'+(relative==='/'?'/index.html':relative));if(target!==root&&!target.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}let stat;try{stat=fs.statSync(target);}catch{res.writeHead(404);res.end('File not found');return;}if(!stat.isFile()){res.writeHead(404);res.end();return;}const headers={'Content-Type':types[path.extname(target)]||'application/octet-stream','Accept-Ranges':'bytes','Cache-Control':'no-cache'};let from=0,to=stat.size-1,status=200;const range=req.headers.range;if(range){const match=/^bytes=(\d*)-(\d*)$/.exec(range);if(!match){res.writeHead(416,{'Content-Range':`bytes */${stat.size}`});res.end();return;}if(!match[1])from=Math.max(0,stat.size-Number(match[2]));else from=Number(match[1]);if(match[2]&&match[1])to=Math.min(to,Number(match[2]));if(from>to||from>=stat.size){res.writeHead(416,{'Content-Range':`bytes */${stat.size}`});res.end();return;}status=206;headers['Content-Range']=`bytes ${from}-${to}/${stat.size}`;}headers['Content-Length']=to-from+1;res.writeHead(status,headers);if(req.method==='HEAD'){res.end();return;}fs.createReadStream(target,{start:from,end:to}).pipe(res);});
// A stable origin keeps local choices and slide positions accessible after restart.
const portFile=path.join(root,'.server-port');
let preferred=5195;try{const saved=Number(fs.readFileSync(portFile,'utf8'));if(Number.isInteger(saved)&&saved>=1024&&saved<=65535)preferred=saved;}catch{/* first launch */}
const requested=process.env.IM_OFFLINE_PORT===undefined?preferred:Number(process.env.IM_OFFLINE_PORT);
if(!Number.isInteger(requested)||requested<0||requested>65535)throw Error('Invalid offline port');
server.on('error',error=>{if(error.code==='EADDRINUSE')console.error(`Port ${requested} is busy. Close that service and retry, or set IM_OFFLINE_PORT explicitly. A different port uses separate browser storage.`);else console.error(error.message);process.exitCode=1;});
server.listen(requested,'127.0.0.1',()=>{const port=server.address().port;fs.writeFileSync(portFile,String(port));console.log(`http://127.0.0.1:${port}/`);});
setInterval(()=>{if(Date.now()-lastRequest>3*60*60*1000)server.close(()=>process.exit(0));},60000).unref();
