import type { ReactNode } from 'react';
import { STATISTICAL_ANALYSIS_DATA as D } from '@edu/course-content/statistical-analysis';
export const amber='#b87921',teal='#197f7a',ink='#152e3e',muted='#7c8589';
export const people=D.people,groups=D.groups;
export const fmt=(v:number,d=1)=>v.toFixed(d);
const x=(v:number,max=2600)=>90+v/max*990;
const y=(v:number,max=100)=>420-v/max*340;
export function Plot({children,label,height=520}:{children:ReactNode;label:string;height?:number}) {return <svg role="img" aria-label={label} viewBox={`0 0 1200 ${height}`} className="sa-plot">{children}</svg>;}
export function Axis({max=2600,step=500,label='月消费（元/人/月）',base=420}:{max?:number;step?:number;label?:string;base?:number}) {return <g className="sa-axis"><path d={`M90 ${base}H1080`} />{Array.from({length:Math.floor(max/step)+1},(_,i)=>i*step).map(v=><g key={v}><path d={`M${x(v,max)} ${base}v8`}/><text x={x(v,max)} y={base+37} textAnchor="middle">{v}</text></g>)}<text x="1080" y={base+78} textAnchor="end">{label}</text></g>;}
export function Groups({mode='dots',city,interval=false}:{mode?:'dots'|'box'|'violin'|'means'|'bars';city?:string;interval?:boolean}) {
 const subsets=[true,false].map(m=>people.filter(p=>p.member===m&&(!city||p.city===city)));
 const stats=subsets.map((ps,g)=>{const a=ps.map(p=>p.spend).sort((a,b)=>a-b),n=a.length;const q=(p:number)=>{const i=(n-1)*p,l=Math.floor(i);return a[l]!+(a[Math.min(n-1,l+1)]!-a[l]!)*(i-l);}; const mean=a.reduce((a,b)=>a+b,0)/n; const sd=Math.sqrt(a.reduce((s,v)=>s+(v-mean)**2,0)/(n-1));const ci=(city?D.cells.find(c=>c.city===city&&c.member===(g===0))!:groups[g]!).ci;return {mean,n,sd,ci,se:sd/Math.sqrt(n),q1:q(.25),median:q(.5),q3:q(.75),lo:a.find(v=>v>=q(.25)-1.5*(q(.75)-q(.25)))!,hi:a.filter(v=>v<=q(.75)+1.5*(q(.75)-q(.25))).at(-1)!};});
 return <Plot label={`${city?city+'城 · ':''}会员与非会员${mode}比较`}><Axis/>{subsets.map((ps,g)=>{const c=g===0?amber:teal,cy=150+g*180,s=stats[g]!;
  const kde=Array.from({length:131},(_,i)=>{const v=i*20;return {v,d:ps.reduce((a,p)=>a+Math.exp(-.5*((v-p.spend)/100)**2),0)/(ps.length*100*Math.sqrt(2*Math.PI))};}); const kmax=Math.max(...kde.map(p=>p.d));const path=kde.map((p,i)=>`${i?'L':'M'}${x(p.v)},${cy-p.d/kmax*57}`).join(' ')+[...kde].reverse().map(p=>`L${x(p.v)},${cy+p.d/kmax*57}`).join(' ')+'Z';
  return <g key={g}><text x="90" y={cy-76} fill={c} className="sa-chart-label">{g===0?'会员':'非会员'}{city?` · ${city}城`:''}　n={s.n}</text>
   {mode==='bars'?<rect x={90} y={cy-18} width={x(s.mean)-90} height={36} fill={c}/>:null}
   {mode==='violin'?<path d={path} fill={c} opacity=".28"/>:null}
   {(mode==='dots'||mode==='box')?ps.map((p,i)=><circle key={p.id} cx={x(p.spend)} cy={cy+((i*37)%89-44)} r="3.8" fill={c} opacity={mode==='box'?.22:.58}/>):null}
   {mode==='box'?<g stroke={c} strokeWidth="3" fill="none"><path d={`M${x(s.lo)} ${cy}H${x(s.hi)}M${x(s.lo)} ${cy-20}v40M${x(s.hi)} ${cy-20}v40`}/><rect x={x(s.q1)} y={cy-30} width={x(s.q3)-x(s.q1)} height="60" fill={c} fillOpacity=".13"/><path d={`M${x(s.median)} ${cy-30}v60`}/></g>:null}
   {(mode==='means'||mode==='bars'||interval)?<g><circle cx={x(s.mean)} cy={cy} r="8" fill={c}/>{interval?<path d={`M${x(s.ci[0]!)} ${cy}H${x(s.ci[1]!)}M${x(s.ci[0]!)} ${cy-10}v20M${x(s.ci[1]!)} ${cy-10}v20`} stroke={c} strokeWidth="4"/>:null}<text x={x(s.mean)+20} y={cy-20} fill={c}>{fmt(s.mean)}</text></g>:null}
  </g>;
 })}</Plot>;
}
export function Histogram({bin=200,sample=false}:{bin?:number;sample?:boolean}) {
 const values=sample?D.sampling.means25:people.map(p=>p.spend),max=sample?800:3000,min=sample?200:0;
 const bins=Array.from({length:Math.ceil((max-min)/bin)},(_,i)=>({v:min+i*bin,n:values.filter(v=>v>=min+i*bin&&v<min+(i+1)*bin).length}));
 const ymax=sample?35:180;
 return <Plot label={`直方图，箱宽${bin}，${values.length}个值`}><Axis max={max} step={sample?100:500} label={sample?'样本均值（元）':'月消费（元/人/月）'}/><g className="sa-axis"><path d="M90 80V420"/>{[0,ymax/2,ymax].map(v=><text key={v} x="74" y={y(v,ymax)+8} textAnchor="end">{v}</text>)}<text x="90" y="45">{sample?'抽样次数':'顾客数'}</text></g>{bins.map(b=><rect key={b.v} x={x(b.v,max)} y={y(b.n,ymax)} width={990*bin/max-2} height={420-y(b.n,ymax)} fill={teal} opacity=".85"/> )}</Plot>;
}
export function RawStrip({values=people.map(p=>p.spend),mean=true,reference=false,max=2600}:{values?:number[];mean?:boolean;reference?:boolean;max?:number}) {const avg=values.reduce((s,v)=>s+v,0)/values.length;return <Plot label="原始数值点图"><Axis max={max} step={max===2600?500:200} label={max===2600?'月消费（元/人/月）':'观测值（元）'}/>{values.map((v,i)=><circle key={i} cx={x(v,max)} cy={180+(i*37%170)} r={values.length>100?4:8} fill={teal} opacity=".6"/>)}{reference?<g stroke={amber}><path d={`M${x(500,max)} 80V420`} strokeWidth="3" strokeDasharray="10 8"/><text x={x(500,max)+15} y="80" fill={amber} stroke="none">总体 μ=500</text></g>:null}{mean?<g><path d={`M${x(avg,max)} 100V410`} stroke={ink} strokeWidth="3"/><text x={x(avg,max)+20} y="118">均值 {fmt(avg)}</text></g>:null}</Plot>;}
export function Sampling({large=false,coverage=false,one=false}:{large?:boolean;coverage?:boolean;one?:boolean}) {
 const vals=large?D.sampling.means100:D.sampling.means25;const scale=(v:number)=>100+(v-350)/300*950;
 return <Plot label={coverage?'100次重复抽样构造的95%区间':'重复抽样的样本均值'} height={620}><g className="sa-axis"><path d="M100 550H1050"/>{[350,400,450,500,550,600,650].map(v=><text key={v} x={scale(v)} y="590" textAnchor="middle">{v}</text>)}</g><path d={`M${scale(500)} 30V550`} stroke={amber} strokeWidth="3" strokeDasharray="8 6"/><text x={scale(500)+14} y="28" fill={amber}>固定总体均值 500元</text>{coverage?D.sampling.intervals.slice(0,one?1:100).map((v,i)=><g key={i} stroke={v.lo<=500&&v.hi>=500?teal:'#bc5446'}><path d={`M${scale(v.lo)} ${55+i*4.7}H${scale(v.hi)}`} strokeWidth="2"/><circle cx={scale(v.mean)} cy={55+i*4.7} r="2.8" fill="currentColor"/></g>):vals.map((v,i)=><circle key={i} cx={scale(v)} cy={100+((i*23)%400)} r="5" fill={teal} opacity=".65"/>)}</Plot>;
}
export function Difference({illustration=false,city=false}:{illustration?:boolean;city?:boolean}) {
 const sx=(v:number)=>150+(v+200)/500*880;
 const rows=illustration?[{name:'示意A：范围较窄',delta:0,ci:[-15,15]},{name:'示意B：范围较宽',delta:0,ci:[-180,180]}]:city?[D.cellWelch[0]!,D.cellWelch[1]!].map((s,i)=>({name:`${i===0?'甲':'乙'}城 · 会员 − 非会员`,...s})):[{name:'全样本 · 会员 − 非会员',...D.welch}];
 return <Plot label="均值差及其95%置信区间"><g className="sa-axis"><path d="M150 420H1030"/>{[-200,-100,0,100,200,300].map(v=><text key={v} x={sx(v)} y="462" textAnchor="middle">{v}</text>)}<text x="1030" y="510" textAnchor="end">均值差（元/人/月）</text></g><path d={`M${sx(0)} 70V420`} stroke={muted} strokeDasharray="8 6"/>{rows.map((r,i)=><g key={r.name}><text x="150" y={75+i*160} fill={ink}>{r.name}</text><path d={`M${sx(r.ci[0]!)} ${125+i*160}H${sx(r.ci[1]!)}M${sx(r.ci[0]!)} ${113+i*160}v24M${sx(r.ci[1]!)} ${113+i*160}v24`} stroke={teal} strokeWidth="5"/><circle cx={sx(r.delta)} cy={125+i*160} r="9" fill={amber}/><text x={sx(r.delta)+14} y={170+i*160}>{fmt(r.delta)} [{fmt(r.ci[0]!)}, {fmt(r.ci[1]!)}]</text></g>)}</Plot>;
}
export function Anscombe({which,labels=false}:{which?:number;labels?:boolean}) {const sets=which?[D.anscombe[which-1]!]:D.anscombe;return <div className={`sa-anscombe ${which?'single':''}`}>{sets.map((s,i)=>{const index=which??i+1;const sx=(v:number)=>50+v/20*470,sy=(v:number)=>270-v/15*240;return <svg key={index} viewBox="0 0 580 345" role="img" aria-label={`Anscombe ${index}，x 0至20，y 0至15`}><g className="sa-axis"><path d="M50 25V270H520"/>{[0,5,10,15,20].map(v=><text key={v} x={sx(v)} y="304" textAnchor="middle">{v}</text>)}{[0,5,10,15].map(v=><text key={v} x="35" y={sy(v)+6} textAnchor="end">{v}</text>)}</g><path d={`M${sx(0)} ${sy(3)}L${sx(20)} ${sy(13)}`} stroke={muted} strokeWidth="2"/>{s.x.map((v,j)=><circle key={j} cx={sx(v)} cy={sy(s.y[j]!)} r="6" fill={index===3&&j===2||index===4&&v===19?amber:teal}/>)}<text x="510" y="40" textAnchor="end" fill={ink} fontSize="29">{['Ⅰ','Ⅱ','Ⅲ','Ⅳ'][index-1]}</text>{labels?<text x="285" y="340" textAnchor="middle">{['近似线性','弯曲关系','异常y值','高杠杆x值'][index-1]}</text>:null}</svg>;})}</div>;}
export function Scatter({color=false,big=false,first=false,city}:{color?:boolean;big?:boolean;first?:boolean;city?:string}) {const ps=(first?people.slice(0,1):people).filter(p=>!city||p.city===city);return <Plot label="顾客月收入与月消费散点图"><Axis max={16000} step={4000} label="月收入（元）"/><g className="sa-axis"><path d="M90 80V420"/>{[0,1000,2000].map(v=><text key={v} x="72" y={y(v,2600)+8} textAnchor="end">{v}</text>)}<text x="90" y="38">月消费（元）</text></g>{ps.map(p=>color&&!p.member?<path key={p.id} d={`M${x(p.income,16000)} ${y(p.spend,2600)-5}l5 10h-10Z`} fill={teal} opacity=".65"/>:<circle key={p.id} cx={x(p.income,16000)} cy={y(p.spend,2600)} r={big?13:first?12:4.5} fill={color?amber:ink} opacity={big?1:.48}/>)}{first?<text x={x(ps[0]!.income,16000)+20} y={y(ps[0]!.spend,2600)-22}>{ps[0]!.id}：收入{fmt(ps[0]!.income,2)}，消费{fmt(ps[0]!.spend,2)}</text>:null}{color?<g><circle cx="740" cy="46" r="7" fill={amber}/><text x="758" y="54">会员</text><path d="M925 37l8 16h-16Z" fill={teal}/><text x="945" y="54">非会员</text></g>:null}</Plot>;}
export function Composition() {return <Plot label="会员与非会员内部的城市构成"><defs><pattern id="sa-city-hatch" width="12" height="12" patternUnits="userSpaceOnUse"><path d="M0 12L12 0" stroke="#fff" strokeWidth="3"/></pattern></defs>{[.75,.25].map((v,i)=><g key={i}><text x="90" y={90+i*185} fill={i?teal:amber}>{i?'非会员':'会员'}，n=240</text><rect x="90" y={115+i*185} width="1000" height="70" fill={i?teal:amber}/><rect x={90+1000*v} y={115+i*185} width={1000*(1-v)} height="70" fill="url(#sa-city-hatch)"/><text x={90+500*v} y={160+i*185} textAnchor="middle" fill="white">甲城 {v*100}%</text><text x={90+1000*v+500*(1-v)} y={160+i*185} textAnchor="middle" fill="white">乙城 {(1-v)*100}%</text></g>)}<text x="90" y="485">城市用纹理区分；每一条的分母为该会员身份组的240人。</text></Plot>;}
export function TimeSeries({metric='perPerson',quarter=false,missing=false}:{metric?:'perPerson'|'total'|'customers';quarter?:boolean;missing?:boolean}) {
 const rows=quarter?Array.from({length:8},(_,i)=>({v:D.monthly.slice(i*3,i*3+3).reduce((s,v)=>s+v.total,0),label:`Q${i%4+1}`})):D.monthly.map((r,i)=>({v:r[metric],label:String(i+1)}));
 const max=quarter?4500000:metric==='total'?1700000:metric==='customers'?2000:800;
 const sx=(i:number)=>90+i/(rows.length-1)*990,sy=(v:number)=>420-v/max*340;
 const segments: string[]=[];let fresh=true;rows.forEach((r,i)=>{if(missing&&[7,8].includes(i)){fresh=true;return;}segments.push(`${fresh?'M':'L'}${sx(i)} ${sy(r.v)}`);fresh=false;});
 return <Plot label={`${quarter?'季度总额':metric==='total'?'月销售总额':metric==='customers'?'顾客数':'月人均消费'}时间序列`}><g className="sa-axis"><path d="M90 60V420H1080"/>{[0,max/2,max].map(v=><text key={v} x="75" y={sy(v)+8} textAnchor="end">{v>=10000?v/10000+'万':v}</text>)}{rows.map((r,i)=>(quarter||i%3===0||i===23)?<text key={i} x={sx(i)} y="465" textAnchor="middle">{r.label}</text>:null)}<text x="1080" y="510" textAnchor="end">{quarter?'连续8个季度':'连续24个自然月'}</text></g><text x="95" y="38">{quarter||metric==='total'?'销售额（元）':metric==='customers'?'顾客数（人）':'人均消费（元/人/月）'}</text><path d={segments.join(' ')} stroke={teal} strokeWidth="4" fill="none"/>{missing?<text x={sx(7)} y="105" fill={amber}>第8、9月未知</text>:null}</Plot>;
}
export function ErrorBars() {const s=groups[0]!;const rows=[{label:'均值 ± SD：个体变异',lo:s.mean-s.sd,hi:s.mean+s.sd},{label:'均值 ± SE：估计波动',lo:s.mean-s.se,hi:s.mean+s.se},{label:'均值的95% t CI',lo:s.ci[0]!,hi:s.ci[1]!}];return <Plot label="会员均值的SD、SE与95%置信区间"><Axis max={1200} step={200}/>{rows.map((r,i)=><g key={r.label}><text x="90" y={55+i*115}>{r.label}</text><path d={`M${x(r.lo,1200)} ${85+i*115}H${x(r.hi,1200)}`} stroke={teal} strokeWidth="5"/><circle cx={x(650,1200)} cy={85+i*115} r="8" fill={amber}/><text x="1080" y={122+i*115} textAnchor="end">{fmt(r.lo)}—{fmt(r.hi)}</text></g>)}</Plot>;}
export function Heatmap() {const labels=['消费','收入','年龄','到店次数'];return <Plot label="四个变量的Pearson相关矩阵，色标负1到1">{labels.map((l,i)=><g key={l}><text x="295" y={125+i*85} textAnchor="end">{l}</text><text x={360+i*130} y="45" textAnchor="middle">{l}</text></g>)}{D.correlation.map((r,i)=>r.map((v,j)=><g key={`${i}-${j}`}><rect x={300+j*130} y={70+i*85} width="124" height="79" fill={v>=0?teal:amber} opacity={.12+Math.abs(v)*.88}/><text x={362+j*130} y={120+i*85} textAnchor="middle" fill={Math.abs(v)>.65?'white':ink}>{fmt(v,2)}</text></g>))}<defs><linearGradient id="sa-corr"><stop offset="0" stopColor={amber}/><stop offset=".5" stopColor="#f5f1e8"/><stop offset="1" stopColor={teal}/></linearGradient></defs><rect x="300" y="440" width="515" height="15" fill="url(#sa-corr)"/>{[-1,0,1].map((v,i)=><text key={v} x={300+i*257.5} y="492" textAnchor="middle">{v}</text>)}</Plot>;}
export function BadChart({fixed=false}:{fixed?:boolean}) {const base=fixed?0:480,sy=(v:number)=>420-(v-base)/(700-base)*320;return <Plot label={fixed?'修订图：零基线的均值条形图':'错误示例：截断纵轴的均值条形图'}><g className="sa-axis"><path d="M170 80V420H1080"/>{(fixed?[0,200,400,600]:[480,500,550,600,650,700]).map(v=><text key={v} x="152" y={sy(v)+7} textAnchor="end">{v}</text>)}</g>{[650,500].map((v,i)=><g key={i}><rect x={330+i*400} y={sy(v)} width="180" height={420-sy(v)} fill={i?teal:amber}/><text x={420+i*400} y={sy(v)-20} textAnchor="middle" fontSize="38">{v}</text><text x={420+i*400} y="470" textAnchor="middle">{i?'非会员':'会员'}</text></g>)}<text x="170" y="35">月均消费（元/人/月）</text>{!fixed?<text x="1070" y="95" textAnchor="end" fill="#bc5446">错误示例 · 基线480元</text>:null}</Plot>;}
