import type { ReactNode, CSSProperties } from 'react';
import { PORT_LESSON_FIVE_EVIDENCE as E, capacityTime, type PortLessonFivePage, type LessonFivePlan } from '@edu/course-content';
const teal='#278b98', gold='#a77e43';
const clamp=(v:number)=>Math.max(0,Math.min(1,v));
function T({x=84,y,w=1400,size=34,color,children,style={}}:{x?:number;y:number;w?:number;size?:number;color?:string;children:ReactNode;style?:CSSProperties}) { return <div className="l5-text" data-l5-bounds="text" style={{left:x,top:y,width:w,fontSize:size,color,...style}}>{children}</div>; }
function D({children,label,y=420,h=430}:{children:ReactNode;label:string;y?:number;h?:number}) { return <svg className="l5-diagram" data-l5-bounds="diagram" style={{top:y,height:h}} viewBox={`0 0 1440 ${h}`} role="img" aria-label={label}>{children}</svg>; }
function Box({x,y,scale=1,color=teal}:{x:number;y:number;scale?:number;color?:string}) { return <g transform={`translate(${x} ${y}) scale(${scale})`}><path d="M0 0l15-12h66l-15 12Z" fill={color} opacity=".65"/><path d="M66 0l15-12v47L66 47Z" fill={color} opacity=".8"/><rect width="66" height="47" fill={color}/>{[10,24,38,52].map(v=><path key={v} d={`M${v} 5v36`} stroke="currentColor" opacity=".25"/>)}</g>; }
function Chain({p,values=['岸桥','运输','堆场'],narrow=false}:{p:number;values?:readonly string[];narrow?:boolean}) {
  return <D label="岸桥、运输和堆场接续"><path d="M85 225H1350" fill="none" stroke="currentColor" strokeWidth="3" opacity=".24"/>{values.map((v,i)=><g key={i}><text x={180+i*490} y="70" textAnchor="middle" fontSize="39" fill="currentColor">{v}</text><path d={`M${180+i*490} 97v46`} stroke="currentColor" opacity=".3"/><rect x={95+i*490} y="155" width={narrow&&i===1?120:170} height="125" rx="2" fill={i===1?gold:teal} opacity=".18"/><text x={180+i*490} y="335" textAnchor="middle" fontSize="27" fill="currentColor">{['交出','接续','接收'][i]}</text></g>)}{Array.from({length:7},(_,i)=><Box key={i} x={100+((p*.9+i*.12)%1)*1170} y={187} scale={.68} color={i%2?gold:teal}/>)}<path d="M1325 213l25 12-25 12" fill="none" stroke={teal} strokeWidth="4"/></D>;
}
function QuayQueue({p}:{p:number}) {
 return <D label="上游持续交出，运输慢接，岸侧队列逐渐积累"><path d="M90 240H1330" stroke="currentColor" opacity=".3" strokeWidth="3"/>{['岸桥交出','岸侧等候','运输接走'].map((s,i)=><text key={s} x={160+i*515} y="65" textAnchor="middle" fontSize="38" fill="currentColor">{s}</text>)}<rect x="345" y="142" width="550" height="150" fill={gold} opacity=".12"/>{Array.from({length:6},(_,i)=>{const t=clamp((p-i*.11)*4),x=110+(760-i*80-110)*t;return <g key={i} opacity={clamp((p-i*.11)*10)}><Box x={x} y={185} scale={.8} color={gold}/></g>;})}<g opacity={clamp(p*5)}><Box x={950+270*p} y={185} scale={.8}/></g><text x="620" y="365" textAnchor="middle" fontSize="30" fill="#dfba7b">交出快于接走，等待在接口处增加</text></D>;
}
function Formula({p,items}:{p:number;items:readonly string[]}) { return <>{items.map((v,i)=><T key={i} y={430+i*126} size={i===items.length-1?58:40} color={i===items.length-1?teal:undefined} style={{opacity:clamp(p*items.length-i+1)}}>{v}</T>)}</>; }
function Config({left,right}:{left:LessonFivePlan;right?:LessonFivePlan}) {const ids=right?[left,right]:[left];return <D label="对照方案配置">{ids.map((id,i)=>{const c=E[id].configuration,x=ids.length===1?120:70+i*740;return <g key={id}><text x={x} y="75" fontSize="68" fill={i?gold:teal}>方案 {id}</text><text x={x} y="160" fontSize="35" fill="currentColor">S01岸桥 {c.cranes} 台</text><text x={x} y="235" fontSize="35" fill="currentColor">运输岗位 {c.drivers} 个</text><path d={`M${x} 275h570`} stroke="currentColor" opacity=".3"/><text x={x} y="335" fontSize="27" fill="currentColor">场桥4 · 闸口2 · 同一起点</text></g>;})}</D>;}
export function CapacityChart({plans,p=1}:{plans:readonly LessonFivePlan[];p?:number}) {
 const max=48000,x=(t:number)=>110+t/max*1230,y=(n:number)=>325-n/194*270;
 return <D label="实际模型运行的累计装卸量曲线"><text x="120" y="25" fontSize="22" fill="currentColor">累计装卸 / 箱　·　图例用时：时:分:秒</text><path d="M110 35V325H1360" fill="none" stroke="currentColor" strokeWidth="2"/>{[0,50,100,150,194].map(n=><g key={n}><path d={`M110 ${y(n)}H1360`} stroke="currentColor" opacity=".12"/><text x="90" y={y(n)+7} textAnchor="end" fontSize="21" fill="currentColor">{n}</text></g>)}{[0,4,8,12].map(h=><text key={h} x={x(h*3600)} y="365" textAnchor="middle" fontSize="24" fill="currentColor">{h}小时</text>)}{plans.map((id,i)=>{const v=E[id],color=[teal,gold,'#6a8f6a','#a46e68','#667cb0'][i]!;return <g key={id}><path d={v.samples.map((s,j)=>`${j?'L':'M'}${x(s.elapsed)} ${y(s.unloaded+s.loaded)}`).join(' ')} fill="none" stroke={color} strokeWidth={id==='D'?8:4} pathLength="1" strokeDasharray="1" strokeDashoffset={1-p}/><text x={120+i*255} y="410" fontSize="24" fill={color}>{id} · {capacityTime(v.elapsed!)}</text></g>;})}</D>;
}
function Results({ids,p=1}:{ids:readonly LessonFivePlan[];p?:number}) { return <D label="实际装卸完成时间"><text x="1070" y="18" fontSize="22" fill="currentColor">用时（时:分:秒）</text>{ids.map((id,i)=>{const value=E[id].elapsed!,y=65+i*125;return <g key={id}><text x="10" y={y} fontSize="45" fill="currentColor">{id}</text><rect x="105" y={y-35} width={value/48000*930*p} height="49" fill={i?gold:teal}/><text x="1070" y={y+2} fontSize="40" fill="currentColor">{capacityTime(value)}</text></g>;})}<text x="105" y="377" fontSize="27" fill="currentColor">同一终点：进口卸船116箱 + 出口装船78箱</text></D>; }
function Queue({burst,p=1,small=false}:{burst:boolean;p?:number;small?:boolean}) { const height=small?230:440;return <D label={burst?'集中到达的服务与等待':'均匀到达的服务与等待'} y={small?440:395} h={height}><g transform={small?'scale(1 .5)':''}>{Array.from({length:6},(_,i)=>{const y=40+i*53,start=110+i*96,arrival=burst?110:start;return <g key={i} opacity={clamp(p*6-i+1)}><text x="30" y={y+22} fontSize="24" fill="currentColor">车{i+1}</text><path d={`M${arrival} ${y+12}H${start}`} stroke={gold} strokeWidth="9"/><circle cx={arrival} cy={y+12} r="6" fill={gold}/><rect x={start} y={y} width="96" height="26" fill={teal}/><text x="830" y={y+22} fontSize="25" fill="currentColor">等待 {burst?i*2:0} 分钟</text></g>;})}<path d="M110 360H686" stroke="currentColor"/>{[0,2,4,6,8,10,12].map((t,i)=><text key={t} x={110+i*96} y="395" textAnchor="middle" fontSize="24" fill="currentColor">{t}</text>)}<text x="1110" y="150" fontSize="34" fill={gold}>等待</text><text x="1110" y="210" fontSize="34" fill={teal}>服务</text></g></D>; }
function Pair({left,right}:{left:readonly string[];right:readonly string[]}) { return <>{left.map((s,i)=><T key={`l${i}`} y={430+i*110} w={640} size={i===0?48:31} color={i===0?teal:undefined}>{s}</T>)}{right.map((s,i)=><T key={`r${i}`} x={840} y={430+i*110} w={680} size={i===0?48:31} color={i===0?gold:undefined}>{s}</T>)}</>; }
const photoPages:Record<number,string>={1:'terminal-dawn',2:'terminal-dusk',4:'quay-crane',17:'ship-deck',18:'yard-waiting',19:'import-handoff',21:'quay-crane',22:'yard-aerial',24:'terminal-dusk',31:'yard-waiting',34:'import-handoff',44:'yard-aerial',48:'terminal-dusk'};
const darkPages=new Set([3,8,11,15,30,33,42]);
export function PortLessonFiveComposition({page,p=1,revealed=false,readOnly=true,onOpen}:{page:PortLessonFivePage;p?:number;revealed?:boolean;readOnly?:boolean;onOpen?:(id:LessonFivePlan,personal?:boolean)=>void}) {
 const n=page.localPage,photo=photoPages[n],dark=!!photo||darkPages.has(n),a1=E.A.samples.find(s=>s.elapsed===3600)!,b1=E.B.samples.find(s=>s.elapsed===3600)!;
 const content=(()=>{switch(n){
 case 1:return <><T y={635} size={29} color="#dfb878">S01 / 同一艘船，五种资源配置</T><T y={716} size={42} w={1150}>能力　→　等待　→　瓶颈　→　判断</T><T y={808} size={26}>{page.points.join('　　')}</T></>;
 case 2:return <><T y={446} size={74} color="#72c5ce">如果……，那么……</T><T y={588} w={1100}>增加一项资源，应该改变哪条记录？</T><T y={714} w={1050} color="#e7be80">什么结果会推翻这个解释？</T></>;
 case 3:return <><QuayQueue p={p}/><T y={830} size={28}>上游仍在作业 ≠ 整条链没有等待</T></>;
 case 4:return <><T y={405} size={118} color="#e7be80">？</T>{page.points.map((s,i)=><T key={s} x={280} y={467+i*105} w={1080} size={38}>{s}</T>)}</>;
 case 5:return <D label="一个60秒作业循环"><circle cx="440" cy="210" r="145" fill="none" stroke="currentColor" opacity=".2" strokeWidth="25"/><circle cx="440" cy="210" r="145" fill="none" stroke={teal} strokeWidth="25" pathLength="1" strokeDasharray="1" strokeDashoffset={1-p} transform="rotate(-90 440 210)"/><text x="440" y="226" textAnchor="middle" fontSize="66" fill="currentColor">60秒</text>{['取箱','移动','放箱','返回'].map((s,i)=><text key={s} x={850} y={75+i*91} fill="currentColor" fontSize="38">{String(i+1).padStart(2,'0')}　{s}</text>)}</D>;
 case 6:return <Formula p={p} items={['1小时 = 3600秒','3600 ÷ 60 = 60','60 箱 / 小时']}/>;
 case 7:return <D label="四辆牵引车与两名到岗人员">{[0,1,2,3].map(i=><g key={i} opacity={i<2?1:.3}><rect x={80+i*350} y="190" width="240" height="80" fill={teal}/><circle cx={130+i*350} cy="285" r="19" fill="currentColor"/><circle cx={270+i*350} cy="285" r="19" fill="currentColor"/>{i<2&&<g opacity={p}><circle cx={200+i*350} cy="50" r="23" fill={gold}/><path d={`M${200+i*350} 85v70`} stroke={gold} strokeWidth="28"/></g>}<text x={190+i*350} y="350" textAnchor="middle" fill="currentColor" fontSize="29">{i<2?'岗位到位':'等待到岗'}</text></g>)}</D>;
 case 8:return <D label="四个接收位置占满，新增箱子停在入口">{[0,1,2,3].map(i=><g key={i}><rect x={475+i*180} y="140" width="125" height="105" fill="none" stroke="currentColor" opacity=".4"/><g opacity={clamp(p*5-i+1)}><Box x={495+i*180} y={175}/></g></g>)}<g opacity={clamp(p*4-1)}><Box x={120+180*clamp(p*2)} y={175} color={gold}/></g><path d="M420 130v140" stroke={gold} strokeWidth="7"/><text x="345" y="350" textAnchor="middle" fill="#dfba7b" fontSize="34">入口等候</text><text x="850" y="350" textAnchor="middle" fill="currentColor" fontSize="34">接收位置已满</text></D>;
 case 9:return <D label="能力与累计完成量示意"><path d="M130 20v290h1140" stroke="currentColor" fill="none" strokeWidth="3"/><path d="M130 310L1180 35" stroke={gold} strokeWidth="4" strokeDasharray="12 10"/><path d="M130 310H320L630 255H810L1180 110" stroke={teal} strokeWidth="5" fill="none" pathLength="1" strokeDasharray="1" strokeDashoffset={1-p}/><text x="710" y="52" fill={gold} fontSize="30">连续能力参考</text><text x="780" y="255" fill={teal} fontSize="30">累计完成量</text><text x="1040" y="380" fill="currentColor" fontSize="27">观察时间 →</text></D>;
 case 10:return <Pair left={['比较对象','同一艘船 / 同一货量','同一起点 / 同一规则']} right={['完成终点','进口卸船116 + 出口装船78','进口提离另外记录']}/>;
 case 11:return <Chain p={p}/>;
 case 12:return <Chain p={0} values={['岸桥 60','运输 40','堆场 50']}/>;
 case 13:return <><Chain p={p} values={['岸桥 60','运输 40','堆场 50']} narrow/><T y={831} size={38} color={teal}>持续产出上限：40箱/小时</T></>;
 case 14:return <><Pair left={['原方案','60 → 40 → 50','上限 40箱/小时']} right={['只增加岸桥','90 → 40 → 50','上限仍为40箱/小时']}/><T y={820} size={28} style={{opacity:p}}>运输接续条件没有改变</T></>;
 case 15:return <><Chain p={p} values={['岸桥 60','运输 60','堆场 50']}/><T y={835} size={38} color="#dfba7b">上限40 → 50，堆场接过限制</T></>;
 case 16:return <Pair left={['简化模型','同一种箱流、同一单位','稳定状态、货源充足']} right={['实际作业还需检查','起步与缓冲、运输距离','双向箱流、共享任务']}/>;
 case 17:return <><T y={435} size={115} color="#76c3cb" w={630}>116<span className="l5-unit">箱进口</span></T><T x={850} y={435} size={115} color="#e0b77c" w={640}>78<span className="l5-unit">箱出口</span></T><T y={650} size={35}>已靠妥　·　四批回执有效　·　堆场已分配</T><T y={786} size={29}>统一开工，相对时间归零</T></>;
 case 18:return <Config left="A"/>;
 case 19:case 22:case 34:return <><T y={446} size={94} color="#e0b77c">方案 {page.experiment}</T><T y={585} size={35} w={1040}>{page.points[0]}</T><T y={664} size={35} w={1040}>{page.points[1]}</T>{!readOnly&&onOpen?<button className="l5-experiment-entry" onClick={()=>onOpen(page.experiment!,n===34)}>{n===34?'进入个人C实验':'打开教师演示'} ↗</button>:<T y={801} size={27} color="#9fcbd0">{n===34?'个人任务 · 从冻结起点执行C':'现场观察 · 同一时点核对箱流'}</T>}</>;
 case 20:return <D label="A方案1小时真实快照">{[{v:a1.unloaded,t:'已卸船'},{v:a1.quay,t:'位置在岸侧'},{v:a1.waitingTransport,t:'尚未接上运输任务'}].map((o,i)=><g key={o.t} opacity={clamp(p*3-i+1)}><text x={90+i*480} y="170" fill={i===1?gold:teal} fontSize="130">{o.v}</text><text x={90+i*480} y="250" fill="currentColor" fontSize="31">{o.t}</text><text x={90+i*480} y="312" fill="currentColor" fontSize="25">实体箱</text></g>)}</D>;
 case 21:return <Config left="A" right="B"/>;
 case 23:return <><Results ids={['A','B']} p={p}/><T y={850} size={27}>1小时卸船：A {a1.unloaded}箱 / B {b1.unloaded}箱；B整船结束晚{E.B.elapsed!-E.A.elapsed!}秒</T></>;
 case 24:return <>{['原判断','观察记录','修订解释'].map((s,i)=><T key={s} y={445+i*130} size={38}><span className="l5-gold">{s}</span>　{page.points[i]?.split('：').slice(1).join('：')}</T>)}</>;
 case 25:return <><D label="到达、等待、服务与完成"><path d="M100 165H1320" stroke="currentColor" strokeWidth="3"/>{['到达','等待','开始服务','完成'].map((s,i)=><g key={s}><circle cx={150+i*370} cy="165" r="12" fill={i===1?gold:teal}/><text x={150+i*370} y="250" textAnchor="middle" fontSize="35" fill="currentColor">{s}</text></g>)}</D><T y={806} size={35}>等待时间 = 开始服务时刻 − 到达时刻</T></>;
 case 26:return <Queue burst={false} p={p}/>;
 case 27:return <Queue burst p={p}/>;
 case 28:return <Formula p={p} items={['0 + 2 + 4 + 6 + 8 + 10 = 30分钟','30分钟 ÷ 6辆','平均等待 5分钟 / 辆']}/>;
 case 29:return <><Pair left={['均匀到达','忙碌 12分钟','平均等待 0分钟']} right={['集中到达','忙碌 12分钟','平均等待 5分钟']}/><T y={842} size={30} style={{opacity:p}}>相同利用率，不能独自说明等待分布</T></>;
 case 30:return <D label="四种资源观察状态">{page.points.map((s,i)=><g key={s} opacity={clamp(p*4-i+1)}><circle cx="40" cy={50+i*100} r="15" fill={i===0?teal:i===3?'#98a5a8':gold}/><text x="95" y={61+i*100} fontSize="34" fill="currentColor">{s}</text></g>)}</D>;
 case 31:return <><Config left="A" right="C"/><T y={850} size={26}>A是教师参考；C保留你的独立记录</T></>;
 case 32:return <>{page.points.map((s,i)=><T key={s} y={443+i*133} size={44}><span className="l5-gold">0{i+1}</span>　{s}</T>)}</>;
 case 33:return <><D label="仅运输岗位2改为4">{page.points.map((s,i)=><text key={s} x="160" y={80+i*133} fontSize={i===1?65:41} fill={i===1?'#e0b77c':'currentColor'} opacity={clamp(p*3-i+1)}>{s}</text>)}</D></>;
 case 35:return <>{page.points.map((s,i)=><T key={s} y={425+i*132} size={36}><span className="l5-check">□</span>　{s}</T>)}</>;
 case 36:return <>{page.points.map((s,i)=><T key={s} y={426+i*130} size={38} style={{borderBottom:'1px solid #b4beb8',paddingBottom:28}}>{s}</T>)}</>;
 case 37:return <Pair left={['教师参考','版本与起点已冻结','A—E生成记录']} right={['个人运行','自己的假设与C执行','先查差异，再作解释']}/>;
 case 38:return <Results ids={['A','C']} p={p}/>;
 case 39:return <Results ids={['C','D']} p={p}/>;
 case 40:return <><Results ids={['D','E']} p={p}/><T y={841} size={28}>终点相同，不代表每个时刻的箱流都相同</T></>;
 case 41:return <CapacityChart plans={['A','B','C','D','E']} p={p}/>;
 case 42:return <><Chain p={p} values={['上游供给','资源任务','下游接收']}/><T y={845} size={29}>先提出候选解释，再设计下一次比较</T></>;
 case 43:return <>{page.points.map((s,i)=><T key={s} y={422+i*137} size={44}><span className="l5-gold">{['资源','结果','投入'][i]}</span>　{s}</T>)}</>;
 case 44:return <>{page.points.map((s,i)=><T key={s} y={454+i*124} size={44}><span className="l5-gold">{['↓','↑','提前'][i]}</span>　{s}</T>)}</>;
 case 45:return revealed?<><T y={417} w={1370} size={37}>{page.reveal}</T><T y={785} size={30} color={teal}>保留其他有证据支持的候选解释</T></>:<>{page.points.map((s,i)=><T key={s} y={435+i*131} size={39}><span className="l5-gold">0{i+1}</span>　{s}</T>)}</>;
 case 46:return <>{page.points.map((s,i)=><T key={s} y={438+i*127} size={36} color={i===0?teal:undefined}>{s}</T>)}</>;
 case 47:return <>{page.points.map((s,i)=><T key={s} y={416+i*105} size={35}><span className="l5-gold">0{i+1}</span>　{s}</T>)}</>;
 case 48:return <><T y={470} size={78} color="#dfba7b">船 → 岸 → 场 → 腹地</T><T y={654} size={40} style={{opacity:p}}>装卸完成，货物的旅程仍在继续。</T><T y={803} size={28}>{page.points.join('　/　')}</T></>;
 default:return null;
 }})();
 return <article className={'port-l5-slide '+(dark?'l5-dark':'l5-paper')} aria-label={`第5讲第${n}页`}>
 {photo&&<><img className="l5-background" src={`/course-assets/port-management/l4/${photo}-v1.png`} alt=""/><div className="l5-shade"/></>}
 <header className="l5-heading"><div className="l5-kicker">{String(n).padStart(2,'0')} / CAPACITY & BOTTLENECKS</div><h1 data-l5-bounds="heading">{page.title}</h1><p data-l5-bounds="lead">{page.lead}</p></header>
 {content}<footer data-l5-bounds="footer"><span>{photo?'AI生成背景 · ':''}{page.sourceIds?.[0]==='port-l5-concept'?'概念模型 · 参数为教学设定':n>=17&&n<=43?'教学模型 · 固定情境运行 / port-capacity 1.0':'教学情境 · 本课程编制'}</span><span>港口管理概论 · 第5讲　<b>{String(n).padStart(2,'0')} / 48</b></span></footer>
 </article>;
}
