import {author,type Insertion} from './authoring.js';import {lesson16} from '../lessons/lesson-16.js';import type {PlotSpec} from '../types.js';
const {m,c,q,e,t,g}=author(16,lesson16.sources[0]!);
const rates=(extras:Partial<PlotSpec>={}):PlotSpec=>({xRange:[0,1],yRange:[0,20000],xLabel:'Time (years)',yLabel:'Flow (€/year)',curves:[{kind:'polynomial',coefficients:[10000],color:'blue'},{kind:'polynomial',coefficients:[6000,12000],color:'coral'}],...extras});
export const additions16:readonly Insertion[]=[
 c('02','a','Two plans deliver money over time','Plan A delivers €10,000 per year. Plan B starts at €6,000 per year and rises.','A flow rate is measured in euros per year; its accumulated amount is in euros.'),
 m('02','b','Write the rising flow rule',String.raw`b(t)=6000+12000t,\qquad0\le t\le1`,'Time is measured in years from the start of both plans.'),
 t('03','a','Take three rate snapshots',['t (years)','A (€/year)','B (€/year)'],[['0','10000','6000'],['0.5','10000','12000'],['1','10000','18000']],'These readings compare current rates rather than totals received.'),
 q('03','b','Predict the cumulative ranking','At t=0.5, B has the higher current rate. Must B have delivered more by then?','No. Earlier rates also contribute to the cumulative amounts.'),
 m('04','a','Find when current rates are equal',String.raw`10000=6000+12000t`,'This equation compares heights on the flow graph.',{sequence:'rate-crossing'}),
 m('04','b','Solve the rate-crossing time',String.raw`t=\frac{4000}{12000}=\frac13`,'The equality occurs four months after the start.',{sequence:'rate-crossing'}),
 g('04','c','Locate the crossing on the rate graph',rates({points:[{x:1/3,y:10000,label:'Equal rates'}]}),String.raw`t=\frac13`,'After this time, B catches up at a faster rate.',{sequence:'rate-crossing'}),
 c('04','d','A faster rate does not erase an earlier gap','A has already delivered more during the first four months.','B needs additional time to recover that lead.'),
 m('05','a','Accumulate Plan A over a horizon',String.raw`I_A(T)=\int_0^T10000\,dt`,'T is the length of the evaluation window in years.',{sequence:'accumulate-A'}),
 m('05','b','Find an antiderivative',String.raw`10000t`,'Multiplying the annual rate by years gives euros.',{sequence:'accumulate-A'}),
 m('06','a','Evaluate at the two endpoints',String.raw`I_A(T)=10000T-10000(0)`,'No money is assumed to have accumulated before time zero.',{sequence:'accumulate-A'}),
 m('06','b','Use a half-year horizon',String.raw`I_A(0.5)=5000`,'The constant-rate rectangle gives €5,000.'),
 m('07','a','Accumulate Plan B term by term',String.raw`I_B(T)=\int_0^T(6000+12000t)\,dt`,'Both parts of the flow contribute to the total.',{sequence:'accumulate-B'}),
 m('07','b','Recover the cumulative expression',String.raw`6000t+6000t^2`,'The slope of this expression is the original flow.',{sequence:'accumulate-B'}),
 m('07','c','Evaluate the full time window',String.raw`I_B(T)=6000T+6000T^2`,'The lower-end value is zero.',{sequence:'accumulate-B'}),
 q('07','d','Check rate versus amount','What are b(0.5) and I_B(0.5), including units?','b(0.5)=€12,000/year; I_B(0.5)=€4,500.'),
 m('08','a','Compare totals at six months',String.raw`I_A(0.5)=5000>4500=I_B(0.5)`,'A leads in accumulated money even though B currently flows faster.'),
 m('08','b','Compare totals at one year',String.raw`I_A(1)=10000<12000=I_B(1)`,'B has recovered the earlier deficit by this later horizon.'),
 m('09','a','Set accumulated amounts equal',String.raw`10000T=6000T+6000T^2`,'This equation compares cumulative totals.',{sequence:'total-crossing'}),
 m('09','b','Factor before dividing',String.raw`T(6000T-4000)=0`,'Keep the initial equality at T=0 visible.',{sequence:'total-crossing'}),
 m('09','c','Identify the later crossing',String.raw`T=\frac23`,'Eight months are needed for B to match the accumulated amount of A.',{sequence:'total-crossing'}),
 q('09','d','Interpret both roots','Why is T=0 also a solution?','Both plans have accumulated zero money at the common start.'),
 t('10','a','Separate the two crossing questions',['Question','Equation','Time (years)'],[['Equal current rates','10000=6000+12000t','1/3'],['Equal accumulated amounts','10000T=6000T+6000T²','0 and 2/3']],'Only the second equation answers when B catches up in total.'),
 e('10','b','Diagnose a crossing substitution','“B has caught up in total when the two rate curves first cross.”','At T=1/3, A has €3333.33 and B has €2666.67. Equal rates do not imply equal totals.'),
 g('11','a','Read the accumulated-money curves',{xRange:[0,1],yRange:[0,13000],xLabel:'Horizon (years)',yLabel:'Accumulated (€)',curves:[{kind:'polynomial',coefficients:[0,10000],color:'blue'},{kind:'polynomial',coefficients:[0,6000,6000],color:'coral'}],points:[{x:2/3,y:20000/3,label:'Equal totals'}]},String.raw`T=\frac23`,'The curve slopes are the current rates; the heights are accumulated money.'),
 q('11','b','Read the correct graph feature','To compare money received by T=0.5, should we compare cumulative heights or slopes?','Heights. Slopes compare the current flow rates.'),
 m('12','a','Form the difference of the flows',String.raw`b(t)-a(t)=12000t-4000`,'Negative values favour A; positive values favour B.',{sequence:'difference-integral'}),
 m('12','b','Accumulate the signed difference',String.raw`I_B(T)-I_A(T)=6000T^2-4000T`,'The integral combines B’s early deficit and later advantage.',{sequence:'difference-integral'}),
 m('13','a','Evaluate the one-year difference',String.raw`6000(1)^2-4000(1)=2000`,'B delivers €2,000 more during the first year.',{sequence:'difference-integral'}),
 c('13','b','State the horizon with the decision','B delivers more by one year; A delivers more by six months.','The preferred flow depends on the chosen evaluation window.'),
 m('14','a','Differentiate the cumulative amount of A',String.raw`I_A'(T)=10000`,'This recovers the constant annual flow rate.'),
 m('14','b','Differentiate the cumulative amount of B',String.raw`I_B'(T)=6000+12000T`,'The fundamental theorem links the total and the flow.'),
 c('15','a','Write a complete comparison statement','Same starting time, same currency and horizon; rates supplied by the model.','These calculations compare undiscounted accumulated money.'),
 q('15','b','Name the missing decision detail','A statement says “B wins”. Which time detail must it include?','The evaluation horizon. B wins in accumulated money for T>2/3 within this model’s one-year domain.'),
 m('16','a','Return to a current marginal-cost question',String.raw`C(q)=100+20q+\frac12q^2`,'This is a total-cost function, not a time-flow rate.',{sequence:'business-tool-choice'}),
 m('16','b','Differentiate for the next-unit estimate',String.raw`C'(20)=20+20=40`,'Marginal cost is €40 per output unit at q=20.',{sequence:'business-tool-choice'}),
 m('17','a','Differentiate profit for a candidate',String.raw`\pi'(q)=80-3q=0\quad\Longrightarrow\quad q=\frac{80}{3}`,'The profit function is 80q−1.5q²−100 on 0≤q≤100.',{sequence:'business-tool-choice'}),
 c('17','b','Check the candidate against the feasible range','The candidate is inside [0,100] and profit is concave.','Endpoint profits are −€100 and −€7100; the candidate gives the maximum.'),
 m('18','a','Integrate for an accumulated-money question',String.raw`\int_0^1a(t)\,dt=10000`,'Here the required quantity is a total delivered over one year.'),
 c('18','b','Let the requested quantity choose the tool','A local rate, an optimum and an accumulated amount are different tasks.','Read the question and units before choosing a formula.'),
 t('19','a','Match three business questions to tools',['Business question','Tool','Output unit'],[['Marginal cost at q=20','Differentiate C','€/output unit'],['Profit-maximizing feasible output','Candidate and endpoint comparison','Output units'],['Money delivered over a year','Definite integral of flow','€']],'The same calculus ideas answer different kinds of questions.'),
 q('19','b','Choose a tool with a reason','A delivery rate changes all day. Which tool finds total parcels delivered?','A definite integral over the day; rate × time gives parcels.'),
 m('20','a','Compare two new one-year flows',String.raw`u(t)=8000,\qquad v(t)=4000+8000t`,'Both rules use euros per year and the domain 0≤t≤1.',{sequence:'new-flow-comparison'}),
 m('20','b','Recover both cumulative functions',String.raw`I_U(T)=8000T,\qquad I_V(T)=4000T+4000T^2`,'Both cumulative totals start at zero.',{sequence:'new-flow-comparison'}),
 m('20','c','Evaluate at one year',String.raw`I_U(1)=I_V(1)=8000`,'The rising flow has only caught up at the endpoint of this domain.',{sequence:'new-flow-comparison'}),
 q('20','d','Check a rising-flow shortcut','Does a rising annual flow guarantee more money over the first year?','No. U and V both deliver €8,000 here.'),
 m('21','a','Evaluate the shorter window',String.raw`I_U(0.5)=4000,\qquad I_V(0.5)=3000`,'U leads by €1,000 after six months.'),
 e('21','b','Diagnose an endpoint rectangle','“V delivers 12000×1=€12000 during year one.”','€12,000/year is only the final rate. Integrating the changing flow gives €8,000.'),
 c('22','a','Revisit the original misleading snapshot','At half a year, B’s current rate is €12,000/year.','Its accumulated €4,500 is still below A’s €5,000.'),
 c('22','b','Use the whole interval as evidence','A total depends on the rate history, not just the latest observation.','The rate graph provides the history that an integral accumulates.'),
 c('23','a','Keep the business conclusion bounded','Compare amounts for the stated horizon and model assumptions.','Different horizons, costs or discounting can require a new calculation.'),
 q('23','b','Make a one-sentence decision','For A and B, which plan delivers more at T=0.8, and by how much?','B: 6000(0.8)²−4000(0.8)=€640 more, within the stated one-year model.'),
];
export const guides16=[
 '第1学时：区分流率、累计量与两种交点，逐步计算 A 与 B 的积分，保留半年度预测及核对。英文：Are we comparing the current rate or the amount received so far? 用带单位的数值说明1/3和2/3的差别。',
 '第2学时：以差额积分形成经营判断，再复用边际成本、可行利润优化和新流量案例。英文：Which quantity does this question ask us to find? 出口检查要求附时间窗口与单位；连续贴现只在核心90分钟之后选学。',
] as const;
