import {author,type Insertion} from './authoring.js';import {lesson13} from '../lessons/lesson-13.js';
const {m,c,q,e,t,g}=author(13,lesson13.sources[0]!);
export const additions13:readonly Insertion[]=[
 c('02','a','A slope report has lost its total','A factory records C′(q)=20+q, in euros per output unit.','We need a total-cost rule whose derivative matches that report.'),
 q('02','b','Predict the missing power','Which function differentiates to q: q² or q²/2?','q²/2; its derivative is q.'),
 m('03','a','Recover the constant rate',String.raw`\frac{d}{dq}(20q)=20`,'Multiplying by quantity converts euros per unit into euros.',{sequence:'recover-cost'}),
 m('03','b','Recover the changing rate',String.raw`\frac{d}{dq}\left(\frac{q^2}{2}\right)=q`,'The coefficient compensates for the power rule.',{sequence:'recover-cost'}),
 m('03','c','Combine the two recovered terms',String.raw`F(q)=20q+\frac{q^2}{2}`,'Differentiate both terms to check F′(q)=20+q.',{sequence:'recover-cost'}),
 q('03','d','Check one more candidate','Does 250+20q+q²/2 have the same derivative?','Yes. The derivative of 250 is zero.'),
 m('04','a','Add a level without changing a slope',String.raw`G(q)=F(q)+100`,'At every quantity, G costs €100 more than F.'),
 t('04','b','Compare levels and local rates',['q','F(q) (€)','G(q) (€)','Both derivatives'],[['0','0','100','20'],['10','250','350','30'],['20','600','700','40']],'Different totals can share the same marginal-cost schedule.'),
 g('05','a','Parallel vertical shifts',{xRange:[0,20],yRange:[0,750],xLabel:'q',yLabel:'Cost (€)',curves:[{kind:'polynomial',coefficients:[0,20,.5],color:'blue'},{kind:'polynomial',coefficients:[100,20,.5],color:'coral'}]},String.raw`G-F=100`,'The gap is constant even though both curves become steeper.'),
 e('05','b','Diagnose the missing fixed cost','“The marginal-cost rule proves that fixed cost is zero.”','No. Differentiation removes every constant; a level datum is needed.'),
 m('06','a','Name the unknown vertical shift',String.raw`C(q)=20q+\frac{q^2}{2}+K`,'K represents the unrecovered constant level.',{sequence:'constant-gap'}),
 m('06','b','Differentiate the whole family',String.raw`C'(q)=20+q+0`,'Every constant K produces the same derivative.',{sequence:'constant-gap'}),
 m('06','c','Test the gap between any two members',String.raw`C_2(q)-C_1(q)=K_2-K_1`,'The family differs only by a constant vertical displacement.',{sequence:'constant-gap'}),
 q('06','d','Distinguish family and fitted function','Does an indefinite integral return one function or a family?','A family, until additional information fixes K.'),
 c('07','a','Read the integral sign as a recovery request','Find functions whose derivative with respect to q is 20+q.','The variable after d tells us which variable changes.'),
 m('07','b','Keep the variable consistent',String.raw`\int(20+q)\,dq=20q+\frac{q^2}{2}+K`,'This is an indefinite integral: there are no endpoint bounds.'),
 m('08','a','Reverse the exponent change',String.raw`x^n\longrightarrow x^{n+1}`,'An antiderivative raises the power by one.',{sequence:'power-recovery'}),
 m('08','b','Compensate for differentiation',String.raw`\frac{d}{dx}\left(\frac{x^{n+1}}{n+1}\right)=x^n`,'Division by n+1 cancels the multiplier.',{sequence:'power-recovery'}),
 m('08','c','State the exception',String.raw`n\ne-1`,'The formula cannot divide by zero. The reciprocal case is optional.',{sequence:'power-recovery'}),
 m('08','d','Use the simplest allowed exponent',String.raw`\int x^0\,dx=x+K`,'A constant integrand is included in the power rule.'),
 m('09','a','Restore a cubic from a quadratic',String.raw`\int x^2\,dx=\frac{x^3}{3}+K`,'The new exponent is three, so the divisor is three.'),
 q('09','b','Verify before accepting','Differentiate x³/3+K. What remains?','x². The constant differentiates to zero.'),
 m('10','a','Write the constant as a power',String.raw`5=5x^0`,'This makes the exponent rule visible.'),
 m('10','b','Recover a constant rate over distance',String.raw`\int5\,dx=5x+K`,'A constant rate creates a linear accumulated level.'),
 m('11','a','Keep the multiplier outside',String.raw`\int6x^2\,dx=6\int x^2\,dx`,'The factor 6 does not change with x.'),
 m('11','b','Simplify the coefficient',String.raw`6\frac{x^3}{3}=2x^3`,'The answer still needs an arbitrary constant.'),
 m('12','a','Recover the three terms separately',String.raw`\int(6x^2+4x+3)\,dx`,'Use linearity to split the sum.',{sequence:'three-term-recovery'}),
 m('12','b','Raise powers and divide',String.raw`6\frac{x^3}{3}+4\frac{x^2}{2}+3x+K`,'One arbitrary constant is sufficient for the sum.',{sequence:'three-term-recovery'}),
 m('13','a','Check the simplified result',String.raw`\frac{d}{dx}(2x^3+2x^2+3x+K)=6x^2+4x+3`,'A derivative check tests all three coefficients.',{sequence:'three-term-recovery'}),
 e('13','b','Diagnose an unchanged exponent','“An antiderivative of 6x² is 3x².”','Its derivative is 6x, not 6x². Raise the exponent before dividing.'),
 c('14','a','A single cost datum restores the level','The factory reports total cost C(0)=€100.','The datum includes costs incurred before any output is produced.'),
 m('14','b','Substitute into the recovered family',String.raw`100=20(0)+\frac{0^2}{2}+K`,'Use the same quantity in the known total and the recovered formula.',{sequence:'fit-fixed-cost'}),
 m('14','c','Isolate the constant',String.raw`K=100`,'The level is now fixed, rather than arbitrary.',{sequence:'fit-fixed-cost'}),
 q('14','d','Interpret the fitted constant','What does K=100 mean in this cost example?','Fixed cost of €100, because K=C(0).'),
 m('15','a','Write the fitted total-cost function',String.raw`C(q)=100+20q+\frac{q^2}{2}`,'Its derivative matches the rate and its value at zero matches the datum.',{sequence:'fit-fixed-cost'}),
 c('15','b','Use two independent checks','Check the derivative; then check the supplied total-cost value.','Matching a slope alone does not validate the constant.'),
 m('16','a','Evaluate the variable part at ten units',String.raw`20(10)+\frac{10^2}{2}=250`,'This is the increase above fixed cost, in euros.'),
 m('16','b','Add the recovered level',String.raw`C(10)=100+250=350`,'Total cost includes both the fixed part and the accumulated variable part.'),
 c('17','a','The known datum need not be at zero','Suppose the only reported total is C(10)=€350.','The same constant can be found from a nonzero quantity.'),
 m('17','b','Fit the level at the reported quantity',String.raw`350=20(10)+\frac{10^2}{2}+K`,'Subtract the recovered variable part to obtain K=100.'),
 m('18','a','Recover revenue from marginal revenue',String.raw`R'(q)=100-2q`,'The integral recovers the revenue level up to a constant.',{sequence:'recover-revenue'}),
 m('18','b','Integrate the two terms',String.raw`R(q)=100q-q^2+K`,'A constant and a linear rate become linear and quadratic totals.',{sequence:'recover-revenue'}),
 m('18','c','Use zero sales in the stated model',String.raw`R(0)=0\quad\Longrightarrow\quad K=0`,'With no other revenue source, zero sales implies zero sales revenue.',{sequence:'recover-revenue'}),
 q('18','d','Check marginal revenue recovery','For R(q)=100q−q², what is R′(20)?','60 euros per extra unit.'),
 m('19','a','Recover the marginal-profit family',String.raw`\pi'(q)=80-3q\quad\Longrightarrow\quad\pi(q)=80q-\frac32q^2+K`,'The profit level still requires one observed profit.'),
 m('19','b','Use a loss at zero output',String.raw`\pi(0)=-100\quad\Longrightarrow\quad K=-100`,'Profit at zero may be negative because fixed cost remains.'),
 m('20','a','Expose the unresolved amount',String.raw`C(10)=250+K`,'Without a cost datum, the total cannot be uniquely calculated.'),
 q('20','b','Choose useful extra information','Would C(5)=€212.50 or C′(5)=25 identify K?','C(5)=€212.50 identifies K=100; the derivative datum adds no level information.'),
 c('21','a','Check a proposed recovery by differentiation','For a claimed total, compare its derivative with the given marginal rule.','A mismatch identifies a coefficient or power error before fitting K.'),
 m('21','b','Repair a wrong coefficient',String.raw`\frac{d}{dq}(20q+q^2)=20+2q`,'The q² coefficient must be 1/2 to recover 20+q.'),
 m('22','a','Recover a new factory total',String.raw`C'(q)=6q+4\quad\Longrightarrow\quad C(q)=3q^2+4q+K`,'Use C(0)=80 to set K=80.'),
 m('22','b','Test the fitted formula at three units',String.raw`C(3)=3(9)+4(3)+80=119`,'The total is €119, while the marginal cost at three is €22 per unit.'),
 c('23','a','A marginal report and a datum have different jobs','The rate determines the shape. One total fixes the vertical position.','Together they identify the total function in these polynomial examples.'),
 q('23','b','Recover, fit and verify','Given F′(x)=4x+1 and F(2)=15, find F(x).','F(x)=2x²+x+5. Its derivative is 4x+1 and F(2)=15.'),
];
export const guides13=[
 '第1学时：从同一边际成本对应不同总量入手，完成幂积分、常数与和的逐项恢复；在每段恢复后停顿做求导检查。英文：Which part of the total disappears when we differentiate? 带学生口述指数加一与除数，强调 n≠−1。',
 '第2学时：复核恢复结果，分别使用零产量与非零产量数据确定 K，完成收入和利润恢复。英文：Does this datum tell us a slope or a level? 保留计算、单位与出口检查的暂停；选学倒数与指数积分置于90分钟之后。',
] as const;
