import {author,type Insertion} from './authoring.js';import {lesson12} from '../lessons/lesson-12.js';
const {m,c,q,e,t,g}=author(12,lesson12.sources[0]!);
export const additions12:readonly Insertion[]=[
 c('02','a','Reuse one familiar demand rule','Q(P)=100−2P relates quantity to price in euros.','We will compare responses at different starting prices.'),
 m('02','b','Use positive price and quantity for percentages',String.raw`0<P<50`,'A percentage needs a positive base for the interpretation used here.'),
 m('03','a','Differentiate the demand rule',String.raw`Q'(P)=-2`,'The slope is two fewer quantity units per extra euro.'),
 c('03','b','A constant slope can hide different shocks','The same absolute quantity loss can be a small or large share of the starting demand.','Elasticity compares relative changes.'),
 m('04','a','Divide each change by its own base',String.raw`\frac{\Delta Q}{Q},\qquad\frac{\Delta P}{P}`,'The quantity and price bases are different.'),
 q('04','b','Compare equal quantity losses','Is a loss of 2 units a larger percentage of 20 units or 80 units?','20 units: 10% versus 2.5%.'),
 t('05','a','Record two starting situations',['P (€)','Q(P)'],[['10','80'],['40','20']],'The slope is −2 in both situations, but the bases differ.'),
 q('05','b','Translate a ten-percent price rise','How many euros is a 10% increase from €10 and from €40?','€1 and €4 respectively.'),
 m('06','a','Start with a ratio of relative changes',String.raw`\frac{\Delta Q/Q}{\Delta P/P}`,'This compares percentage responses rather than raw units.',{sequence:'point-elasticity'}),
 m('06','b','Rearrange the finite-change ratio',String.raw`\frac{P}{Q}\frac{\Delta Q}{\Delta P}`,'Both bases refer to the starting point.',{sequence:'point-elasticity'}),
 m('06','c','Use the local quantity slope',String.raw`E(P)=\frac{P}{Q(P)}Q'(P)`,'The derivative defines point elasticity.',{sequence:'point-elasticity'}),
 c('06','d','Keep the sign in the definition','For falling demand, Q′ is negative and signed elasticity is negative.','Classification will use its magnitude.',{sequence:'point-elasticity'}),
 m('07','a','Insert the known derivative',String.raw`E(P)=\frac{P}{100-2P}(-2)`,'The denominator is the current quantity.',{sequence:'point-elasticity'}),
 m('07','b','Combine the numerator',String.raw`E(P)=-\frac{2P}{100-2P}`,'The negative sign records the opposite directions of price and demand.',{sequence:'point-elasticity'}),
 m('07','c','Check cancellation of units',String.raw`\frac{\mathrm{euros}}{\mathrm{units}}\frac{\mathrm{units}}{\mathrm{euro}}=1`,'Elasticity is dimensionless.',{sequence:'point-elasticity'}),
 c('07','d','Point elasticity belongs to a point','Changing the starting price changes the price-to-quantity ratio.','A constant linear slope does not imply constant elasticity.',{sequence:'point-elasticity'}),
 m('08','a','Evaluate the low-price case',String.raw`E(10)=-\frac{20}{80}=-0.25`,'The local quantity percentage is one quarter of the price percentage in magnitude.'),
 q('08','b','Interpret the magnitude at ten','What does |E(10)|=0.25 predict for a small 1% price rise?','Approximately a 0.25% quantity fall locally.'),
 m('09','a','Evaluate the high-price case',String.raw`E(40)=-\frac{80}{20}=-4`,'The same slope now produces a much larger relative response.'),
 c('09','b','The starting quantity magnifies the percentage','At the high price, the quantity base is only twenty.','A quantity loss is a larger share of a smaller base.'),
 t('10','a','Classify by magnitude',['Magnitude','Classification'],[['|E|<1','Inelastic'],['|E|=1','Unit elastic'],['|E|>1','Elastic']],'The sign still describes direction; the magnitude describes sensitivity.'),
 q('10','b','Classify a negative elasticity','Is E=−4 elastic or inelastic under the magnitude convention?','Elastic because |E|=4>1.'),
 m('11','a','Set the magnitude equal to one',String.raw`\frac{2P}{100-2P}=1`,'The denominator is positive on the stated domain.',{sequence:'unit-elastic-price'}),
 m('11','b','Multiply by the positive denominator',String.raw`2P=100-2P`,'This retains the equality.',{sequence:'unit-elastic-price'}),
 m('11','c','Collect price terms and solve',String.raw`4P=100\quad\Longrightarrow\quad P=25`,'The unit-elastic price is inside the domain.',{sequence:'unit-elastic-price'}),
 m('11','d','Recover the quantity and sign',String.raw`Q(25)=50,\qquad E(25)=-1`,'Unit elastic refers to magnitude one, not positive elasticity.',{sequence:'unit-elastic-price'}),
 g('12','a','Read elasticity along the same demand',{xRange:[1,45],yRange:[-10,0],xLabel:'Price P (€)',yLabel:'Signed elasticity',curves:[{kind:'polynomial',coefficients:[0],color:'muted'}],points:[{x:10,y:-.25,label:'Low price'},{x:25,y:-1,label:'Unit elastic'},{x:40,y:-4,label:'High price'}]},String.raw`E=-\frac{2P}{100-2P}`,'The three marked values come from the same linear demand model.'),
 c('12','b','A line need not have one elasticity','Slope remains −2 while the P/Q ratio changes.','Read a rate and a proportional response separately.'),
 m('13','a','Use price as the revenue input',String.raw`R(P)=P\,Q(P)`,'Revenue is now expressed as a function of price.',{sequence:'price-revenue'}),
 m('13','b','Insert the linear demand model',String.raw`R(P)=P(100-2P)`,'Higher price changes both the price factor and sold quantity.',{sequence:'price-revenue'}),
 m('14','a','Differentiate both factors',String.raw`R'(P)=Q(P)+P Q'(P)`,'The product rule retains both effects.',{sequence:'price-revenue'}),
 m('14','b','Insert the actual quantity and slope',String.raw`R'(P)=(100-2P)+P(-2)`,'The quantity response offsets some direct price gain.',{sequence:'price-revenue'}),
 m('14','c','Combine the two price terms',String.raw`R'(P)=100-4P`,'Revenue slope changes with the current price.',{sequence:'price-revenue'}),
 m('14','d','Evaluate at the two earlier prices',String.raw`R'(10)=60,\qquad R'(40)=-60`,'The same price increase has opposite local revenue effects.',{sequence:'price-revenue'}),
 m('15','a','Factor quantity from the revenue derivative',String.raw`R'=Q\left(1+\frac{P Q'}Q\right)`,'Quantity is positive on the stated comparison domain.'),
 m('15','b','Recognize the elasticity term',String.raw`R'=Q(1+E)`,'The sign of 1+E determines the local revenue direction.'),
 m('16','a','Read the inelastic case',String.raw`E=-0.25\quad\Longrightarrow\quad1+E=0.75>0`,'A small price increase locally raises revenue.'),
 c('16','b','The percentage quantity loss is relatively small','The direct price gain exceeds the local loss from quantity.','This is a local prediction at the starting point.'),
 m('17','a','Read the elastic case',String.raw`E=-4\quad\Longrightarrow\quad1+E=-3<0`,'A small price increase locally lowers revenue.'),
 c('17','b','The quantity response can dominate','A higher unit price does not guarantee more revenue.','The magnitude of demand response matters.'),
 m('18','a','Find the revenue stationary price',String.raw`100-4P=0\quad\Longrightarrow\quad P=25`,'It agrees with the unit-elastic point.'),
 m('18','b','Evaluate revenue at that price',String.raw`R(25)=25(50)=1250`,'The negative quadratic curvature supports the peak.'),
 m('19','a','Calculate the new low price',String.raw`P_{new}=10(1.10)=11`,'A ten-percent rise from ten is one euro.',{sequence:'finite-price-change'}),
 m('19','b','Calculate the new demand and receipt',String.raw`Q(11)=78,\qquad R(11)=11(78)=858`,'The original receipt was 10×80=800.',{sequence:'finite-price-change'}),
 m('20','a','Calculate the new high price',String.raw`P_{new}=40(1.10)=44`,'The same percentage now means four euros.',{sequence:'finite-price-change'}),
 m('20','b','Calculate the remaining demand',String.raw`Q(44)=100-88=12`,'Demand falls by eight units, forty percent of the initial twenty.',{sequence:'finite-price-change'}),
 m('20','c','Calculate the new receipt',String.raw`R(44)=44(12)=528`,'The original high-price receipt was also 800.',{sequence:'finite-price-change'}),
 m('20','d','Compare the finite revenue loss',String.raw`\frac{528-800}{800}=-0.34`,'Revenue falls thirty-four percent in this finite comparison.',{sequence:'finite-price-change'}),
 c('21','a','Local sensitivity is not every finite outcome','Point elasticity describes response near the starting point.','For a stated finite price change, calculate the new quantity and revenue too.'),
 q('21','b','Which method verifies the ten-percent case?','Would you report only the local revenue slope, or also calculate R at the new price?','Calculate the new-price revenue to obtain the finite outcome.'),
 e('22','a','A negative sign does not mean inelastic','“E=−4 is below one, so demand is inelastic.”','Use magnitude: |−4|=4, so demand is elastic.'),
 e('22','b','Slope and elasticity have different units','“A slope of −2 means elasticity is always −2.”','Elasticity multiplies slope by P/Q and is dimensionless; it changes along this line.'),
 m('23','a','Calculate the quantity at twenty',String.raw`Q(20)=60`,'The denominator in elasticity is the current quantity.'),
 m('23','b','Evaluate and classify',String.raw`E(20)=-\frac{40}{60}=-\frac23`,'The magnitude is below one, so demand is locally inelastic.')
];
export const guides12=['0–10分钟同斜率不同百分比基数；10–26分钟逐步构造有符号弹性并核对单位；26–36分钟低高价格与单位弹性点；36–41分钟分类检查；41–45分钟短问。话术：“Which base makes this a percentage?” “Keep the sign, classify the magnitude.”','0–14分钟收入乘积求导和弹性联系；14–28分钟两种10%涨价逐项核对有限结果；28–36分钟局部与有限变化区别；36–41分钟符号错解；41–45分钟出口题。话术：“Calculate the new receipt too.” “A local statement has a reference point.”'] as const;
