import {author,type Insertion} from './authoring.js';import {lesson09} from '../lessons/lesson-09.js';
const {m,c,q,e,t,g}=author(9,lesson09.sources[0]!);
export const additions09:readonly Insertion[]=[
 c('02','a','One formula contains a level and a response','C(q)=100+20q+0.5q² describes total cost in euros.','The fixed cost is paid even when q is zero.'),
 m('02','b','Keep the quantity unit visible',String.raw`q=\mathrm{number\ of\ parcels}`,'The cost output is currency; the input counts parcels.'),
 m('03','a','Insert twenty into every variable term',String.raw`C(20)=100+20(20)+0.5(20)^2`,'Use the same output throughout the cost function.',{sequence:'cost-level'}),
 m('03','b','Compute the linear cost part',String.raw`20(20)=400`,'This term contributes four hundred euros.',{sequence:'cost-level'}),
 m('03','c','Compute the quadratic cost part',String.raw`0.5(20)^2=200`,'Square before multiplying by one half.',{sequence:'cost-level'}),
 m('03','d','Add the fixed and variable parts',String.raw`C(20)=100+400+200=700`,'The result is a total, not a per-parcel amount.',{sequence:'cost-level'}),
 m('04','a','Share the total across all parcels',String.raw`AC(20)=\frac{700}{20}=35`,'Average cost is euros per parcel.'),
 q('04','b','What does the average summarize?','Does AC(20)=€35 say the next parcel costs exactly €35?','No. It allocates the current total across twenty parcels.'),
 m('05','a','Calculate the new total at twenty-one',String.raw`C(21)=100+20(21)+0.5(21)^2`,'The next-unit calculation needs the new total.',{sequence:'next-parcel'}),
 m('05','b','Evaluate the new variable terms',String.raw`20(21)=420,\qquad0.5(21)^2=220.5`,'Both variable terms change.',{sequence:'next-parcel'}),
 m('05','c','Add the new total cost',String.raw`C(21)=100+420+220.5=740.5`,'This is the total for all twenty-one parcels.',{sequence:'next-parcel'}),
 m('05','d','Subtract the old total',String.raw`\Delta C=740.5-700=40.5`,'The exact extra parcel adds forty euros and fifty cents.',{sequence:'next-parcel'}),
 m('06','a','Differentiate the total cost',String.raw`C'(q)=0+20+q`,'The fixed part contributes no derivative.',{sequence:'marginal-cost'}),
 m('06','b','Name the derivative',String.raw`MC(q)=20+q`,'Marginal cost is the local rate of total cost change.',{sequence:'marginal-cost'}),
 m('06','c','Evaluate at the current output',String.raw`MC(20)=20+20=40`,'The derivative is taken at twenty, before expansion.',{sequence:'marginal-cost'}),
 c('06','d','A local rate predicts a small change','Multiply the rate by a small quantity step to estimate the total cost increment.','The derivative need not equal a full discrete next-unit cost.',{sequence:'marginal-cost'}),
 g('07','a','Read the tangent at twenty',{xRange:[15,25],yRange:[450,950],xLabel:'Parcels q',yLabel:'Total cost (€)',curves:[{kind:'polynomial',coefficients:[100,20,.5],color:'blue'}],tangent:{curve:0,x:20}},String.raw`m=40`,'The tangent slope is a currency-per-parcel rate.'),
 c('07','b','A tangent is a local reference line','It follows the cost curve closely near the current output.','A larger step can expose the curve-line difference.'),
 t('08','a','Keep three numbers in separate columns',['Quantity','Total','Average','Marginal'],[['q=20','€700','€35/parcel','€40/parcel']],'A level, an allocation and a local rate answer different questions.'),
 q('08','b','Choose the needed quantity','Which value helps estimate the extra cost of a small expansion: total, average or marginal?','Marginal cost, multiplied by the quantity change.'),
 m('09','a','Pair the local rate with the step',String.raw`\Delta C\approx MC(20)\Delta q`,'The step supplies the quantity unit.'),
 m('09','b','Use a one-parcel local estimate',String.raw`\Delta C\approx40(1)=40`,'The estimate differs from the exact €40.50 increment.'),
 m('10','a','Expand the new quadratic cost',String.raw`C(20+h)=100+20(20+h)+0.5(20+h)^2`,'Keep the entire new output inside the square.'),
 m('10','b','Separate first-order and curved contributions',String.raw`C(20+h)-C(20)=40h+0.5h^2`,'The derivative estimate keeps 40h and omits the quadratic remainder.'),
 m('11','a','Calculate a five-parcel estimate',String.raw`MC(20)(5)=200`,'The derivative predicts two hundred euros for the larger step.'),
 q('11','b','Find the omitted remainder','For h=5 in 40h+0.5h², how much does the local estimate omit?','€12.50; the exact increase is €212.50.'),
 m('12','a','Build revenue from quantity and price',String.raw`R(q)=q(100-q)`,'This is the same price-dependent revenue model used earlier.'),
 m('12','b','Expand for a convenient derivative',String.raw`R(q)=100q-q^2`,'The quadratic term records the declining price.'),
 m('13','a','Differentiate revenue',String.raw`MR(q)=100-2q`,'Marginal revenue is the local revenue rate.'),
 m('13','b','Evaluate at twenty parcels',String.raw`MR(20)=60`,'The derivative predicts about sixty euros for a small extra quantity unit.'),
 m('14','a','Calculate the original revenue',String.raw`R(20)=2000-400=1600`,'Keep the current total before calculating the next total.',{sequence:'revenue-increment'}),
 m('14','b','Calculate the new revenue',String.raw`R(21)=2100-441=1659`,'The new output has a lower price per parcel.',{sequence:'revenue-increment'}),
 m('14','c','Subtract to get the finite increase',String.raw`1659-1600=59`,'The exact one-parcel revenue increase is fifty-nine euros.',{sequence:'revenue-increment'}),
 m('14','d','Compare against the local prediction',String.raw`MR(20)(1)=60`,'The curvature reduces the finite increment by one euro.',{sequence:'revenue-increment'}),
 m('15','a','Differentiate net money',String.raw`\pi'(q)=R'(q)-C'(q)`,'Profit changes through both revenue and cost.'),
 m('15','b','Read the marginal profit at twenty',String.raw`60-40=20`,'A small expansion has a positive local profit effect.'),
 m('16','a','Use finite increments for a full next unit',String.raw`\Delta\pi=\Delta R-\Delta C`,'Both terms must refer to the same quantity interval.',{sequence:'profit-increment'}),
 m('16','b','Insert the exact increments',String.raw`\Delta\pi=59-40.5`,'Use the earlier finite changes, not the derivatives.',{sequence:'profit-increment'}),
 m('16','c','Calculate the exact extra profit',String.raw`\Delta\pi=18.5`,'The next parcel adds eighteen euros and fifty cents.',{sequence:'profit-increment'}),
 m('16','d','Measure the local-prediction difference',String.raw`20-18.5=1.5`,'The difference combines revenue and cost curvature.',{sequence:'profit-increment'}),
 m('17','a','Raise only the fixed cost',String.raw`C_2(q)-C_1(q)=100`,'The whole cost curve moves up by one hundred euros.'),
 m('17','b','Compare rates after the fixed-cost change',String.raw`C'_2(q)=C'_1(q)=20+q`,'The average changes, but the marginal derivative does not.'),
 c('18','a','Parcels are discrete; the model is smooth','A differentiable curve approximates a relationship between nearby output levels.','A literal extra parcel requires a finite increment.'),
 c('18','b','State which meaning of marginal you use','Here marginal cost means the derivative of the smooth cost model.','Do not silently replace it by an exact next-unit cost.'),
 m('19','a','A marginal statement needs a reference output',String.raw`MC(30)=50`,'The fifty-euro rate belongs to output thirty.'),
 m('19','b','Use a small signed output change',String.raw`\Delta C\approx50h`,'A negative h describes a small reduction in output.'),
 e('20','a','Average cost is not the next cost','“The next parcel costs €35 because AC(20)=35.”','The exact next cost is €40.50; average cost allocates existing total cost.'),
 e('20','b','A derivative is not an exact full step','“MC(20)=40 proves C(21)−C(20)=40.”','For this quadratic model the exact increment is 40.5, including curvature.'),
 m('21','a','Differentiate the simpler factory model',String.raw`C(q)=80+10q+q^2\quad\Longrightarrow\quad MC=10+2q`,'Keep total and rate formulas separate.'),
 m('21','b','Check at five output units',String.raw`MC(5)=20`,'The local cost rate is twenty currency units per output unit.'),
 q('22','a','Use the local profit test','At q=20, MR=60 and MC=40. What does a small feasible expansion suggest?','A positive local profit change, approximately 20 per extra quantity unit.'),
 c('22','b','A local benefit needs feasibility','Capacity, demand and the size of the step still matter.','A positive current rate is not a complete global production decision.'),
 q('23','a','Finish the sentence precisely','State the difference between “€40 per parcel locally” and “€40.50 for the next parcel.”','The first is the derivative rate at q=20; the second is the exact finite cost increment from 20 to 21.'),
 c('23','b','Attach quantity, unit and interval','A cost conclusion needs its reference output and the kind of change.','This prevents a correct number from answering the wrong question.')
];
export const guides09=['0–12分钟逐项算总成本和平均成本；12–25分钟精确下一件成本；25–36分钟导数、切线和局部估计；36–41分钟较大步误差；41–45分钟短问。话术：“A level, an allocation or a rate?” “Which interval does this change cover?”','0–12分钟收入有限增量与边际收入；12–26分钟利润增量逐步计算；26–34分钟固定成本和离散产量；34–41分钟错解与小幅扩张建议；41–45分钟出口题。话术：“Use the same interval for both increments.” “An estimate needs a step size.”'] as const;
