import {author,type Insertion} from './authoring.js';import {lesson08} from '../lessons/lesson-08.js';
const {m,c,q,e,t,g}=author(8,lesson08.sources[0]!);
export const additions08:readonly Insertion[]=[
 m('02','a','Natural powers and logs reverse each other',String.raw`\ln(e^x)=x`,'The exponential output is positive.'),
 m('02','b','The inverse relation has a domain',String.raw`e^{\ln y}=y,\quad y>0`,'Natural logarithms require a positive input.'),
 g('03','a','Compare equal input steps',{xRange:[0,3],yRange:[0,22],xLabel:'Input x',yLabel:'Exponential value',curves:[{kind:'exponential',scale:1,rate:1,color:'blue'}]},String.raw`f(x)=e^x`,'The absolute increases become larger as x increases.'),
 q('03','b','Predict the later change','For e^x, should a unit step near x=2 add more or less than a unit step near x=0?','More, because the exponential grows faster at larger inputs.'),
 m('04','a','Use the natural exponential derivative',String.raw`(e^x)'=e^x`,'This special base has a derivative equal to its own value.'),
 m('04','b','Check the slope at zero',String.raw`f'(0)=e^0=1`,'The derivative value is one at the zero input.'),
 m('05','a','Keep a constant scale factor',String.raw`(5e^x)'=5(e^x)'`,'Multipliers remain outside differentiation.'),
 m('05','b','Evaluate the scaled slope',String.raw`f'(0)=5e^0=5`,'Scaling the level also scales its local rate.'),
 m('06','a','Identify time inside the exponent',String.raw`u(t)=0.1t`,'The inner variable changes at rate 0.1.',{sequence:'exponential-growth'}),
 m('06','b','Differentiate the outside exponential',String.raw`\frac{d}{du}e^u=e^u`,'The outside alone does not supply the time rate.',{sequence:'exponential-growth'}),
 m('06','c','Include the inner derivative',String.raw`\frac{d}{dt}e^{0.1t}=e^{0.1t}(0.1)`,'Apply the chain rule.',{sequence:'exponential-growth'}),
 c('06','d','Read the parameter as a time rate','If t is measured in years, 0.1 has units per year.','The exponent itself must be dimensionless.',{sequence:'exponential-growth'}),
 m('07','a','Keep the starting scale',String.raw`N(t)=100e^{0.1t}`,'The initial group is one hundred.',{sequence:'exponential-growth'}),
 m('07','b','Differentiate the whole model',String.raw`N'(t)=100(0.1)e^{0.1t}`,'Both the starting scale and inner rate remain.',{sequence:'exponential-growth'}),
 m('07','c','Simplify the coefficient',String.raw`N'(t)=10e^{0.1t}`,'The derivative is a group increase per time unit.',{sequence:'exponential-growth'}),
 m('07','d','Check the initial local increase',String.raw`N'(0)=10`,'The current rate is ten group units per time unit.',{sequence:'exponential-growth'}),
 t('08','a','Larger groups have larger absolute rates',['Group size','100','200','500'],[['Current increase rate','10','20','50']],'All three cases share the same relative rate.'),
 q('08','b','Use the current group size','When N=300 under N′=0.1N, what is the current increase rate?','30 group units per time unit.'),
 m('09','a','Divide the rate by the level',String.raw`\frac{N'}N=\frac{10e^{0.1t}}{100e^{0.1t}}`,'The common positive exponential factor cancels.'),
 m('09','b','Interpret the relative rate',String.raw`\frac{N'}N=0.1`,'This is an instantaneous relative rate, not an exact finite-step percentage.'),
 m('10','a','A negative exponent creates decay',String.raw`V(t)=100e^{-0.2t}`,'The exponential value remains positive.',{sequence:'exponential-decay'}),
 m('10','b','Differentiate the decreasing model',String.raw`V'(t)=100e^{-0.2t}(-0.2)`,'The negative inner derivative controls the sign.',{sequence:'exponential-decay'}),
 m('11','a','Read the initial decay rate',String.raw`V'(0)=-20`,'The level initially falls by twenty units per time unit.',{sequence:'exponential-decay'}),
 q('11','b','A falling positive level','Does V′<0 imply V<0 for this exponential decay model?','No. V remains positive while its derivative is negative.'),
 t('12','a','Compare logarithmic increments',['x','1','2','4'],[['ln x','0','0.6931','1.3863']],'Doubling gives equal log differences, while equal additive steps do not.'),
 c('12','b','The logarithm rises with diminishing slope','Its output increases on positive inputs.','Each later unit of input contributes less additional output.'),
 m('13','a','Use the logarithmic derivative',String.raw`(\ln x)'=\frac1x`,'The core real domain is x>0.',{sequence:'logarithmic-rate'}),
 m('13','b','Evaluate at input one',String.raw`f'(1)=1`,'The log slope is one at x=1.',{sequence:'logarithmic-rate'}),
 m('13','c','Evaluate at input two',String.raw`f'(2)=\frac12`,'The slope is smaller at a larger input.',{sequence:'logarithmic-rate'}),
 m('13','d','Evaluate at input four',String.raw`f'(4)=\frac14`,'The rate continues to decline while staying positive.',{sequence:'logarithmic-rate'}),
 g('14','a','Plot the derivative itself',{xRange:[.5,4],yRange:[0,2.2],xLabel:'Positive input x',yLabel:'Log slope',curves:[{kind:'power',scale:1,power:-1,color:'green'}]},String.raw`y=1/x`,'The derivative graph is different from the log-level graph.'),
 c('14','b','A slope graph answers a new question','Its height is now a rate, rather than the original response level.','Always read the vertical axis label.'),
 m('15','a','Scale the logarithmic response',String.raw`B(x)=3\ln x`,'The coefficient triples every response level.'),
 m('15','b','Scale its rate as well',String.raw`B'(x)=\frac3x`,'The domain remains x>0.'),
 m('16','a','Name the inner logarithm input',String.raw`u=2x+1`,'The logarithm requires u>0.',{sequence:'nested-log'}),
 m('16','b','Differentiate the outer logarithm',String.raw`\frac{d}{du}\ln u=\frac1u`,'The denominator is the entire inner value.',{sequence:'nested-log'}),
 m('16','c','Multiply by the inner derivative',String.raw`f'(x)=\frac1{2x+1}(2)`,'The inner slope supplies the numerator.',{sequence:'nested-log'}),
 m('16','d','Solve the positive-input restriction',String.raw`2x+1>0\quad\Longrightarrow\quad x>-\frac12`,'The derivative and original function need valid logarithm inputs.',{sequence:'nested-log'}),
 m('17','a','Evaluate at a permitted value',String.raw`f'(1)=\frac2{2(1)+1}=\frac23`,'Check the original log argument before calculating.'),
 q('17','b','Reject an invalid input','Can ln(2x+1) be evaluated as a real number at x=−1?','No. Its argument is −1, which is not positive.'),
 m('18','a','Follow a scaled inner input',String.raw`(\ln(3x))'=\frac1{3x}(3)`,'The chain rule includes the factor three.'),
 m('18','b','Cancel without erasing the domain',String.raw`\frac3{3x}=\frac1x,\quad x>0`,'The positive-domain condition comes from the original function.'),
 m('19','a','Differentiate an exponential-plus-log sum',String.raw`(2e^x+3\ln x)'=2e^x+\frac3x`,'Add the two separate derivatives.'),
 c('19','b','Use the common domain of a sum','The exponential permits all real inputs, but the logarithm requires x>0.','The combined function uses the stricter restriction.'),
 m('20','a','Identify both product factors',String.raw`u=x,\qquad v=e^x`,'Neither factor is constant.',{sequence:'exponential-product'}),
 m('20','b','Differentiate each factor',String.raw`u'=1,\qquad v'=e^x`,'Retain the original factors for the product rule.',{sequence:'exponential-product'}),
 m('20','c','Add both contributions',String.raw`f'=1(e^x)+x(e^x)`,'The same exponential appears in both terms.',{sequence:'exponential-product'}),
 m('20','d','Factor the shared exponential',String.raw`f'=e^x(1+x)`,'Factoring simplifies the final expression.',{sequence:'exponential-product'}),
 t('21','a','Read selected logarithm rates',['x','0.5','1','2'],[['1/x','2','1','0.5']],'Inputs close to zero from above have larger positive log slopes.'),
 c('21','b','A positive log slope does not give a uniform gain','The size of the gain depends on the current input.','One unit of change is relatively larger at a small base.'),
 e('22','a','An inner exponential rate cannot be omitted','“(e^(2x))′=e^(2x).”','The derivative is 2e^(2x), because the exponent has derivative 2.'),
 e('22','b','Logarithms do not differentiate to themselves','“(ln x)′=ln x.”','For x>0, the derivative is 1/x.'),
 m('23','a','Compute the full first-step increase',String.raw`N(1)-N(0)=100(e^{0.1}-1)`,'This is a finite increase rather than an instantaneous rate.'),
 q('23','b','Compare local and finite growth','N′(0)=10 while N(1)−N(0)≈10.517. Which is the exact one-step change?','Approximately 10.517 is the finite change; 10 is the initial derivative rate.')
];
export const guides08=['0–10分钟自然指数与对数互逆；10–24分钟逐步求指数增长导数；24–35分钟绝对与相对增长率、衰减；35–41分钟比较有限增长；41–45分钟短问。话术：“The exponent has its own rate.” “Relative rate is not a finite percentage.”','0–12分钟对数斜率与正定义域；12–26分钟嵌套对数逐步求导；26–36分钟指数乘积与和；36–41分钟错误诊断和输入检查；41–45分钟出口题。话术：“The whole argument belongs in the denominator.” “Check positivity first.”'] as const;
