import {author,type Insertion} from './authoring.js';import {lesson11} from '../lessons/lesson-11.js';
const {m,c,q,e,t,g}=author(11,lesson11.sources[0]!);
export const additions11:readonly Insertion[]=[
 c('02','a','Output affects the selling price','The model p(q)=100−q lowers price as output increases.','Revenue must include this price response.'),
 m('02','b','State the nonnegative price range',String.raw`0\le q\le100`,'The planning problem will compare feasible output levels.'),
 m('03','a','Write the revenue identity',String.raw`R(q)=q\,p(q)`,'Revenue is unit price times quantity.',{sequence:'profit-model'}),
 m('03','b','Insert the demand-related price',String.raw`R(q)=q(100-q)`,'Both factors use the same quantity.',{sequence:'profit-model'}),
 m('03','c','Expand the revenue function',String.raw`R(q)=100q-q^2`,'The falling price contributes the negative quadratic term.',{sequence:'profit-model'}),
 c('03','d','Revenue is only the inflow side','The receipt does not yet subtract production costs.','Do not choose output from revenue alone.',{sequence:'profit-model'}),
 m('04','a','Record the fixed cost',String.raw`FC=100`,'This model pays the fixed cost even at zero output.',{sequence:'profit-model'}),
 m('04','b','Record the variable cost',String.raw`VC(q)=20q+0.5q^2`,'Variable cost rises with production.',{sequence:'profit-model'}),
 m('04','c','Combine total cost',String.raw`C(q)=100+20q+0.5q^2`,'The total includes both parts.',{sequence:'profit-model'}),
 m('04','d','Check cost at zero',String.raw`C(0)=100`,'The baseline fixed payment is retained.',{sequence:'profit-model'}),
 m('05','a','Subtract the whole cost expression',String.raw`\pi(q)=(100q-q^2)-(100+20q+0.5q^2)`,'Apply the subtraction to every cost term.',{sequence:'profit-model'}),
 m('05','b','Collect linear terms',String.raw`100q-20q=80q`,'Revenue and linear cost have opposite signs in profit.',{sequence:'profit-model'}),
 m('05','c','Collect quadratic terms',String.raw`-q^2-0.5q^2=-1.5q^2`,'Both terms reduce profit at larger output.',{sequence:'profit-model'}),
 m('05','d','Write the complete profit objective',String.raw`\pi(q)=80q-1.5q^2-100`,'This is the function to maximize.',{sequence:'profit-model'}),
 g('06','a','Read the feasible profit hill',{xRange:[0,60],yRange:[-1000,1100],xLabel:'Output q',yLabel:'Profit',curves:[{kind:'polynomial',coefficients:[-100,80,-1.5],color:'green'}]},String.raw`\pi(q)=80q-1.5q^2-100`,'A plotted peak suggests a candidate; calculation supplies the decision.'),
 c('06','b','A high profit level differs from a fast increase','The current height gives profit; the slope gives its local change.','Near the peak, the level is high while the slope approaches zero.'),
 m('07','a','Differentiate the profit objective',String.raw`\pi'(q)=80-3q`,'The derivative measures marginal profit.'),
 m('07','b','Connect it to revenue and cost rates',String.raw`\pi'=MR-MC`,'Extra revenue must be compared with extra cost.'),
 m('08','a','Read a positive marginal profit',String.raw`\pi'(20)=80-60=20`,'A small feasible expansion locally raises profit.'),
 q('08','b','Which comparison suggests expansion?','If MR is 60 and MC is 40, what is the marginal profit?','20 currency units per output unit; locally positive.'),
 m('09','a','Read a negative marginal profit',String.raw`\pi'(30)=80-90=-10`,'A small expansion locally lowers profit.'),
 q('09','b','Which direction helps locally?','At a feasible interior point with marginal profit −10, does a small output reduction raise or lower profit?','It raises profit locally, provided the reduction stays feasible.'),
 m('10','a','Set the interior profit rate to zero',String.raw`80-3q=0`,'This locates a stationary candidate.',{sequence:'stationary-profit'}),
 m('10','b','Move the quantity term',String.raw`3q=80`,'Keep the positive coefficient before dividing.',{sequence:'stationary-profit'}),
 m('10','c','Solve the candidate exactly',String.raw`q^*=\frac{80}{3}`,'Retain the exact fraction until reporting.',{sequence:'stationary-profit'}),
 m('10','d','Check the candidate domain',String.raw`0<\frac{80}{3}<100`,'The stationary candidate is feasible for the initial model.',{sequence:'stationary-profit'}),
 m('11','a','Write the equivalent marginal condition',String.raw`100-2q=20+q`,'The equality MR=MC comes from zero marginal profit.',{sequence:'stationary-profit'}),
 m('11','b','Collect both sides',String.raw`80=3q`,'This is the same stationary equation.',{sequence:'stationary-profit'}),
 m('11','c','Evaluate marginal revenue at the candidate',String.raw`MR(80/3)=\frac{140}{3}`,'The common rate is about 46.67.',{sequence:'stationary-profit'}),
 m('11','d','Evaluate marginal cost at the candidate',String.raw`MC(80/3)=\frac{140}{3}`,'The two local rates match.',{sequence:'stationary-profit'}),
 m('12','a','Calculate the second derivative',String.raw`\pi''(q)=-3`,'The profit slope decreases everywhere in this model.'),
 c('12','b','Concavity classifies the interior point','A negative second derivative at the stationary point gives a local maximum.','Endpoint comparison completes the interval decision.'),
 m('13','a','Evaluate zero production',String.raw`\pi(0)=-100`,'The fixed cost remains at the left endpoint.',{sequence:'profit-boundaries'}),
 m('13','b','Evaluate the price-zero endpoint',String.raw`\pi(100)=-7100`,'Producing one hundred units earns no price revenue but incurs costs.',{sequence:'profit-boundaries'}),
 m('13','c','Evaluate the stationary objective',String.raw`\pi(80/3)=\frac{2900}{3}`,'The candidate profit is approximately 966.67.',{sequence:'profit-boundaries'}),
 t('13','d','Compare feasible values',['q','0','80/3','100'],[['Profit','−100','2900/3','−7100']],'The interior candidate has the largest value.',{sequence:'profit-boundaries'}),
 m('14','a','Recover the selling price',String.raw`p^*=100-\frac{80}{3}=\frac{220}{3}`,'An output recommendation also identifies its model price.'),
 c('14','b','Report the complete recommendation','The continuous optimum is q=80/3 with price 220/3 and profit 2900/3.','State the model and feasible interval with these values.'),
 c('15','a','A smaller capacity changes feasibility','A firm may be limited to q≤20.','The earlier stationary quantity cannot be chosen.'),
 q('15','b','Is the old optimum still available?','Does q=80/3 satisfy a capacity bound of twenty?','No. The constrained problem needs a new candidate comparison.'),
 m('16','a','Read the derivative at capacity',String.raw`\pi'(20)=20>0`,'The profit is still rising as the feasible interval ends.'),
 m('16','b','Evaluate the constrained maximum',String.raw`\pi(20)=900`,'The maximum on [0,20] occurs at capacity, even though MR exceeds MC there.'),
 m('17','a','Locate neighboring whole outputs',String.raw`26<\frac{80}{3}<27`,'Indivisible units require checking nearby integers.',{sequence:'integer-output'}),
 m('17','b','Evaluate twenty-six units',String.raw`\pi(26)=966`,'Use the original profit function.',{sequence:'integer-output'}),
 m('17','c','Evaluate twenty-seven units',String.raw`\pi(27)=966.5`,'The larger neighboring integer has slightly higher profit.',{sequence:'integer-output'}),
 m('17','d','Check the next integer for comparison',String.raw`\pi(28)=964`,'Concavity and these comparisons support choosing twenty-seven whole units.',{sequence:'integer-output'}),
 m('18','a','The revenue optimum answers another question',String.raw`R'(q)=100-2q=0\quad\Longrightarrow\quad q=50`,'The revenue peak ignores the changing cost side.'),
 q('18','b','Compare objectives at fifty','At q=50, revenue is 2500 and cost is 2350. Is this the profit optimum?','No. Profit is only 150, below the verified maximum.'),
 m('19','a','Change the fixed cost parameter',String.raw`\pi_F(q)=80q-1.5q^2-F`,'A higher unavoidable fixed cost shifts all profit levels downward.'),
 m('19','b','Check whether the stationary equation changes',String.raw`\pi_F'(q)=80-3q`,'The interior optimizing quantity is unchanged under these fixed-cost assumptions.'),
 e('20','a','A candidate outside capacity cannot be chosen','“Produce 26.67 units even though capacity is twenty.”','The proposed output is infeasible. On [0,20], compare the feasible boundary values.'),
 c('20','b','Write the constraint before solving','Capacity determines which outputs can enter the comparison.','Keep the chosen output inside the feasible set.'),
 m('21','a','Set up a second firm objective',String.raw`\pi(q)=12q-q^2-20,\quad0\le q\le8`,'A new model gets its own feasible interval.',{sequence:'second-firm'}),
 m('21','b','Differentiate and solve',String.raw`12-2q=0\quad\Longrightarrow\quad q=6`,'Six is feasible for this firm.',{sequence:'second-firm'}),
 m('21','c','Evaluate the candidate',String.raw`\pi(6)=72-36-20=16`,'The candidate profit is sixteen.',{sequence:'second-firm'}),
 t('21','d','Compare with both boundaries',['q','0','6','8'],[['Profit','−20','16','12']],'The candidate exceeds both endpoints.',{sequence:'second-firm'}),
 m('22','a','Restrict the second firm to four units',String.raw`\pi(4)=48-16-20=12`,'The interior candidate six is no longer feasible.'),
 q('22','b','Use the smaller feasible interval','For the second firm on [0,4], should the maximum be at six or four?','Four; profit is increasing throughout the allowed interval.'),
 e('23','a','MR equals MC is not a universal stopping instruction','“Every constrained optimum must satisfy MR=MC.”','An optimum can occur at a capacity boundary with MR>MC. Interior conditions do not replace constraints.'),
 c('23','b','A recommendation needs a condition and a check','Explain the objective, domain, candidate classification and comparisons.','The production rule is bounded by the model assumptions.')
];
export const guides11=['0–14分钟从价量逐步构造收入、成本和利润；14–25分钟看利润斜率和边际差；25–37分钟求驻点及MR=MC；37–41分钟形状与候选检查；41–45分钟短问。话术：“Which function is the objective?” “Extra revenue minus extra cost.”','0–12分钟逐项比较端点并报告价量利润；12–24分钟容量与整数量逐步检查；24–32分钟固定成本与收入目标的区别；32–41分钟第二企业案例；41–45分钟出口题。话术：“Feasibility comes first.” “Check neighboring whole quantities.”'] as const;
