import {author,type Insertion} from './authoring.js';import {lesson03} from '../lessons/lesson-03.js';
const {m,c,q,e,t,g}=author(3,lesson03.sources[0]!);
export const additions03:readonly Insertion[]=[
 c('02','a','A larger quantity can lower the price','The ticket model charges p(q)=100−q dollars per ticket.','Price and quantity change together.'),
 t('02','b','Read the price schedule',['q','10','30','50'],[['p(q) ($)','90','70','50']],'Higher modelled sales require a lower price.'),
 m('03','a','Multiply the unit price by quantity',String.raw`R(q)=p(q)q`,'Revenue is money received before costs.',{sequence:'ticket-revenue'}),
 m('03','b','Substitute the price rule',String.raw`R(q)=(100-q)q`,'The same q appears in both factors.',{sequence:'ticket-revenue'}),
 m('04','a','Distribute the quantity',String.raw`q(100-q)=100q-q^2`,'The moving price creates a quadratic term.',{sequence:'ticket-revenue'}),
 m('04','b','Test a twenty-ticket receipt',String.raw`R(20)=100(20)-20^2=1600`,'Twenty tickets at eighty dollars give the same revenue.',{sequence:'ticket-revenue'}),
 t('05','a','Equal quantity steps, unequal revenue steps',['q','20','30','40'],[['R(q) ($)','1600','2100','2400']],'The successive gains are $500 and $300.'),
 q('05','b','Will ten more always add the same revenue?','Revenue rises $500 from 20 to 30 tickets. Must it rise $500 from 30 to 40?','No. The price falls with quantity; the next gain is $300.'),
 m('06','a','Match each coefficient to its term',String.raw`100q-q^2=-1q^2+100q+0`,'The quadratic coefficient is −1, not 100.'),
 c('06','b','A nonzero square term makes it quadratic','The coefficient of q² must be nonzero.','A zero quadratic coefficient reduces the expression to a line.'),
 c('07','a','The leading sign controls the bend','A negative quadratic coefficient gives a downward opening parabola.','It permits a peak, but the feasible domain still matters.'),
 e('07','b','A negative coefficient is not a negative value','“Because the q² coefficient is negative, all revenues are negative.”','The full expression can be positive. At q=20 revenue is $1600.'),
 m('08','a','Use the factored revenue form',String.raw`q(100-q)=0`,'A zero product requires at least one zero factor.',{sequence:'revenue-zeros'}),
 m('08','b','Read the first zero factor',String.raw`q=0`,'Selling no tickets gives no ticket revenue.',{sequence:'revenue-zeros'}),
 m('09','a','Read the second zero factor',String.raw`100-q=0\quad\Longrightarrow\quad q=100`,'The price reaches zero at one hundred tickets.',{sequence:'revenue-zeros'}),
 c('09','b','Two zeros can have different meanings','Zero quantity and zero price both make revenue vanish.','Keep the algebraic roots connected to the receipt.',{sequence:'revenue-zeros'}),
 m('09','c','Check the factors in a second equation',String.raw`(x-2)(x-3)=x^2-3x-2x+6`,'The cross terms combine to −5x.'),
 m('10','a','Identify a, b and c before substitution',String.raw`x^2-5x+6=0:\quad a=1,\ b=-5,\ c=6`,'The sign belongs to the coefficient.',{sequence:'quadratic-roots'}),
 m('10','b','Calculate the discriminant',String.raw`b^2-4ac=(-5)^2-4(1)(6)=1`,'A positive discriminant permits two real roots.',{sequence:'quadratic-roots'}),
 m('10','c','Calculate the square root',String.raw`\sqrt{1}=1`,'The plus-or-minus sign in the formula supplies the two branches.',{sequence:'quadratic-roots'}),
 q('10','d','Keep the coefficient sign','If b=−5, what is −b in the quadratic formula?','+5.'),
 m('11','a','Use the plus branch',String.raw`x=\frac{5+1}{2}=3`,'The denominator is 2a, here equal to two.',{sequence:'quadratic-roots'}),
 m('11','b','Use the minus branch',String.raw`x=\frac{5-1}{2}=2`,'Both real solutions must be recorded.',{sequence:'quadratic-roots'}),
 m('11','c','Check one root in the original expression',String.raw`2^2-5(2)+6=4-10+6=0`,'Substitution checks arithmetic and signs.',{sequence:'quadratic-roots'}),
 m('11','d','Check the other root',String.raw`3^2-5(3)+6=9-15+6=0`,'Both returned values solve the equation.',{sequence:'quadratic-roots'}),
 t('12','a','Use test points between and beyond roots',['x','1','2.5','4'],[['x²−5x+6','2','−0.25','2']],'The expression is negative between the two roots.'),
 c('12','b','Roots divide a sign diagram','The factors can change sign only at their zeros.','Test each interval rather than guessing from one point.'),
 m('13','a','Find the midpoint of the revenue zeros',String.raw`\frac{0+100}{2}=50`,'The revenue parabola is symmetric around q=50.'),
 t('13','b','Check a symmetric pair',['q','40','50','60'],[['R(q) ($)','2400','2500','2400']],'Equal distances from the symmetry axis give equal values.'),
 q('13','c','Predict the matching value','If R(30)=2100, what is R(70) by symmetry around q=50?','$2100; both quantities are twenty units from the symmetry axis.'),
 m('14','a','Reorder the revenue polynomial',String.raw`100q-q^2=-(q^2-100q)`,'Factor the negative sign before completing the square.',{sequence:'revenue-peak'}),
 m('14','b','Complete the square inside the bracket',String.raw`q^2-100q=(q-50)^2-2500`,'The middle term is −2×50×q.',{sequence:'revenue-peak'}),
 m('14','c','Return to the original sign',String.raw`R(q)=2500-(q-50)^2`,'A nonnegative square is subtracted from 2500.',{sequence:'revenue-peak'}),
 c('14','d','Locate the largest possible value','The square is smallest when q=50.','The model revenue cannot exceed $2500.',{sequence:'revenue-peak'}),
 m('15','a','Recover the price at the peak',String.raw`p(50)=100-50=50`,'The quantity answer determines a price answer.',{sequence:'revenue-peak'}),
 m('15','b','Check the peak receipt directly',String.raw`50\times50=2500`,'The multiplication confirms the completed-square result.',{sequence:'revenue-peak'}),
 c('16','a','Costs describe another money flow','C(q)=100+20q+0.5q² contains fixed and variable costs.','The fixed part remains when no tickets are sold.'),
 m('16','b','Calculate costs at twenty tickets',String.raw`C(20)=100+400+200=700`,'Costs must use the same output as revenue.',{sequence:'ticket-profit'}),
 m('16','c','Separate fixed and variable cost',String.raw`VC(20)=400+200=600`,'Adding the $100 fixed part gives total cost $700.',{sequence:'ticket-profit'}),
 m('17','a','Subtract the entire cost function',String.raw`\pi(q)=(100q-q^2)-(100+20q+0.5q^2)`,'The minus sign applies to every cost term.',{sequence:'ticket-profit'}),
 m('17','b','Collect like terms',String.raw`\pi(q)=80q-1.5q^2-100`,'The fixed cost appears with a negative sign in profit.',{sequence:'ticket-profit'}),
 m('18','a','Use equal output on both sides',String.raw`\pi(20)=R(20)-C(20)`,'A comparison at different quantities would not be this profit.',{sequence:'ticket-profit'}),
 m('18','b','Calculate the net result',String.raw`1600-700=900`,'At twenty tickets the model profit is nine hundred dollars.',{sequence:'ticket-profit'}),
 m('18','c','Verify with the collected profit rule',String.raw`80(20)-1.5(20)^2-100=900`,'The direct polynomial evaluation agrees with revenue minus cost.',{sequence:'ticket-profit'}),
 t('19','a','A quantity comparison needs profit too',['q','Revenue','Cost','Profit'],[['20','1600','700','900'],['50','2500','2350','150']],'More revenue can accompany less profit.'),
 q('19','b','Do more sales guarantee more profit?','Compare the model profits at q=20 and q=50. What does the result show?','Profit falls from $900 to $150; higher sales do not guarantee higher profit.'),
 c('20','a','Break-even means two money flows match','Revenue equals total cost, so profit is zero.','Break-even is different from maximizing either flow.'),
 m('20','b','Write the break-even equation',String.raw`80q-1.5q^2-100=0`,'The roots are candidate output levels, subject to the domain.'),
 c('21','a','A root must also be a feasible output','The model permits quantities from zero to one hundred.','An algebraic answer must be checked against business constraints.'),
 q('21','b','Interpret a fractional ticket count','A model root is 1.28 tickets. Can a firm literally sell 1.28 indivisible tickets?','No. The continuous model can locate a boundary; whole-ticket decisions need separate checks.'),
 c('22','a','Change one coefficient at a time','A coefficient change can move the curve, change its curvature, or shift its symmetry axis.','Specify what changed before comparing graphs.'),
 m('22','b','A fixed cost shifts profit vertically',String.raw`\pi_K(q)=80q-1.5q^2-K`,'Changing K does not change the revenue curve.'),
 e('23','a','Revenue leaves out the cost side','“The largest revenue is automatically the largest profit.”','Profit equals revenue minus cost. Changing costs can move the profit-maximizing output.'),
 m('23','b','Repair a missing bracket',String.raw`R-(100+20q)=R-100-20q`,'Subtract both cost terms, not just the first.'),
 q('23','c','Read an empty-operation profit','At q=0, revenue is zero and fixed cost is $100. What is profit?','−$100 under the stated cost model.'),
 c('23','d','Name the objective before optimizing','Maximum sales, maximum revenue and maximum profit are different questions.','Choose the function that answers the stated decision.')
];
export const guides03=['0–8分钟票价随销量变化；8–20分钟逐步构造收入并识别二次项；20–32分钟因式分解与公式求根；32–40分钟符号和对称性；40–45分钟检查。话术：“Both factors move.” “Keep the sign in the coefficient.”','0–13分钟完成平方并核对收入峰值；13–27分钟逐步计算成本和利润；27–35分钟比较销量与利润；35–41分钟盈亏平衡和可行范围；41–45分钟出口题。话术：“Subtract the whole cost.” “Which objective are we maximizing?”'] as const;
