import {author,type Insertion} from './authoring.js';import {lesson06} from '../lessons/lesson-06.js';
const {m,c,q,e,t,g}=author(6,lesson06.sources[0]!);
export const additions06:readonly Insertion[]=[
 t('02','a','Three bills respond differently',['q','0','1','2'],[['Fixed fee','10','10','10'],['Linear charge','10','12','14'],['Curved charge','10','12.1','14.4']],'Equal input steps reveal different patterns of change.'),
 q('02','b','Which bill never changes?','If output rises but the fee stays $10, what instantaneous slope should its graph have?','Zero.'),
 m('03','a','Compare two constant outputs',String.raw`\frac{10-10}{h}=0,\quad h\ne0`,'Every nonzero interval gives zero change.'),
 c('03','b','A fixed amount disappears from a rate','The derivative of a constant is zero.','The constant still matters for the level of the original function.'),
 m('04','a','Start with the simplest moving term',String.raw`\frac{(x+h)-x}{h}=1`,'A unit input change produces the same output change.'),
 m('04','b','Scale the rate with the coefficient',String.raw`\frac{2(x+h)-2x}{h}=2`,'A constant multiplier scales the derivative too.'),
 m('05','a','Recall the square difference quotient',String.raw`\frac{(x+h)^2-x^2}{h}`,'The earlier motion calculation applies at any allowed x.'),
 m('05','b','Expand the square',String.raw`(x+h)^2-x^2=2xh+h^2`,'The x² terms cancel.'),
 m('05','c','Factor and simplify',String.raw`\frac{h(2x+h)}h=2x+h`,'The identity requires h≠0.'),
 m('05','d','Take the limit',String.raw`\lim_{h\to0}(2x+h)=2x`,'The derivative of x² is 2x.'),
 c('06','a','Two actions form the power rule','Multiply by the exponent, then reduce that exponent by one.','Keep these as two separate actions.'),
 m('06','b','Apply the rule symbolically',String.raw`x^n\longmapsto nx^{n-1}`,'Use the rule only where the real function and derivative are defined.'),
 m('07','a','Bring down the cube exponent',String.raw`x^3\longmapsto3x^{3-1}`,'The original exponent supplies the new coefficient.',{sequence:'scaled-cube'}),
 q('07','b','Check the new exponent','For x³, is the new exponent 3 or 2?','2: reduce the original exponent by one.'),
 m('08','a','Leave the outside coefficient in place',String.raw`\frac{d}{dx}(5x^3)=5\frac{d}{dx}(x^3)`,'A constant multiplier does not change the input.',{sequence:'scaled-cube'}),
 m('08','b','Differentiate the power inside',String.raw`5(3x^2)`,'The exponent contributes its own factor of three.',{sequence:'scaled-cube'}),
 m('08','c','Combine the numeric factors',String.raw`5\times3=15`,'Only the coefficients multiply.',{sequence:'scaled-cube'}),
 m('08','d','Read the derivative as a function',String.raw`f'(x)=15x^2`,'Its value still depends on x.',{sequence:'scaled-cube'}),
 m('09','a','Separate fixed and variable charge',String.raw`C(q)=10+2q`,'Differentiate the two terms independently.'),
 m('09','b','Add the separate rates',String.raw`C'(q)=0+2`,'A sum of functions gives a sum of derivatives.'),
 m('10','a','List the three cost terms',String.raw`C(q)=10+2q+0.1q^2`,'Keep the fixed, linear and quadratic parts visible.',{sequence:'curved-cost'}),
 m('10','b','Differentiate the fixed and linear parts',String.raw`\frac{d}{dq}(10+2q)=0+2`,'These two terms contribute a constant rate.',{sequence:'curved-cost'}),
 m('10','c','Differentiate the curved part',String.raw`\frac{d}{dq}(0.1q^2)=0.1(2q)`,'Both the original coefficient and exponent contribute.',{sequence:'curved-cost'}),
 m('10','d','Combine the derivative terms',String.raw`C'(q)=2+0.2q`,'The local cost rate increases with output.',{sequence:'curved-cost'}),
 m('11','a','Evaluate after differentiating',String.raw`C'(5)=2+0.2(5)`,'Substituting first would leave only a number to differentiate.',{sequence:'curved-cost'}),
 q('11','b','Level or local rate?','C′(5)=3. Does that mean the total cost of five units is $3?','No. It is the local cost rate at q=5, in dollars per unit.'),
 g('12','a','Compare a curved level and its rate',{xRange:[0,10],yRange:[0,6],xLabel:'Output q',yLabel:'Local cost rate',curves:[{kind:'polynomial',coefficients:[2,.2],color:'green'}]},String.raw`C'(q)=2+0.2q`,'A quadratic cost has a linear derivative.'),
 c('12','b','Differentiation lowers the polynomial degree','The squared term becomes a linear term.','The degree falls by one for a nonconstant polynomial.'),
 m('13','a','Keep subtraction signs attached',String.raw`\frac{d}{dx}(-2x^2)=-4x`,'A negative coefficient remains negative.'),
 m('13','b','Combine a longer polynomial',String.raw`(5x^3-2x^2+7x-4)'=15x^2-4x+7`,'The constant vanishes and the other signs remain.'),
 m('14','a','Evaluate a negative rate',String.raw`f'(2)=-2(2)=-4`,'A negative derivative means the function decreases locally.'),
 c('14','b','The derivative sign is a direction','A positive level can still have a negative rate.','Do not confuse the sign of f with the sign of f′.'),
 m('15','a','Rewrite a reciprocal as a power',String.raw`\frac1x=x^{-1},\quad x\ne0`,'The domain excludes zero.',{sequence:'reciprocal-rate'}),
 m('15','b','Bring down the negative exponent',String.raw`(x^{-1})'=-1x^{-2}`,'The exponent contributes a negative coefficient.',{sequence:'reciprocal-rate'}),
 m('15','c','Rewrite the new negative power',String.raw`-x^{-2}=-\frac1{x^2}`,'The denominator is squared.',{sequence:'reciprocal-rate'}),
 m('15','d','Check the sign at a positive input',String.raw`f'(2)=-\frac14`,'The reciprocal falls as a positive input increases.',{sequence:'reciprocal-rate'}),
 m('16','a','Rewrite a square root',String.raw`\sqrt{x}=x^{1/2}`,'The derivative formula will use positive x.'),
 m('16','b','Reduce the fractional exponent',String.raw`\frac12x^{1/2-1}=\frac12x^{-1/2}`,'One half minus one is negative one half.'),
 g('17','a','Read the shrinking positive rate',{xRange:[.25,4],yRange:[0,1.2],xLabel:'Input x',yLabel:'Derivative',curves:[{kind:'power',scale:.5,power:-.5,color:'green'}]},String.raw`f'(x)=\frac1{2\sqrt{x}}`,'The rate is positive but smaller at larger positive x.'),
 c('17','b','Growing more slowly is still growing','A positive derivative can decrease as x increases.','The level rises while its rate becomes smaller.'),
 m('18','a','Split the mixed expression',String.raw`f(x)=3x^2+2x^{-1}`,'Rewriting the reciprocal lets the same power rule handle both terms.',{sequence:'mixed-powers'}),
 m('18','b','Differentiate the polynomial part',String.raw`(3x^2)'=6x`,'The factor three stays outside.',{sequence:'mixed-powers'}),
 m('18','c','Differentiate the reciprocal part',String.raw`(2x^{-1})'=-2x^{-2}`,'The original plus term can have a negative derivative.',{sequence:'mixed-powers'}),
 m('18','d','Reassemble the result',String.raw`f'(x)=6x-\frac2{x^2},\quad x\ne0`,'Retain the original domain restriction.',{sequence:'mixed-powers'}),
 e('19','a','Do not lose the exponent multiplier','“(4x³)′=4x².”','The exponent contributes three: the derivative is 12x².'),
 m('19','b','Repair both power-rule actions',String.raw`4x^3\longmapsto4(3)x^{3-1}`,'Multiplying and lowering the exponent are separate steps.'),
 e('20','a','A constant does not survive differentiation','“(x²+9)′=2x+9.”','The derivative of 9 is zero, so the result is 2x.'),
 c('20','b','The original level still contains the constant','Removing the constant from the derivative does not remove it from f.','Two functions can have the same derivative but different levels.'),
 q('21','a','Predict the local cost rate','For C′(q)=2+0.2q, what happens to the rate when q increases from 5 to 10?','It rises from $3/unit to $4/unit.'),
 t('21','b','Read several rate values',['q','0','5','10'],[['C′(q)','2','3','4']],'The table gives rates, not total costs.'),
 m('22','a','Use a small positive step',String.raw`\frac{2.01^3-2^3}{0.01}=12.0601`,'The interval average is close to the derivative 12 at x=2.'),
 c('22','b','Use the difference as a check','An approximate finite-step rate can expose a badly calculated derivative.','It does not replace an exact symbolic rule.'),
 m('23','a','Differentiate a currency model with units',String.raw`C(q)=50+3q+0.2q^2`,'C is dollars and q is output units.'),
 c('23','b','Name the derivative unit','C′(q) is measured in dollars per output unit.','A derivative always refers to its input variable.')
];
export const guides06=['0–10分钟常数和直线的变化率；10–23分钟复现平方差商和幂规则；23–35分钟逐步求常数倍和曲线成本导数；35–41分钟代入与图形检查；41–45分钟短问。话术：“Bring down the exponent.” “Differentiate first, evaluate second.”','0–12分钟和差与负号；12–27分钟负指数和分数指数逐步计算；27–36分钟混合函数及常见错解；36–41分钟有限步检查和量纲；41–45分钟出口题。话术：“Keep the domain.” “A rate is not a level.”'] as const;
