import {author,type Insertion} from './authoring.js';import {lesson10} from '../lessons/lesson-10.js';
const {m,c,q,e,t,g,d}=author(10,lesson10.sources[0]!);
export const additions10:readonly Insertion[]=[
 g('02','a','Read an increasing straight graph',{xRange:[0,3],yRange:[0,7],xLabel:'Input x',yLabel:'Value',curves:[{kind:'polynomial',coefficients:[1,2],color:'green'}]},String.raw`f'(x)=2`,'A positive derivative means a positive local change.'),
 q('02','b','Predict the next nearby value','If f′(a)>0, does a sufficiently small positive input step raise or lower the value?','It raises the value locally.'),
 g('03','a','Read a decreasing straight graph',{xRange:[0,3],yRange:[0,7],xLabel:'Input x',yLabel:'Value',curves:[{kind:'polynomial',coefficients:[7,-2],color:'coral'}]},String.raw`f'(x)=-2`,'Negative slope means the value decreases as x increases.'),
 c('03','b','Direction is read from the slope','A graph may stay above zero while falling.','The function value and derivative sign are different evidence.'),
 c('04','a','A turning point needs two sides','A flat tangent is a candidate that still needs surrounding evidence.','Look immediately before and after the point.'),
 m('04','b','Use one smooth hill model',String.raw`f(x)=4x-x^2`,'We can calculate its changing slope exactly.',{sequence:'hill-test'}),
 m('05','a','Differentiate the hill function',String.raw`f'(x)=4-2x`,'The derivative is a line with decreasing value.',{sequence:'hill-test'}),
 m('05','b','Set the derivative equal to zero',String.raw`4-2x=0`,'We seek an interior stationary candidate.',{sequence:'hill-test'}),
 m('05','c','Solve the candidate input',String.raw`2x=4\quad\Longrightarrow\quad x=2`,'The number two is a location, not yet the function value.',{sequence:'hill-test'}),
 m('05','d','Evaluate the original function there',String.raw`f(2)=8-4=4`,'The candidate point is (2,4).',{sequence:'hill-test'}),
 m('06','a','Test the derivative to the left',String.raw`f'(1)=4-2=2>0`,'The curve rises before the candidate.',{sequence:'hill-test'}),
 m('06','b','Test the derivative to the right',String.raw`f'(3)=4-6=-2<0`,'The curve falls after the candidate.',{sequence:'hill-test'}),
 t('06','c','Combine the two signs',['Region','x<2','x=2','x>2'],[['Derivative sign','+','0','−'],['Direction','Rising','Stationary','Falling']],'The positive-to-negative sign change establishes a local maximum.',{sequence:'hill-test'}),
 c('06','d','A maximum comes from the direction change','The hill rises into the point and falls away from it.','Zero slope identifies the candidate; the signs classify it.',{sequence:'hill-test'}),
 c('07','a','A valley also has a flat bottom','Zero derivative can occur at a minimum as well as a maximum.','A flat tangent alone cannot choose between them.'),
 q('07','b','Predict a valley sign pattern','Should a smooth valley have negative-to-positive or positive-to-negative derivative signs?','Negative-to-positive.'),
 m('08','a','Differentiate the squared-distance model',String.raw`g(x)=(x-2)^2\quad\Longrightarrow\quad g'=2(x-2)`,'The chain rule preserves the shifted input.',{sequence:'valley-test'}),
 m('08','b','Find its stationary input',String.raw`2(x-2)=0\quad\Longrightarrow\quad x=2`,'The candidate matches the center of the square.',{sequence:'valley-test'}),
 m('08','c','Compare derivatives on both sides',String.raw`g'(1)=-2,\qquad g'(3)=2`,'The derivative changes from negative to positive.',{sequence:'valley-test'}),
 m('08','d','Read the minimum value',String.raw`g(2)=0`,'A square cannot be negative, confirming this minimum.',{sequence:'valley-test'}),
 m('09','a','Differentiate a flat-through curve',String.raw`h(x)=x^3\quad\Longrightarrow\quad h'=3x^2`,'The derivative is zero at x=0.'),
 q('09','b','Does the cube turn around at zero?','h′(0)=0. Do the values of x³ start falling after zero?','No. The function continues increasing through zero.'),
 t('10','a','Test both sides of the cube',['x','−1','0','1'],[['h′(x)','3','0','3']],'The derivative stays positive on both sides.'),
 c('10','b','No sign change means no turn in this case','The horizontal tangent at zero is not a maximum or minimum.','Classify using surrounding behavior.'),
 m('11','a','Differentiate the derivative',String.raw`f''(x)=(4-2x)'=-2`,'The second derivative measures how the slope changes.'),
 c('11','b','A negative second derivative bends downward','The slope falls as x increases.','This can classify an already stationary point.'),
 c('12','a','Check stationarity before the quick test','The second-derivative test begins with f′(a)=0.','A curvature sign alone does not create a stationary point.'),
 m('12','b','Use a negative curvature at a candidate',String.raw`f'(a)=0,\quad f''(a)<0`,'These conditions establish a local maximum.'),
 m('12','c','Use a positive curvature at a candidate',String.raw`f'(a)=0,\quad f''(a)>0`,'These conditions establish a local minimum.'),
 q('12','d','Which test condition is missing?','A graph has f″(a)<0 but f′(a)=5. Has a stationary maximum been identified?','No. The derivative is not zero at that input.'),
 m('13','a','Verify both hill-test conditions',String.raw`f'(2)=0,\qquad f''(2)=-2`,'The quick test agrees with the derivative sign change.'),
 c('13','b','Agreement between methods is useful evidence','A sign table and the second derivative support the same classification.','Neither replaces domain and endpoint checks for a global decision.'),
 e('14','a','Zero second derivative is inconclusive','“h″(0)=0 proves x³ has no stationary point.”','It has h′(0)=0; the second-derivative test is inconclusive, so inspect the sign change.'),
 c('14','b','Return to the first-derivative signs','When the quick test is inconclusive, another method can settle the shape.','For x³, the derivative remains positive on both sides.'),
 c('15','a','A global problem includes the allowed interval','The feasible inputs are 0 ≤ x ≤ 3.','Endpoints belong to the comparison.'),
 m('15','b','List the candidates on the interval',String.raw`x=0,\quad x=2,\quad x=3`,'Include the interior stationary input and both boundaries.',{sequence:'bounded-hill'}),
 m('16','a','Evaluate the left endpoint',String.raw`f(0)=0`,'Use the original function, not the derivative.',{sequence:'bounded-hill'}),
 m('16','b','Evaluate the stationary candidate',String.raw`f(2)=4`,'A candidate value can now be compared.',{sequence:'bounded-hill'}),
 m('16','c','Evaluate the right endpoint',String.raw`f(3)=12-9=3`,'The boundary value is lower than the interior value.',{sequence:'bounded-hill'}),
 t('16','d','Choose the largest feasible value',['Input','0','2','3'],[['Value','0','4','3']],'The global maximum on [0,3] is four at x=2.',{sequence:'bounded-hill'}),
 m('17','a','A line can peak at a boundary',String.raw`k(x)=1+2x,\quad0\le x\le3`,'The derivative is positive throughout the interval.'),
 q('17','b','Where is the largest linear value?','For k(x)=1+2x on [0,3], where is the maximum?','At x=3, with value 7; no stationary point is needed.'),
 c('18','a','A shorter interval can exclude the hilltop','If 0 ≤ x ≤ 1, the stationary input x=2 is not feasible.','The unconstrained answer cannot be used.'),
 m('18','b','Compare the new boundaries',String.raw`f(0)=0,\qquad f(1)=3`,'The function rises over this shorter interval.'),
 d('19','a','Organize the decision',['Domain','Candidates','Values'],['Allowed inputs','Stationary points and ends','Compare'],String.raw`\mathrm{location}\to\mathrm{value}\to\mathrm{decision}`,'Every part of the conclusion has evidence.'),
 c('19','b','Local and global maxima differ','A local maximum compares nearby inputs; a global maximum compares all feasible inputs.','State which kind the question asks for.'),
 m('20','a','Write the revenue and feasible interval',String.raw`R(q)=12q-q^2,\quad0\le q\le10`,'The output restriction is part of the business problem.',{sequence:'ticket-maximum'}),
 m('20','b','Differentiate the objective',String.raw`R'(q)=12-2q`,'We need revenue change, not a price derivative.',{sequence:'ticket-maximum'}),
 m('20','c','Solve its stationary equation',String.raw`12-2q=0\quad\Longrightarrow\quad q=6`,'Six lies in the feasible interval.',{sequence:'ticket-maximum'}),
 m('20','d','Check curvature at the candidate',String.raw`R''(q)=-2<0`,'The stationary point is a local maximum.',{sequence:'ticket-maximum'}),
 m('21','a','Calculate the candidate revenue',String.raw`R(6)=72-36=36`,'The value is thirty-six currency units.',{sequence:'ticket-maximum'}),
 m('21','b','Calculate the endpoint revenues',String.raw`R(0)=0,\qquad R(10)=20`,'The endpoint values also matter.',{sequence:'ticket-maximum'}),
 t('21','c','Compare all candidates',['q','0','6','10'],[['R(q)','0','36','20']],'The feasible maximum occurs at six.',{sequence:'ticket-maximum'}),
 c('21','d','Report the decision with its value','Choose six output units for a maximum model revenue of thirty-six.','The conclusion is restricted to the stated model and interval.',{sequence:'ticket-maximum'}),
 e('22','a','A flat point is not enough','“h′(0)=0, so x³ is maximized at zero.”','Its derivative is positive on both sides; zero is stationary without a local maximum.'),
 e('22','b','Do not optimize the derivative value','“The largest f′ tells us the largest f.”','A large derivative means rapid increase, not the largest function level.'),
 q('23','a','Complete an optimization report','What three things should accompany an optimal input?','The objective value, feasibility and a justification comparing candidates.'),
 c('23','b','Match the report to the question','A stationary input is only one part of an optimization answer.','Name the maximum or minimum and the allowed interval.')
];
export const guides10=['0–10分钟斜率符号与方向；10–24分钟山峰逐步求导、求驻点、两侧符号；24–35分钟谷底和立方反例；35–41分钟第二导数条件；41–45分钟短问。话术：“A flat point is a candidate.” “What happens on both sides?”','0–12分钟第二导数结论与不确定情形；12–26分钟区间候选及端点逐项比较；26–36分钟票务收入完整优化；36–41分钟常见捷径错误；41–45分钟出口题。话术：“Use the original function for the values.” “Check the ends too.”'] as const;
