import {author,type Insertion} from './authoring.js';
import {lesson14} from '../lessons/lesson-14.js';
import type {PlotSpec} from '../types.js';
const {m,c,q,e,t,g,d}=author(14,lesson14.sources[0]!);
const flow=(extras:Partial<PlotSpec>={}):PlotSpec=>({xRange:[0,4],yRange:[0,7],xLabel:'Time (min)',yLabel:'Flow (L/min)',curves:[{kind:'polynomial',coefficients:[2,1],color:'blue'}],...extras});
export const additions14:readonly Insertion[]=[
 c('02','a','A meter reading is a rate','Three litres per minute tells us how fast water arrives.','It does not yet tell us the amount received.'),
 m('02','b','Pair one rate with one duration',String.raw`3\,\frac{\mathrm L}{\mathrm{min}}\times4\,\mathrm{min}`,'The minutes cancel when multiplying.',{sequence:'constant-flow'}),
 g('02','c','Read a constant rate as one rectangle',flow({curves:[{kind:'polynomial',coefficients:[3],color:'green'}],area:{curve:0,from:0,to:4}}),String.raw`V=3\times4`,'The vertical unit times the horizontal unit gives litres.',{sequence:'constant-flow'}),
 c('03','a','A changing rate needs smaller intervals','For r(t)=2+t, later minutes have higher flow readings.','One fixed rectangle cannot follow the whole curve.'),
 m('03','b','Divide the time window equally',String.raw`\Delta t=\frac{4-0}{4}=1\,\mathrm{min}`,'Four equal intervals each last one minute.',{sequence:'left-sum'}),
 t('03','c','Read the left edges',['Left time (min)','0','1','2','3'],[['Rate (L/min)','2','3','4','5']],'Each interval uses its starting flow reading.',{sequence:'left-sum'}),
 m('04','a','Calculate one strip contribution',String.raw`r(0)\Delta t=2\times1=2\,\mathrm L`,'A rate reading becomes volume only after multiplication by width.',{sequence:'left-sum'}),
 m('04','b','Add the four strip volumes',String.raw`L_4=2(1)+3(1)+4(1)+5(1)`,'The sum is made of small volumes, not bare rate readings.',{sequence:'left-sum'}),
 g('04','c','Locate what the rectangles miss',flow({rectangles:{curve:0,from:0,to:4,n:4}}),String.raw`L_4=14`,'The gaps above the rectangles represent omitted water.',{sequence:'left-sum'}),
 t('05','a','Read the right edges instead',['Right time (min)','1','2','3','4'],[['Rate (L/min)','3','4','5','6']],'The same intervals now use ending readings.'),
 m('05','b','Sum the right-edge contributions',String.raw`R_4=3(1)+4(1)+5(1)+6(1)=18`,'For this increasing rate, the right readings are too high.'),
 q('05','c','Explain the bound without integrating','Why should the true volume lie between 14 L and 18 L for this flow?','The increasing rate stays above each left rectangle and below each right rectangle.'),
 m('06','a','Double the number of intervals',String.raw`n=8\quad\Longrightarrow\quad\Delta t=0.5`,'The time window is unchanged; only the strip width shrinks.'),
 m('06','b','A smaller width changes every contribution',String.raw`(2+0.5)\times0.5=1.25\,\mathrm L`,'A half-minute reading must be multiplied by half a minute.'),
 g('06','c','Compare eight narrower strips',flow({rectangles:{curve:0,from:0,to:4,n:8}}),String.raw`\Delta t=0.5`,'The thinner staircase follows the changing rate more closely.'),
 t('07','a','Compare estimates and their gaps',['n','Left (L)','Right (L)','Gap (L)'],[['4','14','18','4'],['8','15','17','2'],['16','15.5','16.5','1']],'Both estimates approach the same amount.'),
 m('07','b','Read the left-sum pattern',String.raw`16-\frac8{16}=15.5`,'The finite left sum still has an error at n=16.'),
 e('07','c','Many strips do not mean exact','“Sixteen rectangles always give the exact volume.”','They give an approximation. Here the left sum is 15.5 L while the exact total is 16 L.'),
 c('08','a','An integral names the limiting total','Make the interval widths smaller and smaller while covering the same time window.','The limiting sum is the definite integral.'),
 m('08','b','Read the lower and upper limits',String.raw`\int_{0}^{4}r(t)\,dt`,'The limits identify the start and end times, in minutes.'),
 c('08','c','The differential belongs to the variable','The symbol dt indicates accumulation with respect to time.','Rate times small time contributes small volume.'),
 m('09','a','Find a function with the given derivative',String.raw`F(t)=2t+\frac12t^2`,'We want a derivative equal to the rate 2+t.',{sequence:'fundamental-theorem'}),
 m('09','b','Differentiate the first term',String.raw`\frac{d}{dt}(2t)=2`,'This produces the constant part of the rate.',{sequence:'fundamental-theorem'}),
 m('09','c','Differentiate the second term',String.raw`\frac{d}{dt}\left(\frac12t^2\right)=t`,'Together the derivatives recover 2+t.',{sequence:'fundamental-theorem'}),
 c('10','a','Link accumulation and antiderivatives','For a continuous rate r, an antiderivative F evaluates its accumulated change.','Use the same start and end points as the time window.',{sequence:'fundamental-theorem'}),
 m('10','b','Write the endpoint subtraction',String.raw`\int_a^b r(t)\,dt=F(b)-F(a)`,'The difference gives change over the interval.',{sequence:'fundamental-theorem'}),
 q('10','c','Choose the first evaluation','To calculate the accumulated flow from 0 to 4, which two values of F are needed?','F(4) and F(0), in that order for subtraction.'),
 m('11','a','Evaluate the upper endpoint',String.raw`F(4)=2(4)+\frac12(4)^2=8+8`,'Square the entire endpoint value before multiplying by one half.',{sequence:'fundamental-theorem'}),
 m('11','b','Evaluate the lower endpoint',String.raw`F(0)=2(0)+\frac12(0)^2=0`,'The lower evaluation is explicit even when it is zero.',{sequence:'fundamental-theorem'}),
 m('11','c','Subtract and state the amount',String.raw`F(4)-F(0)=16-0=16\,\mathrm L`,'This exact value lies within the earlier rectangle bounds.',{sequence:'fundamental-theorem'}),
 m('12','a','A later start changes the lower limit',String.raw`[1,3],\qquad\mathrm{duration}=3-1=2`,'The upper endpoint is not the duration.'),
 m('12','b','Evaluate both new endpoints',String.raw`F(3)=10.5,\qquad F(1)=2.5`,'Both numbers come from the same antiderivative.'),
 m('12','c','Subtract the new accumulated levels',String.raw`10.5-2.5=8\,\mathrm L`,'Only the flow between minutes one and three is counted.'),
 c('13','a','A negative rate describes direction','A net flow below zero means water leaves the tank faster than it arrives.','An accumulated change may therefore be negative.'),
 m('13','b','An antiderivative for a signed rate',String.raw`G(t)=\frac12t^2-2t`,'Its derivative is t−2 on the stated interval.'),
 m('13','c','Calculate the net change',String.raw`G(3)-G(0)=4.5-6=-1.5`,'The negative result describes a net loss, not negative water.'),
 g('14','a','Separate the two directions',flow({xRange:[0,3],yRange:[-3,3],curves:[{kind:'polynomial',coefficients:[-2,1],color:'coral'}],area:{curve:0,from:0,to:2}}),String.raw`t=2`,'The rate changes sign at two; split the interval there.'),
 m('14','b','Count outflow by its positive magnitude',String.raw`\mathrm{outflow}=\frac12(2)(2)=2`,'The first triangular region has magnitude two.'),
 m('14','c','Add magnitudes for total movement',String.raw`2+\frac12(1)(1)=2.5`,'Adding magnitudes answers a different question from net change.'),
 m('15','a','Keep the same constant at both endpoints',String.raw`[F(b)+C]-[F(a)+C]`,'Both evaluations use the same member of the antiderivative family.'),
 m('15','b','Distribute the subtraction sign',String.raw`F(b)+C-F(a)-C`,'The sign applies to every term in the second bracket.'),
 e('15','c','A definite total has no extra free constant','“The four-minute volume is 16+C litres.”','The same constant cancels in endpoint subtraction; the definite accumulated change is 16 L.'),
 c('16','a','Let the ending time move','A(x) measures flow received from zero up to the current time x.','The integration variable t is a running time inside the interval.'),
 m('16','b','Write the accumulation function explicitly',String.raw`A(x)=2x+\frac12x^2`,'The zero starting endpoint makes the lower value vanish.'),
 m('16','c','Differentiate the accumulated amount',String.raw`A'(x)=2+x=r(x)`,'For this continuous rate, the derivative recovers the current flow.'),
 d('17','a','Track the disappearing unit',['Rate','Duration','Amount'],['L/min','min','L'],String.raw`\frac{\mathrm L}{\mathrm{min}}\times\mathrm{min}=\mathrm L`,'The horizontal unit cancels the rate denominator.'),
 m('17','b','Apply the same unit logic to cost',String.raw`\frac{\mathrm{euros}}{\mathrm{unit}}\times\mathrm{units}=\mathrm{euros}`,'Integrating marginal cost gives a cost change.'),
 q('17','c','Name the unit of the integral','A rate is measured in people per hour and the limits are hours. What unit does its integral have?','People, as an accumulated count or modelled quantity.'),
 c('18','a','A falling positive rate still adds water','A rate can decrease while remaining above zero.','The accumulated amount grows, but at a slowing pace.'),
 m('18','b','Find the antiderivative of the falling rate',String.raw`\int(6-t)\,dt=6t-\frac12t^2+C`,'The negative slope of the rate does not make the rate negative.'),
 m('18','c','Evaluate its four-hour accumulation',String.raw`[6t-\tfrac12t^2]_0^4=24-8=16`,'Positive rates produce a positive accumulated change.'),
 m('19','a','Use the smallest rate for a lower bound',String.raw`2\,\frac{\mathrm L}{\mathrm{min}}\times4\,\mathrm{min}=8\,\mathrm L`,'The actual rate is never below two on this interval.'),
 m('19','b','Use the largest rate for an upper bound',String.raw`6\,\frac{\mathrm L}{\mathrm{min}}\times4\,\mathrm{min}=24\,\mathrm L`,'The actual rate is never above six on this interval.'),
 q('19','c','Reject an impossible result','A calculation claims 40 L for a four-minute rate between 2 and 6 L/min. Is it plausible?','No. The simple upper bound is 24 L.'),
 e('20','a','A rate is not a final volume','“The integral equals 16 L/min.”','The integral is 16 L; integration over minutes changes the unit from rate to volume.'),
 e('20','b','An endpoint value is not an integral','“For r(t)=2+t, the integral over [0,4] is r(4)=6.”','Six is an endpoint rate. Find an antiderivative and subtract its endpoint values.'),
 c('20','c','Three checks protect the interpretation','Check the method, the integrated unit and the meaning of the sign.','A correct number with the wrong unit still answers the wrong question.'),
 m('21','a','A new flow starts a new calculation',String.raw`r(t)=3+2t,\quad 0\le t\le2`,'The model is a rate in litres per minute.',{sequence:'new-flow'}),
 m('21','b','Integrate each term',String.raw`F(t)=3t+t^2`,'Differentiate it mentally to confirm the rate.',{sequence:'new-flow'}),
 m('21','c','Evaluate and subtract',String.raw`F(2)-F(0)=6+4=10\,\mathrm L`,'The two-minute model receives ten litres.',{sequence:'new-flow'}),
 c('22','a','Differentiate a level to get a rate','A volume function V(t) already records the amount in the tank.','Its derivative gives the current net flow.'),
 m('22','b','Add accumulated change to the initial level',String.raw`V(4)=V(0)+\int_0^4r(t)\,dt`,'A flow law does not supply the initial volume.'),
 q('22','c','Include the starting amount','A tank starts with 5 L and has a net inflow of 16 L. What final volume follows?','21 L, assuming no additional unmodelled flow.'),
 c('23','a','Translate symbols into one useful sentence','State the amount received, the time window and the unit.','The interval is part of the result, not optional background.'),
 c('23','b','Name the assumption behind the total','The displayed rate represents the net modelled flow.','Other unrecorded inflows or outflows would change the final stock.'),
 q('23','c','Distinguish two managerial questions','Does “16 litres arrive” tell us how much water is currently in the tank?','Not by itself. The initial amount and any other flows must also be known.')
];
export const guides14=['0–8分钟复习常量流速与量纲；8–21分钟逐个构造左右矩形并比较误差；21–29分钟缩小宽度、读极限符号；29–39分钟验证原函数并逐步代入端点；39–45分钟改换区间与短问。话术：“Rate times width gives a small volume.” “Which time window are we counting?”','0–10分钟区分净变化和总流动；10–17分钟积分常数抵消；17–26分钟移动上限与累计函数；26–35分钟单位、界限和错误诊断；35–41分钟新流速算例；41–45分钟出口解释。话术：“What is the initial amount?” “The unit must change after accumulation.”'] as const;
