import {author,type Insertion} from './authoring.js';import {lesson04} from '../lessons/lesson-04.js';
const {m,c,q,e,t,g}=author(4,lesson04.sources[0]!);
export const additions04:readonly Insertion[]=[
 t('02','a','Compare two ways to grow',['Step','0','1','2','3'],[['Add 100','100','200','300','400'],['Multiply by 2','100','200','400','800']],'The first change agrees; later changes reveal the different rules.'),
 c('02','b','A growth factor compares consecutive values','Equal ratios signal multiplication; equal differences signal addition.','Choose a model from the pattern, not the first two values.'),
 m('03','a','Write repeated doubling without shorthand',String.raw`2\times2\times2`,'There are three factors, not three additions.',{sequence:'doubling-model'}),
 m('03','b','Count factors in the exponent',String.raw`2^3=8`,'The exponent counts how many doubling factors are applied.',{sequence:'doubling-model'}),
 m('03','c','Zero steps retain the starting amount',String.raw`2^0=1`,'A multiplier of one leaves a starting amount unchanged.',{sequence:'doubling-model'}),
 e('03','d','An exponent is not a multiplier','“2³ equals 2×3.”','2³ is 2×2×2=8; 2×3=6 is a different calculation.'),
 m('04','a','Keep the starting group outside the power',String.raw`N(t)=100\cdot2^t`,'The group begins at one hundred.',{sequence:'doubling-model'}),
 m('04','b','Check the model at time zero',String.raw`N(0)=100\cdot1=100`,'A sensible growth rule reproduces its initial value.',{sequence:'doubling-model'}),
 m('05','a','Apply two doubling steps',String.raw`N(2)=100(2^2)=400`,'The number of steps belongs in the exponent.',{sequence:'doubling-model'}),
 m('05','b','Read the factor from consecutive values',String.raw`\frac{N(3)}{N(2)}=\frac{800}{400}=2`,'Each complete step multiplies the group by two.',{sequence:'doubling-model'}),
 c('06','a','Join two strings of factors','Two factors of two followed by three more give five factors.','The base must be the same for this exponent rule.'),
 q('06','b','Combine the powers','Simplify 3²×3⁴ without multiplying all six factors.','3⁶; add the exponents because the bases match.'),
 m('07','a','Cancel factors rather than exponents',String.raw`\frac{2^5}{2^3}=\frac{2\cdot2\cdot2\cdot2\cdot2}{2\cdot2\cdot2}`,'Three common factors cancel.'),
 m('07','b','A negative exponent names a reciprocal',String.raw`2^{-3}=\frac1{2^3}=\frac18`,'It does not mean a negative value.'),
 m('08','a','Count factors in a repeated power',String.raw`(2^3)^2=(2^3)(2^3)`,'Two copies each contain three factors.'),
 m('08','b','Multiply the exponent counts',String.raw`(2^3)^2=2^{3\cdot2}=2^6`,'This rule multiplies exponents, unlike multiplying equal-base powers.'),
 c('09','a','A fractional power reverses a whole power','The positive square root reverses squaring for a nonnegative value.','A half exponent names the square root.'),
 q('09','b','Recognize a root','What positive value is 16^(1/2)?','4, because 4²=16.'),
 c('10','a','A twenty-percent rise keeps the original amount','The next amount is the old amount plus 20% of that old amount.','The multiplier is 1.20, not 0.20.'),
 m('10','b','Build the first growth step',String.raw`100+0.20(100)=120`,'The starting amount participates in the new total.'),
 t('11','a','Compare percentage growth across steps',['t','0','1','2','3'],[['N(t)','100','120','144','172.8']],'The added amounts grow because the base grows.'),
 g('11','b','Read upward curvature',{xRange:[0,5],yRange:[0,300],xLabel:'Time (steps)',yLabel:'Group size',curves:[{kind:'exponential',scale:100,rate:Math.log(1.2),color:'blue'}]},String.raw`N(t)=100(1.2)^t`,'The curve represents a smooth teaching model between recorded steps.'),
 m('12','a','A twenty-percent loss leaves eighty percent',String.raw`1-0.20=0.80`,'A decay multiplier is between zero and one.'),
 m('12','b','Apply two loss steps',String.raw`1000(0.8)^2=640`,'The second loss uses the smaller new base.'),
 m('13','a','Set the target equal to the model',String.raw`100(1.2)^t=200`,'The unknown is the time exponent.',{sequence:'target-time'}),
 m('13','b','Remove the starting scale',String.raw`(1.2)^t=2`,'Divide both sides by the positive starting amount.',{sequence:'target-time'}),
 c('14','a','Ask which exponent gives the target','A logarithm returns the exponent needed for a stated base.','The target must be positive.'),
 m('14','b','Rename the exponent question',String.raw`2^3=8\quad\Longleftrightarrow\quad\log_2 8=3`,'The power and logarithm describe the same relation.'),
 m('15','a','Undo a power with the matching logarithm',String.raw`\log_2(2^t)=t`,'Use the same base and a valid positive argument.'),
 m('15','b','Undo a logarithm with the matching power',String.raw`2^{\log_2 x}=x,\quad x>0`,'The positivity condition belongs with the identity.'),
 c('16','a','Natural logarithms use the base e','The constant e is approximately 2.71828.','ln is a logarithm name, not a multiplication instruction.'),
 m('16','b','A simple natural-logarithm check',String.raw`\ln(e)=1,\qquad\ln(1)=0`,'The statements correspond to e¹=e and e⁰=1.'),
 m('17','a','Apply the logarithm to both sides',String.raw`\ln((1.2)^t)=\ln2`,'Both sides are positive before taking logarithms.',{sequence:'target-time'}),
 m('17','b','Bring the exponent outside',String.raw`t\ln1.2=\ln2`,'The power rule transforms an unknown exponent into a coefficient.',{sequence:'target-time'}),
 m('17','c','Isolate the time',String.raw`t=\frac{\ln2}{\ln1.2}`,'The denominator is nonzero because the growth factor is not one.',{sequence:'target-time'}),
 c('17','d','Keep the time unit from the model','If one exponent step means one week, t is measured in weeks.','A logarithm does not supply a time unit by itself.',{sequence:'target-time'}),
 m('18','a','Evaluate the logarithms consistently',String.raw`\ln2\approx0.69315,\quad\ln1.2\approx0.18232`,'Use the same logarithm base in numerator and denominator.',{sequence:'target-time'}),
 m('18','b','Calculate the continuous target time',String.raw`t\approx3.8018`,'The smooth model reaches the target between steps three and four.',{sequence:'target-time'}),
 m('18','c','Check through the original growth rule',String.raw`100(1.2)^{3.8018}\approx200`,'Substitution checks the transformed equation.',{sequence:'target-time'}),
 t('18','d','Compare the surrounding whole steps',['Step','3','4'],[['Group size','172.8','207.36']],'A target of two hundred lies between these values.',{sequence:'target-time'}),
 c('19','a','A threshold and a reporting date differ','A continuous crossing near 3.80 weeks is not a whole-week observation.','The first complete weekly observation meeting the target is week four.'),
 q('19','b','Choose the reporting step','If measurements occur only at whole weeks, at which first observation is N(t)≥200?','Week 4 under the stated growth model.'),
 m('20','a','Model a balance with a five-percent factor',String.raw`B(t)=1000(1.05)^t`,'This is a teaching balance model with one factor per step.',{sequence:'balance-growth'}),
 m('20','b','Apply three complete factors',String.raw`B(3)=1000(1.05)(1.05)(1.05)`,'Multiplication implements repeated percentage changes.',{sequence:'balance-growth'}),
 m('21','a','Read the resulting balance',String.raw`B(3)=1157.625`,'Round only after the calculation if the reporting rule requires it.',{sequence:'balance-growth'}),
 c('21','b','A logarithmic scale compresses ratios','Equal multiplicative changes become equal logarithmic differences.','It is useful across a wide range of positive amounts.'),
 e('22','a','Logarithms do not distribute over addition','“ln(2+3)=ln2+ln3.”','The left side is ln5; the right side is ln6.'),
 m('22','b','Use the actual product rule',String.raw`\ln a+\ln b=\ln(ab),\quad a,b>0`,'Multiplication inside a logarithm corresponds to addition outside.'),
 c('23','a','The growth rule needs a valid time range','The model is intended for a specified planning horizon.','Long extrapolation requires evidence beyond the algebra.'),
 q('23','b','Check the zero-time value','For N(t)=50×2^t, what starting group must the model reproduce?','50 at t=0.')
];
export const guides04=['0–12分钟比较加法与乘法增长；12–25分钟展开因子并核对幂规则；25–35分钟增长因子与衰减；35–41分钟建立目标方程；41–45分钟短问。话术：“The exponent counts steps.” “What is the starting amount?”','0–12分钟幂与对数的互逆关系；12–27分钟逐步反推时间并代回；27–35分钟连续时间与整周观察；35–41分钟另一增长模型和对数错误诊断；41–45分钟出口题。话术：“Use the same logarithm base.” “Which observation first reaches the target?”'] as const;
