import {author,type Insertion} from './authoring.js';
import {lesson01} from '../lessons/lesson-01.js';
const {m,c,q,e,t,d}=author(1,lesson01.sources[0]!);
export const additions01:readonly Insertion[]=[
 c('02','a','Three numbers, three meanings','A cup price, a cup count and a payment measure different things.','Attach a unit before multiplying.'),
 m('02','b','Write the unit beside the number',String.raw`8\,\frac{\$}{\mathrm{cup}}\times3\,\mathrm{cups}`,'The number 3 counts cups. It does not measure dollars.',{sequence:'receipt-units'}),
 q('03','a','A cheaper label?','Pack A costs $12. Pack B costs $9. Can the lower label alone prove better value?','No. Compare equal volumes or unit prices.'),
 t('03','b','Put both quantities on the receipt',['Pack','Volume','Price'],[['A','750 mL','$12'],['B','500 mL','$9']],'We need one common unit before comparing.',{sequence:'unit-drinks'}),
 m('04','a','Convert the larger pack',String.raw`750\,\mathrm{mL}\times\frac{1\,\mathrm L}{1000\,\mathrm{mL}}=0.75\,\mathrm L`,'Millilitres cancel. The remaining unit is litres.',{sequence:'unit-drinks'}),
 m('04','b','Convert the smaller pack',String.raw`500\,\mathrm{mL}=\frac{500}{1000}\,\mathrm L=0.5\,\mathrm L`,'Keep the conversion consistent for both packs.',{sequence:'unit-drinks'}),
 m('04','c','Divide money by the larger volume',String.raw`\frac{12\,\$}{0.75\,\mathrm L}=16\,\frac{\$}{\mathrm L}`,'This is a price for one litre, even though the pack is smaller.',{sequence:'unit-drinks'}),
 m('04','d','Make the comparison on one scale',String.raw`\frac9{0.5}=18>16`,'A saves $2 for each litre bought at these unit prices.',{sequence:'unit-drinks'}),
 c('05','a','A balance records direction','Adding money increases the balance. Spending money decreases it.','A change can be negative even when the purchase price is positive.'),
 m('05','b','A spend changes the starting balance',String.raw`15+(-6)=9`,'The new balance is $9 before the later $10 deposit.'),
 q('06','a','Which bill does this describe?','A $2 discount applies to each of three $8 cups. Write the bill without calculating it.','3(8−2), measured in dollars.'),
 e('06','b','Multiplication cannot wait','“8 − 0.25 × 8 means (8 − 0.25) × 8.”','Multiply 0.25 by 8 first. The original expression is 8−2=6.'),
 d('07','a','One part of four equal parts',['Chosen part','All parts','Fraction'],['1','4','1/4'],String.raw`\frac14`,'The denominator names the size of the whole.'),
 m('07','b','Rename the same share',String.raw`\frac14=\frac{25}{100}`,'Multiplying numerator and denominator by 25 keeps the fraction unchanged.'),
 c('08','a','Find the whole before the share','“25% off” refers to the original menu price.','The base is $8 for this coffee.',{sequence:'coffee-discount'}),
 m('08','b','Calculate the money removed',String.raw`\mathrm{saving}=\frac{25}{100}\times8`,'Convert the percentage to a multiplier before using the price.',{sequence:'coffee-discount'}),
 m('09','a','Remove the calculated saving',String.raw`\mathrm{payment}=8-2=6`,'Subtract the dollar saving from the original dollar price.',{sequence:'coffee-discount'}),
 m('09','b','Check through the remaining share',String.raw`\mathrm{payment}=(1-0.25)\times8`,'A second method checks the first calculation.',{sequence:'coffee-discount'}),
 m('10','a','Read a fixed discount in dollars',String.raw`\mathrm{payment}_B=8-1.50=6.50`,'Offer B subtracts an amount, not a percentage.',{sequence:'coffee-discount'}),
 m('10','b','Compare the amounts paid',String.raw`6.50-6.00=0.50`,'The smaller payment saves an additional fifty cents.',{sequence:'coffee-discount'}),
 t('11','a','Try a new base price',['Menu price','25% saving','Fixed saving'],[['$4','$1','$1.50'],['$8','$2','$1.50'],['$12','$3','$1.50']],'The percentage saving changes with the base; the fixed saving does not.'),
 c('11','b','One symbol replaces many prices','Let p mean the original price in dollars.','The same rule can now describe several receipts.'),
 m('12','a','Substitute without changing the rule',String.raw`A=0.75p,\qquad p=12`,'Replace only the price variable with twelve.'),
 m('12','b','Keep the value and its meaning together',String.raw`A=0.75(12)=9`,'The expression gives a $9 payment, not a 9% discount.'),
 c('13','a','Read the fee carefully','Three coffees share one $2 service fee.','“Once” tells us where the fee belongs.',{sequence:'service-equation'}),
 m('13','b','Translate each part before combining',String.raw`\mathrm{coffee\ total}=3x,\qquad\mathrm{fee}=2`,'The unknown x is the price per cup.',{sequence:'service-equation'}),
 m('14','a','Match the known payment',String.raw`3x+2=20`,'An equation states that two expressions have the same value.',{sequence:'service-equation'}),
 m('14','b','Undo the added fee on both sides',String.raw`3x+2-2=20-2`,'The same operation keeps the two sides equal.',{sequence:'service-equation'}),
 m('15','a','Read the simpler equation',String.raw`3x=18`,'The three coffees together cost eighteen dollars.',{sequence:'service-equation'}),
 m('15','b','Undo three equal copies',String.raw`\frac{3x}{3}=\frac{18}{3}`,'Dividing both sides by three preserves equality.',{sequence:'service-equation'}),
 m('15','c','Attach the correct unit',String.raw`x=6\,\frac{\$}{\mathrm{cup}}`,'The solution is a unit price, not the total payment.',{sequence:'service-equation'}),
 m('15','d','Return to the original sentence',String.raw`3(6)+2=18+2=20`,'The substitution confirms both the equation and the receipt.',{sequence:'service-equation'}),
 c('16','a','Count quantities of one kind','Two cups plus three cups make five cups.','Like terms follow the same counting logic.'),
 m('16','b','Keep the common variable',String.raw`2x+3x=(2+3)x`,'Only the coefficients are added; x remains the same quantity.'),
 q('17','a','Isolate the unknown','Solve 5x − 7 = 18. Which operation should come first?','Add 7 to both sides, giving 5x=25; then divide by 5.'),
 m('17','b','A minus sign also has an inverse',String.raw`5x-7+7=18+7`,'Undo subtraction by adding the same amount on both sides.'),
 c('18','a','The paid price is only a share','After 20% off, the buyer pays 80% of the original price.','The original price is the unknown whole.',{sequence:'reverse-percentage'}),
 m('18','b','Recover the unknown whole',String.raw`0.8p=72\quad\Longrightarrow\quad p=\frac{72}{0.8}`,'Divide by the remaining share; do not add twenty percent to $72.',{sequence:'reverse-percentage'}),
 m('19','a','The second discount uses a new base',String.raw`100(0.9)=90`,'After the first ten-percent discount, the base is ninety dollars.'),
 m('19','b','Apply the next discount to that base',String.raw`90(0.9)=81`,'Two ten-percent discounts leave eighty-one percent of the original price.'),
 c('20','a','State the tax base','In this teaching receipt, a 10% tax applies after the discount.','Different stated rules can give different bills.'),
 m('20','b','Apply the stated order',String.raw`8(0.75)(1.10)=6.60`,'The discounted price is $6, and the model adds $0.60 tax.'),
 e('21','a','Reverse percentages need division','“A $72 price after 20% off means the original price was $72 × 1.2.”','The original price is 72/0.8=$90. Adding 20% uses the wrong base.'),
 q('21','b','Check the proposed repair','A $40 product loses 25% of its price. Is its new price $10 or $30? Explain.','$10 is the saving; $30 is the payment.'),
 m('22','a','A tie compares payments',String.raw`0.75p=p-1.50`,'Both offers must charge the same amount at the boundary.',{sequence:'offer-boundary'}),
 m('22','b','Collect the price terms',String.raw`p-0.75p=1.50`,'Subtract the smaller price term from both sides.',{sequence:'offer-boundary'}),
 m('23','a','Solve for the boundary',String.raw`0.25p=1.50\quad\Longrightarrow\quad p=6`,'At a six-dollar menu price the offers tie.',{sequence:'offer-boundary'}),
 t('23','b','Check either side of the tie',['p','A = 0.75p','B = p − 1.50'],[['$4','$3','$2.50'],['$6','$4.50','$4.50'],['$8','$6','$6.50']],'The better deal changes at the verified boundary.',{sequence:'offer-boundary'})
];
export const guides01=['0–7分钟观察咖啡与单位；7–19分钟逐步统一体积和单价；19–31分钟解释百分比的基数并算两种优惠；31–40分钟用新价格复查规则；40–45分钟即时检查。话术：“Which amount is the whole?” “What unit remains?”','0–8分钟从收费句子建立等式；8–22分钟逐步逆运算、单位和代回；22–33分钟逆百分比与连续折扣；33–40分钟求优惠切换边界；40–45分钟出口题。话术：“Do the same to both sides.” “Check it in the receipt.”'] as const;
