import {author,type Insertion} from './authoring.js';import {lesson07} from '../lessons/lesson-07.js';
const {m,c,q,e,t,d}=author(7,lesson07.sources[0]!);
export const additions07:readonly Insertion[]=[
 c('02','a','The square acts on a whole expression','In (2x+3)², the square receives the output of 2x+3.','The two operations happen in a specific order.'),
 d('02','b','Trace the input through two machines',['Input','Inner rule','Outer rule'],['x','2x+3','Square'],String.raw`x\to2x+3\to(2x+3)^2`,'Changing x first changes the inner output.'),
 m('03','a','Give the inner output a name',String.raw`u=2x+3`,'Naming u makes the two dependency links visible.',{sequence:'square-chain'}),
 m('03','b','Write the outer function in u',String.raw`y=u^2`,'The outer function responds to u, not directly to x.',{sequence:'square-chain'}),
 m('03','c','Evaluate the inner input at x=1',String.raw`u(1)=2(1)+3=5`,'The outer rule receives five.',{sequence:'square-chain'}),
 m('03','d','Evaluate the outer output',String.raw`y(1)=5^2=25`,'The nested model returns twenty-five.',{sequence:'square-chain'}),
 m('04','a','Compare two nearby inner values',String.raw`u(x+h)-u(x)=2h`,'The inside changes by twice the x step.',{sequence:'square-chain'}),
 m('04','b','Read the inner rate',String.raw`\frac{du}{dx}=2`,'This rate links the original input to the inner output.',{sequence:'square-chain'}),
 c('04','c','Keep the two rates distinct','The inner rate measures change in u per change in x.','The outer rate will measure change in y per change in u.',{sequence:'square-chain'}),
 t('04','d','A small step passes through the inside',['x','1','1.01'],[['u(x)','5','5.02']],'A 0.01 input increase produces a 0.02 inner increase.',{sequence:'square-chain'}),
 m('05','a','Differentiate the outer rule',String.raw`\frac{dy}{du}=2u`,'The power rule applies to u².',{sequence:'square-chain'}),
 m('05','b','Evaluate the outer rate at the current u',String.raw`\left.\frac{dy}{du}\right|_{u=5}=10`,'This is a rate per unit of u.',{sequence:'square-chain'}),
 c('05','c','The outer rate still needs the inner link','Ten units of y per unit u does not yet give change per unit x.','The inner variable itself changes with x.',{sequence:'square-chain'}),
 m('05','d','Restore the inner expression',String.raw`2u=2(2x+3)`,'The final derivative must be expressed in the original input.',{sequence:'square-chain'}),
 m('06','a','Multiply the linked rates',String.raw`\frac{dy}{dx}=\frac{dy}{du}\frac{du}{dx}`,'The chain rule joins the two dependency links.',{sequence:'square-chain'}),
 m('06','b','Substitute both rates',String.raw`\frac{dy}{dx}=2(2x+3)\cdot2`,'The second factor comes from differentiating the inside.',{sequence:'square-chain'}),
 m('06','c','Simplify the constant factors',String.raw`y'=4(2x+3)`,'Keep the remaining inner expression intact.',{sequence:'square-chain'}),
 m('06','d','Evaluate the final rate',String.raw`y'(1)=4(5)=20`,'The full rate at x=1 is twenty, not ten.',{sequence:'square-chain'}),
 m('07','a','Check by expanding first',String.raw`(2x+3)^2=4x^2+12x+9`,'Expansion gives a second route to the same derivative.'),
 q('07','b','Compare the two derivative forms','Are 8x+12 and 4(2x+3) equal for every x?','Yes; distributing 4 gives 8x+12.'),
 m('08','a','Identify a new inner rule',String.raw`u=3x-1,\qquad y=u^4`,'The outer power is four.',{sequence:'fourth-power-chain'}),
 m('08','b','Differentiate the outside in u',String.raw`\frac{dy}{du}=4u^3`,'Reduce the outer exponent by one.',{sequence:'fourth-power-chain'}),
 m('08','c','Differentiate the inside',String.raw`\frac{du}{dx}=3`,'The linear inner slope supplies another factor.',{sequence:'fourth-power-chain'}),
 m('08','d','Combine and restore x',String.raw`y'=4(3x-1)^3(3)`,'The result is 12(3x−1)³.',{sequence:'fourth-power-chain'}),
 m('09','a','Rewrite the nested square root',String.raw`y=(2x+1)^{1/2}`,'The derivative formula requires 2x+1>0.',{sequence:'root-chain'}),
 m('09','b','Differentiate the half power',String.raw`\frac{dy}{du}=\frac12u^{-1/2}`,'The outer rate is defined at positive u.',{sequence:'root-chain'}),
 m('09','c','Include the inner slope',String.raw`y'=\frac12(2x+1)^{-1/2}(2)`,'The inner factor cancels the one half.',{sequence:'root-chain'}),
 m('09','d','Report the rate and domain',String.raw`y'=\frac1{\sqrt{2x+1}},\quad x>-\frac12`,'The square-root function exists at the endpoint, but this derivative does not.',{sequence:'root-chain'}),
 m('10','a','Read a negative inner slope',String.raw`u=5-x\quad\Longrightarrow\quad u'=-1`,'Increasing x decreases the inner input.'),
 q('10','b','Predict the derivative sign','For y=(5−x)² at x=2, should the derivative be positive or negative?','Negative: y′=−2(5−2)=−6.'),
 e('11','a','The outer derivative is only half the chain','“((2x+3)²)′=2(2x+3).”','Multiply by the inner derivative 2; the full derivative is 4(2x+3).'),
 c('11','b','Check both dependency links','Identify the outside operation and the inside rate separately.','A forgotten inner factor changes the result.'),
 c('12','a','Revenue has two moving factors','In R(q)=q(100−q), both quantity and price depend on q.','A product needs contributions from both factors.'),
 q('12','b','Name both factors','For q(100−q), which factor changes when q changes?','Both q and 100−q.'),
 c('13','a','A change can enter through either factor','Hold price at its current level while quantity changes, then account for the price change.','The product rule sums both first-order contributions.',{sequence:'revenue-product'}),
 m('13','b','Differentiate the first factor',String.raw`u(q)=q,\qquad u'(q)=1`,'The other factor remains at its current value in this contribution.',{sequence:'revenue-product'}),
 m('13','c','Differentiate the second factor',String.raw`v(q)=100-q,\qquad v'(q)=-1`,'A rising quantity lowers the price in this model.',{sequence:'revenue-product'}),
 m('13','d','Write the two product contributions',String.raw`R'=u'v+uv'`,'This is a sum, not a product of two derivatives.',{sequence:'revenue-product'}),
 m('14','a','Substitute the first contribution',String.raw`u'v=1(100-q)`,'One extra quantity unit at the current price contributes 100−q.',{sequence:'revenue-product'}),
 m('14','b','Substitute the second contribution',String.raw`uv'=q(-1)`,'The price response changes revenue on the current quantity.',{sequence:'revenue-product'}),
 m('14','c','Add the contributions',String.raw`R'=(100-q)-q`,'The price decline offsets some quantity-related gain.',{sequence:'revenue-product'}),
 m('14','d','Collect like terms',String.raw`R'=100-2q`,'The slope depends on the current quantity.',{sequence:'revenue-product'}),
 m('15','a','Expand the original product',String.raw`R=100q-q^2`,'A polynomial provides an independent check.'),
 m('15','b','Differentiate the expanded form',String.raw`R'=100-2q`,'Both approaches return the same function.'),
 t('16','a','Read the two contributions at thirty',['Contribution','Value'],[['Current price × quantity rate','70'],['Quantity × price rate','−30']],'Their sum is a local revenue rate of forty.'),
 m('16','b','Check the net local rate',String.raw`70-30=40`,'The second term cannot be dropped.'),
 m('17','a','Find where the revenue rate is zero',String.raw`100-2q=0\quad\Longrightarrow\quad q=50`,'The derivative changes sign across this candidate.'),
 q('17','b','Read the sign at sixty','For R′=100−2q, is revenue increasing or decreasing near q=60?','Decreasing: R′(60)=−20.'),
 m('18','a','Identify the two new factors',String.raw`u=x^2,\quad v=3x+1`,'Each factor has its own derivative.',{sequence:'second-product'}),
 m('18','b','Differentiate each factor',String.raw`u'=2x,\quad v'=3`,'Keep the original factors as well.',{sequence:'second-product'}),
 m('18','c','Assemble the product rule',String.raw`f'=2x(3x+1)+3x^2`,'The second contribution multiplies x² by three.',{sequence:'second-product'}),
 m('18','d','Simplify the result',String.raw`f'=6x^2+2x+3x^2=9x^2+2x`,'Collect the two quadratic terms.',{sequence:'second-product'}),
 e('19','a','Multiplying derivatives loses terms','“(x²×x)′=(2x)(1)=2x.”','The product rule gives 2x·x+x²·1=3x².'),
 m('19','b','Check with the combined power',String.raw`x^2x=x^3\quad\Longrightarrow\quad f'=3x^2`,'A simpler equivalent expression exposes the wrong shortcut.'),
 t('20','a','Choose a rule from the structure',['Expression','Structure','Rule'],[['(2x+3)²','Nested functions','Chain'],['x²(3x+1)','Product','Product'],['x²+3x','Sum','Term by term']],'Read the operations before calculating.'),
 c('20','b','A function can need several rules','Differentiate a product term and use the chain rule inside either factor when needed.','Structure decides the order of the calculation.'),
 m('21','a','Evaluate the revenue derivative at thirty',String.raw`R'(30)=100-60=40`,'The rate is currency per output unit.'),
 c('21','b','A rate graph describes the changing response','Moving q changes the local slope.','The original revenue value and derivative value remain distinct.'),
 m('22','a','Compare a finite revenue increment',String.raw`R(31)-R(30)=2139-2100=39`,'A full extra unit produces a finite change of thirty-nine.'),
 q('22','b','Is the derivative the exact next-unit change?','At q=30, R′=40 but the one-unit increment is 39. Are the statements inconsistent?','No. The derivative is local; the one-unit change includes curvature.'),
 m('23','a','Use a small-step check for the chain',String.raw`\frac{(2(1.01)+3)^2-25}{0.01}=20.04`,'This nearby average approaches the exact rate twenty.'),
 c('23','b','Check without changing the target','The first input stays at x=1 while the second input approaches it.','A numerical check supports, but does not prove, the symbolic rule.')
];
export const guides07=['0–9分钟识别内外函数；9–24分钟逐步完成平方链式法则并展开核对；24–35分钟四次幂和根式案例；35–41分钟负内导数及漏乘诊断；41–45分钟结构检查。话术：“Differentiate the outside, keep the inside.” “Now multiply by the inner rate.”','0–10分钟辨认收入的两项变化；10–25分钟逐项构建乘积法则并解释贡献；25–35分钟第二乘积算例与错解；35–41分钟符号和有限步核对；41–45分钟出口题。话术：“Both factors can change.” “Add both contributions.”'] as const;
