import {author,type Insertion} from './authoring.js';import {lesson15} from '../lessons/lesson-15.js';import type {PlotSpec} from '../types.js';
const {m,c,q,e,t,g}=author(15,lesson15.sources[0]!);
const market=(extras:Partial<PlotSpec>={}):PlotSpec=>({xRange:[0,40],yRange:[0,65],xLabel:'Quantity',yLabel:'Price (€/unit)',curves:[{kind:'polynomial',coefficients:[60,-1],color:'blue'},{kind:'polynomial',coefficients:[20,1],color:'coral'},{kind:'polynomial',coefficients:[40],color:'green'}],...extras});
export const additions15:readonly Insertion[]=[
 c('02','a','Read a willingness-to-pay schedule','D(q)=60−q gives the value of the next unit to buyers.','S(q)=20+q gives the marginal supply cost in this competitive model.'),
 t('02','b','Compare values before choosing a price',['q','D(q) (€/unit)','S(q) (€/unit)'],[['0','60','20'],['10','50','30'],['20','40','40'],['30','30','50']],'Buyer value falls while marginal supply cost rises.'),
 m('03','a','Set the two schedules equal',String.raw`60-q=20+q`,'At a competitive equilibrium, demand and supply quantities agree.',{sequence:'equilibrium'}),
 m('03','b','Solve for the traded quantity',String.raw`40=2q\quad\Longrightarrow\quad q^*=20`,'The two schedules meet at twenty units.',{sequence:'equilibrium'}),
 m('03','c','Recover the common price',String.raw`p^*=60-20=20+20=40`,'Either schedule gives €40 per unit.',{sequence:'equilibrium'}),
 q('03','d','Check the equilibrium against both schedules','At q=20, what are demand price and supply price?','Both are €40 per unit.'),
 g('04','a','Locate price and quantity together',market({points:[{x:20,y:40,label:'Equilibrium'}]}),String.raw`(q^*,p^*)=(20,40)`,'The horizontal price line is the payment for every traded unit.'),
 c('04','b','Keep price and total payment separate','A price of €40 per unit is not total revenue.','Twenty units at that price generate €800 in sales revenue.'),
 m('05','a','Find the value gap at the first unit',String.raw`D(0)-p^*=60-40=20`,'Buyers value the first marginal unit €20 above its payment.',{sequence:'consumer-surplus'}),
 m('05','b','Find the gap at any traded quantity',String.raw`D(q)-p^*=20-q`,'The gap shrinks towards zero at the equilibrium quantity.',{sequence:'consumer-surplus'}),
 t('05','c','Sample the buyer value gap',['q','Value gap (€/unit)'],[['0','20'],['5','15'],['10','10'],['15','5'],['20','0']],'These are heights; accumulation across quantity gives euros.',{sequence:'consumer-surplus'}),
 q('05','d','Check the units of a surplus strip','What unit results from (euros per unit) × quantity units?','Euros.'),
 m('06','a','Accumulate value above payment',String.raw`CS=\int_0^{20}(20-q)\,dq`,'Integrate only over units that are traded.',{sequence:'consumer-surplus'}),
 m('06','b','Recover an antiderivative of the gap',String.raw`20q-\frac{q^2}{2}`,'Use endpoint evaluation to obtain the area in euros.',{sequence:'consumer-surplus'}),
 m('07','a','Evaluate at the upper quantity',String.raw`20(20)-\frac{20^2}{2}=200`,'The lower-end value is zero.',{sequence:'consumer-surplus'}),
 m('07','b','State the economic quantity',String.raw`CS=200\ \text{euros}`,'This is value above payment, under the stated demand model.',{sequence:'consumer-surplus'}),
 g('07','c','View the consumer gap as an area',market({area:{curve:0,from:0,to:20,baseline:40}}),String.raw`CS=200`,'The blue area lies below demand and above the €40 price line.'),
 q('07','d','Separate surplus from spending','Are buyers’ total payments €200 or €800?','€800. The €200 is consumer surplus, not spending.'),
 m('08','a','Use geometry as an independent check',String.raw`CS=\frac12(20)(20)`,'The base is twenty units and the height is €20 per unit.'),
 c('08','b','Why a triangle works here','The gap is linear and reaches zero at the endpoint.','A curved demand schedule would require its own integral.'),
 m('09','a','Find the seller gap per unit',String.raw`p^*-S(q)=40-(20+q)=20-q`,'Revenue per marginal unit exceeds its marginal supply cost.',{sequence:'producer-surplus'}),
 t('09','b','Read the seller gap at three quantities',['q','Price','Marginal cost','Gap'],[['0','40','20','20'],['10','40','30','10'],['20','40','40','0']],'Prices and cost readings are in euros per unit.',{sequence:'producer-surplus'}),
 m('10','a','Integrate the seller gap',String.raw`PS=\int_0^{20}(20-q)\,dq`,'The supply schedule is interpreted as marginal cost here.',{sequence:'producer-surplus'}),
 m('10','b','Apply the same endpoint calculation',String.raw`\left[20q-\frac{q^2}{2}\right]_0^{20}=200`,'The numerical equality to CS comes from these particular slopes.',{sequence:'producer-surplus'}),
 m('11','a','Express producer surplus geometrically',String.raw`PS=\frac12(20)(20)=200`,'The area is above supply and below the price line.'),
 q('11','b','Check whether equality is universal','Must CS and PS be equal in every market?','No. Their equality here follows from this pair of linear schedules.'),
 m('12','a','Calculate total sales revenue',String.raw`TR=p^*q^*=40(20)=800`,'A price rectangle gives total sales revenue.',{sequence:'revenue-cost-surplus'}),
 c('12','b','Price does not measure production cost','The payment for a unit is €40, but its marginal cost depends on q.','Accumulating the supply schedule gives variable cost.'),
 m('13','a','Accumulate the marginal supply cost',String.raw`VC=\int_0^{20}(20+q)\,dq`,'This cost excludes any fixed cost.',{sequence:'revenue-cost-surplus'}),
 m('13','b','Evaluate variable cost',String.raw`\left[20q+\frac{q^2}{2}\right]_0^{20}=600`,'The marginal-cost area is €600.',{sequence:'revenue-cost-surplus'}),
 m('13','c','Compare a rectangle and a trapezoid',String.raw`TR=800,\qquad VC=600`,'Sales revenue and variable cost are different regions.'),
 t('13','d','Track all money quantities',['Quantity','Amount (€)'],[['Sales revenue','800'],['Variable cost','600'],['Revenue minus variable cost','200']],'The final row is producer surplus under these assumptions.'),
 m('14','a','Recover surplus by subtraction',String.raw`PS=TR-VC=800-600=200`,'This agrees with the direct gap integral.'),
 c('14','b','Keep both calculation routes available','Integrate price minus supply, or subtract variable cost from revenue.','Agreement is a useful arithmetic and interpretation check.'),
 m('15','a','Introduce a fixed cost',String.raw`FC=50\quad\Longrightarrow\quad TC=600+50=650`,'Fixed cost does not appear in the marginal-cost area.',{sequence:'profit-boundary'}),
 m('15','b','Calculate profit after fixed cost',String.raw`\pi=800-650=150`,'Profit is €50 lower than producer surplus.',{sequence:'profit-boundary'}),
 m('15','c','Write the complete total-cost rule',String.raw`C(q)=50+20q+\frac{q^2}{2}`,'Its derivative is the supply schedule; C(0)=50 supplies the fixed cost.'),
 q('15','d','Trace the omitted constant','If fixed cost rises from €50 to €90 with the schedules unchanged, what happens to PS and profit?','PS remains €200; profit falls from €150 to €110.'),
 m('16','a','Connect producer surplus and profit',String.raw`\pi=PS-FC`,'This identity uses the present cost interpretation.',{sequence:'profit-boundary'}),
 e('16','b','Diagnose an omitted cost','“Producer surplus is €200, so profit must be €200.”','Only if fixed cost is zero here. With FC=€50, profit is €150.'),
 m('17','a','Add buyer and seller gains',String.raw`TS=CS+PS=200+200=400`,'Total surplus counts the value gap across the market.',{sequence:'total-surplus'}),
 m('17','b','Subtract the two schedules directly',String.raw`D(q)-S(q)=40-2q`,'Price cancels when buyer and seller gaps are added.',{sequence:'total-surplus'}),
 m('17','c','Integrate the combined gap',String.raw`TS=\int_0^{20}(40-2q)\,dq`,'The gain from each traded marginal unit is value minus marginal cost.',{sequence:'total-surplus'}),
 m('17','d','Evaluate the total gain',String.raw`[40q-q^2]_0^{20}=400`,'The direct integral agrees with CS+PS.',{sequence:'total-surplus'}),
 m('18','a','Measure gains if trade stops early',String.raw`\int_0^{10}(40-2q)\,dq=400-100=300`,'Stopping at ten units leaves some positive value gaps untraded.'),
 m('18','b','Find the omitted gains',String.raw`400-300=100`,'Under the same schedules, another ten units add €100 of total surplus.'),
 c('19','a','A unit beyond equilibrium can reduce gains','At q=25, willingness to pay is €35 and marginal cost is €45.','Producing that marginal unit costs €10 more than its value.'),
 e('19','b','Diagnose “more trade is always better”','“Every unit beyond q=20 must increase total surplus.”','Beyond q=20, D(q)−S(q) is negative in this model.'),
 c('20','a','State the model interpretation','Competitive price; demand as marginal value; supply as marginal cost.','These interpretations support the surplus calculation.'),
 q('20','b','Check what the area can establish','Does a calculated consumer-surplus area tell us each household’s gain?','No. It is the aggregate gain represented by the demand schedule.'),
 m('21','a','Solve a shifted market',String.raw`50-q=10+q\quad\Longrightarrow\quad q^*=20,\ p^*=30`,'Both schedules moved down by €10.',{sequence:'shifted-market'}),
 m('21','b','Recalculate buyer and seller gaps',String.raw`D(q)-30=30-S(q)=20-q`,'The two surplus gaps are unchanged despite the lower price.',{sequence:'shifted-market'}),
 m('21','c','Compare surplus with total revenue',String.raw`CS=PS=200,\qquad TR=30(20)=600`,'Surplus is unchanged while sales revenue falls.',{sequence:'shifted-market'}),
 q('21','d','Recover variable cost in the shifted market','If revenue is €600 and PS is €200, what is variable cost?','€400; equivalently integrate 10+q from 0 to 20.'),
 m('22','a','Use the new fixed-cost datum',String.raw`FC=80,\quad\pi=PS-FC=120`,'Profit depends on a cost that the surplus area does not include.'),
 t('22','b','Compare the two markets',['Market','Price','TR','VC','PS','FC','Profit'],[['Original','40','800','600','200','50','150'],['Shifted','30','600','400','200','80','120']],'All money totals are euros; prices are euros per unit.'),
 c('23','a','Explain the extra value precisely','Consumer surplus: buyer value above payment. Producer surplus: revenue above variable cost.','Profit also deducts fixed cost in this model.'),
 q('23','b','Choose the right subtraction','A firm has TR=900, VC=640 and FC=70. Find PS and profit.','PS=€260 and profit=€190, under the stated marginal-cost interpretation.'),
];
export const guides15=[
 '第1学时：先读需求与供给，再逐步求均衡和消费者剩余；每个面积都核对高度与横轴单位。英文：Is this number a price, a payment, or value above payment? 三角形只作为当前线性案例的独立核对。',
 '第2学时：从生产者剩余进入收入、可变成本、固定成本与利润，再比较总剩余及少交易、过量交易。英文：Which cost is missing from the marginal-cost area? 在平移市场与出口题保留独立作答停顿；选学在核心90分钟外。',
] as const;
