import {author,type Insertion} from './authoring.js';
import {lesson05} from '../lessons/lesson-05.js';
import type {PlotSpec} from '../types.js';
const {m,c,q,e,t,g}=author(5,lesson05.sources[0]!);
const motion=(extras:Partial<PlotSpec>={}):PlotSpec=>({xRange:[0,4],yRange:[0,16],xLabel:'Time (s)',yLabel:'Position (m)',curves:[{kind:'polynomial',coefficients:[0,0,1],color:'blue'}],...extras});
export const additions05:readonly Insertion[]=[
 c('02','a','A position is not a journey length','The vehicle is 4 metres from the origin at t = 2.','A recorded position describes a location.'),
 t('02','b','Follow the clock and the location',['t (s)','0','1','2'],[['s(t) (m)','0','1','4']],'The clock advances equally; the position does not.'),
 q('02','c','Read the change, not the last reading','At t=2 the position is 4 m; at t=3 it is 9 m. How much does position change?','9−4=5 metres.'),
 c('03','a','Join observations with a model','The rule s(t)=t² reproduces the recorded positions.','It is a simplified teaching model on 0 ≤ t ≤ 4.'),
 m('03','b','Test the rule at a recorded time',String.raw`s(3)=3^2=9`,'Substitution recovers the nine-metre observation.'),
 g('03','c','Read height as position',motion({points:[{x:2,y:4,label:'(2,4)'}]}),String.raw`s(2)=4`,'The height is a position. It is not the slope.'),
 m('04','a','Choose the interval first',String.raw`[1,3],\qquad\Delta t=3-1=2`,'The interval lasts two seconds.',{sequence:'average-motion'}),
 m('04','b','Subtract the endpoint positions',String.raw`\Delta s=s(3)-s(1)=9-1=8`,'The vehicle advances eight metres over this interval.',{sequence:'average-motion'}),
 m('04','c','Divide change by elapsed time',String.raw`\frac{\Delta s}{\Delta t}=\frac{8\,\mathrm m}{2\,\mathrm s}`,'This division produces metres per second.',{sequence:'average-motion'}),
 m('05','a','Interpret the quotient',String.raw`\mathrm{average\ speed}=4\,\mathrm{m/s}`,'Eight metres over two seconds gives a four-metre-per-second average.',{sequence:'average-motion'}),
 c('05','b','An average compresses an interval','One number summarizes the total change across two endpoints.','It does not specify the speed at each intervening moment.',{sequence:'average-motion'}),
 q('05','c','Change the interval','For s(t)=t², find the average rate from t=0 to t=2.','(4−0)/(2−0)=2 m/s.'),
 g('06','a','Mark the first endpoint',motion({points:[{x:1,y:1,label:'Start'}]}),String.raw`(1,1)`,'The first coordinate is time; the second is position.'),
 g('06','b','Mark the second endpoint',motion({points:[{x:1,y:1},{x:3,y:9,label:'End'}]}),String.raw`(3,9)`,'The rise is eight metres and the run is two seconds.'),
 g('06','c','A secant connects the observations',motion({secant:{curve:0,x:1,h:2}}),String.raw`m=\frac{9-1}{3-1}`,'The line slope represents the interval average.'),
 t('07','a','Several intervals, several rates',['Interval','Position change','Average rate'],[['[0,1]','1 m','1 m/s'],['[1,2]','3 m','3 m/s'],['[2,3]','5 m','5 m/s']],'An equal one-second duration does not force equal distance changes.'),
 c('07','b','Ask a more local question','Which interval tells us most about the moment t=2?','A shorter interval stays closer to the target time.'),
 e('07','c','Do not call a height a speed','“s(2)=4 means the speed at two seconds is 4 m/s.”','s(2)=4 is a position in metres. Speed must come from a rate calculation.'),
 g('08','a','Hold the target point fixed',motion({points:[{x:2,y:4,label:'Target'}]}),String.raw`t=2`,'All comparisons now start from the same target time.'),
 m('08','b','A full second still covers a range',String.raw`\frac{s(3)-s(2)}{1}=5`,'This average uses times from two to three seconds.'),
 c('08','c','The target is one moment','An interval average is a useful estimate, but the target is instantaneous speed.','We need to see what happens as the interval becomes shorter.'),
 m('09','a','Move the second time closer',String.raw`2+0.5=2.5`,'The new interval is half a second.',{sequence:'local-estimates'}),
 m('09','b','Calculate its position change',String.raw`s(2.5)-s(2)=6.25-4=2.25`,'The change is in metres, before division by time.',{sequence:'local-estimates'}),
 m('09','c','Calculate the shorter average',String.raw`\frac{2.25}{0.5}=4.5\,\mathrm{m/s}`,'A shorter interval gives a different local estimate.',{sequence:'local-estimates'}),
 m('10','a','Try one tenth of a second',String.raw`\frac{2.1^2-2^2}{0.1}=\frac{0.41}{0.1}=4.1`,'Keep the small position change and time change paired.',{sequence:'local-estimates'}),
 m('10','b','Try one hundredth of a second',String.raw`\frac{2.01^2-4}{0.01}=4.01`,'The estimate is approaching a stable value.',{sequence:'local-estimates'}),
 t('10','c','Read the trend in the estimates',['h (s)','1','0.5','0.1','0.01'],[['Average (m/s)','5','4.5','4.1','4.01']],'The values approach four, but every listed interval still has positive length.',{sequence:'local-estimates'}),
 c('11','a','Name the small time step','Let h be the change in time from the fixed target t=2.','The second time is 2+h, not h alone.',{sequence:'difference-quotient'}),
 m('11','b','Use the model at the new time',String.raw`s(2+h)=(2+h)^2`,'The entire new time goes inside the square.',{sequence:'difference-quotient'}),
 m('11','c','Form the quotient before simplifying',String.raw`\frac{(2+h)^2-2^2}{h}`,'The numerator is position change; the denominator is time change.',{sequence:'difference-quotient'}),
 m('12','a','Open both factors of the square',String.raw`(2+h)^2=(2+h)(2+h)`,'There are four multiplication terms.',{sequence:'difference-quotient'}),
 m('12','b','Keep the cross terms',String.raw`(2+h)^2=4+2h+2h+h^2`,'Both cross products contribute to the result.',{sequence:'difference-quotient'}),
 m('12','c','Remove the original position',String.raw`(4+4h+h^2)-4=4h+h^2`,'The starting four metres cancels in the position difference.',{sequence:'difference-quotient'}),
 m('13','a','Find a common factor first',String.raw`4h+h^2=h(4+h)`,'Every term in the numerator contains h.',{sequence:'difference-quotient'}),
 m('13','b','Cancel the common nonzero factor',String.raw`\frac{h(4+h)}h=4+h,\quad h\ne0`,'Cancellation is valid for a nonzero interval.',{sequence:'difference-quotient'}),
 e('13','c','Zero cannot be inserted too soon','“Set h=0 in ((2+h)²−4)/h and divide.”','The original quotient gives 0/0. Simplify for h≠0, then examine the limit.'),
 c('14','a','Approach zero without dividing by zero','The quotient equals 4+h whenever h is nonzero.','Its approached value can exist even though the original quotient is undefined at zero.'),
 m('14','b','The varying part becomes small',String.raw`h\to0\quad\Longrightarrow\quad4+h\to4`,'Only the interval-dependent part disappears.'),
 m('14','c','Attach the instantaneous-rate unit',String.raw`s'(2)=4\,\mathrm{m/s}`,'The limit defines the instantaneous rate at two seconds.'),
 g('15','a','Bring the second point near the first',motion({secant:{curve:0,x:2,h:0.5}}),String.raw`h=0.5`,'The secant has two distinct points.'),
 g('15','b','Compare a still shorter secant',motion({secant:{curve:0,x:2,h:0.1}}),String.raw`h=0.1`,'Its direction moves toward the tangent direction.'),
 g('15','c','Read the limiting direction',motion({tangent:{curve:0,x:2}}),String.raw`m=4`,'The tangent describes local change, not the whole curve.'),
 c('16','a','Prime notation names a rate','s′(2) is the derivative of position evaluated at two seconds.','Read it aloud: “s prime at two.”'),
 m('16','b','Leibniz notation names both variables',String.raw`\left.\frac{ds}{dt}\right|_{t=2}`,'Read it aloud: “the derivative of s with respect to t, at t equals two.”'),
 q('16','c','Name the requested quantity','A question asks for position at t=2. Should you calculate s(2) or s′(2)?','Calculate s(2). The derivative answers a rate question.'),
 m('17','a','Replace two seconds by any target',String.raw`\frac{(a+h)^2-a^2}{h}`,'The same construction works at a general target a.',{sequence:'derivative-function'}),
 m('17','b','Expand and subtract the starting value',String.raw`(a+h)^2-a^2=2ah+h^2`,'The a² terms cancel.',{sequence:'derivative-function'}),
 m('17','c','Factor and cancel for nonzero h',String.raw`\frac{h(2a+h)}h=2a+h`,'The expression is valid away from h=0.',{sequence:'derivative-function'}),
 m('18','a','Take the approached value',String.raw`\lim_{h\to0}(2a+h)=2a`,'The derivative at the arbitrary target a is 2a.',{sequence:'derivative-function'}),
 m('18','b','Make the rate into its own function',String.raw`s'(t)=2t`,'A new input time produces a new instantaneous rate.',{sequence:'derivative-function'}),
 t('18','c','Compare position and rate',['t (s)','s(t) (m)','s′(t) (m/s)'],[['1','1','2'],['2','4','4'],['3','9','6']],'The two functions answer different questions.',{sequence:'derivative-function'}),
 c('19','a','Positive slope means increasing position','At positive times, s′(t)=2t is positive.','The model moves in the positive position direction.'),
 c('19','b','Zero slope can mean a still moment','The local rate may be zero at an endpoint or an interior point.','A zero derivative does not by itself describe the whole journey.'),
 q('19','c','Interpret a signed derivative','A position model has derivative −3 m/s at one moment. What does the sign say?','Position is decreasing at that moment; the negative sign specifies direction.'),
 m('20','a','A linear model has equal interval rates',String.raw`\frac{[3(t+h)+1]-(3t+1)}h`,'Compare any two distinct times in the linear position model.'),
 m('20','b','The time step cancels exactly',String.raw`\frac{3h}{h}=3,\quad h\ne0`,'Every interval gives the same rate for this linear model.'),
 c('20','c','A straight line already has its tangent direction','The secant and tangent directions coincide for a line.','This special case should not be assumed for a curved graph.'),
 q('21','a','Predict before moving the slider','For s(t)=t² near t=2, will the average rate with h=0.01 be above or below 4?','Above: it is 4+h=4.01 for positive h.'),
 c('21','b','Keep the first point fixed during the experiment','Change h while preserving the target time and its position.','Otherwise two different comparisons change at once.'),
 m('22','a','Measure the finite-step discrepancy',String.raw`4.1-4=0.1\,\mathrm{m/s}`,'The nearby interval average differs from the instantaneous rate.'),
 c('22','b','An estimate is not an identity','A small finite interval can approximate a derivative closely.','Report the interval and distinguish approximate from exact.'),
 e('22','c','Small is not the same as zero','“The h=0.1 average is exactly the derivative because 0.1 is small.”','It is 4.1 m/s; the derivative is 4 m/s. Small finite increments remain estimates.'),
 t('23','a','Approach a corner from either side',['Direction','Slope near 0'],[['From the left','−1'],['From the right','+1']],'A single limiting tangent slope needs the two directions to agree.'),
 c('23','b','Continuity does not guarantee a derivative','The graph of |x| meets at zero, but its two slopes disagree.','The value exists at the corner; the derivative does not.')
];
export const guides05=['0–7分钟分清位置与位移；7–19分钟逐步求区间平均速度；19–30分钟读割线与变换区间；30–40分钟缩小时间步、数值预测；40–45分钟即时检查。话术：“Which two times define the interval?” “Position is a height; rate is a slope.”','0–12分钟展开差商并先因式分解；12–22分钟从非零h的式子理解极限；22–33分钟推导一般时刻的导数函数；33–40分钟符号、线性例与尖点；40–45分钟出口解释。话术：“Simplify before approaching zero.” “A finite estimate is still an estimate.”'] as const;
