import {author,type Insertion} from './authoring.js';import {lesson02} from '../lessons/lesson-02.js';
const {m,c,q,e,t,g}=author(2,lesson02.sources[0]!);
export const additions02:readonly Insertion[]=[
 c('02','a','Choose the input','Distance is the input; the delivery charge is the output.','One allowed distance receives one charge.'),
 c('02','b','A rule can have many inputs','The same distance-charge rule applies to several deliveries.','A function records the relationship, not one receipt.'),
 m('03','a','Name the charge rule',String.raw`f(x)=3+2x`,'The base fee is $3; the distance rate is $2 per kilometre.',{sequence:'charge-table'}),
 m('03','b','Insert a distance into the rule',String.raw`f(4)=3+2(4)`,'The input replaces x everywhere it appears.',{sequence:'charge-table'}),
 c('04','a','State the service boundary','This delivery service accepts distances from 0 to 20 km.','A formula and its allowed inputs belong together.'),
 q('04','b','Formula or valid model?','The formula gives f(25)=53. Does that establish a valid charge for this service?','No. Twenty-five kilometres lies outside the stated domain.'),
 m('04','c','Include both boundary values',String.raw`0\le x\le20`,'Zero and twenty are included in this model.'),
 e('04','d','A formula does not erase a restriction','“Any number can be used because 3+2x can be calculated.”','A calculable expression may still be outside the modelled service domain.'),
 m('05','a','Calculate the first nonzero example',String.raw`f(1)=3+2=5`,'A one-kilometre trip costs five dollars.',{sequence:'charge-table'}),
 m('05','b','Calculate a second example',String.raw`f(2)=3+4=7`,'The two-kilometre trip adds two dollars.',{sequence:'charge-table'}),
 c('06','a','A coordinate has an order','Write the input first and the output second.','The point (2,7) means 2 km and $7.'),
 e('06','b','Do not reverse the receipt','“The point (7,2) records a 2 km trip costing $7.”','With distance on the horizontal axis, the correct ordered pair is (2,7).'),
 t('07','a','Compare equal distance changes',['x (km)','0','1','2','3'],[['Charge ($)','3','5','7','9']],'Every additional kilometre adds the same charge.'),
 c('07','b','A constant rate makes a line','A fixed increase in output per unit input gives a straight graph.','The starting output sets the height at zero.'),
 m('08','a','Read the output change',String.raw`\Delta y=11-7=4`,'The charge rises four dollars between the two points.',{sequence:'line-slope'}),
 m('08','b','Read the input change',String.raw`\Delta x=4-2=2`,'The trips differ by two kilometres.',{sequence:'line-slope'}),
 m('08','c','Divide rise by run',String.raw`b=\frac42=2\,\frac{\$}{\mathrm{km}}`,'Slope is a rate with a unit.',{sequence:'line-slope'}),
 q('08','d','Use a longer interval','The charge rises $6 across 3 km. What slope follows?','2 dollars per kilometre; 6/3=2.'),
 m('09','a','Set the input to zero',String.raw`f(0)=3+2(0)`,'No distance charge remains at zero kilometres.'),
 c('09','b','The intercept is a starting fee','The point (0,3) is where this line meets the vertical axis.','A zero trip length does not force a zero bill.'),
 c('10','a','Shift a fee without changing its rate','A higher base fee moves every receipt up by the same amount.','Parallel lines can share a slope but have different intercepts.'),
 q('10','b','Compare the starting fees','A(x)=3+2x and B(x)=5+2x. How much more does B charge at every common input?','$2 more; the slopes are equal.'),
 m('11','a','Use two observed points',String.raw`(1,5),\qquad(3,9)`,'Find the slope before the intercept.',{sequence:'recover-line'}),
 m('11','b','Recover the slope from evidence',String.raw`b=\frac{9-5}{3-1}=2`,'The line rises two dollars per kilometre.',{sequence:'recover-line'}),
 m('11','c','Substitute one observed point',String.raw`5=a+2(1)`,'Any known point on the line can determine a.',{sequence:'recover-line'}),
 m('11','d','Recover the starting fee',String.raw`a=5-2=3`,'The two observations identify the complete linear rule.',{sequence:'recover-line'}),
 m('12','a','Reverse the input-output question',String.raw`3+2x=15`,'A known charge asks for the unknown distance.'),
 q('12','b','Check a recovered distance','A $15 charge gives x=6. Is that input allowed, and does it reproduce the bill?','Yes: 0≤6≤20 and 3+2(6)=15.'),
 c('13','a','Buyers respond to the price input','The model QD(p)=100−2p predicts the quantity buyers want.','Price is the independent variable in this view.'),
 m('13','b','Read the demand slope',String.raw`\frac{\Delta Q_D}{\Delta p}=-2`,'Each extra dollar reduces modelled demand by two units.'),
 m('14','a','Find where demand reaches zero',String.raw`100-2p=0\quad\Longrightarrow\quad p=50`,'The linear demand boundary is fifty dollars.'),
 c('14','b','Reject negative quantities as demand predictions','The demand rule is used only where its quantity is nonnegative.','The stated price domain is 0 ≤ p ≤ 50.'),
 m('15','a','Read the seller slope',String.raw`Q_S(p)=2p-20`,'Higher prices increase offered quantity in this teaching model.'),
 m('15','b','Find the nonnegative supply boundary',String.raw`2p-20\ge0\quad\Longrightarrow\quad p\ge10`,'Below ten, the linear formula needs a different interpretation or truncation.'),
 t('16','a','Compare both sides at one price',['p ($)','QD','QS'],[['20','60','20'],['30','40','40'],['40','20','60']],'Both quantities must use the same price input.'),
 c('16','b','Read the common model interval','The two untruncated linear quantities are nonnegative for 10 ≤ p ≤ 50.','A matching point must lie in the common feasible region.'),
 m('17','a','Translate agreement into equality',String.raw`Q_D(p)=Q_S(p)`,'Market agreement means equal quantities, not equal slopes.',{sequence:'market-equilibrium'}),
 m('17','b','Substitute both linear rules',String.raw`100-2p=2p-20`,'There is one shared price variable.',{sequence:'market-equilibrium'}),
 m('17','c','Collect the price terms',String.raw`100+20=2p+2p`,'Add 2p and 20 to both sides.',{sequence:'market-equilibrium'}),
 m('17','d','Solve the candidate price',String.raw`120=4p\quad\Longrightarrow\quad p=30`,'The candidate lies inside the common price domain.',{sequence:'market-equilibrium'}),
 m('18','a','Recover the buyer quantity',String.raw`Q_D(30)=100-2(30)=40`,'A price solution still needs its traded quantity.',{sequence:'market-equilibrium'}),
 m('18','b','Recover the seller quantity',String.raw`Q_S(30)=2(30)-20=40`,'Checking both rules confirms agreement.',{sequence:'market-equilibrium'}),
 c('19','a','Report price and quantity together','The model equilibrium is $30 and 40 units.','A useful market answer has both coordinates.'),
 q('19','b','Would equal slopes prove equilibrium?','The slopes are −2 and +2. Does their magnitude alone determine the matching price?','No. The intercepts matter, and equilibrium requires equal quantities.'),
 m('20','a','Measure excess demand at twenty',String.raw`Q_D(20)-Q_S(20)=60-20=40`,'Buyers want forty more units than sellers offer.'),
 c('20','b','Read a shortage as a model gap','At the lower price, desired purchases exceed offered quantity.','The gap is measured in units, not dollars.'),
 m('21','a','Measure excess supply at forty',String.raw`Q_S(40)-Q_D(40)=60-20=40`,'Offered quantity exceeds desired purchases by forty units.'),
 q('21','b','Choose the appropriate gap','At a high price, QS exceeds QD. What quantity difference describes the excess?','QS−QD, a positive excess-supply quantity.'),
 m('22','a','Move the demand quantity to the other side',String.raw`Q=100-2p\quad\Longrightarrow\quad2p=100-Q`,'Rearrangement gives the price as a function of quantity.'),
 m('22','b','Read the inverse demand rule',String.raw`p=50-\frac12Q`,'Changing which variable is input changes the slope unit.'),
 c('23','a','A model covers its stated situation','The linear rule summarizes a specified price and quantity range.','It need not describe every market or every possible price.'),
 e('23','b','Demand is not the same as a sale','“QD(20)=60 proves that exactly 60 units were sold.”','Demand is desired quantity at that price. Actual trade also depends on supply and market rules.')
];
export const guides02=['0–10分钟输入输出及允许输入；10–22分钟逐步制表与读坐标；22–34分钟由两点求斜率和截距；34–40分钟反推输入；40–45分钟检查。话术：“Input first, output second.” “What does the slope measure?”','0–10分钟分别读供需模型及公共定义域；10–24分钟建立相等方程并逐步求价量；24–35分钟比较短缺与过剩；35–41分钟反需求与模型范围；41–45分钟出口题。话术：“Use one price in both rules.” “Report both price and quantity.”'] as const;
