import { defineEconomicMathematicsLesson } from "../types.js";

export const economicMathematicsLesson16 = defineEconomicMathematicsLesson({
  number: 16,
  unit: 4,
  unitTitle: "导数应用、边际与弹性分析",
  title: "哪个客群更怕涨价？",
  hours: 2,
  expectedSlides: 47,
  coreQuestion: "怎样用无量纲弹性比较不同客群的价格敏感性，并区分弹性对收益与利润的不同含义？",
  exerciseCapability: "能计算点弹性与弧弹性，判断弹性区间，并结合成本解释价格变化对收益和利润的方向。",
  slides: [
    {
      slideKey: "econ-math-l16-01",
      compositionId: "two-segment-price-alert",
      section: "同涨1元，谁更敏感",
      title: "两个客群都少买10杯，反应一样大吗？",
      kicker: "山城新饮 · 分客群定价",
      kind: "scene",
      visual: "editorial-scene",
      lead: "价格上调1元后，A客群和B客群的预测销量都下降，但原有价格与销量基数不同。",
      body: ["绝对减少量便于核算。", "跨客群比较还需要把变化放回各自基数。"],
      prompt: "少10杯占700杯与占100杯，能否视为同等反应？",
      sourceLabel: "教学情境",
      sourceNote: "虚构客群比较",
      accent: "vermilion",
      teachingCue: "先让学生用百分比语言解释，再引出弹性。",
      assistantCue: "强调相对变化；不提前给点弹性公式。"
    },
    {
      slideKey: "econ-math-l16-02",
      compositionId: "absolute-relative-change",
      section: "同涨1元，谁更敏感",
      title: "敏感性需要比较两个百分比",
      kicker: "结果变化率 ÷ 原因变化率",
      kind: "question",
      visual: "comparison-board",
      data: ["价格增加1元：绝对输入变化", "销量减少若干杯：绝对结果变化", "价格变化百分比：相对输入变化", "销量变化百分比：相对结果变化"],
      prompt: "哪个比值能消除“元”和“杯”的量纲差异？",
      sourceLabel: "概念模型",
      accent: "amber",
      teachingCue: "期待“销量变化百分比/价格变化百分比”。",
      assistantCue: "弹性是相对变化之比，无单位。"
    },
    {
      slideKey: "econ-math-l16-03",
      compositionId: "point-elasticity-definition",
      section: "价格弹性",
      title: "需求价格弹性",
      kicker: "点弹性定义",
      kind: "definition",
      visual: "formula-board",
      formula: String.raw`E_d(p)=-\frac{p}{q(p)}q'(p)`,
      body: ["q′(p)描述价格变化引起的销量瞬时变化。", "p/q把带单位斜率转换为百分比之比。", "需求通常随价格下降，前置负号使弹性报告为正。"],
      sourceLabel: "教材框架",
      accent: "vermilion",
      teachingCue: "从(dq/q)/(dp/p)逐步整理到公式，说明负号约定。",
      assistantCue: "本课程报告弹性绝对值为正；如引用带符号弹性需明确约定。"
    },
    {
      slideKey: "econ-math-l16-04",
      compositionId: "signed-vs-absolute-elasticity",
      section: "价格弹性",
      title: "先声明符号约定",
      kicker: "避免“负弹性”歧义",
      kind: "definition",
      visual: "comparison-board",
      data: ["带符号形式：(p/q)q′(p)，一般为负", "绝对值形式：−(p/q)q′(p)，一般为正", "本课程后续E_d均使用正值形式"],
      body: ["正值大小表示敏感程度，不表示销量随价格同向变化。"],
      sourceLabel: "教材框架",
      accent: "ink",
      teachingCue: "要求学生在作业第一次使用时写明约定。",
      assistantCue: "后续“E>1”均基于正值约定。"
    },
    {
      slideKey: "econ-math-l16-05",
      compositionId: "elasticity-unit-cancellation",
      section: "价格弹性",
      title: "弹性没有单位",
      kicker: "因此可以跨客群比较",
      kind: "derivation",
      visual: "formula-board",
      formula: String.raw`\frac{p}{q}\frac{dq}{dp}:\quad\frac{\text{元}}{\text{杯}}\times\frac{\text{杯}}{\text{元}}=1`,
      body: ["斜率会随计量单位改变。", "弹性在价格、销量单位同步换算后保持不变。"],
      sourceLabel: "概念模型",
      accent: "cyan",
      teachingCue: "让学生说明为何“每元少10杯”不能直接跨规模比较。",
      assistantCue: "弹性无量纲，但仍依赖所在点与模型。"
    },
    {
      slideKey: "econ-math-l16-06",
      compositionId: "elasticity-classification",
      section: "价格弹性",
      title: "三个敏感区间",
      kicker: "比较销量百分比与价格百分比",
      kind: "definition",
      visual: "data-ledger",
      data: ["0≤E_d<1：缺乏弹性，销量百分比变化较小", "E_d=1：单位弹性，两个百分比大小相同", "E_d>1：富有弹性，销量百分比变化较大"],
      sourceLabel: "教材框架",
      accent: "green",
      teachingCue: "用1%涨价对应0.6%、1%、1.4%销量下降举例。",
      assistantCue: "分类只描述局部相对敏感性，不直接等同购买意愿强弱。"
    },
    {
      slideKey: "econ-math-l16-07",
      compositionId: "point-vs-arc-elasticity-map",
      section: "价格弹性",
      title: "小改动看点弹性，大区间看弧弹性",
      kicker: "两种测量尺度",
      kind: "definition",
      visual: "comparison-board",
      formula: String.raw`E_{arc}=\left|\frac{\Delta q/\bar q}{\Delta p/\bar p}\right|`,
      body: ["点弹性：一个价格点附近的瞬时敏感性。", "弧弹性：两个价格点之间的平均敏感性。", "中点基数减少方向选择造成的不对称。"],
      sourceLabel: "教材框架",
      accent: "cyan",
      teachingCue: "说明本讲主要用点弹性，最后用弧弹性核验区间变化。",
      assistantCue: "弧弹性分子分母都使用中点平均基数。"
    },
    {
      slideKey: "econ-math-l16-08",
      compositionId: "segment-a-elasticity-derivation",
      section: "A客群弹性",
      title: "A客群弹性随价格上升",
      kicker: "q_A=1200−10p",
      kind: "derivation",
      visual: "formula-board",
      formula: String.raw`E_A(p)=-\frac{p}{1200-10p}(-10)=\frac{p}{120-p}`,
      body: ["定义域还要求销量q_A>0，即p<120。", "价格越接近需求截距120，销量基数越小，弹性越高。"],
      sourceLabel: "教学情境",
      sourceNote: "山城新饮虚构A客群模型",
      accent: "vermilion",
      teachingCue: "逐项代入q与q′，防止负号丢失。",
      assistantCue: "E_A正值表达式p/(120−p)，仅在0<p<120讨论。"
    },
    {
      slideKey: "econ-math-l16-09",
      compositionId: "segment-a-elasticity-fifty",
      section: "A客群弹性",
      title: "50元：E_A≈0.714",
      kicker: "缺乏弹性",
      kind: "worked-example",
      visual: "worked-grid",
      formula: String.raw`E_A(50)=\frac{50}{120-50}=\frac57\approx0.714`,
      body: ["价格在50元附近增加1%，模型销量约下降0.714%。"],
      sourceLabel: "教学情境",
      accent: "green",
      teachingCue: "让学生用完整百分比句解释，不说“销量下降0.714杯”。",
      assistantCue: "弹性解释为百分比，不带杯数。"
    },
    {
      slideKey: "econ-math-l16-10",
      compositionId: "segment-a-unit-elasticity",
      section: "A客群弹性",
      title: "60元：E_A=1",
      kicker: "单位弹性点",
      kind: "worked-example",
      visual: "formula-board",
      formula: String.raw`E_A(60)=\frac{60}{60}=1`,
      body: ["价格与销量的局部百分比变化大小相同、方向相反。", "这一点也将成为收益方向切换点。"],
      sourceLabel: "教学情境",
      accent: "cyan",
      teachingCue: "暂不证明收益结论，要求学生记下预测。",
      assistantCue: "单位弹性不表示销量等于价格。"
    },
    {
      slideKey: "econ-math-l16-11",
      compositionId: "segment-a-elasticity-seventy",
      section: "A客群弹性",
      title: "70元：E_A=1.4",
      kicker: "富有弹性",
      kind: "worked-example",
      visual: "formula-board",
      formula: String.raw`E_A(70)=\frac{70}{50}=1.4`,
      body: ["价格在70元附近增加1%，模型销量约下降1.4%。", "销量百分比反应超过价格百分比。"],
      sourceLabel: "教学情境",
      accent: "amber",
      teachingCue: "让学生比较50、60、70三点，写出敏感性随价格的变化。",
      assistantCue: "局部解释，不将1%变化外推为大幅涨价。"
    },
    {
      slideKey: "econ-math-l16-12",
      compositionId: "segment-a-elasticity-plot",
      section: "A客群弹性",
      title: "同一条线性需求曲线，弹性并非常数",
      kicker: "斜率固定，基数在变",
      kind: "evidence",
      visual: "coordinate-plot",
      data: ["需求斜率始终为−10杯/元", "50元：销量700杯，E≈0.714", "70元：销量500杯，E=1.4"],
      body: ["斜率相同不代表百分比敏感性相同。"],
      sourceLabel: "自制图形",
      accent: "cyan",
      teachingCue: "追问变化来自公式p/q中的哪两个基数。",
      assistantCue: "弹性随p上升源于p增大且q减小。"
    },
    {
      slideKey: "econ-math-l16-13",
      compositionId: "segment-b-elasticity-derivation",
      section: "B客群弹性",
      title: "B客群的弹性函数",
      kicker: "q_B=900−6p",
      kind: "derivation",
      visual: "formula-board",
      formula: String.raw`E_B(p)=-\frac{p}{900-6p}(-6)=\frac{p}{150-p}`,
      body: ["正销量要求p<150。", "同一价格下，B客群的弹性基数与A不同。"],
      sourceLabel: "教学情境",
      sourceNote: "山城新饮虚构B客群模型",
      accent: "vermilion",
      teachingCue: "让学生独立完成约分，再显示p/(150−p)。",
      assistantCue: "表达式与定义域正确。"
    },
    {
      slideKey: "econ-math-l16-14",
      compositionId: "segment-b-elasticity-sixty",
      section: "B客群弹性",
      title: "60元：E_B=2/3",
      kicker: "仍属缺乏弹性",
      kind: "worked-example",
      visual: "formula-board",
      formula: String.raw`E_B(60)=\frac{60}{150-60}=\frac23\approx0.667`,
      body: ["价格在60元附近增加1%，模型销量约下降0.667%。"],
      sourceLabel: "教学情境",
      accent: "green",
      teachingCue: "让学生与A客群同价弹性1进行比较。",
      assistantCue: "B在60元点比A不敏感。"
    },
    {
      slideKey: "econ-math-l16-15",
      compositionId: "segment-elasticity-comparison-sixty",
      section: "B客群弹性",
      title: "同为60元，A客群更敏感",
      kicker: "无量纲比较",
      kind: "evidence",
      visual: "comparison-board",
      data: ["A客群：q=600杯，E_A=1", "B客群：q=540杯，E_B≈0.667", "结论：A的销量百分比反应更大"],
      body: ["比较的是局部敏感性，不是客群价值高低。"],
      sourceLabel: "教学情境",
      accent: "cyan",
      teachingCue: "要求学生避免写“A客群更差”，改写为可测量结论。",
      assistantCue: "只比较价格敏感性，不作价值判断。"
    },
    {
      slideKey: "econ-math-l16-16",
      compositionId: "segment-pricing-question",
      section: "B客群弹性",
      title: "更不敏感，就一定应该涨更多吗？",
      kicker: "弹性只是决策证据之一",
      kind: "question",
      visual: "decision-split",
      body: ["弹性提示销量百分比风险。", "利润还受到价格、单位成本和销量水平共同影响。", "长期客群关系与公平边界也未进入模型。"],
      prompt: "若只允许再补一个量，你会先补成本还是总销量？说明理由。",
      sourceLabel: "概念模型",
      accent: "amber",
      teachingCue: "允许不同选择，但要求说明如何进入利润判断。",
      assistantCue: "不要给单一必然答案；强调需要利润函数与约束。"
    },
    {
      slideKey: "econ-math-l16-17",
      compositionId: "elasticity-revenue-derivation",
      section: "弹性与收益",
      title: "弹性怎样决定涨价时的收益方向？",
      kicker: "把R′写成q与E的乘积",
      kind: "derivation",
      visual: "formula-board",
      formula: String.raw`R'(p)=q(p)+p q'(p)=q(p)\,[1-E_d(p)]`,
      body: ["使用正值弹性定义E_d=−(p/q)q′。", "在q>0时，R′的符号由1−E_d决定。"],
      sourceLabel: "教材框架",
      accent: "vermilion",
      teachingCue: "逐步把pq′替换为−qE，保持负号可见。",
      assistantCue: "关系只用于需求函数可导且q>0的区间。"
    },
    {
      slideKey: "econ-math-l16-18",
      compositionId: "elasticity-revenue-cases",
      section: "弹性与收益",
      title: "三种弹性对应三种局部收益方向",
      kicker: "涨价方向判断",
      kind: "definition",
      visual: "data-ledger",
      data: ["E_d<1：R′>0，小幅涨价使收益增加", "E_d=1：R′=0，收益处于驻点", "E_d>1：R′<0，小幅涨价使收益减少"],
      body: ["结论针对小幅价格变化与当前需求模型。"],
      sourceLabel: "教材框架",
      accent: "green",
      teachingCue: "让学生用“价格效应”与“销量效应”解释三种结果。",
      assistantCue: "本页讨论收益，不是利润。"
    },
    {
      slideKey: "econ-math-l16-19",
      compositionId: "segment-a-revenue-maximum",
      section: "弹性与收益",
      title: "A客群收益在60元达到峰值",
      kicker: "单位弹性点",
      kind: "derivation",
      visual: "formula-board",
      formula: String.raw`R_A(p)=1200p-10p^2,\quad R_A'(p)=1200-20p=0\Rightarrow p=60`,
      body: ["p<60时E_A<1，收益随价格上升。", "p>60时E_A>1，收益随价格下降。"],
      sourceLabel: "教学情境",
      accent: "cyan",
      teachingCue: "让学生从弹性公式与直接求导两条路径互证。",
      assistantCue: "最大收益36000元，销量600杯。"
    },
    {
      slideKey: "econ-math-l16-20",
      compositionId: "segment-a-revenue-table",
      section: "弹性与收益",
      title: "50、60、70元的收益形成对称峰",
      kicker: "数值核验",
      kind: "evidence",
      visual: "data-ledger",
      data: ["50元：q=700，R=35000，E≈0.714", "60元：q=600，R=36000，E=1", "70元：q=500，R=35000，E=1.4"],
      body: ["收益最大点与单位弹性点一致。"],
      sourceLabel: "教学情境",
      accent: "green",
      teachingCue: "让学生指出50与70收益相同但弹性不同。",
      assistantCue: "数据来自同一线性需求模型。"
    },
    {
      slideKey: "econ-math-l16-21",
      compositionId: "revenue-vs-demand-interpretation",
      section: "弹性与收益",
      title: "涨价后销量总会下降，收益却可能先升后降",
      kicker: "两个效应的较量",
      kind: "manager-brief",
      visual: "manager-memo",
      body: ["价格效应：每杯收入提高。", "销量效应：售出杯数减少。", "E<1时价格效应占优；E>1时销量效应占优。"],
      sourceLabel: "概念模型",
      accent: "amber",
      teachingCue: "让学生分别用50元和70元点解释。",
      assistantCue: "不要说弹性导致收益变化；两者都由需求函数结构决定。"
    },
    {
      slideKey: "econ-math-l16-22",
      compositionId: "elasticity-profit-derivation",
      section: "弹性与利润",
      title: "利润还要扣除销量变化带来的成本",
      kicker: "单位成本c",
      kind: "derivation",
      visual: "formula-board",
      formula: String.raw`P(p)=(p-c)q(p)-F,\quad P'(p)=q(p)\left[1-E_d(p)\left(1-\frac{c}{p}\right)\right]`,
      body: ["固定成本F不影响导数位置。", "利润方向不仅由E与1比较，还由成本占价格的比例决定。"],
      sourceLabel: "教材框架",
      accent: "vermilion",
      teachingCue: "从P′=q+(p−c)q′代入弹性，逐步整理。",
      assistantCue: "要求p>0、q>0，且单位成本c为常数。"
    },
    {
      slideKey: "econ-math-l16-23",
      compositionId: "segment-a-profit-elasticity-condition",
      section: "弹性与利润",
      title: "A客群利润最大点的弹性为1.4",
      kicker: "p=70，c=20",
      kind: "worked-example",
      visual: "worked-grid",
      formula: String.raw`P'(p)=0\Rightarrow E_d=\frac{p}{p-c},\qquad\frac{70}{70-20}=1.4=E_A(70)`,
      body: ["利润最大点位于富有弹性的区间。", "这与收益最大点E=1并不矛盾。"],
      sourceLabel: "教学情境",
      accent: "cyan",
      teachingCue: "让学生解释单位成本为何使利润最优价格高于收益最优价格。",
      assistantCue: "A模型利润最大价70，收益最大价60。"
    },
    {
      slideKey: "econ-math-l16-24",
      compositionId: "revenue-profit-optima-comparison",
      section: "弹性与利润",
      title: "同一条需求曲线，两种“最优”",
      kicker: "目标函数决定答案",
      kind: "evidence",
      visual: "comparison-board",
      data: ["最大收益：p=60，E=1，R=36000", "最大利润：p=70，E=1.4，P=23000", "差异来源：利润扣除了单位成本与固定成本"],
      body: ["不能把“单位弹性”直接写成“利润最大”。"],
      sourceLabel: "教学情境",
      accent: "amber",
      teachingCue: "让学生圈出两个目标函数名称。",
      assistantCue: "固定成本不改最大利润位置，但改利润数值。"
    },
    {
      slideKey: "econ-math-l16-25",
      compositionId: "elasticity-profit-lab-entry",
      section: "动态实验：价格联动",
      title: "同一根价格滑杆，同时牵动四个量",
      kicker: "先预测再拖动",
      kind: "question",
      visual: "comparison-board",
      data: ["销量q(p)", "点弹性E(p)", "收益R(p)", "利润P(p)"],
      prompt: "A客群从60元拖到70元：销量、弹性、收益、利润分别向哪边变化？",
      sourceLabel: "自制图形",
      accent: "amber",
      teachingCue: "先让学生画四个方向箭头，再进入交互。",
      assistantCue: "60到70：销量降、弹性升、收益降、利润升。"
    },
    {
      slideKey: "econ-math-l16-26",
      compositionId: "elasticity-profit-interactive",
      section: "动态实验：价格联动",
      title: "拖动价格，寻找收益峰与利润峰",
      kicker: "A/B客群切换实验",
      kind: "interaction",
      visual: "coordinate-plot",
      body: ["价格滑杆：30至100元。", "客群开关：A或B。", "四个读数同步显示销量、弹性、收益与利润。", "竖线标出E=1和P′=0的位置。"],
      prompt: "分别记录A、B客群的收益峰价格与利润峰价格。",
      sourceLabel: "自制图形",
      sourceNote: "确定性需求与成本模型交互",
      accent: "cyan",
      interactionId: "elasticity-profit-lab",
      teachingCue: "先A后B；每次先预测峰值顺序，再用交互核验。",
      assistantCue: "A收益峰60、利润峰70；B收益峰75、利润峰85，固定成本2000、单位成本20。"
    },
    {
      slideKey: "econ-math-l16-27",
      compositionId: "lab-a-revenue-crossover",
      section: "动态实验：价格联动",
      title: "观察一：E=1处收益由升转降",
      kicker: "A客群p=60",
      kind: "evidence",
      visual: "coordinate-plot",
      body: ["60元左侧E<1，R′>0。", "60元右侧E>1，R′<0。", "收益曲线在60元处达到峰值。"],
      sourceLabel: "自制图形",
      accent: "green",
      teachingCue: "让学生用R′=q(1−E)逐段解释。",
      assistantCue: "限定A客群模型。"
    },
    {
      slideKey: "econ-math-l16-28",
      compositionId: "lab-a-profit-crossover",
      section: "动态实验：价格联动",
      title: "观察二：利润峰比收益峰更靠右",
      kicker: "A客群p=70",
      kind: "evidence",
      visual: "coordinate-plot",
      data: ["p=60：R最大，P仍在上升", "p=70：P最大，E=1.4", "单位成本20元使低价销量带来额外成本"],
      sourceLabel: "自制图形",
      accent: "amber",
      teachingCue: "让学生说明为什么“收益少了”仍可能“利润多了”。",
      assistantCue: "60到70收益从36000降至35000，利润从22000升至23000。"
    },
    {
      slideKey: "econ-math-l16-29",
      compositionId: "lab-segment-comparison",
      section: "动态实验：价格联动",
      title: "观察三：B客群的两个峰都更靠右",
      kicker: "需求截距不同",
      kind: "evidence",
      visual: "comparison-board",
      data: ["A：收益峰60，利润峰70", "B：收益峰75，利润峰85", "B在同价下弹性较低，单位弹性点更晚出现"],
      body: ["峰值位置来自各自模型，不能只凭客群标签判断。"],
      sourceLabel: "自制图形",
      accent: "cyan",
      teachingCue: "要求学生从E_B=p/(150−p)解E=1得到75。",
      assistantCue: "B利润函数驻点85。"
    },
    {
      slideKey: "econ-math-l16-30",
      compositionId: "lab-decision-memo",
      section: "动态实验：价格联动",
      title: "弹性支持分客群判断，不自动生成差别定价",
      kicker: "证据与决策之间",
      kind: "manager-brief",
      visual: "manager-memo",
      body: ["模型显示A在相同价格下通常更敏感。", "收益目标与利润目标给出不同候选价格。", "真实差别定价还需考虑可识别性、公平、合规与长期反应。"],
      sourceLabel: "概念模型",
      accent: "vermilion",
      teachingCue: "让学生将“可以差别定价”改写成“值得进一步评估”。",
      assistantCue: "不得提供现实中的歧视性定价建议。"
    },
    {
      slideKey: "econ-math-l16-31",
      compositionId: "paper-exercise-a-point-elasticity",
      section: "纸笔练习一",
      title: "A客群55元处的点弹性",
      kicker: "独立计算 · 4分钟",
      kind: "exercise",
      visual: "exercise-desk",
      formula: String.raw`q_A=1200-10p,\qquad p=55`,
      body: ["计算销量q。", "计算点弹性E。", "判断弹性区间。", "解释价格上涨1%的局部销量反应。"],
      sourceLabel: "教学情境",
      accent: "ink",
      teachingCue: "计时4分钟，要求保留分数。",
      assistantCue: "解答前不给数值；q=650，E=11/13≈0.846。"
    },
    {
      slideKey: "econ-math-l16-32",
      compositionId: "a-point-elasticity-solution",
      section: "纸笔练习一",
      title: "解答：E_A(55)≈0.846",
      kicker: "缺乏弹性",
      kind: "solution",
      visual: "worked-grid",
      formula: String.raw`q_A(55)=650,\qquad E_A(55)=\frac{55}{65}=\frac{11}{13}\approx0.846`,
      body: ["在55元附近，价格上涨1%，模型销量约下降0.846%。", "该点属于缺乏弹性区间。"],
      sourceLabel: "教学情境",
      accent: "green",
      teachingCue: "让学生核对解释中没有“杯”单位。",
      assistantCue: "弹性为无量纲百分比比值。"
    },
    {
      slideKey: "econ-math-l16-33",
      compositionId: "paper-exercise-b-unit-elasticity",
      section: "纸笔练习二",
      title: "B客群75元处发生什么？",
      kicker: "独立计算 · 4分钟",
      kind: "exercise",
      visual: "exercise-desk",
      formula: String.raw`q_B=900-6p,\qquad p=75`,
      body: ["计算q与E。", "判断小幅涨价对收益的一阶影响。", "说明能否据此判断利润最大。"],
      sourceLabel: "教学情境",
      accent: "vermilion",
      teachingCue: "要求学生分别回答收益与利润，不能合并。",
      assistantCue: "q=450，E=1，收益一阶不变；不能据此判利润最大。"
    },
    {
      slideKey: "econ-math-l16-34",
      compositionId: "b-unit-elasticity-solution",
      section: "纸笔练习二",
      title: "解答：75元是B客群收益峰，不是利润峰",
      kicker: "目标函数分开",
      kind: "solution",
      visual: "comparison-board",
      formula: String.raw`E_B(75)=\frac{75}{150-75}=1,\qquad R_B'(75)=q(1-E)=0`,
      body: ["单位弹性说明收益处于驻点。", "单位成本20元下，利润在75元处仍有上升空间；利润峰为85元。"],
      sourceLabel: "教学情境",
      accent: "green",
      teachingCue: "让学生用利润导数或交互读数复核。",
      assistantCue: "B利润P_B=-6p²+1020p−20000，驻点85。"
    },
    {
      slideKey: "econ-math-l16-35",
      compositionId: "paper-exercise-arc-elasticity",
      section: "纸笔练习三",
      title: "A客群从50元到70元的弧弹性",
      kicker: "独立计算 · 5分钟",
      kind: "exercise",
      visual: "exercise-desk",
      data: ["p₁=50，q₁=700", "p₂=70，q₂=500", "使用中点弧弹性公式"],
      body: ["计算价格与销量的中点基数。", "计算两个相对变化率。", "报告弧弹性并判断区间。"],
      sourceLabel: "教学情境",
      accent: "ink",
      teachingCue: "巡视分母是否分别使用600与60。",
      assistantCue: "答案弧弹性1。"
    },
    {
      slideKey: "econ-math-l16-36",
      compositionId: "arc-elasticity-solution",
      section: "纸笔练习三",
      title: "解答：整段弧弹性为1",
      kicker: "中点法",
      kind: "solution",
      visual: "formula-board",
      formula: String.raw`E_{arc}=\left|\frac{(-200)/600}{20/60}\right|=1`,
      body: ["销量中点为600杯，价格中点为60元。", "区间平均敏感性为单位弹性。", "这不表示区间内每一点弹性都等于1。"],
      sourceLabel: "概念模型",
      accent: "green",
      teachingCue: "与点弹性0.714、1、1.4对照，强化点与弧差别。",
      assistantCue: "弧弹性为1，点弹性随价格变化。"
    },
    {
      slideKey: "econ-math-l16-37",
      compositionId: "stage-check-mixed-question",
      section: "阶段考核准备",
      title: "一道题同时检查导数、弹性与收益判断",
      kicker: "限时5分钟",
      kind: "exercise",
      visual: "exercise-desk",
      formula: String.raw`q(p)=1000-5p,\qquad p=100`,
      body: ["① 求q′(p)与q(100)。", "② 求点弹性。", "③ 判断需求弹性类型。", "④ 判断小幅涨价对收益的一阶影响。"],
      prompt: "每一问都写单位或百分比解释。",
      sourceLabel: "概念模型",
      accent: "vermilion",
      teachingCue: "按阶段测试节奏计时5分钟，不提示公式。",
      assistantCue: "q=500，E=1，收益一阶不变。"
    },
    {
      slideKey: "econ-math-l16-38",
      compositionId: "stage-check-mixed-solution",
      section: "阶段考核准备",
      title: "解答：单位弹性点",
      kicker: "逐问自检",
      kind: "solution",
      visual: "worked-grid",
      formula: String.raw`q'(p)=-5,\quad q(100)=500,\quad E=-\frac{100}{500}(-5)=1`,
      body: ["需求在该点为单位弹性。", "R′=q(1−E)=0，因此小幅涨价对收益的一阶影响为0。", "这不是利润结论。"],
      sourceLabel: "概念模型",
      accent: "green",
      teachingCue: "让学生按四问各得一分自评，并标记丢分环节。",
      assistantCue: "强调收益一阶不变，不是有限涨价后收益精确不变。"
    },
    {
      slideKey: "econ-math-l16-39",
      compositionId: "error-audit-slope-equals-elasticity",
      section: "错因诊断",
      title: "错解一：需求斜率就是弹性",
      kicker: "有单位与无单位",
      kind: "error-audit",
      visual: "error-lens",
      formula: String.raw`q'(p)=-10\quad\not=\quad E_d(p)`,
      body: ["斜率单位为杯/元。", "弹性还需乘p/q并按约定处理负号。", "同一条线性需求曲线上，斜率固定而弹性变化。"],
      sourceLabel: "概念模型",
      accent: "vermilion",
      teachingCue: "让学生用A客群50与70元反证。",
      assistantCue: "A两点斜率均−10，弹性分别约0.714与1.4。"
    },
    {
      slideKey: "econ-math-l16-40",
      compositionId: "slope-elasticity-repair",
      section: "错因诊断",
      title: "修正：弹性把斜率标准化",
      kicker: "乘上输入/输出基数",
      kind: "solution",
      visual: "formula-board",
      formula: String.raw`E_d=-\frac{p}{q}\,q'(p)`,
      body: ["先算斜率，再乘当前价格与销量基数之比。", "不同客群只有在同一点口径下才能公平比较。"],
      sourceLabel: "教材框架",
      accent: "cyan",
      teachingCue: "让学生圈出公式中的“当前”p与q。",
      assistantCue: "弹性仍然是点依赖的，不是客群永久标签。"
    },
    {
      slideKey: "econ-math-l16-41",
      compositionId: "error-audit-negative-insensitive",
      section: "错因诊断",
      title: "错解二：弹性为负，所以不敏感",
      kicker: "符号约定混乱",
      kind: "error-audit",
      visual: "error-lens",
      body: ["带符号需求弹性常为负，负号表示价格与销量反向。", "敏感程度看绝对值大小。", "本课程用正值E_d报告敏感程度。"],
      prompt: "带符号弹性−1.4应归为哪一类？",
      sourceLabel: "概念模型",
      accent: "amber",
      teachingCue: "期待绝对值1.4>1，富有弹性。",
      assistantCue: "不要用正负号判断强弱。"
    },
    {
      slideKey: "econ-math-l16-42",
      compositionId: "sign-convention-repair",
      section: "错因诊断",
      title: "修正：先写约定，再比较大小",
      kicker: "报告口径",
      kind: "solution",
      visual: "data-ledger",
      data: ["若报告正值：E=1.4，称富有弹性", "若报告带符号：E=−1.4，同时说明|E|>1", "同一份报告中不得混用两套阈值表述"],
      sourceLabel: "概念模型",
      accent: "green",
      teachingCue: "让学生检查自己练习中的符号是否前后一致。",
      assistantCue: "本课统一正值口径。"
    },
    {
      slideKey: "econ-math-l16-43",
      compositionId: "error-audit-elastic-profit",
      section: "错因诊断",
      title: "错解三：E>1，涨价一定让利润下降",
      kicker: "把收益规律误套到利润",
      kind: "error-audit",
      visual: "error-lens",
      body: ["E>1可推出小幅涨价使收益下降。", "利润还要考虑少卖产品节省的单位成本。", "A客群60到70元之间，收益下降但利润上升。"],
      sourceLabel: "教学情境",
      accent: "vermilion",
      teachingCue: "让学生用R与P的数值变化举证。",
      assistantCue: "R从36000降35000；P从22000升23000。"
    },
    {
      slideKey: "econ-math-l16-44",
      compositionId: "revenue-profit-repair",
      section: "错因诊断",
      title: "修正：先问目标是收益还是利润",
      kicker: "两条判断式",
      kind: "solution",
      visual: "comparison-board",
      formula: String.raw`R'=q(1-E_d),\qquad P'=q\left[1-E_d\left(1-\frac cp\right)\right]`,
      body: ["收益方向看E与1。", "利润方向还要带入单位成本c。"],
      sourceLabel: "教材框架",
      accent: "cyan",
      teachingCue: "让学生在两式上分别标出“收入目标”“利润目标”。",
      assistantCue: "固定成本不在一阶式中，但报告利润值时仍需带回。"
    },
    {
      slideKey: "econ-math-l16-45",
      compositionId: "stage-assessment-checklist",
      section: "阶段考核准备",
      title: "阶段题的五个得分点",
      kicker: "概念—计算—判别—解释—边界",
      kind: "evidence",
      visual: "data-ledger",
      data: ["写对导数与弹性公式", "代入当前p、q并保留符号约定", "按E<1、=1、>1分类", "区分收益与利润方向", "用百分比、单位与局部条件解释"],
      body: ["工具可以核验数值，推导和判断必须独立完成。"],
      sourceLabel: "概念模型",
      accent: "green",
      teachingCue: "让学生对第37题逐项打勾，记录一个最需复习的点。",
      assistantCue: "不提供考试原题预测；只围绕大纲能力。"
    },
    {
      slideKey: "econ-math-l16-46",
      compositionId: "elasticity-exit-ticket",
      section: "课堂收束",
      title: "离场题：80元时谁更敏感？",
      kicker: "2分钟独立作答",
      kind: "exercise",
      visual: "exercise-desk",
      formula: String.raw`E_A(p)=\frac{p}{120-p},\qquad E_B(p)=\frac{p}{150-p}`,
      body: ["计算E_A(80)与E_B(80)。", "判断各自弹性区间。", "用一句话比较敏感性。"],
      sourceLabel: "教学情境",
      accent: "ink",
      teachingCue: "计时2分钟，要求分数形式。",
      assistantCue: "E_A=2，E_B=8/7≈1.143；均富有弹性，A更敏感。"
    },
    {
      slideKey: "econ-math-l16-47",
      compositionId: "antiderivative-bridge",
      section: "课堂收束",
      title: "知道每一刻的边际变化，能找回总量吗？",
      kicker: "下一单元：不定积分",
      kind: "transition",
      visual: "chapter-bridge",
      formula: String.raw`F'(x)=f(x)\quad\Longrightarrow\quad F(x)=?`,
      lead: "本单元一直从总量求导得到边际量；下一单元反向追问，已知变化率时如何恢复原函数。",
      prompt: "两个函数导数完全相同，它们一定是同一个函数吗？",
      sourceLabel: "概念模型",
      accent: "vermilion",
      teachingCue: "期待“可能相差常数”，连接第12讲推论。",
      assistantCue: "答案是不一定，可相差常数C。"
    }
  ]
});
