import {
  defineEconomicMathematicsLesson,
  type EconomicMathematicsAuthoredSlide
} from "../types.js";

const slides: readonly EconomicMathematicsAuthoredSlide[] = [
  {
    slideKey: "em-l22-01-campaign-clock",
    compositionId: "l22-campaign-clock-opening",
    section: "从速率到累计",
    title: "活动进行到现在，一共卖了多少？",
    kicker: "VARIABLE-UPPER-LIMIT INTEGRAL",
    kind: "scene",
    visual: "editorial-scene",
    lead: "运营屏每分钟刷新销量率，但经理要的是从开场到此刻的累计销量。",
    body: ["销量率回答“此刻有多快”", "累计销量回答“到现在有多少”", "本讲改用八日会员情境：函数形式与第21讲相同，时间与销量单位不同"],
    sourceLabel: "教学情境",
    sourceNote: "独立八日会员情境 · 与第21讲只共享函数形式，不混用单位",
    accent: "cyan",
    teachingCue: "先让学生区分屏幕上的速率读数与累计读数，再提出积分上限会移动的问题。",
    assistantCue: "说明这是独立八日连续化教学模型；不要把第21讲的小时/杯口径带入，也不要把瞬时销量率直接称为销量。"
  },
  {
    slideKey: "em-l22-02-two-dashboard-numbers",
    compositionId: "l22-rate-total-dashboard",
    section: "从速率到累计",
    title: "同一块看板上的两个数，单位不同",
    kicker: "READ THE UNIT FIRST",
    kind: "evidence",
    visual: "data-ledger",
    data: ["当前销量率：165 件/日", "累计销量：441 件", "当前时刻：第 3 日"],
    prompt: "哪一个数能够直接与库存件数相减？",
    sourceLabel: "教学情境",
    sourceNote: "数值来自 v(t)=120+24t-3t²",
    accent: "cyan",
    teachingCue: "要求学生先圈出单位，再回答库存核算只能使用累计量。",
    assistantCue: "强调件/日与件不能直接相加减。"
  },
  {
    slideKey: "em-l22-03-rate-strip",
    compositionId: "l22-rate-strip-observation",
    section: "从速率到累计",
    title: "每一小段时间都贡献一小块销量",
    kicker: "RATE × TIME",
    kind: "evidence",
    visual: "area-studio",
    formula: "小段销量 ≈ v(t)·Δt",
    formulaLabel: "局部矩形",
    body: ["高度是销量率", "宽度是时间", "面积单位是件"],
    sourceLabel: "概念模型",
    accent: "green",
    teachingCue: "把上一讲的黎曼矩形收束为“局部贡献”，为变上限积分铺垫。",
    assistantCue: "只解释面积的量纲，不提前给出基本定理。"
  },
  {
    slideKey: "em-l22-04-moving-finish-line",
    compositionId: "l22-moving-finish-question",
    section: "从速率到累计",
    title: "终点从 1 日移到 2 日，累计量怎样变化？",
    kicker: "THE UPPER LIMIT MOVES",
    kind: "question",
    visual: "decision-split",
    prompt: "新增的累计量来自整段重算，还是只来自新增加的窄条？",
    sourceLabel: "自制图形",
    accent: "vermilion",
    teachingCue: "让学生先指认新增区域，不急于写导数。",
    assistantCue: "引导观察区间 [b,b+Δb]，不要直接报公式。"
  },
  {
    slideKey: "em-l22-05-accumulation-function",
    compositionId: "l22-accumulation-definition",
    section: "累计函数",
    title: "把“到此刻为止”写成一个函数",
    kicker: "ACCUMULATION FUNCTION",
    kind: "definition",
    visual: "formula-board",
    formula: "A(b)=∫₀ᵇ v(t)dt",
    formulaLabel: "从活动开始到第 b 日的累计销量",
    body: ["t 是积分变量", "b 是可以变化的输入", "A(b) 的单位是件"],
    sourceLabel: "教材框架",
    accent: "ink",
    teachingCue: "逐一指出 t 与 b 的角色，防止学生把积分变量和上限混为一谈。",
    assistantCue: "保持符号角色清楚：t 在积分后消失，b 留在结果中。"
  },
  {
    slideKey: "em-l22-06-add-one-strip",
    compositionId: "l22-increment-strip",
    section: "累计函数",
    title: "A(b+Δb) 比 A(b) 多出哪一块？",
    kicker: "INCREMENT",
    kind: "derivation",
    visual: "area-studio",
    formula: "A(b+Δb)-A(b)=∫ᵦᵇ⁺Δᵇ v(t)dt",
    formulaLabel: "累计量的增量",
    sourceLabel: "概念模型",
    accent: "green",
    teachingCue: "只完成区间相减这一步，让学生在图上标出被保留的窄条。",
    assistantCue: "可使用定积分区间可加性解释，不跳到极限。"
  },
  {
    slideKey: "em-l22-07-average-strip-height",
    compositionId: "l22-average-strip-height",
    section: "累计函数",
    title: "窄条面积除以宽度，得到平均高度",
    kicker: "DIFFERENCE QUOTIENT",
    kind: "derivation",
    visual: "formula-board",
    formula: "[A(b+Δb)-A(b)]/Δb = (1/Δb)∫ᵦᵇ⁺Δᵇv(t)dt",
    formulaLabel: "累计函数的差商",
    body: ["左边是累计量的平均变化率", "右边是窄区间上的平均销量率"],
    sourceLabel: "教材框架",
    accent: "ink",
    teachingCue: "要求学生口头说出等式两侧的单位均为件/日。",
    assistantCue: "突出平均值联系，不把等式称为近似。"
  },
  {
    slideKey: "em-l22-08-strip-shrinks",
    compositionId: "l22-strip-shrinks-limit",
    section: "累计函数",
    title: "当窄条收缩，平均高度靠近当前高度",
    kicker: "LET Δb → 0",
    kind: "derivation",
    visual: "coordinate-plot",
    formula: "lim(Δb→0) (1/Δb)∫ᵦᵇ⁺Δᵇv(t)dt = v(b)",
    formulaLabel: "连续条件下的局部极限",
    sourceLabel: "概念模型",
    accent: "cyan",
    teachingCue: "把连续性作为平均高度收敛到点高的条件明确写出。",
    assistantCue: "说明若 v 在 b 附近不连续，需要重新检查结论条件。"
  },
  {
    slideKey: "em-l22-09-ftc-part-one",
    compositionId: "l22-ftc-part-one",
    section: "微积分基本定理",
    title: "累计函数的导数，就是当前速率",
    kicker: "FUNDAMENTAL THEOREM I",
    kind: "definition",
    visual: "formula-board",
    formula: "A'(b)=d/db ∫₀ᵇv(t)dt=v(b)",
    formulaLabel: "微积分基本定理的累计形式",
    sourceLabel: "教材框架",
    accent: "vermilion",
    teachingCue: "用一句话收束推导：新增累计量只由终点附近的速率决定。",
    assistantCue: "允许解释定理，不扩展到未讲的测度或严格证明。"
  },
  {
    slideKey: "em-l22-10-business-reading",
    compositionId: "l22-ftc-business-reading",
    section: "微积分基本定理",
    title: "A′(3)=165 的管理含义是什么？",
    kicker: "READ THE NUMBER",
    kind: "question",
    visual: "manager-memo",
    prompt: "第3日这一刻，累计销量正以什么单位增加？",
    data: ["A′(3)=165", "不是累计销量 165", "而是累计曲线此刻的斜率 165 件/日"],
    sourceLabel: "教学情境",
    accent: "amber",
    teachingCue: "要求学生用完整句子解释数值、对象、时刻和单位。",
    assistantCue: "拒绝把导数值解释成截至第3日的销量。"
  },
  {
    slideKey: "em-l22-11-two-graphs-one-event",
    compositionId: "l22-rate-accumulation-pair",
    section: "微积分基本定理",
    title: "上图看速率，下图看累计",
    kicker: "PAIR THE GRAPHS",
    kind: "evidence",
    visual: "comparison-board",
    body: ["v(t)>0 时 A(t) 持续上升", "v(t) 变大时 A(t) 越来越陡", "v(t) 变小时 A(t) 仍可上升但逐渐变平"],
    sourceLabel: "自制图形",
    accent: "cyan",
    teachingCue: "让学生逐句用两张图互相核验。",
    assistantCue: "强调速率下降不等于累计量下降。"
  },
  {
    slideKey: "em-l22-12-rate-model",
    compositionId: "l22-sales-rate-model",
    section: "完整例题",
    title: "八日活动的销量率模型",
    kicker: "WORKED EXAMPLE",
    kind: "worked-example",
    visual: "data-ledger",
    formula: "v(t)=120+24t-3t², 0≤t≤8",
    formulaLabel: "件/日",
    body: ["t=0 对应活动开始", "模型把日内波动连续化", "只在八日窗口内使用"],
    sourceLabel: "教学情境",
    sourceNote: "课程累计销量主线模型",
    accent: "green",
    teachingCue: "先检查定义域和单位，再开始积分。",
    assistantCue: "不得把模型称为某企业真实销售数据。"
  },
  {
    slideKey: "em-l22-13-find-antiderivative",
    compositionId: "l22-antiderivative-step",
    section: "完整例题",
    title: "第一步：求销量率的原函数",
    kicker: "INTEGRATE TERM BY TERM",
    kind: "derivation",
    visual: "formula-board",
    formula: "∫(120+24t-3t²)dt=120t+12t²-t³+C",
    formulaLabel: "原函数",
    sourceLabel: "教材框架",
    accent: "ink",
    teachingCue: "逐项核对指数和系数，随后用求导回查。",
    assistantCue: "若学生问常数 C，说明定积分端点相减时会抵消。"
  },
  {
    slideKey: "em-l22-14-form-accumulation",
    compositionId: "l22-form-accumulation",
    section: "完整例题",
    title: "第二步：把上限 b 留在结果里",
    kicker: "APPLY THE ENDPOINTS",
    kind: "derivation",
    visual: "formula-board",
    formula: "A(b)=[120t+12t²-t³]₀ᵇ=120b+12b²-b³",
    formulaLabel: "累计销量函数",
    sourceLabel: "概念模型",
    accent: "cyan",
    teachingCue: "强调下限0也必须代入，虽本题其贡献为0。",
    assistantCue: "保持 b 的范围 0≤b≤8。"
  },
  {
    slideKey: "em-l22-15-derivative-check",
    compositionId: "l22-derivative-check",
    section: "完整例题",
    title: "第三步：用导数把累计函数核回来",
    kicker: "VERIFY",
    kind: "worked-example",
    visual: "comparison-board",
    formula: "A'(b)=120+24b-3b²=v(b)",
    formulaLabel: "基本定理核验",
    body: ["符号一致", "单位回到件/日", "有效区间保持不变"],
    sourceLabel: "概念模型",
    accent: "green",
    teachingCue: "让学生把“求导核验”写进规范解题过程。",
    assistantCue: "若结果不一致，应回到积分系数检查。"
  },
  {
    slideKey: "em-l22-16-day-two-total",
    compositionId: "l22-day-two-total",
    section: "完整例题",
    title: "到第2日：累计 280 件",
    kicker: "READ A(2)",
    kind: "worked-example",
    visual: "worked-grid",
    formula: "A(2)=120×2+12×2²-2³=280",
    formulaLabel: "件",
    prompt: "为什么这里的答案不再带“/日”？",
    sourceLabel: "教学情境",
    accent: "amber",
    teachingCue: "停顿，让学生用面积量纲回答。",
    assistantCue: "用速率乘时间得到累计量解释。"
  },
  {
    slideKey: "em-l22-17-day-four-total",
    compositionId: "l22-day-four-total",
    section: "完整例题",
    title: "到第4日：累计 608 件",
    kicker: "READ A(4)",
    kind: "worked-example",
    visual: "worked-grid",
    formula: "A(4)=480+192-64=608",
    formulaLabel: "件",
    body: ["前两日累计 280", "后两日新增 328", "新增量可由 A(4)-A(2) 得到"],
    sourceLabel: "教学情境",
    accent: "amber",
    teachingCue: "连接区间积分与累计函数差值。",
    assistantCue: "不要把 A(4)-A(2) 说成第4日单日销量。"
  },
  {
    slideKey: "em-l22-18-day-eight-total",
    compositionId: "l22-day-eight-total",
    section: "完整例题",
    title: "活动结束：模型累计 1216 件",
    kicker: "READ A(8)",
    kind: "worked-example",
    visual: "manager-memo",
    formula: "A(8)=960+768-512=1216",
    formulaLabel: "八日累计销量",
    sourceLabel: "教学情境",
    accent: "vermilion",
    teachingCue: "要求学生同时报告模型窗口和单位。",
    assistantCue: "表述为连续模型估计，不宣称精确订单台账。"
  },
  {
    slideKey: "em-l22-19-current-rate-day-four",
    compositionId: "l22-current-rate-day-four",
    section: "完整例题",
    title: "第4日累计很多，不等于第4日速率最大",
    kicker: "TOTAL ≠ RATE",
    kind: "error-audit",
    visual: "error-lens",
    formula: "v(4)=120+96-48=168 件/日",
    body: ["A(4)=608 件", "v(4)=168 件/日", "两个数字回答不同问题"],
    sourceLabel: "概念模型",
    accent: "vermilion",
    teachingCue: "并排写出 A(4) 与 v(4)，让学生指出误读。",
    assistantCue: "持续守住量纲边界。"
  },
  {
    slideKey: "em-l22-20-interaction-brief",
    compositionId: "l22-accumulation-lab-brief",
    section: "同步实验",
    title: "移动上限前，先预测累计曲线的形状",
    kicker: "ACCUMULATION LAB",
    kind: "interaction",
    visual: "area-studio",
    prompt: "从 b=0 移到 b=8，A(b) 会一直变陡吗？",
    interactionId: "accumulation-limit-lab",
    sourceLabel: "概念模型",
    accent: "cyan",
    teachingCue: "先收集口头预测，再操作上限；不展示自动答案。",
    assistantCue: "只追问预测依据，不替学生判断。"
  },
  {
    slideKey: "em-l22-21-interaction-early",
    compositionId: "l22-accumulation-lab-early",
    section: "同步实验",
    title: "b=2：新增面积仍在扩大",
    kicker: "PRESET 01",
    kind: "interaction",
    visual: "area-studio",
    data: ["A(2)=280 件", "v(2)=156 件/日", "累计曲线斜率为正"],
    interactionId: "accumulation-limit-lab",
    sourceLabel: "概念模型",
    accent: "green",
    teachingCue: "停在预设2日，让学生把曲线斜率与速率读数配对。",
    assistantCue: "解释同步读数，不额外外推。"
  },
  {
    slideKey: "em-l22-22-interaction-peak-rate",
    compositionId: "l22-accumulation-lab-rate-peak",
    section: "同步实验",
    title: "b=4：销量率到峰值，累计曲线最陡",
    kicker: "PRESET 02",
    kind: "interaction",
    visual: "area-studio",
    data: ["v′(t)=24-6t", "v′(4)=0", "A′(4)=v(4)=168"],
    interactionId: "accumulation-limit-lab",
    sourceLabel: "概念模型",
    accent: "amber",
    teachingCue: "让学生观察速率峰值对应累计曲线最大斜率。",
    assistantCue: "区分 v 的峰值与 A 的峰值；A 此时仍在增长。"
  },
  {
    slideKey: "em-l22-23-interaction-late",
    compositionId: "l22-accumulation-lab-late",
    section: "同步实验",
    title: "b=8：速率回落，累计仍继续增加",
    kicker: "PRESET 03",
    kind: "interaction",
    visual: "area-studio",
    data: ["v(8)=120 件/日", "A(8)=1216 件", "A′(8)>0"],
    interactionId: "accumulation-limit-lab",
    sourceLabel: "概念模型",
    accent: "cyan",
    teachingCue: "用该帧纠正“速率下降所以累计下降”的直觉。",
    assistantCue: "强调只有 v<0 才会令 A 下降。"
  },
  {
    slideKey: "em-l22-24-slope-identity",
    compositionId: "l22-slope-identity",
    section: "同步实验",
    title: "每一个上限位置都满足同一条关系",
    kicker: "LIVE IDENTITY",
    kind: "interaction",
    visual: "comparison-board",
    formula: "累计曲线斜率 = 当前销量率",
    formulaLabel: "A′(b)=v(b)",
    interactionId: "accumulation-limit-lab",
    sourceLabel: "概念模型",
    accent: "vermilion",
    teachingCue: "自由拖动上限，随机停三次，请学生口头核对两侧读数。",
    assistantCue: "只在模型区间内核对。"
  },
  {
    slideKey: "em-l22-25-when-total-falls",
    compositionId: "l22-negative-rate-boundary",
    section: "符号与边界",
    title: "累计量什么时候才会下降？",
    kicker: "SIGN MATTERS",
    kind: "question",
    visual: "decision-split",
    formula: "A′(b)=v(b)",
    prompt: "若 v(b)<0，这在库存、净现金流或净新增会员中可能表示什么？",
    sourceLabel: "概念模型",
    accent: "vermilion",
    teachingCue: "把“销量率”扩展到可为负的净变化率，但说明实际销量本身不能为负。",
    assistantCue: "允许用净库存变化或净会员变化举例，不称负数为负销量。"
  },
  {
    slideKey: "em-l22-26-monotonicity-reading",
    compositionId: "l22-accumulation-monotonicity",
    section: "符号与边界",
    title: "由速率符号直接判断累计函数单调性",
    kicker: "RATE SIGN → TOTAL TREND",
    kind: "derivation",
    visual: "formula-board",
    body: ["v(b)>0 ⇒ A 递增", "v(b)=0 ⇒ A 出现水平切线", "v(b)<0 ⇒ A 递减"],
    sourceLabel: "教材框架",
    accent: "ink",
    teachingCue: "把第14讲单调性知识与基本定理连接起来。",
    assistantCue: "提醒水平切线不必然是极值，仍需看两侧符号。"
  },
  {
    slideKey: "em-l22-27-general-basepoint",
    compositionId: "l22-general-basepoint",
    section: "推广",
    title: "累计不一定从0开始",
    kicker: "CHANGE THE BASEPOINT",
    kind: "definition",
    visual: "formula-board",
    formula: "F(x)=∫ₐˣ f(t)dt ⇒ F′(x)=f(x)",
    formulaLabel: "任意固定下限",
    body: ["a 固定", "x 变化", "导数与固定下限取值无关"],
    sourceLabel: "教材框架",
    accent: "ink",
    teachingCue: "用两个不同起算日说明累计水平不同、当前斜率相同。",
    assistantCue: "不把固定下限误说成无关；它影响 F 的水平但不影响 F′。"
  },
  {
    slideKey: "em-l22-28-upper-limit-function",
    compositionId: "l22-composite-upper-limit",
    section: "推广",
    title: "若上限本身也是函数，还要乘一层变化率",
    kicker: "CHAIN RULE RETURNS",
    kind: "derivation",
    visual: "variable-map",
    formula: "H(x)=∫ₐᵍ⁽ˣ⁾f(t)dt ⇒ H′(x)=f(g(x))g′(x)",
    formulaLabel: "变上限积分的链式法则",
    sourceLabel: "教材框架",
    accent: "cyan",
    teachingCue: "画出 x→g(x)→累计量的依赖链，再写公式。",
    assistantCue: "强调 g′(x) 不能遗漏。"
  },
  {
    slideKey: "em-l22-29-composite-example",
    compositionId: "l22-composite-upper-worked",
    section: "推广",
    title: "例：促销时钟按 x² 加速",
    kicker: "WORKED EXAMPLE",
    kind: "worked-example",
    visual: "worked-grid",
    formula: "H(x)=∫₀ˣ²(1+t)dt ⇒ H′(x)=(1+x²)·2x",
    formulaLabel: "先代上限，再乘上限导数",
    sourceLabel: "概念模型",
    accent: "green",
    teachingCue: "分两页口算：先得到被积函数在x²的值，再乘2x。",
    assistantCue: "不需要先把定积分完整算出；可在之后用显式结果复核。"
  },
  {
    slideKey: "em-l22-30-composite-check",
    compositionId: "l22-composite-upper-check",
    section: "推广",
    title: "把积分算完，结果仍应一致",
    kicker: "SECOND ROUTE",
    kind: "worked-example",
    visual: "comparison-board",
    formula: "H(x)=x²+x⁴/2 ⇒ H′(x)=2x+2x³=2x(1+x²)",
    formulaLabel: "显式求导核验",
    sourceLabel: "概念模型",
    accent: "green",
    teachingCue: "比较两条路线，明确基本定理路线更直接。",
    assistantCue: "允许两种方法，要求最终形式等价。"
  },
  {
    slideKey: "em-l22-31-exercise-one",
    compositionId: "l22-independent-exercise-one",
    section: "独立练习",
    title: "独立完成：累计访问量的当前增速",
    kicker: "TRY BEFORE REVEAL",
    kind: "exercise",
    visual: "exercise-desk",
    formula: "V(x)=∫₁ˣ(3t²-2t+4)dt",
    prompt: "求 V′(x)，并解释 V′(2) 的单位和业务含义。",
    sourceLabel: "教学情境",
    accent: "amber",
    teachingCue: "给4分钟独立作答，只提醒先看上限是否就是x。",
    assistantCue: "本页不得显示答案；只可追问单位。"
  },
  {
    slideKey: "em-l22-32-exercise-one-solution",
    compositionId: "l22-independent-solution-one",
    section: "独立练习",
    title: "解答：直接读取终点处的访问率",
    kicker: "SOLUTION 01",
    kind: "solution",
    visual: "worked-grid",
    formula: "V′(x)=3x²-2x+4；V′(2)=12",
    formulaLabel: "千次访问/日",
    body: ["无需先求原函数", "x=2 表示第2日", "12 是累计访问曲线的当日斜率"],
    sourceLabel: "教学情境",
    accent: "green",
    teachingCue: "让学生对照是否多做了无必要积分。",
    assistantCue: "解释直接使用基本定理的效率。"
  },
  {
    slideKey: "em-l22-33-exercise-two",
    compositionId: "l22-independent-exercise-two",
    section: "独立练习",
    title: "独立完成：上限是 2x+1",
    kicker: "CHAIN RULE CHECK",
    kind: "exercise",
    visual: "exercise-desk",
    formula: "W(x)=∫₀²ˣ⁺¹ √(1+t²)dt",
    prompt: "求 W′(x)，明确哪一步来自基本定理、哪一步来自链式法则。",
    sourceLabel: "教材框架",
    accent: "amber",
    teachingCue: "给5分钟，要求用颜色标出两层变化。",
    assistantCue: "本页不提供结果。"
  },
  {
    slideKey: "em-l22-34-exercise-two-solution",
    compositionId: "l22-independent-solution-two",
    section: "独立练习",
    title: "解答：终点函数值还要乘 2",
    kicker: "SOLUTION 02",
    kind: "solution",
    visual: "formula-board",
    formula: "W′(x)=√(1+(2x+1)²)·2",
    formulaLabel: "f(g(x))g′(x)",
    body: ["终点：g(x)=2x+1", "终点移动速度：g′(x)=2"],
    sourceLabel: "教材框架",
    accent: "green",
    teachingCue: "逐项对应学生标色，检查是否漏乘2。",
    assistantCue: "保持根号内括号完整。"
  },
  {
    slideKey: "em-l22-35-exercise-three",
    compositionId: "l22-independent-exercise-three",
    section: "独立练习",
    title: "判断题：速率下降，累计量一定下降",
    kicker: "CONCEPT CHECK",
    kind: "exercise",
    visual: "decision-split",
    prompt: "写“对”或“错”，再用 A′(t)=v(t) 给出一行理由。",
    sourceLabel: "概念模型",
    accent: "vermilion",
    teachingCue: "先让全班独立写理由，不进行电子投票。",
    assistantCue: "答案是错；只有速率为负才令累计量下降，但本页先不揭示。"
  },
  {
    slideKey: "em-l22-36-exercise-three-solution",
    compositionId: "l22-independent-solution-three",
    section: "独立练习",
    title: "解答：下降的是斜率，不一定是累计量",
    kicker: "SOLUTION 03",
    kind: "solution",
    visual: "comparison-board",
    formula: "v′(t)<0 与 v(t)<0 是两件事",
    body: ["v′<0：速率在下降", "v>0：累计量仍上升", "必须看 v 的符号判断 A 的方向"],
    sourceLabel: "概念模型",
    accent: "green",
    teachingCue: "用第4日至第8日区间作为反例。",
    assistantCue: "不要混淆一阶与二阶关系。"
  },
  {
    slideKey: "em-l22-37-error-missing-chain",
    compositionId: "l22-error-missing-chain",
    section: "错误审计",
    title: "错误一：只代上限，漏掉上限的导数",
    kicker: "ERROR AUDIT",
    kind: "error-audit",
    visual: "error-lens",
    formula: "错误：d/dx ∫₀ˣ²f(t)dt=f(x²)",
    formulaLabel: "缺少 2x",
    prompt: "依赖链中的哪一条箭头没有被计入？",
    sourceLabel: "教材框架",
    accent: "vermilion",
    teachingCue: "要求学生在错误式旁补画 x→x²。",
    assistantCue: "指出链式法则缺项即可。"
  },
  {
    slideKey: "em-l22-38-error-variable-confusion",
    compositionId: "l22-error-variable-confusion",
    section: "错误审计",
    title: "错误二：积分变量 t 被错误保留",
    kicker: "BOUND VARIABLE",
    kind: "error-audit",
    visual: "error-lens",
    formula: "错误：A(b)=120t+12t²-t³",
    body: ["t 是积分内部的哑变量", "端点代入后结果只能依赖 b", "改名为 u 不应改变 A(b)"],
    sourceLabel: "教材框架",
    accent: "vermilion",
    teachingCue: "让学生把 t 全部改名为 u，检验结果为何不应变化。",
    assistantCue: "解释绑定变量概念，避免使用过深逻辑术语。"
  },
  {
    slideKey: "em-l22-39-error-unit-collapse",
    compositionId: "l22-error-unit-collapse",
    section: "错误审计",
    title: "错误三：把件与件/日写成同一个指标",
    kicker: "UNIT AUDIT",
    kind: "error-audit",
    visual: "data-ledger",
    data: ["A(4)=608 件", "A′(4)=168 件/日", "v′(4)=0 件/日²"],
    prompt: "三者分别描述水平、速度还是速度变化？",
    sourceLabel: "教学情境",
    accent: "amber",
    teachingCue: "要求学生按量纲给三个数贴标签。",
    assistantCue: "对应为累计水平、累计速度、销量率变化。"
  },
  {
    slideKey: "em-l22-40-manager-question",
    compositionId: "l22-manager-question",
    section: "管理解释",
    title: "经理问“活动还在增长吗”，先问他指什么",
    kicker: "CLARIFY THE METRIC",
    kind: "manager-brief",
    visual: "manager-memo",
    body: ["累计销量是否还在增加？看 v(t) 的符号", "当前销量率是否还在增加？看 v′(t) 的符号", "累计曲线是否越来越陡？同样看 v′(t)"],
    sourceLabel: "概念模型",
    accent: "cyan",
    teachingCue: "训练学生先澄清“增长”的层级，再回答。",
    assistantCue: "不要将增长一词自动解释为任一特定导数。"
  },
  {
    slideKey: "em-l22-41-manager-brief",
    compositionId: "l22-manager-brief",
    section: "管理解释",
    title: "八日活动的三句可复核结论",
    kicker: "BRIEF WITH UNITS",
    kind: "manager-brief",
    visual: "manager-memo",
    body: ["模型累计销量为1216件", "第4日销量率达到模型峰值168件/日", "第4日后销量率回落，但因仍为正，累计销量继续增加"],
    sourceLabel: "教学情境",
    sourceNote: "仅适用于0至8日连续模型",
    accent: "green",
    teachingCue: "要求每句都能回指公式或图形证据。",
    assistantCue: "保持“模型”限定词，不生成现实营销建议。"
  },
  {
    slideKey: "em-l22-42-model-boundary",
    compositionId: "l22-continuous-model-boundary",
    section: "管理解释",
    title: "连续积分不会替代真实订单台账",
    kicker: "MODEL BOUNDARY",
    kind: "manager-brief",
    visual: "model-boundary",
    body: ["实际订单按件离散发生", "连续曲线用于解释趋势和近似累计", "退货、取消和缺货需在净变化模型中单独定义"],
    sourceLabel: "概念模型",
    accent: "vermilion",
    teachingCue: "明确连续化的用途与禁止外推。",
    assistantCue: "不得声称积分模型自动包含退款或缺货。"
  },
  {
    slideKey: "em-l22-43-tool-check",
    compositionId: "l22-tool-verification",
    section: "复核",
    title: "电子表格只做数值核验，不替代推导",
    kicker: "VERIFY, DO NOT OUTSOURCE",
    kind: "evidence",
    visual: "data-ledger",
    body: ["手算得到 A(8)=1216", "表格用细分时间步近似面积", "两者接近后记录步长与误差"],
    sourceLabel: "教学情境",
    accent: "amber",
    teachingCue: "演示一次数值和，但保留学生手写基本定理过程。",
    assistantCue: "工具结果只能用于核验；不得替学生生成完整解答。"
  },
  {
    slideKey: "em-l22-44-exit-ticket",
    compositionId: "l22-exit-ticket",
    section: "收束",
    title: "离开本讲前，写清三个对象",
    kicker: "EXIT TICKET",
    kind: "exercise",
    visual: "exercise-desk",
    prompt: "分别写出 v(3)、A(3)、A′(3) 的含义和单位，并说明其中哪两个数值相等。",
    sourceLabel: "概念模型",
    accent: "amber",
    teachingCue: "收取一行答案，用于下一讲开场诊断。",
    assistantCue: "正确关系是 A′(3)=v(3)，但不要在学生提交前显示。"
  },
  {
    slideKey: "em-l22-45-one-line-theorem",
    compositionId: "l22-one-line-theorem",
    section: "收束",
    title: "今天建立的桥：速率 ↔ 累计",
    kicker: "THE BRIDGE",
    kind: "manager-brief",
    visual: "formula-board",
    formula: "d/db ∫ₐᵇf(t)dt=f(b)",
    formulaLabel: "累计到哪里，导数就读取哪里的速率",
    sourceLabel: "教材框架",
    accent: "vermilion",
    teachingCue: "用一句学生语言复述后再显示公式。",
    assistantCue: "保持连续性等适用条件在回答中可见。"
  },
  {
    slideKey: "em-l22-46-next-methods",
    compositionId: "l22-transition-methods",
    section: "收束",
    title: "下一讲：会用端点公式，还要会把积分算出来",
    kicker: "NEXT: DEFINITE-INTEGRAL METHODS",
    kind: "transition",
    visual: "chapter-bridge",
    lead: "当被积函数不能直接积分时，换元和分部积分必须连同上下限一起处理。",
    prompt: "换元以后，旧上下限还能直接使用吗？",
    sourceLabel: "教材框架",
    accent: "cyan",
    teachingCue: "用上限变换问题自然进入第23讲。",
    assistantCue: "只提出问题，不提前展开定积分换元步骤。"
  }
];

export const economicMathematicsLesson22 = defineEconomicMathematicsLesson({
  number: 22,
  unit: 6,
  unitTitle: "定积分及累计量应用",
  title: "为什么面积可以用原函数端点相减？——微积分基本定理",
  hours: 2,
  expectedSlides: 46,
  coreQuestion: "瞬时销量率与从活动开始累计到当前时刻的销量为什么互为导数与积分？",
  exerciseCapability: "能使用微积分基本定理计算定积分和变上限积分导数，并用正确单位解释速率与累计量。",
  slides
});
