import { defineEconomicMathematicsLesson } from "../types.js";

export const economicMathematicsLesson17 = defineEconomicMathematicsLesson({
  number: 17,
  unit: 5,
  unitTitle: "不定积分",
  title: "已知边际为何找不回唯一总量？",
  hours: 2,
  expectedSlides: 43,
  coreQuestion: "已知变化率时，怎样寻找原函数族，并利用一个基准条件确定其中唯一的总量函数？",
  exerciseCapability: "能计算基本不定积分、保留积分常数、用求导验算并根据初始条件确定常数。",
  slides: [
    {
      slideKey: "econ-math-l17-01",
      compositionId: "marginal-ledger-missing-total",
      section: "只剩边际记录",
      title: "成本表丢了，只剩边际成本公式",
      kicker: "山城新饮 · 总量恢复",
      kind: "scene",
      visual: "editorial-scene",
      lead: "系统保留了MC(q)=20+0.04q，却遗失了总成本C(q)。分析员能恢复变化部分，但固定成本似乎无处可见。",
      body: ["导数记录曲线的斜率。", "斜率相同的曲线可以处在不同高度。"],
      prompt: "还需要一条什么信息，才能找回唯一总成本函数？",
      sourceLabel: "教学情境",
      sourceNote: "虚构成本恢复场景",
      accent: "vermilion",
      teachingCue: "期待“某个产量下的总成本”或“固定成本”。",
      assistantCue: "引向初始条件，不先给+C。"
    },
    {
      slideKey: "econ-math-l17-02",
      compositionId: "same-derivative-three-functions",
      section: "只剩边际记录",
      title: "三条曲线，导数完全相同",
      kicker: "高度不同，斜率相同",
      kind: "evidence",
      visual: "comparison-board",
      formula: String.raw`F_1=x^2,\qquad F_2=x^2+5,\qquad F_3=x^2-100`,
      body: ["三者导数都是2x。", "只知道2x，无法判断曲线竖直位置。"],
      prompt: "三条曲线之间相差的量有什么共同特征？",
      sourceLabel: "自制图形",
      accent: "cyan",
      teachingCue: "让学生回答“常数”，并指出常数求导为0。",
      assistantCue: "相差常数是同一区间上所有原函数的关系。"
    },
    {
      slideKey: "econ-math-l17-03",
      compositionId: "antiderivative-definition",
      section: "原函数与不定积分",
      title: "原函数：求导能回到f的函数",
      kicker: "逆向问题",
      kind: "definition",
      visual: "formula-board",
      formula: String.raw`F'(x)=f(x)\quad\Rightarrow\quad F(x)\text{是}f(x)\text{的一个原函数}`,
      body: ["原函数关系要在同一个区间内成立。", "“一个”提醒我们答案通常不唯一。"],
      sourceLabel: "教材框架",
      accent: "vermilion",
      teachingCue: "让学生给f(x)=2x找两个不同原函数。",
      assistantCue: "可答x²、x²+任意常数。"
    },
    {
      slideKey: "econ-math-l17-04",
      compositionId: "antiderivative-family-definition",
      section: "原函数与不定积分",
      title: "一个原函数带出整个函数族",
      kicker: "为什么必须写+C",
      kind: "definition",
      visual: "formula-board",
      formula: String.raw`F'(x)=f(x)\quad\Rightarrow\quad F(x)+C\ (C\in\mathbb R)\text{都是原函数}`,
      body: ["每个C对应一条竖直平移后的曲线。", "导数无法识别这个高度差。"],
      sourceLabel: "教材框架",
      accent: "cyan",
      teachingCue: "让学生口头验证(F+C)′=f。",
      assistantCue: "C为任意常数，不是自变量的函数。"
    },
    {
      slideKey: "econ-math-l17-05",
      compositionId: "antiderivatives-differ-by-constant",
      section: "原函数与不定积分",
      title: "所有原函数只差常数",
      kicker: "中值定理再次出现",
      kind: "derivation",
      visual: "formula-board",
      formula: String.raw`F'(x)=G'(x)=f(x)\Rightarrow(F-G)'=0\Rightarrow F(x)-G(x)=C`,
      body: ["导数恒为0的函数在区间上是常数。", "因此F+C没有遗漏其他形状的原函数。"],
      sourceLabel: "教材框架",
      accent: "green",
      teachingCue: "连接第12讲推论，让学生补出最后一步。",
      assistantCue: "结论在同一连通区间上成立。"
    },
    {
      slideKey: "econ-math-l17-06",
      compositionId: "vertical-shift-geometry",
      section: "原函数与不定积分",
      title: "改变C，只上下移动，不改变每一点斜率",
      kicker: "原函数族图像",
      kind: "evidence",
      visual: "coordinate-plot",
      body: ["青色曲线：F(x)。", "朱红曲线：F(x)+4。", "绿色曲线：F(x)−3。", "同一x处三条切线彼此平行。"],
      prompt: "哪一条额外数据能从函数族中选出一条？",
      sourceLabel: "自制图形",
      accent: "cyan",
      teachingCue: "期待一个点(x₀,y₀)或初始值。",
      assistantCue: "一个相容的初始条件通常能确定C。"
    },
    {
      slideKey: "econ-math-l17-07",
      compositionId: "indefinite-integral-notation",
      section: "原函数与不定积分",
      title: "不定积分记录整个原函数族",
      kicker: "积分号、被积函数、积分变量",
      kind: "definition",
      visual: "formula-board",
      formula: String.raw`\int f(x)\,dx=F(x)+C`,
      body: ["∫：积分号。", "f(x)：被积函数。", "dx：积分变量为x。", "F(x)+C：所有原函数。"],
      sourceLabel: "教材框架",
      accent: "vermilion",
      teachingCue: "让学生逐个指认四部分，不把dx当装饰。",
      assistantCue: "本课以一元不定积分语境解释dx。"
    },
    {
      slideKey: "econ-math-l17-08",
      compositionId: "integration-constant-role",
      section: "原函数与不定积分",
      title: "+C不是格式附件，而是缺失的高度信息",
      kicker: "积分常数",
      kind: "definition",
      visual: "manager-memo",
      body: ["没有初始条件：答案必须保留+C。", "给出一个函数值：可以求出C。", "不同业务对象即使边际函数相同，也可能有不同固定水平。"],
      prompt: "两个门店边际成本相同，总成本一定相同吗？",
      sourceLabel: "概念模型",
      accent: "amber",
      teachingCue: "期待“不一定，固定成本可能不同”。",
      assistantCue: "避免把C固定解释为成本；在不同问题中它代表不同初始水平。"
    },
    {
      slideKey: "econ-math-l17-09",
      compositionId: "differentiate-to-verify",
      section: "原函数与不定积分",
      title: "积分结果最直接的核验方式：求导",
      kicker: "正向检查逆向运算",
      kind: "definition",
      visual: "formula-board",
      formula: String.raw`\frac{d}{dx}\left[\int f(x)\,dx\right]=\frac{d}{dx}[F(x)+C]=f(x)`,
      body: ["核验时常数自动消失。", "若求导不能回到原被积函数，积分结果必有错误。"],
      sourceLabel: "教材框架",
      accent: "green",
      teachingCue: "规定本单元每道纸笔题最后用一行导数自检。",
      assistantCue: "求导核验能确认原函数结构，不能凭它确定C。"
    },
    {
      slideKey: "econ-math-l17-10",
      compositionId: "power-rule-integral",
      section: "基本积分公式",
      title: "幂函数积分：指数加1，再除以新指数",
      kicker: "n≠−1",
      kind: "definition",
      visual: "formula-board",
      formula: String.raw`\int x^n\,dx=\frac{x^{n+1}}{n+1}+C\qquad(n\ne-1)`,
      body: ["核验：对右端求导得到xⁿ。", "n=−1会使分母n+1为0，必须单独处理。"],
      sourceLabel: "教材框架",
      accent: "cyan",
      teachingCue: "用n=2与n=−2各口算一例。",
      assistantCue: "n可为常见实数，但需在所讨论区间内有定义。"
    },
    {
      slideKey: "econ-math-l17-11",
      compositionId: "reciprocal-integral",
      section: "基本积分公式",
      title: "1/x的原函数是ln|x|",
      kicker: "幂公式的唯一禁点",
      kind: "definition",
      visual: "formula-board",
      formula: String.raw`\int\frac1x\,dx=\ln|x|+C\qquad(x\ne0)`,
      body: ["绝对值同时覆盖正区间与负区间。", "跨过0的整个区间上，1/x没有连续原函数。"],
      sourceLabel: "教材框架",
      accent: "vermilion",
      teachingCue: "让学生分别验证x>0与x<0时导数。",
      assistantCue: "保持定义域分区；不把ln|x|写成ln x用于负数。"
    },
    {
      slideKey: "econ-math-l17-12",
      compositionId: "basic-integral-table",
      section: "基本积分公式",
      title: "三组最常用原函数",
      kicker: "由导数表反向读取",
      kind: "evidence",
      visual: "data-ledger",
      data: ["∫eˣ dx=eˣ+C", "∫cos x dx=sin x+C", "∫sin x dx=−cos x+C", "∫a dx=ax+C"],
      body: ["每一条都可通过求导立即核验。"],
      sourceLabel: "教材框架",
      accent: "ink",
      teachingCue: "特别核对∫sin x中的负号。",
      assistantCue: "角度默认弧度制。"
    },
    {
      slideKey: "econ-math-l17-13",
      compositionId: "integral-linearity",
      section: "基本积分公式",
      title: "和可以逐项积，常数可以提出",
      kicker: "积分的线性性质",
      kind: "definition",
      visual: "formula-board",
      formula: String.raw`\int[af(x)+bg(x)]dx=a\int f(x)dx+b\int g(x)dx`,
      body: ["逐项积分后只写一个总的+C。", "不要给每一项写互相独立的常数。"],
      sourceLabel: "教材框架",
      accent: "cyan",
      teachingCue: "说明多个任意常数相加仍可合并为一个任意常数。",
      assistantCue: "a、b为常数。"
    },
    {
      slideKey: "econ-math-l17-14",
      compositionId: "polynomial-integral-task",
      section: "例题一：逐项积分",
      title: "把多项式逐项反求导",
      kicker: "完整示范",
      kind: "worked-example",
      visual: "worked-grid",
      formula: String.raw`\int(3x^2-4x+5)\,dx`,
      prompt: "逐项写出原函数，再合并积分常数。",
      sourceLabel: "教材框架",
      accent: "vermilion",
      teachingCue: "让学生先口算3x²和−4x两项。",
      assistantCue: "结果x³−2x²+5x+C。"
    },
    {
      slideKey: "econ-math-l17-15",
      compositionId: "polynomial-integral-solution",
      section: "例题一：逐项积分",
      title: "结果：x³−2x²+5x+C",
      kicker: "指数与系数同步调整",
      kind: "solution",
      visual: "formula-board",
      formula: String.raw`\int(3x^2-4x+5)dx=x^3-2x^2+5x+C`,
      body: ["3x²积分后系数3被新指数3消去。", "常数5积分后成为5x。"],
      sourceLabel: "教材框架",
      accent: "green",
      teachingCue: "让学生用不同颜色标指数变化与系数变化。",
      assistantCue: "只有一个+C。"
    },
    {
      slideKey: "econ-math-l17-16",
      compositionId: "polynomial-integral-verification",
      section: "例题一：逐项积分",
      title: "求导核验回到原式",
      kicker: "一行自检",
      kind: "solution",
      visual: "formula-board",
      formula: String.raw`(x^3-2x^2+5x+C)'=3x^2-4x+5`,
      body: ["核验通过，且C的导数为0。"],
      sourceLabel: "教材框架",
      accent: "cyan",
      teachingCue: "要求学生今后不定积分答案后自行口算导数。",
      assistantCue: "自检不能替代+C。"
    },
    {
      slideKey: "econ-math-l17-17",
      compositionId: "recover-cost-antiderivative",
      section: "例题二：从边际成本恢复总成本",
      title: "先恢复成本函数族",
      kicker: "MC(q)=20+0.04q",
      kind: "worked-example",
      visual: "formula-board",
      formula: String.raw`C(q)=\int(20+0.04q)dq=20q+0.02q^2+C_0`,
      body: ["C₀暂时未知。", "它不会出现在边际成本中。"],
      sourceLabel: "教学情境",
      accent: "vermilion",
      teachingCue: "用C₀避免与成本函数C(q)符号混淆。",
      assistantCue: "积分变量为q；常数记C₀。"
    },
    {
      slideKey: "econ-math-l17-18",
      compositionId: "recover-cost-initial-condition",
      section: "例题二：从边际成本恢复总成本",
      title: "零产量成本确定C₀=2000",
      kicker: "初始条件选中唯一曲线",
      kind: "derivation",
      visual: "formula-board",
      formula: String.raw`C(0)=2000\Rightarrow 20\times0+0.02\times0^2+C_0=2000`,
      body: ["因此C₀=2000。"],
      sourceLabel: "教学情境",
      accent: "cyan",
      teachingCue: "让学生说明为什么q=0时的总成本可解释为固定成本。",
      assistantCue: "在本模型中C(0)=2000是固定成本。"
    },
    {
      slideKey: "econ-math-l17-19",
      compositionId: "recovered-cost-function",
      section: "例题二：从边际成本恢复总成本",
      title: "唯一总成本函数被找回",
      kicker: "边际信息 + 一个水平信息",
      kind: "solution",
      visual: "formula-board",
      formula: String.raw`C(q)=2000+20q+0.02q^2`,
      body: ["求导得到20+0.04q，与原边际成本一致。", "代入q=0得到2000，与初始条件一致。"],
      sourceLabel: "教学情境",
      accent: "green",
      teachingCue: "让学生完成“求导+代初值”双重核验。",
      assistantCue: "两项核验都必须通过。"
    },
    {
      slideKey: "econ-math-l17-20",
      compositionId: "integration-constant-business-meaning",
      section: "例题二：从边际成本恢复总成本",
      title: "积分常数在这里就是固定成本",
      kicker: "但不是所有题都叫固定成本",
      kind: "manager-brief",
      visual: "manager-memo",
      body: ["成本题中，C(0)常可解释为固定成本。", "库存题中，常数可能是初始库存。", "累计销售题中，常数可能是起始累计量。", "数学角色相同，业务含义随对象改变。"],
      sourceLabel: "概念模型",
      accent: "amber",
      teachingCue: "让学生为“账户余额变化率”提出常数含义。",
      assistantCue: "不要把所有积分常数固定称为固定成本。"
    },
    {
      slideKey: "econ-math-l17-21",
      compositionId: "recover-revenue-antiderivative",
      section: "例题三：从边际收益恢复收益",
      title: "已知MR(q)=120−0.2q",
      kicker: "先得到收益函数族",
      kind: "worked-example",
      visual: "formula-board",
      formula: String.raw`R(q)=\int(120-0.2q)dq=120q-0.1q^2+C_1`,
      prompt: "收益函数常见的自然初始条件是什么？",
      sourceLabel: "教学情境",
      accent: "vermilion",
      teachingCue: "期待“销量为0时收益为0”。",
      assistantCue: "在无其他收入项的模型中可用R(0)=0。"
    },
    {
      slideKey: "econ-math-l17-22",
      compositionId: "recover-revenue-condition",
      section: "例题三：从边际收益恢复收益",
      title: "R(0)=0确定C₁=0",
      kicker: "恢复唯一收益函数",
      kind: "solution",
      visual: "formula-board",
      formula: String.raw`R(0)=0\Rightarrow C_1=0\Rightarrow R(q)=120q-0.1q^2`,
      body: ["若业务还有与销量无关的补贴收入，初始条件可能不同。"],
      sourceLabel: "教学情境",
      accent: "green",
      teachingCue: "让学生说明R(0)=0是模型条件，不是数学定理。",
      assistantCue: "保持收益模型边界。"
    },
    {
      slideKey: "econ-math-l17-23",
      compositionId: "marginal-to-total-manager-memo",
      section: "例题三：从边际收益恢复收益",
      title: "边际曲线决定形状，初始值决定高度",
      kicker: "恢复总量的两类信息",
      kind: "manager-brief",
      visual: "manager-memo",
      data: ["变化信息：MR(q)决定收益怎样随q改变", "水平信息：R(0)决定整条曲线上下位置", "验证：对恢复结果求导，并代回初始值"],
      sourceLabel: "概念模型",
      accent: "cyan",
      teachingCue: "让学生用成本例题再复述“形状+高度”。",
      assistantCue: "避免说导数完全决定原函数。"
    },
    {
      slideKey: "econ-math-l17-24",
      compositionId: "differential-integral-notation",
      section: "书写与核验",
      title: "dx告诉我们对谁积分",
      kicker: "变量不可混用",
      kind: "definition",
      visual: "comparison-board",
      formula: String.raw`\int 2x\,dx=x^2+C,\qquad\int 2q\,dq=q^2+C`,
      body: ["被积表达式与积分变量必须匹配。", "业务题中q、p、t分别代表不同对象，不能随意互换。"],
      sourceLabel: "教材框架",
      accent: "ink",
      teachingCue: "给出∫2q dx，让学生指出信息不足或变量不匹配。",
      assistantCue: "本课不讨论把q视为x函数的复合积分，避免歧义。"
    },
    {
      slideKey: "econ-math-l17-25",
      compositionId: "paper-exercise-polynomial",
      section: "纸笔练习一",
      title: "逐项积分并求导核验",
      kicker: "独立计算 · 4分钟",
      kind: "exercise",
      visual: "exercise-desk",
      formula: String.raw`\int(4x^3-6x+2)\,dx`,
      body: ["写出完整原函数族。", "用一行导数核验。"],
      sourceLabel: "教材框架",
      accent: "vermilion",
      teachingCue: "巡视是否漏写+C、是否把−6x积分为−6x²。",
      assistantCue: "答案x⁴−3x²+2x+C。"
    },
    {
      slideKey: "econ-math-l17-26",
      compositionId: "polynomial-exercise-solution",
      section: "纸笔练习一",
      title: "解答：x⁴−3x²+2x+C",
      kicker: "逐项反求导",
      kind: "solution",
      visual: "worked-grid",
      formula: String.raw`\int(4x^3-6x+2)dx=x^4-3x^2+2x+C`,
      body: ["核验：(x⁴−3x²+2x+C)′=4x³−6x+2。"],
      sourceLabel: "教材框架",
      accent: "green",
      teachingCue: "让学生对照自己的指数与系数逐项打勾。",
      assistantCue: "结果正确且必须含+C。"
    },
    {
      slideKey: "econ-math-l17-27",
      compositionId: "paper-exercise-root-reciprocal",
      section: "纸笔练习二",
      title: "根式与1/x同时出现",
      kicker: "独立计算 · 5分钟",
      kind: "exercise",
      visual: "exercise-desk",
      formula: String.raw`\int\left(2\sqrt{x}+\frac3x\right)dx\qquad(x>0)`,
      body: ["把√x改写成幂。", "对1/x使用专门公式。", "写出定义域与积分常数。"],
      sourceLabel: "教材框架",
      accent: "ink",
      teachingCue: "提醒√x=x^(1/2)，但不给结果。",
      assistantCue: "答案(4/3)x^(3/2)+3ln x+C，因x>0可不写绝对值。"
    },
    {
      slideKey: "econ-math-l17-28",
      compositionId: "root-reciprocal-solution",
      section: "纸笔练习二",
      title: "解答：两类公式分别使用",
      kicker: "幂公式 + 对数公式",
      kind: "solution",
      visual: "formula-board",
      formula: String.raw`\frac43x^{3/2}+3\ln x+C\qquad(x>0)`,
      body: ["2·x^(1/2)积分后系数为2/(3/2)=4/3。", "3/x积分为3ln x。"],
      sourceLabel: "教材框架",
      accent: "green",
      teachingCue: "让学生求导核验(4/3)x^(3/2)这一项。",
      assistantCue: "导数为2sqrt(x)+3/x。"
    },
    {
      slideKey: "econ-math-l17-29",
      compositionId: "root-reciprocal-domain",
      section: "纸笔练习二",
      title: "定义域决定ln x还是ln|x|",
      kicker: "公式边界",
      kind: "evidence",
      visual: "model-boundary",
      body: ["原题限定x>0，因此ln x有定义。", "一般∫1/x dx应写ln|x|+C。", "根式√x也要求x≥0，而1/x进一步排除x=0。"],
      sourceLabel: "教材框架",
      accent: "amber",
      teachingCue: "让学生求交集得到本题x>0。",
      assistantCue: "定义域交集为(0,∞)。"
    },
    {
      slideKey: "econ-math-l17-30",
      compositionId: "initial-value-exercise-task",
      section: "纸笔练习三",
      title: "由边际成本与一个观测点恢复总成本",
      kicker: "独立计算 · 6分钟",
      kind: "exercise",
      visual: "exercise-desk",
      formula: String.raw`MC(q)=12+0.02q,\qquad C(100)=2500`,
      body: ["求总成本函数族。", "代入观测点确定常数。", "用求导与代值双重核验。", "解释C(0)的业务含义。"],
      sourceLabel: "教学情境",
      accent: "vermilion",
      teachingCue: "计时6分钟；观察学生是否把0.02q积分成0.01q²。",
      assistantCue: "答案C(q)=1200+12q+0.01q²。"
    },
    {
      slideKey: "econ-math-l17-31",
      compositionId: "initial-value-exercise-antiderivative",
      section: "纸笔练习三",
      title: "解答：先保留C₀",
      kicker: "第一步",
      kind: "solution",
      visual: "formula-board",
      formula: String.raw`C(q)=\int(12+0.02q)dq=12q+0.01q^2+C_0`,
      sourceLabel: "教学情境",
      accent: "cyan",
      teachingCue: "让学生先核验导数，再代初值。",
      assistantCue: "积分结构正确。"
    },
    {
      slideKey: "econ-math-l17-32",
      compositionId: "initial-value-exercise-constant",
      section: "纸笔练习三",
      title: "解答：观测点给出C₀=1200",
      kicker: "第二步",
      kind: "solution",
      visual: "worked-grid",
      formula: String.raw`2500=12(100)+0.01(100)^2+C_0=1300+C_0`,
      body: ["因此C₀=1200。", "总成本C(q)=1200+12q+0.01q²。"],
      sourceLabel: "教学情境",
      accent: "green",
      teachingCue: "让学生用C(100)=2500回代复核。",
      assistantCue: "1200+1200+100=2500。"
    },
    {
      slideKey: "econ-math-l17-33",
      compositionId: "initial-value-business-meaning",
      section: "纸笔练习三",
      title: "C(0)=1200：模型中的固定成本",
      kicker: "从常数回到业务",
      kind: "manager-brief",
      visual: "manager-memo",
      body: ["零产量时模型仍有1200元成本。", "边际成本数据无法单独识别这1200元。", "一个总成本观测点补齐了水平信息。"],
      sourceLabel: "教学情境",
      accent: "amber",
      teachingCue: "让学生说明若观测点有误，会影响曲线形状还是整体高度。",
      assistantCue: "在边际函数固定时，初值误差改变整体高度。"
    },
    {
      slideKey: "econ-math-l17-34",
      compositionId: "error-audit-missing-c",
      section: "错因诊断",
      title: "错解一：不定积分只写一个函数",
      kicker: "漏掉整个函数族",
      kind: "error-audit",
      visual: "error-lens",
      formula: String.raw`\int2x\,dx=x^2\quad\text{（不完整）}`,
      body: ["x²+5、x²−100同样求导得到2x。", "没有初始条件时，不能选择其中一条。"],
      prompt: "怎样用最少字符修正？",
      sourceLabel: "概念模型",
      accent: "vermilion",
      teachingCue: "期待在末尾补+C。",
      assistantCue: "完整答案x²+C。"
    },
    {
      slideKey: "econ-math-l17-35",
      compositionId: "missing-c-counterexample",
      section: "错因诊断",
      title: "求导核验抓不出“漏C”，逻辑核验可以",
      kicker: "一种特殊错误",
      kind: "evidence",
      visual: "comparison-board",
      body: ["x²求导确实等于2x。", "但不定积分问的是全部原函数，而不是任意一个。", "因此还要检查答案是否表达函数族。"],
      sourceLabel: "概念模型",
      accent: "amber",
      teachingCue: "强调求导核验是必要但不充分的答案完整性检查。",
      assistantCue: "不要说x²数学上不是原函数；它是一个原函数，但不是完整不定积分答案。"
    },
    {
      slideKey: "econ-math-l17-36",
      compositionId: "missing-c-repair",
      section: "错因诊断",
      title: "修正：无初值保留+C，有初值再求C",
      kicker: "两种题型分流",
      kind: "solution",
      visual: "variable-map",
      data: ["纯不定积分 → F(x)+C", "给定F(x₀)=y₀ → 先写+C，再代入求C", "报告总量函数 → 同时核验导数与初值"],
      sourceLabel: "教材框架",
      accent: "green",
      teachingCue: "让学生给三类题分别写答案末行。",
      assistantCue: "初值相容时确定唯一常数。"
    },
    {
      slideKey: "econ-math-l17-37",
      compositionId: "error-audit-power-minus-one",
      section: "错因诊断",
      title: "错解二：把n=−1硬塞进幂公式",
      kicker: "分母会变成0",
      kind: "error-audit",
      visual: "error-lens",
      formula: String.raw`\int x^{-1}dx\stackrel{?}=\frac{x^0}{0}+C`,
      body: ["除以0没有定义。", "1/x必须使用对数原函数。"],
      sourceLabel: "概念模型",
      accent: "vermilion",
      teachingCue: "让学生在幂公式旁醒目标注n≠−1。",
      assistantCue: "正确为ln|x|+C。"
    },
    {
      slideKey: "econ-math-l17-38",
      compositionId: "power-minus-one-repair",
      section: "错因诊断",
      title: "修正：看到1/x立即切换对数公式",
      kicker: "例外要单列",
      kind: "solution",
      visual: "formula-board",
      formula: String.raw`\int\frac1x dx=\ln|x|+C,\qquad(\ln|x|)'=\frac1x`,
      sourceLabel: "教材框架",
      accent: "green",
      teachingCue: "用求导再次核验。",
      assistantCue: "定义域x≠0，并在各连通区间理解C。"
    },
    {
      slideKey: "econ-math-l17-39",
      compositionId: "error-audit-condition-on-derivative",
      section: "错因诊断",
      title: "错解三：把初值代进边际函数求C",
      kicker: "C根本不在导数里",
      kind: "error-audit",
      visual: "error-lens",
      body: ["初始条件C(100)=2500属于总成本函数。", "边际函数MC(100)只给斜率，不包含积分常数。", "必须先积分，再把初值代入原函数族。"],
      sourceLabel: "概念模型",
      accent: "amber",
      teachingCue: "让学生在变量图上把观测点连到C(q)，而不是MC(q)。",
      assistantCue: "不要将函数C与常数C₀混淆。"
    },
    {
      slideKey: "econ-math-l17-40",
      compositionId: "initial-condition-repair",
      section: "错因诊断",
      title: "修正：先积分，后代值，最后双检",
      kicker: "固定顺序",
      kind: "solution",
      visual: "data-ledger",
      data: ["边际函数 → 不定积分得到F+C", "初始条件 → 代入求C", "求导 → 检查变化率", "代值 → 检查水平信息"],
      sourceLabel: "概念模型",
      accent: "cyan",
      teachingCue: "让学生遮住文字，只看箭头复述。",
      assistantCue: "顺序不可倒置。"
    },
    {
      slideKey: "econ-math-l17-41",
      compositionId: "antiderivative-information-boundary",
      section: "解释与边界",
      title: "变化率数据不能自动恢复历史水平",
      kicker: "信息边界",
      kind: "evidence",
      visual: "model-boundary",
      body: ["边际函数可恢复总量的变化形状。", "绝对水平至少需要一个可靠基准点。", "若边际关系只在局部区间有效，积分结果也只能在该区间解释。", "初值测量误差会整体平移恢复曲线。"],
      sourceLabel: "概念模型",
      accent: "amber",
      teachingCue: "让学生指出四条分别对应数学常数、定义域和数据质量。",
      assistantCue: "不得声称积分能创造缺失的初始信息。"
    },
    {
      slideKey: "econ-math-l17-42",
      compositionId: "antiderivative-exit-ticket",
      section: "课堂收束",
      title: "离场题：积分常数由一个点确定",
      kicker: "3分钟独立作答",
      kind: "exercise",
      visual: "exercise-desk",
      formula: String.raw`F'(x)=6x^2-4,\qquad F(1)=5`,
      body: ["求F(x)。", "用求导与代值核验。"],
      sourceLabel: "教材框架",
      accent: "ink",
      teachingCue: "计时3分钟，随后口头核对C。",
      assistantCue: "F=2x³−4x+7。"
    },
    {
      slideKey: "econ-math-l17-43",
      compositionId: "integral-patterns-bridge",
      section: "课堂收束",
      title: "公式表能处理逐项积分，遇到嵌套结构怎么办？",
      kicker: "下一讲：基本公式与结构识别",
      kind: "transition",
      visual: "chapter-bridge",
      formula: String.raw`\int 2x\cos(x^2)\,dx`,
      lead: "下一讲先巩固常见积分公式，再学习识别“外层函数的导数恰好藏在旁边”的结构。",
      prompt: "式中哪一部分像是x²的导数？",
      sourceLabel: "概念模型",
      accent: "vermilion",
      teachingCue: "期待2x，只留下结构观察，不计算。",
      assistantCue: "不提前完整讲换元；可确认2x dx与d(x²)对应。"
    }
  ]
});
