import { defineEconomicMathematicsLesson } from "../types.js";

export const economicMathematicsLesson15 = defineEconomicMathematicsLesson({
  number: 15,
  unit: 4,
  unitTitle: "导数应用、边际与弹性分析",
  title: "多卖一单究竟值多少？",
  hours: 2,
  expectedSlides: 45,
  coreQuestion: "怎样把导数解释为边际成本、边际收益与边际利润，并用边际关系支持产量决策？",
  exerciseCapability: "能计算边际量、核验一单位真实增量、使用MR=MC寻找候选产量并说明边界。",
  slides: [
    {
      slideKey: "econ-math-l15-01",
      compositionId: "last-cup-opening",
      section: "最后一杯值不值得做",
      title: "订单已经排到第500杯",
      kicker: "山城新饮 · 临时加单",
      kind: "scene",
      visual: "editorial-scene",
      lead: "门店刚完成第500杯，平台又来一单。经理不想重算全天账目，只想知道多做这一杯大约增加多少成本、收益与利润。",
      body: ["总成本回答“已经花了多少”。", "边际成本回答“再增加一点会怎样”。"],
      prompt: "你会比较哪两个“多出来的量”？",
      sourceLabel: "教学情境",
      sourceNote: "虚构门店加单场景",
      accent: "vermilion",
      teachingCue: "收集“新增收益与新增成本”，追问为什么不比较总收益和总成本。",
      assistantCue: "引向边际收益与边际成本，不先给MR=MC。"
    },
    {
      slideKey: "econ-math-l15-02",
      compositionId: "total-average-marginal-split",
      section: "最后一杯值不值得做",
      title: "三个问题对应三个量",
      kicker: "总量、平均量、边际量",
      kind: "question",
      visual: "decision-split",
      data: ["全天一共花多少？→ 总成本C(q)", "平均每杯花多少？→ 平均成本C(q)/q", "再多做一杯约多花多少？→ 边际成本C′(q)"],
      prompt: "“第501杯的成本”最接近哪一个量？为什么仍是近似？",
      sourceLabel: "概念模型",
      accent: "amber",
      teachingCue: "让学生指出导数是连续模型的瞬时变化率，一杯是有限改变量。",
      assistantCue: "边际成本最接近，但精确增量为C(501)−C(500)。"
    },
    {
      slideKey: "econ-math-l15-03",
      compositionId: "marginal-definition",
      section: "边际量是什么",
      title: "边际量就是总量函数的导数",
      kicker: "在当前水平附近",
      kind: "definition",
      visual: "formula-board",
      formula: String.raw`MC(q)=C'(q),\qquad MR(q)=R'(q),\qquad MP(q)=P'(q)`,
      body: ["MC：边际成本。", "MR：边际收益。", "MP：边际利润。", "它们都依赖当前产量q。"],
      sourceLabel: "教材框架",
      accent: "vermilion",
      teachingCue: "要求学生把英文缩写分别读成中文，不把MR误成平均收益。",
      assistantCue: "P=R−C时MP=MR−MC。"
    },
    {
      slideKey: "econ-math-l15-04",
      compositionId: "marginal-units-ledger",
      section: "边际量是什么",
      title: "单位透露了边际量的含义",
      kicker: "每增加一个产量单位",
      kind: "evidence",
      visual: "data-ledger",
      data: ["C：元；q：杯；MC：元/杯", "R：元；q：杯；MR：元/杯", "P：元；q：杯；MP：元/杯"],
      body: ["边际量是变化率，不是总额。"],
      prompt: "“MC=40元”怎样改写得更严谨？",
      sourceLabel: "概念模型",
      accent: "ink",
      teachingCue: "期待“在某产量附近，每增加一杯，成本约增加40元”。",
      assistantCue: "必须补基准产量、每杯单位和近似语气。"
    },
    {
      slideKey: "econ-math-l15-05",
      compositionId: "marginal-vs-discrete-increment",
      section: "边际量是什么",
      title: "导数不是“下一杯”的精确账单",
      kicker: "连续变化率与离散增量",
      kind: "definition",
      visual: "comparison-board",
      formula: String.raw`C'(q)\approx C(q+1)-C(q)`,
      body: ["左边：q处的瞬时变化率。", "右边：从q到q+1的真实有限增量。", "曲线越弯，一杯增量与导数的差异可能越明显。"],
      sourceLabel: "教材框架",
      accent: "cyan",
      teachingCue: "连接上一讲微分，指出dq=1时dC=C′(q)。",
      assistantCue: "近似号不能改成恒等号，除非成本函数为线性。"
    },
    {
      slideKey: "econ-math-l15-06",
      compositionId: "cost-model-task",
      section: "例题一：边际成本",
      title: "500杯附近的成本变化",
      kicker: "固定成本 + 线性成本 + 拥挤成本",
      kind: "worked-example",
      visual: "data-ledger",
      formula: String.raw`C(q)=2000+20q+0.02q^2`,
      data: ["当前产量：500杯", "目标：计算MC(500)", "核验：比较C(501)−C(500)"],
      sourceLabel: "教学情境",
      sourceNote: "虚构短期成本函数",
      accent: "vermilion",
      teachingCue: "让学生先解释三项可能代表什么，再求导。",
      assistantCue: "解释仅为教学含义；不声称来自真实门店估计。"
    },
    {
      slideKey: "econ-math-l15-07",
      compositionId: "cost-marginal-calculation",
      section: "例题一：边际成本",
      title: "边际成本为40元/杯",
      kicker: "当前斜率",
      kind: "solution",
      visual: "formula-board",
      formula: String.raw`MC(q)=C'(q)=20+0.04q,\qquad MC(500)=40\text{元/杯}`,
      body: ["固定成本2000不随q变化，所以导数为0。", "拥挤成本使边际成本随产量上升。"],
      sourceLabel: "概念模型",
      accent: "cyan",
      teachingCue: "追问固定成本为何不进入边际值，但仍进入总利润。",
      assistantCue: "不能说固定成本不存在，只说其边际贡献为0。"
    },
    {
      slideKey: "econ-math-l15-08",
      compositionId: "cost-discrete-check",
      section: "例题一：边际成本",
      title: "第501杯的模型精确增量是40.02元",
      kicker: "用差分核验边际近似",
      kind: "solution",
      visual: "worked-grid",
      formula: String.raw`C(501)-C(500)=40.02\text{元}`,
      body: ["边际估计：40元。", "精确增量：40.02元。", "误差：0.02元。"],
      sourceLabel: "概念模型",
      accent: "green",
      teachingCue: "让学生展开(q+1)²−q²=2q+1复核。",
      assistantCue: "精确增量20+0.02(1001)=40.02。"
    },
    {
      slideKey: "econ-math-l15-09",
      compositionId: "cost-marginal-interpretation",
      section: "例题一：边际成本",
      title: "一句完整解释",
      kicker: "基准 + 改变 + 近似 + 单位",
      kind: "manager-brief",
      visual: "manager-memo",
      lead: "在该成本模型和500杯产量附近，每增加1杯，成本约增加40元；模型对第501杯的精确增量为40.02元。",
      body: ["边际量适合快速判断。", "记账与报价仍可使用离散增量核验。"],
      sourceLabel: "教学情境",
      accent: "green",
      teachingCue: "让学生把句子中的500杯删除，观察含义为何变得不完整。",
      assistantCue: "保持模型限定；不将40元称为平均每杯成本。"
    },
    {
      slideKey: "econ-math-l15-10",
      compositionId: "increasing-marginal-cost-plot",
      section: "例题一：边际成本",
      title: "产量越高，下一杯越贵",
      kicker: "边际成本递增",
      kind: "evidence",
      visual: "coordinate-plot",
      data: ["q=100：MC=24", "q=300：MC=32", "q=500：MC=40", "q=700：MC=48"],
      body: ["二次总成本对应线性上升的边际成本。"],
      prompt: "这条上升线可能对应哪些运营压力？",
      sourceLabel: "自制图形",
      accent: "amber",
      teachingCue: "接受加班、拥挤、加急等解释，但标明它们不是数据事实。",
      assistantCue: "只将运营解释作为可能机制，数学依据是0.02q²。"
    },
    {
      slideKey: "econ-math-l15-11",
      compositionId: "marginal-revenue-model-task",
      section: "例题二：边际收益",
      title: "多卖一杯，为什么收益不一定多120元？",
      kicker: "销量增加伴随价格下降",
      kind: "worked-example",
      visual: "data-ledger",
      formula: String.raw`p(q)=120-0.1q,\qquad R(q)=q\,p(q)=120q-0.1q^2`,
      body: ["当前产量q=400杯。", "增加销量需要沿需求关系降低价格。"],
      prompt: "计算MR(400)，并解释为什么小于当前价格80元。",
      sourceLabel: "教学情境",
      sourceNote: "虚构反需求函数",
      accent: "vermilion",
      teachingCue: "先让学生算当前价格p(400)=80，再求边际收益。",
      assistantCue: "MR(400)=40元/杯；差异来自降价影响所有销量。"
    },
    {
      slideKey: "econ-math-l15-12",
      compositionId: "revenue-marginal-calculation",
      section: "例题二：边际收益",
      title: "400杯附近的边际收益为40元/杯",
      kicker: "收益曲线斜率",
      kind: "solution",
      visual: "formula-board",
      formula: String.raw`MR(q)=R'(q)=120-0.2q,\qquad MR(400)=40\text{元/杯}`,
      body: ["它估计沿需求曲线多销售一杯带来的收益净增量。"],
      sourceLabel: "概念模型",
      accent: "cyan",
      teachingCue: "要求学生不要把MR与价格p(q)混淆。",
      assistantCue: "当前价格80，边际收益40。"
    },
    {
      slideKey: "econ-math-l15-13",
      compositionId: "revenue-discrete-check",
      section: "例题二：边际收益",
      title: "第401杯对应收益增量39.9元",
      kicker: "差分核验",
      kind: "solution",
      visual: "worked-grid",
      formula: String.raw`R(401)-R(400)=39.9\text{元}`,
      body: ["边际估计：40元。", "模型精确增量：39.9元。", "线性估计高0.1元。"],
      sourceLabel: "概念模型",
      accent: "green",
      teachingCue: "让学生用R(q+1)−R(q)=119.9−0.2q验证。",
      assistantCue: "q=400时119.9−80=39.9。"
    },
    {
      slideKey: "econ-math-l15-14",
      compositionId: "revenue-price-effect-interpretation",
      section: "例题二：边际收益",
      title: "新增一杯带来收入，也带来全量降价影响",
      kicker: "MR低于价格的原因",
      kind: "derivation",
      visual: "variable-map",
      formula: String.raw`R'(q)=p(q)+q\,p'(q)`,
      body: ["p(q)：新增销量按当前价格带来的收入。", "q p′(q)：为增加销量而降价，对原有销量造成的收益变化。", "需求向下时p′(q)<0，因此MR通常低于价格。"],
      sourceLabel: "概念模型",
      accent: "amber",
      teachingCue: "把乘积求导的两项对应到业务语言。",
      assistantCue: "仅在可微反需求函数语境下使用该分解。"
    },
    {
      slideKey: "econ-math-l15-15",
      compositionId: "profit-model-combination",
      section: "边际利润与产量决策",
      title: "把收益曲线与成本曲线放到一起",
      kicker: "同一个q",
      kind: "worked-example",
      visual: "comparison-board",
      formula: String.raw`P(q)=R(q)-C(q)=100q-0.12q^2-2000`,
      body: ["收益模型：120q−0.1q²。", "成本模型：2000+20q+0.02q²。"],
      prompt: "先不求最优值：在q=400时，多做一杯约增加多少利润？",
      sourceLabel: "教学情境",
      accent: "vermilion",
      teachingCue: "让学生分别算MR与MC，再做差。",
      assistantCue: "q=400时MR=40，MC=36，MP=4元/杯。"
    },
    {
      slideKey: "econ-math-l15-16",
      compositionId: "marginal-profit-identity",
      section: "边际利润与产量决策",
      title: "边际利润 = 边际收益 − 边际成本",
      kicker: "导数的线性性质",
      kind: "derivation",
      visual: "formula-board",
      formula: String.raw`MP(q)=P'(q)=R'(q)-C'(q)=MR(q)-MC(q)`,
      body: ["MR>MC：边际利润为正，局部增加产量提高利润。", "MR<MC：边际利润为负，局部增加产量降低利润。"],
      sourceLabel: "教材框架",
      accent: "cyan",
      teachingCue: "让学生把正负号翻译成“值得多做一点/应少做一点”。",
      assistantCue: "仅为局部方向判断；还需可行域与整体判别。"
    },
    {
      slideKey: "econ-math-l15-17",
      compositionId: "profit-at-four-hundred",
      section: "边际利润与产量决策",
      title: "q=400：再增加一点仍有利",
      kicker: "MR比MC高4元/杯",
      kind: "evidence",
      visual: "data-ledger",
      data: ["MR(400)=40元/杯", "MC(400)=36元/杯", "MP(400)=4元/杯"],
      body: ["利润曲线在q=400处仍向上。", "这不表示每增加任意多杯都继续有利。"],
      sourceLabel: "教学情境",
      accent: "green",
      teachingCue: "追问增加1000杯是否也能用4×1000估计，连接局部边界。",
      assistantCue: "不能远距离线性外推；MR与MC都随q变化。"
    },
    {
      slideKey: "econ-math-l15-18",
      compositionId: "profit-at-four-fifty",
      section: "边际利润与产量决策",
      title: "q=450：再增加一点会压低利润",
      kicker: "MR比MC低8元/杯",
      kind: "evidence",
      visual: "data-ledger",
      data: ["MR(450)=30元/杯", "MC(450)=38元/杯", "MP(450)=−8元/杯"],
      body: ["利润曲线在q=450处向下。", "局部减少产量反而会提高利润。"],
      sourceLabel: "教学情境",
      accent: "amber",
      teachingCue: "让学生解释负边际利润不是总利润必为负。",
      assistantCue: "q=450时总利润仍可为正；负号只表示局部方向。"
    },
    {
      slideKey: "econ-math-l15-19",
      compositionId: "mr-equals-mc-candidate",
      section: "边际利润与产量决策",
      title: "MR=MC给出利润驻点",
      kicker: "候选产量约416.67杯",
      kind: "derivation",
      visual: "formula-board",
      formula: String.raw`120-0.2q=20+0.04q\Rightarrow q=\frac{100}{0.24}\approx416.67`,
      body: ["此时MP=MR−MC=0。", "这只是连续模型中的候选点，还需判别与可执行化。"],
      sourceLabel: "概念模型",
      accent: "cyan",
      teachingCue: "让学生说明MR=MC与P′=0是同一方程。",
      assistantCue: "精确值q=1250/3。"
    },
    {
      slideKey: "econ-math-l15-20",
      compositionId: "mr-mc-crossing-decision",
      section: "边际利润与产量决策",
      title: "交点左侧增产，右侧减产",
      kicker: "边际关系给出方向",
      kind: "solution",
      visual: "coordinate-plot",
      body: ["MR随q下降。", "MC随q上升。", "交点左侧MR>MC，利润递增；交点右侧MR<MC，利润递减。"],
      prompt: "为什么这次MR=MC对应最大而不是最小？",
      sourceLabel: "自制图形",
      accent: "green",
      teachingCue: "让学生用MP符号由正变负回答。",
      assistantCue: "关键是P′从正变负，不是等式本身。"
    },
    {
      slideKey: "econ-math-l15-21",
      compositionId: "average-cost-definition",
      section: "平均成本与边际成本",
      title: "平均成本摊的是全部成本",
      kicker: "固定成本会被产量分摊",
      kind: "definition",
      visual: "formula-board",
      formula: String.raw`AC(q)=\frac{C(q)}q=\frac{2000}{q}+20+0.02q,\qquad q>0`,
      body: ["2000/q随产量增加而下降。", "0.02q随产量增加而上升。", "两种力量可能形成平均成本谷底。"],
      sourceLabel: "教材框架",
      accent: "vermilion",
      teachingCue: "让学生解释为什么q=0不在平均成本定义域。",
      assistantCue: "AC单位元/杯；不能在q=0计算。"
    },
    {
      slideKey: "econ-math-l15-22",
      compositionId: "average-cost-minimum",
      section: "平均成本与边际成本",
      title: "平均成本最低产量约316.23杯",
      kicker: "对AC求导",
      kind: "derivation",
      visual: "formula-board",
      formula: String.raw`AC'(q)=-\frac{2000}{q^2}+0.02=0\Rightarrow q=\sqrt{100000}\approx316.23`,
      body: ["q>0只保留正根。", "导数由负变正，因此该点为平均成本最小点。"],
      sourceLabel: "教材框架",
      accent: "cyan",
      teachingCue: "要求学生先写定义域q>0再舍去负根。",
      assistantCue: "sqrt(100000)=100sqrt(10)≈316.2278。"
    },
    {
      slideKey: "econ-math-l15-23",
      compositionId: "mc-crosses-ac-proof",
      section: "平均成本与边际成本",
      title: "AC最低时，MC恰好等于AC",
      kicker: "不是两条线碰巧相交",
      kind: "derivation",
      visual: "formula-board",
      formula: String.raw`AC'(q)=\frac{qC'(q)-C(q)}{q^2}=0\Rightarrow MC(q)=AC(q)`,
      body: ["MC<AC时，新增单位比原平均便宜，平均成本被拉低。", "MC>AC时，新增单位比原平均贵，平均成本被抬高。"],
      sourceLabel: "教材框架",
      accent: "green",
      teachingCue: "用“新成绩拉低/抬高平均分”的类比帮助理解。",
      assistantCue: "等式在可导且q>0的内部驻点成立；不是所有q都相等。"
    },
    {
      slideKey: "econ-math-l15-24",
      compositionId: "mc-ac-numeric-check",
      section: "平均成本与边际成本",
      title: "数值核验：两者约32.65元/杯",
      kicker: "q≈316.23",
      kind: "evidence",
      visual: "comparison-board",
      data: ["MC=20+0.04q≈32.649", "AC=2000/q+20+0.02q≈32.649"],
      body: ["相交发生在平均成本曲线的最低点。"],
      sourceLabel: "概念模型",
      sourceNote: "确定性数值复核",
      accent: "green",
      teachingCue: "让学生分别代入两式，观察两项6.3249如何对称出现。",
      assistantCue: "保留约32.65元/杯即可。"
    },
    {
      slideKey: "econ-math-l15-25",
      compositionId: "average-cost-boundary",
      section: "平均成本与边际成本",
      title: "最低平均成本不必等于最大利润",
      kicker: "目标函数不同，答案不同",
      kind: "evidence",
      visual: "model-boundary",
      body: ["最低AC只关注每杯成本。", "最大利润同时取决于收益曲线。", "本模型最低AC约在316杯，最大利润候选约在417杯。"],
      prompt: "若经理问“赚得最多”，应该优化哪一个函数？",
      sourceLabel: "概念模型",
      accent: "amber",
      teachingCue: "期待利润P，而不是平均成本AC。",
      assistantCue: "目标必须由问题指定；不得用成本最低替代利润最大。"
    },
    {
      slideKey: "econ-math-l15-26",
      compositionId: "paper-exercise-marginal-cost",
      section: "纸笔练习一",
      title: "200件附近的边际成本",
      kicker: "独立计算 · 4分钟",
      kind: "exercise",
      visual: "exercise-desk",
      formula: String.raw`C(q)=1000+10q+0.01q^2,\qquad q=200`,
      body: ["计算MC(200)。", "计算C(201)−C(200)。", "写出误差与单位。"],
      sourceLabel: "教学情境",
      accent: "ink",
      teachingCue: "计时4分钟；巡视是否把常数1000带入导数。",
      assistantCue: "解答页前不给结果；MC=14，精确增量14.01。"
    },
    {
      slideKey: "econ-math-l15-27",
      compositionId: "marginal-cost-exercise-solution",
      section: "纸笔练习一",
      title: "解答：边际估计14元，精确增量14.01元",
      kicker: "变化率与差分",
      kind: "solution",
      visual: "worked-grid",
      formula: String.raw`C'(q)=10+0.02q,\quad C'(200)=14,\quad C(201)-C(200)=14.01`,
      body: ["边际估计高效且误差0.01元。"],
      sourceLabel: "概念模型",
      accent: "green",
      teachingCue: "让学生用单位检查14元/件×1件=14元。",
      assistantCue: "边际量单位元/件，有限增量单位元。"
    },
    {
      slideKey: "econ-math-l15-28",
      compositionId: "paper-exercise-marginal-revenue",
      section: "纸笔练习二",
      title: "300件附近的边际收益",
      kicker: "独立计算 · 4分钟",
      kind: "exercise",
      visual: "exercise-desk",
      formula: String.raw`R(q)=80q-0.05q^2,\qquad q=300`,
      body: ["计算MR(300)。", "计算R(301)−R(300)。", "解释两者为何略有差异。"],
      sourceLabel: "教学情境",
      accent: "vermilion",
      teachingCue: "提醒平方项系数求导后乘2。",
      assistantCue: "MR=50，精确增量49.95。"
    },
    {
      slideKey: "econ-math-l15-29",
      compositionId: "marginal-revenue-exercise-solution",
      section: "纸笔练习二",
      title: "解答：边际估计50元，精确增量49.95元",
      kicker: "曲率造成0.05元差异",
      kind: "solution",
      visual: "worked-grid",
      formula: String.raw`R'(q)=80-0.1q,\quad R'(300)=50,\quad R(301)-R(300)=49.95`,
      body: ["收益曲线向下弯，起点切线略高估一单位增量。"],
      sourceLabel: "概念模型",
      accent: "green",
      teachingCue: "让学生把误差与二次项−0.05联系起来。",
      assistantCue: "误差为0.05元，边际估计偏高。"
    },
    {
      slideKey: "econ-math-l15-30",
      compositionId: "paper-exercise-profit-optimum",
      section: "纸笔练习三",
      title: "用MR与MC寻找利润候选产量",
      kicker: "独立计算 · 6分钟",
      kind: "exercise",
      visual: "exercise-desk",
      formula: String.raw`R(q)=80q-0.05q^2,\quad C(q)=1000+10q+0.01q^2,\quad q\in[0,700]`,
      body: ["分别求MR与MC。", "解MR=MC。", "判断交点两侧利润方向。", "比较端点并报告最大利润。"],
      sourceLabel: "教学情境",
      accent: "ink",
      teachingCue: "计时6分钟；要求学生保留分数或至少两位小数。",
      assistantCue: "候选q=1750/3≈583.33，最大利润约19416.67元。"
    },
    {
      slideKey: "econ-math-l15-31",
      compositionId: "profit-optimum-exercise-equation",
      section: "纸笔练习三",
      title: "解答：MR=MC得到q≈583.33",
      kicker: "边际相等",
      kind: "solution",
      visual: "formula-board",
      formula: String.raw`MR=80-0.1q,\quad MC=10+0.02q,\quad70=0.12q\Rightarrow q=\frac{1750}{3}`,
      body: ["候选产量位于(0,700)内。"],
      sourceLabel: "概念模型",
      accent: "cyan",
      teachingCue: "让学生说明为什么不能把70除以0.12算成58.33。",
      assistantCue: "70/0.12=583.333。"
    },
    {
      slideKey: "econ-math-l15-32",
      compositionId: "profit-optimum-exercise-sign",
      section: "纸笔练习三",
      title: "解答：边际利润由正变负",
      kicker: "最大值判别",
      kind: "solution",
      visual: "comparison-board",
      formula: String.raw`MP(q)=MR-MC=70-0.12q`,
      data: ["0<q<583.33：MP>0，利润递增", "583.33<q<700：MP<0，利润递减"],
      body: ["交点是局部最大候选。"],
      sourceLabel: "概念模型",
      accent: "green",
      teachingCue: "让学生用一次函数下降趋势完成判号。",
      assistantCue: "需继续比较端点才能报告区间最大。"
    },
    {
      slideKey: "econ-math-l15-33",
      compositionId: "profit-optimum-exercise-values",
      section: "纸笔练习三",
      title: "解答：连续模型最大利润约19416.67元",
      kicker: "候选值比较",
      kind: "solution",
      visual: "data-ledger",
      data: ["P(0)=−1000元", "P(583.33)≈19416.67元", "P(700)=18600元"],
      body: ["区间最大值在q=1750/3处取得。"],
      sourceLabel: "教学情境",
      accent: "green",
      teachingCue: "让学生用P=70q−0.06q²−1000复核。",
      assistantCue: "精确最大值可由顶点式核验，约19416.67。"
    },
    {
      slideKey: "econ-math-l15-34",
      compositionId: "error-audit-average-vs-marginal",
      section: "错因诊断",
      title: "错解一：平均成本就是边际成本",
      kicker: "一个看全部，一个看下一点",
      kind: "error-audit",
      visual: "error-lens",
      formula: String.raw`AC(q)=\frac{C(q)}q\quad\not\equiv\quad MC(q)=C'(q)`,
      prompt: "在练习一q=200处分别计算AC与MC。",
      sourceLabel: "概念模型",
      accent: "vermilion",
      teachingCue: "让学生口算AC=17，MC=14。",
      assistantCue: "C(200)=3400，AC=17元/件，MC=14元/件。"
    },
    {
      slideKey: "econ-math-l15-35",
      compositionId: "average-marginal-repair",
      section: "错因诊断",
      title: "修正：平均值被边际值拉动",
      kicker: "二者关系不是恒等",
      kind: "solution",
      visual: "comparison-board",
      data: ["MC<AC：新增单位低于原平均，AC下降", "MC=AC：AC可能处于驻点", "MC>AC：新增单位高于原平均，AC上升"],
      body: ["只有在特定交点，两者数值才相等。"],
      sourceLabel: "概念模型",
      accent: "green",
      teachingCue: "用平均分例子让学生再解释一遍。",
      assistantCue: "相等点是否为最低还需结合符号变化。"
    },
    {
      slideKey: "econ-math-l15-36",
      compositionId: "error-audit-fixed-cost-ignored",
      section: "错因诊断",
      title: "错解二：固定成本求导为0，所以可以删除",
      kicker: "边际判断与总利润判断不同",
      kind: "error-audit",
      visual: "error-lens",
      body: ["固定成本不影响MC和利润驻点的位置。", "固定成本会降低每个产量水平的总利润。", "它可能使“最优方案”仍然亏损。"],
      prompt: "若固定成本大幅上升，最优q一定改变吗？最大利润会怎样？",
      sourceLabel: "概念模型",
      accent: "amber",
      teachingCue: "期待“在其他结构不变时q不变，但最大利润下降”。",
      assistantCue: "常数固定成本不改变一阶条件，但改变目标函数值。"
    },
    {
      slideKey: "econ-math-l15-37",
      compositionId: "fixed-cost-repair",
      section: "错因诊断",
      title: "修正：求导时消失，报告时回来",
      kicker: "计算层与决策层",
      kind: "solution",
      visual: "variable-map",
      data: ["求边际量：固定成本导数为0", "找驻点：固定成本不改位置", "算利润值：必须带回固定成本", "判断是否值得经营：比较最大利润与0"],
      sourceLabel: "概念模型",
      accent: "cyan",
      teachingCue: "让学生将四步分别标为“斜率问题”与“水平问题”。",
      assistantCue: "保持固定成本为常数的前提。"
    },
    {
      slideKey: "econ-math-l15-38",
      compositionId: "error-audit-marginal-exact",
      section: "错因诊断",
      title: "错解三：MC(q)就是第q+1件精确成本",
      kicker: "近似号不能丢",
      kind: "error-audit",
      visual: "error-lens",
      formula: String.raw`MC(q)=C'(q)\approx C(q+1)-C(q)`,
      body: ["二次成本例题中两者相差0.02或0.01。", "步长越大，直接用一个边际值乘步长的误差通常越大。"],
      sourceLabel: "概念模型",
      accent: "vermilion",
      teachingCue: "让学生用第500杯和第200件两个数值举证。",
      assistantCue: "线性成本函数是精确相等的特殊情形。"
    },
    {
      slideKey: "econ-math-l15-39",
      compositionId: "marginal-exact-repair",
      section: "错因诊断",
      title: "修正：边际值用于局部决策，差分用于精确核账",
      kicker: "两种量各有用途",
      kind: "solution",
      visual: "comparison-board",
      data: ["快速方向判断：看MR−MC符号", "小幅增量估算：边际值×改变量", "整数一单位核账：计算函数差", "大幅改变：重新积分或完整计算整段变化"],
      sourceLabel: "概念模型",
      accent: "green",
      teachingCue: "“重新积分”只作后续预告，不展开。",
      assistantCue: "大幅变化不能只用单点边际值。"
    },
    {
      slideKey: "econ-math-l15-40",
      compositionId: "integer-output-decision",
      section: "可执行决策",
      title: "连续最优416.67杯，实际做416还是417？",
      kicker: "比较邻近整数",
      kind: "worked-example",
      visual: "data-ledger",
      formula: String.raw`P(q)=100q-0.12q^2-2000`,
      data: ["P(416)=18833.28元", "P(417)=18833.32元", "P(418)=18833.12元"],
      body: ["邻近整数中417杯利润最高。", "不能仅凭四舍五入替代比较。"],
      sourceLabel: "教学情境",
      accent: "vermilion",
      teachingCue: "让学生解释为什么还列418，形成两侧核验。",
      assistantCue: "数值经确定性计算；整数候选417。"
    },
    {
      slideKey: "econ-math-l15-41",
      compositionId: "marginal-decision-manager-memo",
      section: "可执行决策",
      title: "一份边际决策摘要",
      kicker: "当前点、方向、交点、执行值",
      kind: "manager-brief",
      visual: "manager-memo",
      data: ["当前400杯：MR=40，MC=36，仍可增产", "连续候选：MR=MC于416.67杯", "两侧判别：交点左增右减", "整数执行：比较后选417杯"],
      body: ["所有结论依赖给定收益与成本函数在该区间有效。"],
      sourceLabel: "教学情境",
      accent: "green",
      teachingCue: "让学生把摘要压缩成两句话但保留模型边界。",
      assistantCue: "不把417杯推广到其他客群或日期。"
    },
    {
      slideKey: "econ-math-l15-42",
      compositionId: "marginal-analysis-boundaries",
      section: "解释与边界",
      title: "边际分析最怕三个越界",
      kicker: "局部、连续、稳定",
      kind: "evidence",
      visual: "model-boundary",
      body: ["局部越界：用一个点的边际值解释大幅变化。", "连续越界：忽略整数、批量与阶梯成本。", "模型越界：需求或成本关系在新范围内已经改变。"],
      prompt: "临时加班费在第600杯突然启动，哪一种越界最突出？",
      sourceLabel: "概念模型",
      accent: "amber",
      teachingCue: "期待连续模型遇到阶梯成本/规则跳变。",
      assistantCue: "说明需分段建模；不要自行设定加班费数值。"
    },
    {
      slideKey: "econ-math-l15-43",
      compositionId: "marginal-language-check",
      section: "解释与边界",
      title: "四句中哪句可以进报告？",
      kicker: "语言审计",
      kind: "question",
      visual: "decision-split",
      body: ["A  第501杯成本就是40元。", "B  平均每杯成本是40元。", "C  在500杯附近，每增加一杯，成本约增加40元。", "D  总成本为40元。"],
      prompt: "选择并逐项指出其他说法混淆了什么量。",
      sourceLabel: "概念模型",
      accent: "cyan",
      teachingCue: "正确C；让学生分别说精确/平均/总量错误。",
      assistantCue: "C最严谨；模型精确第501杯增量40.02元。"
    },
    {
      slideKey: "econ-math-l15-44",
      compositionId: "marginal-exit-ticket",
      section: "课堂收束",
      title: "离场题：用边际相等找候选",
      kicker: "3分钟独立作答",
      kind: "exercise",
      visual: "exercise-desk",
      formula: String.raw`C(q)=500+8q+0.02q^2,\qquad R(q)=50q-0.03q^2`,
      body: ["写出MC与MR。", "求MR=MC的产量。", "判断交点两侧利润方向。"],
      sourceLabel: "教学情境",
      accent: "ink",
      teachingCue: "计时3分钟，随后口头核对。",
      assistantCue: "MC=8+0.04q，MR=50−0.06q，候选q=420，左增右减。"
    },
    {
      slideKey: "econ-math-l15-45",
      compositionId: "elasticity-bridge",
      section: "课堂收束",
      title: "多一杯值多少，还没有回答“涨1%会怎样”",
      kicker: "下一讲：弹性",
      kind: "transition",
      visual: "chapter-bridge",
      formula: String.raw`\text{绝对变化率}\quad\longrightarrow\quad\text{百分比变化率}`,
      lead: "边际量带着原单位；下一讲将把变化率标准化为弹性，比较不同客群对价格变化的敏感程度。",
      prompt: "销量少10杯，在大客群和小客群中代表同样严重吗？",
      sourceLabel: "概念模型",
      accent: "vermilion",
      teachingCue: "只收直觉，期待“还要看原销量基数”。",
      assistantCue: "引向相对变化，不提前给弹性公式。"
    }
  ]
});
