import { defineEconomicMathematicsLesson } from "../types.js";

export const economicMathematicsLesson14 = defineEconomicMathematicsLesson({
  number: 14,
  unit: 4,
  unitTitle: "导数应用、边际与弹性分析",
  title: "峰值为何不能只看导数等于零？",
  hours: 2,
  expectedSlides: 47,
  coreQuestion: "怎样从导数为零或不存在的候选点出发，结合符号变化、端点与约束判断极值和最值？",
  exerciseCapability: "能寻找临界点、制作导数符号表、比较端点并给出有边界的最优决策。",
  slides: [
    {
      slideKey: "econ-math-l14-01",
      compositionId: "price-profit-boardroom-opening",
      section: "最优点不是一个方程",
      title: "三位分析员给出三个“最优价格”",
      kicker: "山城新饮 · 定价会",
      kind: "scene",
      visual: "editorial-scene",
      lead: "同一条利润曲线，有人只解P′(p)=0，有人选择区间中点，还有人直接选允许的最高价。",
      body: ["三个答案都可能偶然正确。", "可靠结论必须说明候选点、比较范围与最优类型。"],
      prompt: "你会要求每位分析员补交哪一项证据？",
      sourceLabel: "教学情境",
      sourceNote: "虚构定价讨论",
      accent: "vermilion",
      teachingCue: "收集“导数符号、端点利润、可行区间”等证据，不先排序。",
      assistantCue: "不要直接给70元答案；先建立判断标准。"
    },
    {
      slideKey: "econ-math-l14-02",
      compositionId: "optimal-claim-choice",
      section: "最优点不是一个方程",
      title: "P′(70)=0足以证明70元最优吗？",
      kicker: "先判断",
      kind: "question",
      visual: "decision-split",
      body: ["A  足够，导数为0就是最大值", "B  不足，还要看附近增减与可行范围", "C  不足，任何导数为0的点都不是最大值"],
      prompt: "选择，并画一条能支持你判断的简图。",
      sourceLabel: "概念模型",
      accent: "amber",
      teachingCue: "让学生画∩形、∪形或x³，比较同样水平切线的不同结局。",
      assistantCue: "正确为B；导数为0只产生候选点。"
    },
    {
      slideKey: "econ-math-l14-03",
      compositionId: "three-stationary-shapes",
      section: "最优点不是一个方程",
      title: "同样的水平切线，三种结局",
      kicker: "峰、谷、平肩",
      kind: "evidence",
      visual: "comparison-board",
      data: ["−x²在0：局部最大", "x²在0：局部最小", "x³在0：既非最大也非最小"],
      body: ["三者在0处导数都等于0。"],
      prompt: "真正区分它们的，是导数数值还是导数两侧符号？",
      sourceLabel: "自制图形",
      accent: "cyan",
      teachingCue: "要求学生写出三条曲线在0左、右的增减方向。",
      assistantCue: "关键是两侧导数符号及其变化。"
    },
    {
      slideKey: "econ-math-l14-04",
      compositionId: "local-extrema-definition",
      section: "极值与最值",
      title: "极值只比较附近",
      kicker: "局部概念",
      kind: "definition",
      visual: "formula-board",
      formula: String.raw`f(x_0)\ge f(x)\ \text{对x₀附近成立}\Rightarrow f(x_0)\text{为局部最大值}`,
      body: ["局部最小值将不等号反向。", "“附近”不要求覆盖整个定义域。", "极值点是x₀，极值是f(x₀)。"],
      sourceLabel: "教材框架",
      accent: "vermilion",
      teachingCue: "让学生区分“点”和“值”的回答格式。",
      assistantCue: "用邻域直观解释即可，不要求ε语言。"
    },
    {
      slideKey: "econ-math-l14-05",
      compositionId: "absolute-extrema-definition",
      section: "极值与最值",
      title: "最值要与整个可行集合比较",
      kicker: "全局概念",
      kind: "definition",
      visual: "comparison-board",
      formula: String.raw`f(x^*)\ge f(x)\quad\text{对所有可行x成立}`,
      body: ["绝对最大值也称最大值。", "端点可以成为最值点，却通常不称为内部极值点。", "业务“最优”通常指给定约束下的最值。"],
      sourceLabel: "教材框架",
      accent: "green",
      teachingCue: "用山峰与区域最高点区分局部峰和全局最高。",
      assistantCue: "需保留可行集合；脱离约束谈最优不完整。"
    },
    {
      slideKey: "econ-math-l14-06",
      compositionId: "fermat-necessary-condition",
      section: "候选点从哪里来",
      title: "可导的内部极值点，导数必为0",
      kicker: "费马引理",
      kind: "definition",
      visual: "formula-board",
      formula: String.raw`x_0\text{为内部极值点且}f'(x_0)\text{存在}\Rightarrow f'(x_0)=0`,
      body: ["这是必要条件：极值出现时必须满足。", "它不是充分条件：满足后未必是极值。"],
      sourceLabel: "教材框架",
      accent: "cyan",
      teachingCue: "让学生用“如果…那么…”复述，并指出箭头不能反向。",
      assistantCue: "强调内部与可导两个前提。"
    },
    {
      slideKey: "econ-math-l14-07",
      compositionId: "stationary-not-sufficient",
      section: "候选点从哪里来",
      title: "反向箭头为什么失败？",
      kicker: "x³的平肩",
      kind: "error-audit",
      visual: "error-lens",
      formula: String.raw`f(x)=x^3,\qquad f'(0)=0`,
      body: ["x<0时函数继续上升到0。", "x>0时函数仍继续上升。", "导数在0两侧没有由正变负或由负变正。"],
      prompt: "0是临界点、极值点，还是两者都是？",
      sourceLabel: "自制图形",
      accent: "amber",
      teachingCue: "答案为临界点但非极值点；要求说明两侧单调性。",
      assistantCue: "不要把驻点与极值点当同义词。"
    },
    {
      slideKey: "econ-math-l14-08",
      compositionId: "critical-point-definition",
      section: "候选点从哪里来",
      title: "临界点包括两类内部点",
      kicker: "候选清单",
      kind: "definition",
      visual: "variable-map",
      data: ["f′(x)=0的内部点：水平切线或平肩", "f′(x)不存在但f(x)存在的内部点：尖点、竖切线等", "闭区间端点：比较最值时另列候选"],
      body: ["临界点只是候选，最终要继续判别。"],
      sourceLabel: "教材框架",
      accent: "ink",
      teachingCue: "将“临界点”和“端点候选”分列，避免定义混用。",
      assistantCue: "端点是否称临界点依教材约定；本课程把它们作为另列最值候选。"
    },
    {
      slideKey: "econ-math-l14-09",
      compositionId: "derivative-monotonicity-link",
      section: "用符号判别极值",
      title: "导数符号就是函数行进方向",
      kicker: "正上升，负下降",
      kind: "definition",
      visual: "formula-board",
      formula: String.raw`f'(x)>0\Rightarrow f\text{递增},\qquad f'(x)<0\Rightarrow f\text{递减}`,
      body: ["在一个区间内符号保持一致，函数在该区间保持同一增减方向。"],
      sourceLabel: "教材框架",
      accent: "cyan",
      teachingCue: "用上坡、下坡手势对应正负号，再回到坐标图。",
      assistantCue: "结论要求在所讨论区间内成立，不是单点符号决定整段。"
    },
    {
      slideKey: "econ-math-l14-10",
      compositionId: "sign-chart-construction",
      section: "用符号判别极值",
      title: "临界点把数轴切成若干段",
      kicker: "导数符号表",
      kind: "derivation",
      visual: "data-ledger",
      data: ["求出临界点并按大小排列", "在每个开区间选测试点", "判断f′符号", "写出函数递增或递减", "观察临界点两侧方向是否改变"],
      sourceLabel: "教材框架",
      accent: "ink",
      teachingCue: "现场画一条空符号表，让学生提供栏标题。",
      assistantCue: "对可因式分解导数可直接判号，不强制逐点代入。"
    },
    {
      slideKey: "econ-math-l14-11",
      compositionId: "first-derivative-test",
      section: "用符号判别极值",
      title: "第一导数判别法",
      kicker: "看符号如何穿过候选点",
      kind: "definition",
      visual: "comparison-board",
      data: ["+ → −：先增后减，局部最大", "− → +：先减后增，局部最小", "+ → + 或 − → −：单调方向不变，不是极值"],
      sourceLabel: "教材框架",
      accent: "vermilion",
      teachingCue: "让学生配合手势画三种曲线，不背“左正右负”孤立口令。",
      assistantCue: "符号表需基于邻近区间，而非只取临界点值。"
    },
    {
      slideKey: "econ-math-l14-12",
      compositionId: "closed-interval-candidate-method",
      section: "用符号判别最值",
      title: "闭区间最值：内部候选还要与端点同场比较",
      kicker: "候选值比较法",
      kind: "definition",
      visual: "variable-map",
      data: ["1  求(a,b)内所有临界点", "2  计算各临界点函数值", "3  计算f(a)、f(b)", "4  在所有候选值中取最大与最小"],
      body: ["连续函数在闭区间上一定能取得最大值和最小值。"],
      sourceLabel: "教材框架",
      accent: "green",
      teachingCue: "强调“所有”候选点；提醒定义域断点需先分段。",
      assistantCue: "本页假设函数在闭区间连续。"
    },
    {
      slideKey: "econ-math-l14-13",
      compositionId: "optimization-workflow",
      section: "用符号判别最值",
      title: "业务最优题的六步链",
      kicker: "从变量到建议",
      kind: "definition",
      visual: "data-ledger",
      data: ["定义决策变量与可行区间", "建立目标函数", "求导并列出内部候选", "用符号或二阶信息判别", "比较端点与候选值", "带回单位、约束与模型边界解释"],
      sourceLabel: "概念模型",
      accent: "cyan",
      teachingCue: "后续利润例题每完成一步就在清单旁打勾。",
      assistantCue: "不允许跳过可行区间直接报告驻点。"
    },
    {
      slideKey: "econ-math-l14-14",
      compositionId: "segment-a-profit-model",
      section: "例题一：A客群定价",
      title: "从需求函数建立利润函数",
      kicker: "价格可行区间[20,100]",
      kind: "worked-example",
      visual: "data-ledger",
      formula: String.raw`q_A=1200-10p,\quad c=20,\quad F=2000`,
      body: ["利润=销售收入−变动成本−固定成本。", "价格p限制在20至100元。"],
      prompt: "先独立写出P_A(p)，再展开化简。",
      sourceLabel: "教学情境",
      sourceNote: "山城新饮虚构A客群模型",
      accent: "vermilion",
      teachingCue: "检查学生是否把单位成本乘以销量。",
      assistantCue: "正确P_A(p)=(p−20)(1200−10p)−2000。"
    },
    {
      slideKey: "econ-math-l14-15",
      compositionId: "segment-a-profit-derivative",
      section: "例题一：A客群定价",
      title: "内部候选价格为70元",
      kicker: "先求驻点",
      kind: "solution",
      visual: "formula-board",
      formula: String.raw`P_A(p)=-10p^2+1400p-26000,\quad P_A'(p)=-20p+1400=0\Rightarrow p=70`,
      body: ["70位于(20,100)内，因此进入候选清单。"],
      sourceLabel: "教学情境",
      accent: "cyan",
      teachingCue: "让学生核对展开的常数项−26000。",
      assistantCue: "单位成本与固定成本计算后常数项为−26000。"
    },
    {
      slideKey: "econ-math-l14-16",
      compositionId: "segment-a-sign-chart",
      section: "例题一：A客群定价",
      title: "70元左增右减",
      kicker: "第一导数判别",
      kind: "solution",
      visual: "comparison-board",
      data: ["20<p<70：P′(p)>0，利润递增", "p=70：P′(p)=0", "70<p<100：P′(p)<0，利润递减"],
      body: ["70元是区间内部的局部最大点。"],
      sourceLabel: "概念模型",
      accent: "green",
      teachingCue: "让学生用测试点或一次函数符号解释两段。",
      assistantCue: "局部最大尚需与端点比较才能称区间最大。"
    },
    {
      slideKey: "econ-math-l14-17",
      compositionId: "segment-a-candidate-values",
      section: "例题一：A客群定价",
      title: "把70元与两个端点同表比较",
      kicker: "候选值表",
      kind: "solution",
      visual: "data-ledger",
      data: ["p=20：P=−2000元", "p=70：P=23000元", "p=100：P=14000元"],
      body: ["闭区间[20,100]上的最大利润为23000元。"],
      sourceLabel: "教学情境",
      accent: "green",
      teachingCue: "让学生用原始因式形式复核P(70)，减少展开代入错误。",
      assistantCue: "P(70)=(50)(500)−2000=23000。"
    },
    {
      slideKey: "econ-math-l14-18",
      compositionId: "segment-a-manager-result",
      section: "例题一：A客群定价",
      title: "模型建议：A客群价格70元",
      kicker: "最优并非无条件",
      kind: "manager-brief",
      visual: "manager-memo",
      lead: "在需求关系q_A=1200−10p、单位成本20元、固定成本2000元及价格区间[20,100]不变时，利润模型在p=70元取得最大值23000元。",
      body: ["对应销量500杯。", "真实执行前仍需核查线性需求关系在70元附近是否可信。"],
      sourceLabel: "教学情境",
      accent: "vermilion",
      teachingCue: "让学生圈出建议中的四个前提与两个结果。",
      assistantCue: "不要将该教学模型结果推广为真实市场建议。"
    },
    {
      slideKey: "econ-math-l14-19",
      compositionId: "segment-b-price-cap-task",
      section: "例题二：驻点在区间外",
      title: "若价格上限只有80元呢？",
      kicker: "B客群受价格规则约束",
      kind: "worked-example",
      visual: "worked-grid",
      formula: String.raw`q_B=900-6p,\quad P_B(p)=(p-20)(900-6p)-2000,\quad p\in[30,80]`,
      prompt: "求无约束驻点，并判断它能否成为可行候选。",
      sourceLabel: "教学情境",
      sourceNote: "山城新饮虚构B客群模型",
      accent: "amber",
      teachingCue: "强调先算驻点，再立即检查区间。",
      assistantCue: "展开P_B=-6p²+1020p−20000；驻点85不在区间。"
    },
    {
      slideKey: "econ-math-l14-20",
      compositionId: "segment-b-outside-stationary",
      section: "例题二：驻点在区间外",
      title: "85元不可行",
      kicker: "代数根不等于决策候选",
      kind: "solution",
      visual: "formula-board",
      formula: String.raw`P_B'(p)=-12p+1020=0\Rightarrow p=85\notin[30,80]`,
      body: ["85元是延长后的模型曲线驻点。", "它违反当前价格上限，不能作为本问题答案。"],
      sourceLabel: "概念模型",
      accent: "vermilion",
      teachingCue: "让学生在85上画删除线，并写“不可行”。",
      assistantCue: "不可把85投影或四舍五入成80；80需由边界比较得出。"
    },
    {
      slideKey: "econ-math-l14-21",
      compositionId: "segment-b-monotone-feasible",
      section: "例题二：驻点在区间外",
      title: "整个可行区间都在上升",
      kicker: "导数符号给方向",
      kind: "solution",
      visual: "coordinate-plot",
      formula: String.raw`p\in[30,80]\Rightarrow P_B'(p)=-12p+1020\ge60>0`,
      body: ["利润在整个可行区间单调递增。", "因此最大值必在右端点p=80。"],
      sourceLabel: "自制图形",
      accent: "cyan",
      teachingCue: "让学生解释为什么不必逐点比较区间内所有价格。",
      assistantCue: "在p=80导数60仍为正；区间内无内部临界点。"
    },
    {
      slideKey: "econ-math-l14-22",
      compositionId: "segment-b-endpoint-values",
      section: "例题二：驻点在区间外",
      title: "端点核验确认80元",
      kicker: "边界最优",
      kind: "solution",
      visual: "data-ledger",
      data: ["p=30：P_B=5200元", "p=80：P_B=23200元", "区间最大：23200元"],
      sourceLabel: "教学情境",
      accent: "green",
      teachingCue: "让学生核算p=80时销量420杯、单位贡献60元。",
      assistantCue: "P_B(80)=60×420−2000=23200。"
    },
    {
      slideKey: "econ-math-l14-23",
      compositionId: "boundary-optimum-manager",
      section: "例题二：驻点在区间外",
      title: "边界最优意味着“约束正在起作用”",
      kicker: "管理含义",
      kind: "manager-brief",
      visual: "manager-memo",
      body: ["模型在80元处仍有上升趋势。", "若放宽价格上限，模型建议可能继续提高价格，直至85元附近。", "是否放宽上限属于新的业务问题，不能由原优化题自动决定。"],
      sourceLabel: "教学情境",
      accent: "amber",
      teachingCue: "让学生区分数学信号“约束活跃”与管理决定“放宽约束”。",
      assistantCue: "不得直接建议突破价格规则。"
    },
    {
      slideKey: "econ-math-l14-24",
      compositionId: "nondifferentiable-penalty-task",
      section: "例题三：导数不存在也要检查",
      title: "偏离50份越多，协调成本越高",
      kicker: "尖点最小值",
      kind: "worked-example",
      visual: "coordinate-plot",
      formula: String.raw`C(x)=800+12|x-50|,\qquad x\in[30,80]`,
      body: ["x=50处函数连续但不可导。", "该点仍可能成为最小值候选。"],
      prompt: "不用求导公式，先从绝对值含义判断最低成本在哪里。",
      sourceLabel: "教学情境",
      sourceNote: "虚构排班协调成本模型",
      accent: "vermilion",
      teachingCue: "让学生说出|x−50|最小为0。",
      assistantCue: "最低点x=50，C=800。"
    },
    {
      slideKey: "econ-math-l14-25",
      compositionId: "nondifferentiable-sign-analysis",
      section: "例题三：导数不存在也要检查",
      title: "尖点左减右增",
      kicker: "不可导点两侧仍能判方向",
      kind: "solution",
      visual: "comparison-board",
      data: ["30<x<50：C′(x)=−12，成本递减", "x=50：导数不存在，成本为800", "50<x<80：C′(x)=12，成本递增"],
      body: ["方向由“− → +”改变，50是局部最小点。"],
      sourceLabel: "概念模型",
      accent: "cyan",
      teachingCue: "提醒第一导数判别关注两侧符号，不要求候选点本身导数存在。",
      assistantCue: "绝对值分段导数计算正确。"
    },
    {
      slideKey: "econ-math-l14-26",
      compositionId: "nondifferentiable-candidate-compare",
      section: "例题三：导数不存在也要检查",
      title: "端点比较后，50也是区间最小",
      kicker: "候选值表",
      kind: "solution",
      visual: "data-ledger",
      data: ["C(30)=1040", "C(50)=800", "C(80)=1160"],
      body: ["若只解C′(x)=0，本题一个候选都找不到，却会漏掉真正最小值。"],
      sourceLabel: "概念模型",
      accent: "green",
      teachingCue: "让学生把“导数不存在点”补进候选清单。",
      assistantCue: "最小值800在x=50取得。"
    },
    {
      slideKey: "econ-math-l14-27",
      compositionId: "paper-exercise-cubic-task",
      section: "纸笔练习一",
      title: "找出[-2,2]上的极值与最值",
      kicker: "独立计算 · 6分钟",
      kind: "exercise",
      visual: "exercise-desk",
      formula: String.raw`f(x)=x^3-3x,\qquad x\in[-2,2]`,
      body: ["求临界点。", "制作导数符号表并判断局部极值。", "比较端点，给出绝对最大值与最小值。"],
      sourceLabel: "教材框架",
      accent: "ink",
      teachingCue: "计时6分钟；巡视导数因式分解与端点是否齐全。",
      assistantCue: "解答页前不给结果。"
    },
    {
      slideKey: "econ-math-l14-28",
      compositionId: "cubic-exercise-critical-points",
      section: "纸笔练习一",
      title: "解答：临界点为−1与1",
      kicker: "第一步",
      kind: "solution",
      visual: "formula-board",
      formula: String.raw`f'(x)=3x^2-3=3(x-1)(x+1)=0\Rightarrow x=-1,1`,
      body: ["两个点都位于开区间(−2,2)。"],
      sourceLabel: "教材框架",
      accent: "cyan",
      teachingCue: "让学生核对是否漏掉负根。",
      assistantCue: "临界点−1和1。"
    },
    {
      slideKey: "econ-math-l14-29",
      compositionId: "cubic-exercise-sign-chart",
      section: "纸笔练习一",
      title: "解答：先增、后减、再增",
      kicker: "符号表",
      kind: "solution",
      visual: "comparison-board",
      data: ["(−2,−1)：f′>0，递增", "(−1,1)：f′<0，递减", "(1,2)：f′>0，递增"],
      body: ["x=−1为局部最大点。", "x=1为局部最小点。"],
      sourceLabel: "教材框架",
      accent: "green",
      teachingCue: "让学生用+→−与−→+核对极值类型。",
      assistantCue: "局部最大值f(−1)=2；局部最小值f(1)=−2。"
    },
    {
      slideKey: "econ-math-l14-30",
      compositionId: "cubic-exercise-absolute-values",
      section: "纸笔练习一",
      title: "解答：端点与内部点出现并列",
      kicker: "候选值比较",
      kind: "solution",
      visual: "data-ledger",
      data: ["f(−2)=−2", "f(−1)=2", "f(1)=−2", "f(2)=2"],
      body: ["绝对最大值2，在x=−1与x=2取得。", "绝对最小值−2，在x=−2与x=1取得。"],
      sourceLabel: "教材框架",
      accent: "amber",
      teachingCue: "强调最值点可能不唯一，也可能同时出现在端点和内部。",
      assistantCue: "四个函数值均正确；保留并列点。"
    },
    {
      slideKey: "econ-math-l14-31",
      compositionId: "paper-exercise-production-profit",
      section: "纸笔练习二",
      title: "产量限制下的利润最大化",
      kicker: "独立计算 · 6分钟",
      kind: "exercise",
      visual: "exercise-desk",
      formula: String.raw`P(q)=-0.02q^2+24q-3000,\qquad q\in[0,800]`,
      body: ["求内部候选产量。", "判断增减区间。", "比较候选点与端点利润。", "写一句带单位的建议。"],
      sourceLabel: "教学情境",
      sourceNote: "虚构产量—利润模型",
      accent: "vermilion",
      teachingCue: "要求利润可以为负，不能因负数就删除端点。",
      assistantCue: "内部候选q=600；最大利润4200元。"
    },
    {
      slideKey: "econ-math-l14-32",
      compositionId: "production-profit-sign-solution",
      section: "纸笔练习二",
      title: "解答：600单位左增右减",
      kicker: "候选与判别",
      kind: "solution",
      visual: "formula-board",
      formula: String.raw`P'(q)=-0.04q+24=0\Rightarrow q=600`,
      body: ["0<q<600时P′>0。", "600<q<800时P′<0。", "q=600为局部最大点。"],
      sourceLabel: "概念模型",
      accent: "cyan",
      teachingCue: "让学生在数轴上写测试点100与700的符号。",
      assistantCue: "导数与符号区间正确。"
    },
    {
      slideKey: "econ-math-l14-33",
      compositionId: "production-profit-values-solution",
      section: "纸笔练习二",
      title: "解答：最大利润4200元",
      kicker: "端点比较",
      kind: "solution",
      visual: "data-ledger",
      data: ["q=0：P=−3000元", "q=600：P=4200元", "q=800：P=3400元"],
      body: ["闭区间最大值在q=600取得。"],
      sourceLabel: "教学情境",
      accent: "green",
      teachingCue: "让同桌互查三个代入值。",
      assistantCue: "数值正确。"
    },
    {
      slideKey: "econ-math-l14-34",
      compositionId: "production-profit-manager-memo",
      section: "纸笔练习二",
      title: "建议必须把“600”放回模型",
      kicker: "业务表达",
      kind: "manager-brief",
      visual: "manager-memo",
      lead: "在给定二次利润模型与0至800单位产能范围内，模型建议产量600单位，对应最大利润4200元。",
      body: ["若实际只能按整箱生产，还需把600换算为可执行批量并比较邻近方案。", "模型未包含库存与缺货风险。"],
      sourceLabel: "教学情境",
      accent: "amber",
      teachingCue: "追问“若每箱48杯怎么办”，只要求提出比较相邻可行批次。",
      assistantCue: "不要替用户引入未给出的整箱成本；只说明离散化需重新比较。"
    },
    {
      slideKey: "econ-math-l14-35",
      compositionId: "error-audit-stationary-equals-optimum",
      section: "错因诊断",
      title: "错解一：解出f′=0就停笔",
      kicker: "必要条件被误当充分条件",
      kind: "error-audit",
      visual: "error-lens",
      formula: String.raw`f'(x_0)=0\Rightarrow x_0\text{是最大点}\quad\text{（错误）}`,
      prompt: "用一个本讲函数反驳，并补出正确检查。",
      sourceLabel: "概念模型",
      accent: "vermilion",
      teachingCue: "期待x³；再补“看两侧符号或比较候选值”。",
      assistantCue: "标准反例f=x³在0。"
    },
    {
      slideKey: "econ-math-l14-36",
      compositionId: "stationary-error-repair",
      section: "错因诊断",
      title: "修正：驻点只进入候选清单",
      kicker: "判别还没完成",
      kind: "solution",
      visual: "variable-map",
      data: ["f′=0 → 候选", "两侧符号改变 → 局部极值类型", "端点与所有候选值比较 → 闭区间最值", "可行约束检查 → 业务答案"],
      sourceLabel: "概念模型",
      accent: "green",
      teachingCue: "让学生把箭头链抄在错题旁。",
      assistantCue: "不得跳过任何与题设相关的候选。"
    },
    {
      slideKey: "econ-math-l14-37",
      compositionId: "error-audit-missing-endpoints",
      section: "错因诊断",
      title: "错解二：只比较内部点",
      kicker: "边界可能就是最优",
      kind: "error-audit",
      visual: "error-lens",
      body: ["B客群模型的无约束驻点85元不在可行区间。", "若忽略端点，会错误地说“本题无最大值”。", "连续函数在闭区间上仍会取得最大值。"],
      prompt: "本题的区间最大点在哪里？依据是什么？",
      sourceLabel: "教学情境",
      accent: "amber",
      teachingCue: "期待p=80，因为区间内单调递增且右端可行。",
      assistantCue: "答案80元。"
    },
    {
      slideKey: "econ-math-l14-38",
      compositionId: "endpoint-error-repair",
      section: "错因诊断",
      title: "修正：端点写入同一张候选值表",
      kicker: "避免凭印象补漏",
      kind: "solution",
      visual: "data-ledger",
      data: ["左端点a", "全部内部临界点", "右端点b", "不可导但函数有定义的内部点"],
      body: ["先列齐，再计算；不要边算边猜最优。"],
      sourceLabel: "概念模型",
      accent: "cyan",
      teachingCue: "让学生为前三道题各自勾选候选类型。",
      assistantCue: "对不连续点需先确认是否属于定义域与可行集合，不能机械列入。"
    },
    {
      slideKey: "econ-math-l14-39",
      compositionId: "error-audit-ignore-cusp",
      section: "错因诊断",
      title: "错解三：导数不存在就删除该点",
      kicker: "尖点可能正是极值",
      kind: "error-audit",
      visual: "error-lens",
      formula: String.raw`C(x)=800+12|x-50|`,
      body: ["x=50处导数不存在。", "但函数值存在，且两侧由减变增。", "删除它会漏掉区间最小值。"],
      sourceLabel: "概念模型",
      accent: "vermilion",
      teachingCue: "让学生用绝对值图像解释，不依赖复杂导数。",
      assistantCue: "最小点x=50。"
    },
    {
      slideKey: "econ-math-l14-40",
      compositionId: "cusp-error-repair",
      section: "错因诊断",
      title: "修正：导数不存在是“需要检查”，不是“自动排除”",
      kicker: "函数值与邻域行为仍然可比",
      kind: "solution",
      visual: "comparison-board",
      data: ["函数无定义：不能成为函数最值点", "函数有定义但导数不存在：保留并检查", "函数可导且导数为0：保留并检查"],
      sourceLabel: "概念模型",
      accent: "green",
      teachingCue: "让学生给三类各配一个例子。",
      assistantCue: "区分函数不存在与导数不存在。"
    },
    {
      slideKey: "econ-math-l14-41",
      compositionId: "continuous-vs-discrete-decisions",
      section: "解释与边界",
      title: "连续最优值可能无法直接执行",
      kicker: "价格档位、整箱与预算步长",
      kind: "evidence",
      visual: "model-boundary",
      body: ["模型允许p取任意实数，实际价格可能只能到0.1元。", "模型允许q连续变化，实际产量可能必须为整数或整箱。", "先求连续候选，再比较邻近可执行点。"],
      prompt: "连续解70.03元时，能否不比较就直接报70.0元？",
      sourceLabel: "概念模型",
      accent: "amber",
      teachingCue: "期待“不能，应比较可执行的相邻价格档位”。",
      assistantCue: "不要假设四舍五入总保持最优。"
    },
    {
      slideKey: "econ-math-l14-42",
      compositionId: "optimization-model-boundaries",
      section: "解释与边界",
      title: "曲线最优不等于市场最优",
      kicker: "模型之外还有约束",
      kind: "evidence",
      visual: "model-boundary",
      body: ["需求函数可能只在观测价格区间内可信。", "竞争反应、品牌损伤与库存风险未必进入目标函数。", "固定成本不影响一阶导数，却影响是否整体盈利。", "最优结果需配合敏感性与情境比较。"],
      sourceLabel: "概念模型",
      accent: "ink",
      teachingCue: "让学生从四条中选一条，说明它会怎样改变建议。",
      assistantCue: "不要新增未经题设支持的数值。"
    },
    {
      slideKey: "econ-math-l14-43",
      compositionId: "optimization-manager-checklist",
      section: "解释与边界",
      title: "一份可复核的最优建议",
      kicker: "五项缺一不可",
      kind: "manager-brief",
      visual: "manager-memo",
      data: ["决策变量与可行区间", "目标函数及数据来源", "全部候选点与端点", "最值数值及单位", "模型假设、不可执行因素与邻近方案"],
      body: ["“导数等于零”只能放在计算依据一栏，不能独自成为结论。"],
      sourceLabel: "概念模型",
      accent: "green",
      teachingCue: "让学生用该清单给第31题的文字建议打分。",
      assistantCue: "应优先检查可行区间和端点是否出现。"
    },
    {
      slideKey: "econ-math-l14-44",
      compositionId: "extrema-exit-ticket",
      section: "课堂收束",
      title: "离场题：极小值与端点最大值",
      kicker: "3分钟独立作答",
      kind: "exercise",
      visual: "exercise-desk",
      formula: String.raw`f(x)=x^2-4x+5,\qquad x\in[0,5]`,
      body: ["求内部临界点并判断类型。", "比较端点与临界点，给出绝对最大值和最小值。"],
      sourceLabel: "教材框架",
      accent: "vermilion",
      teachingCue: "计时3分钟；提醒最大值可能不在驻点。",
      assistantCue: "解答页前不揭示；最小值1在x=2，最大值10在x=5。"
    },
    {
      slideKey: "econ-math-l14-45",
      compositionId: "extrema-exit-solution",
      section: "课堂收束",
      title: "离场题解答：三个候选全部比较",
      kicker: "自检",
      kind: "solution",
      visual: "worked-grid",
      formula: String.raw`f'(x)=2x-4=0\Rightarrow x=2`,
      data: ["f(0)=5", "f(2)=1", "f(5)=10"],
      body: ["绝对最小值1在x=2取得。", "绝对最大值10在x=5取得。"],
      sourceLabel: "教材框架",
      accent: "green",
      teachingCue: "让学生分别圈出内部极小点和端点最大点。",
      assistantCue: "数值与点均需同时报告。"
    },
    {
      slideKey: "econ-math-l14-46",
      compositionId: "optimization-decision-route-summary",
      section: "课堂收束",
      title: "从水平切线到可靠最优",
      kicker: "本讲路线",
      kind: "manager-brief",
      visual: "variable-map",
      data: ["导数为0或不存在 → 找候选", "两侧符号变化 → 判局部峰谷", "端点与全部候选比较 → 判区间最值", "约束与单位带回 → 写业务建议"],
      sourceLabel: "概念模型",
      accent: "cyan",
      teachingCue: "让学生遮住页面，用四个动词复述：找、判、比、译。",
      assistantCue: "总结不得简化成“令导数为0”。"
    },
    {
      slideKey: "econ-math-l14-47",
      compositionId: "marginal-analysis-bridge",
      section: "课堂收束",
      title: "曲线峰值回答“在哪”，边际量回答“多一单位值多少”",
      kicker: "下一讲：边际分析",
      kind: "transition",
      visual: "chapter-bridge",
      formula: String.raw`C'(q),\quad R'(q),\quad P'(q)`,
      lead: "下一讲把导数重新翻译成边际成本、边际收益与边际利润，判断最后一单位是否值得。",
      prompt: "边际利润为正时，总利润一定已经最大吗？",
      sourceLabel: "概念模型",
      accent: "vermilion",
      teachingCue: "只收判断；正确方向是仍在上升，未必达到最大。",
      assistantCue: "边际利润为正表示局部增加产量会提高利润，不等于已最优。"
    }
  ]
});
