import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {INTERNATIONAL_MATHEMATICS_DEFINITIONS as definitions,INTERNATIONAL_MATHEMATICS_SLIDES as slides,INTERNATIONAL_MATHEMATICS_LESSONS as lessonRanges,INTERNATIONAL_MATHEMATICS_TITLE as title,INTERNATIONAL_MATHEMATICS_DECK_ID as deckId,INTERNATIONAL_MATHEMATICS_VERSION_ID as versionId,getInternationalMathematicsInteractionDefaults} from '@edu/course-content/international-mathematics';
import {InternationalMathematicsStage,MathematicsCanvas} from '../../apps/teacher-web/src/features/international-mathematics/InternationalMathematicsStage';
import {drawOpeningFilm} from '../../apps/teacher-web/src/features/international-mathematics/film-canvas';
import './style.css';
const params=new URLSearchParams(location.search),lesson=Math.max(1,Math.min(16,Number(params.get('lesson')??params.get('film')??1)));
const globals=window as any;
function Film(){useEffect(()=>{const canvas=document.querySelector('canvas')!,images={opening:new Image(),case:new Image()};const ready=Promise.all(Object.entries(images).map(([role,img])=>new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=reject;img.src=`/course-assets/international-mathematics/art/lesson-${String(lesson).padStart(2,'0')}-${role}.png`;}))).then(()=>{drawOpeningFilm(canvas,definitions[lesson-1]!,images,0);globals.imExport={ready:true,seek:(seconds:number)=>drawOpeningFilm(canvas,definitions[lesson-1]!,images,seconds),encode:async()=>{const config={codec:'vp09.00.40.08',width:1920,height:1200,bitrate:4500000,framerate:30,latencyMode:'realtime'};const supported=await VideoEncoder.isConfigSupported(config);if(!supported.supported)throw Error('VP9 encoder unavailable');let encoderError:any;const pending:Promise<unknown>[]=[];const encoder=new VideoEncoder({output:chunk=>{const bytes=new Uint8Array(chunk.byteLength);chunk.copyTo(bytes);let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const b64=btoa(binary);pending.push(globals.receiveVideoChunk(b64,chunk.timestamp,chunk.type));},error:err=>encoderError=err});encoder.configure(config);for(let frame=0;frame<2700;frame++){drawOpeningFilm(canvas,definitions[lesson-1]!,images,frame/30);const vf=new VideoFrame(canvas,{timestamp:Math.round(frame*1000000/30),duration:Math.round(1000000/30)});encoder.encode(vf,{keyFrame:frame%60===0});vf.close();if(encoder.encodeQueueSize>8)await encoder.flush();if(encoderError)throw encoderError;if(frame%90===0)await new Promise(r=>setTimeout(r,0));}await encoder.flush();await Promise.all(pending);encoder.close();return {frames:2700};}};});globals.imFilmReady=ready;},[]);return <canvas className="film-canvas" width="1920" height="1200"/>;}
function Viewer(){const [index,setIndex]=useState(Math.max(0,Math.min(slides.length-1,Number(params.get('page')??(lessonRanges.find(l=>l.number===lesson)?.slideStart??1))-1))),[optional,setOptional]=useState(true);const spec=slides[index]!;globals.imViewer={go:(i:number)=>setIndex(i-1),index:index+1,lessons:lessonRanges};const move=(step:number)=>{let next=index+step;while(next>=0&&next<slides.length&&!optional&&slides[next]?.optionalChallenge)next+=step;if(next>=0&&next<slides.length)setIndex(next);};useEffect(()=>{const key=(e:KeyboardEvent)=>{if(['INPUT','SELECT','TEXTAREA'].includes((e.target as HTMLElement).tagName))return;if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1);};addEventListener('keydown',key);return()=>removeEventListener('keydown',key);},[index,optional]);const frame={deckId,versionId,slideId:spec.slideKey,index:index+1,total:slides.length,logicalWidth:1600 as const,logicalHeight:1000 as const,aspectRatio:'16:10' as const,title:spec.title,lessonNumber:spec.lesson,lessonTitle:spec.lessonTitle,section:spec.kicker,summary:spec.question??spec.title};return <div className="viewer"><nav className="viewer-nav"><strong>CALCULUS / ECONOMICS + BUSINESS</strong><select aria-label="Lesson" value={spec.lesson} onChange={e=>setIndex((lessonRanges.find(l=>l.number===Number(e.target.value))?.slideStart??1)-1)}>{definitions.map(l=><option value={l.number} key={l.number}>{String(l.number).padStart(2,'0')} · {l.title}</option>)}</select><select aria-label="Teaching hour" value={spec.pedagogy?.hour??2} onChange={e=>{const h=lessonRanges.find(l=>l.number===spec.lesson)?.hourRanges?.find(h=>h.number===Number(e.target.value));if(h)setIndex(h.slideStart-1);}}>{lessonRanges.find(l=>l.number===spec.lesson)?.hourRanges?.map(h=><option key={h.number} value={h.number}>Hour {h.number} · {h.title}</option>)}</select><button onClick={()=>move(-1)} disabled={index===0}>Previous</button><span>{spec.localIndex} / {spec.localTotal}</span><button onClick={()=>move(1)} disabled={index===slides.length-1}>Next</button><label><input type="checkbox" checked={optional} onChange={e=>setOptional(e.target.checked)}/> Optional challenges</label></nav><main><InternationalMathematicsStage key={spec.slideKey} frame={frame} interaction={null} readOnly={false} playbackMode="offline"/></main><div className="viewer-info"><span>32 academic hours · English · Jacques, 9th edition</span><a href="/documents/course-syllabus-and-textbook-map.pdf" target="_blank">Syllabus + textbook map</a><a href="/documents/english-exercise-workbook.pdf" target="_blank">Exercises</a></div></div>;}
if(params.has('film'))document.body.className='film';
const content=params.has('film')?<Film/>:params.has('print')?<div className="print-pages">{slides.filter(s=>!params.has('lesson')||s.lesson===lesson).map(spec=><MathematicsCanvas key={spec.slideKey} spec={spec} values={{...getInternationalMathematicsInteractionDefaults(spec.slideKey),revealed:false}}/>)}</div>:<Viewer/>;
document.title=title;createRoot(document.getElementById('root')!).render(content);
