import './features/port-expansion/port-expansion.css';
import {StrictMode,useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {PORT_EXPANSION_SLIDES,PORT_EXPANSION_SOURCES,EXPANSION_DEFAULT,EXPANSION_TITLES,expansionTiming,expansionStateValid,type ExpansionPresentation} from '@edu/course-content';
import {PortExpansionControls,PortExpansionStage} from './features/port-expansion/PortExpansionStage';
const params=new URLSearchParams(location.search),safe=(n:number)=>Number.isInteger(n)?Math.max(1,Math.min(48,n)):1;
function Preview(){
 const [lesson,setLesson]=useState<7|8>(params.get('lesson')==='8'?8:7),[n,setN]=useState(safe(Number(params.get('page')??1))),[projection,setProjection]=useState(params.get('projection')==='1');
 const student=params.get('student')==='1',follower=params.get('projection')==='1',scope=params.get('channel')??'port-expansion';
 const [presented,setPresented]=useState<ExpansionPresentation&{slideKey:string}>({...EXPANSION_DEFAULT,slideKey:''});
 const page=PORT_EXPANSION_SLIDES.find(p=>p.lesson===lesson&&p.localPage===n)!,state=presented.slideKey===page.slideKey?presented:{...EXPANSION_DEFAULT,progress:student?1:0};
 const current=useRef({lesson,n,state}),channel=useRef<BroadcastChannel|null>(null);current.current={lesson,n,state};
 useEffect(()=>{if(student||typeof BroadcastChannel==='undefined')return;const c=new BroadcastChannel('port-expansion:'+scope);channel.current=c;c.onmessage=({data})=>{const p=PORT_EXPANSION_SLIDES.find(p=>p.lesson===data?.lesson&&p.localPage===data?.n);if(follower&&data?.type==='state'&&p&&expansionStateValid(p,data.state)){setLesson(p.lesson);setN(p.localPage);setPresented({...data.state,slideKey:p.slideKey});}if(!follower&&data?.type==='ready')c.postMessage({type:'state',...current.current});};if(follower)c.postMessage({type:'ready'});return()=>{channel.current=null;c.close();};},[scope,follower,student]);
 useEffect(()=>{const url=new URL(location.href);url.searchParams.set('lesson',String(lesson));url.searchParams.set('page',String(n));history.replaceState(null,'',url);if(!follower&&!student)channel.current?.postMessage({type:'state',...current.current});},[lesson,n,presented,student,follower]);
 useEffect(()=>{if(follower)return;const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,select,button,a,textarea'))return;if(['ArrowRight','PageDown'].includes(e.key)){e.preventDefault();setN(v=>safe(v+1));}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();setN(v=>safe(v-1));}if(e.key==='Escape')setProjection(false);};addEventListener('keydown',key);return()=>removeEventListener('keydown',key);},[follower]);
 const timing=expansionTiming(lesson),block=timing.find(t=>page.index>=t.slideStart&&page.index<=t.slideEnd)!,elapsed=timing.slice(0,timing.indexOf(block)).reduce((s,t)=>s+t.minutes,0),source=PORT_EXPANSION_SOURCES[page.source];
 return <PortExpansionControls.Provider value={{scope:(student?'student:':'teacher:')+scope,initial:presented,onChange:(key,state)=>{const p=PORT_EXPANSION_SLIDES.find(p=>p.lesson===current.current.lesson&&p.localPage===current.current.n);if(p?.slideKey===key)setPresented({...state,slideKey:key});}}}><main className={`pe-preview${projection?' pe-preview--projection':''}${student?' pe-preview--student':''}`}>
  {!projection&&<nav className="pe-nav"><strong>港口管理概论 · 授课台</strong><select aria-label="选择讲次" value={lesson} onChange={e=>{setLesson(Number(e.target.value) as 7|8);setN(1);}}><option value="7">第7讲 · 多货种码头</option><option value="8">第8讲 · 港口演进与规划</option></select><button disabled={n===1} onClick={()=>setN(v=>v-1)}>上一页</button><select aria-label="课件页" value={n} onChange={e=>setN(Number(e.target.value))}>{PORT_EXPANSION_SLIDES.filter(p=>p.lesson===lesson).map(p=><option key={p.slideKey} value={p.localPage}>{p.localPage} / 48 · {p.title}</option>)}</select><button disabled={n===48} onClick={()=>setN(v=>v+1)}>下一页</button>{!student&&<><button onClick={()=>setProjection(true)}>本屏投影</button><a target="_blank" rel="noreferrer" href={`/port-expansion-preview.html?lesson=${lesson}&page=${n}&projection=1&channel=${encodeURIComponent(scope)}`}>另开同步投影 ↗</a></>}</nav>}
  <div className="pe-preview-body"><PortExpansionStage page={page} readOnly={projection||student} state={projection?state:student?{...EXPANSION_DEFAULT,progress:1}:undefined}/>{!projection&&!student&&<aside className="pe-guide" aria-label="教师讲稿"><h2>第{lesson}讲教师授课台</h2><p>{EXPANSION_TITLES[lesson]}</p><p>{elapsed}—{elapsed+block.minutes}分钟 · {block.label}</p><h3>本页讲授与操作</h3><p>{page.teachingCue}</p>{page.reveal&&<details><summary>本页参考解析</summary><p>{page.reveal}</p></details>}<details><summary>90分钟进度</summary>{timing.map(t=><button key={t.label} onClick={()=>setN(t.slideStart-(lesson===7?293:341))}>{t.label} · {t.minutes}分钟</button>)}</details><details><summary>来源与助手边界</summary><p className="pe-guide-source"><a href={source.url} target="_blank" rel="noreferrer">{source.label}</a> · {source.date}</p><p>{page.assistantCue}</p></details><p>第24页后课间。教师控制演示；个人口头或纸面判断，无自动提交。</p></aside>}</div>
 </main></PortExpansionControls.Provider>;
}
createRoot(document.getElementById('root')!).render(<StrictMode><Preview/></StrictMode>);
