import {useEffect,useRef,useState} from 'react';
import type {StudySession} from '@edu/contracts';
import {getCourseDeckByCourseId} from '@edu/course-content/deck-registry';
import {api} from '../../api';
import {decodePcm16Base64} from './study-utils';

interface Props {courseId:string;globalIndex:number;onNavigate:(index:number)=>void;}
export function EnglishReadingAssistant({courseId,globalIndex,onNavigate}:Props){
 const [question,setQuestion]=useState(''),[answer,setAnswer]=useState('Ask about this page, or request a lesson or page.'),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[speak,setSpeak]=useState(false),[recording,setRecording]=useState(false);
 const session=useRef<StudySession|undefined>(undefined),turn=useRef<AbortController|undefined>(undefined),audio=useRef<AudioContext|undefined>(undefined),audioStart=useRef(0),sources=useRef(new Set<AudioBufferSourceNode>()),recorder=useRef<MediaRecorder|undefined>(undefined),stream=useRef<MediaStream|undefined>(undefined),speakRef=useRef(false),indexRef=useRef(globalIndex);indexRef.current=globalIndex;speakRef.current=speak;
 const silence=()=>{for(const source of sources.current){try{source.stop();}catch{}}sources.current.clear();audioStart.current=0;};
 useEffect(()=>()=>{turn.current?.abort();recorder.current?.stop();stream.current?.getTracks().forEach(track=>track.stop());silence();void audio.current?.close();},[courseId]);
 const ensureSession=async()=>{if(!session.current)session.current=await api.createStudySession({courseId});const deck=getCourseDeckByCourseId(courseId)!;const slide=deck.getSlide(indexRef.current);session.current=await api.updateStudyProgress(session.current.id,{deckVersion:deck.versionId,slideKey:slide.slideKey,globalIndex:slide.index});return session.current;};
 const playChunk=(base64:string)=>{if(!speakRef.current||!audio.current)return;const context=audio.current,samples=decodePcm16Base64(base64),buffer=context.createBuffer(1,samples.length,24000);buffer.getChannelData(0).set(samples);const source=context.createBufferSource();source.buffer=buffer;source.connect(context.destination);const start=Math.max(context.currentTime+.02,audioStart.current);audioStart.current=start+buffer.duration;sources.current.add(source);source.onended=()=>sources.current.delete(source);source.start(start);};
 async function ask(){if(!question.trim()||busy)return;turn.current?.abort();silence();const controller=new AbortController();turn.current=controller;setBusy(true);setNotice('Thinking…');setAnswer('');try{const current=await ensureSession();await api.streamStudyAssistantTurn(current.id,{text:question.trim(),source:'text'},event=>{if(event.type==='dialogue.delta')setAnswer(event.accumulated);if(event.type==='speech.chunk')playChunk(event.audioBase64);if(event.type==='navigation.command'&&event.result.status==='applied'){session.current=event.result.session;onNavigate(event.result.session.globalIndex);}if(event.type==='turn.failed')throw new Error('Assistant unavailable');if(event.type==='turn.completed')setNotice(event.speechStatus==='unavailable'&&speakRef.current?'Answer ready. Speech is unavailable.':'Answer ready.');},controller.signal);}catch(error){if(!controller.signal.aborted)setNotice('The assistant is unavailable. Check your connection and try again.');}finally{setBusy(false);}}
 async function record(){if(recording){recorder.current?.stop();return;}setNotice('');try{const current=await ensureSession();stream.current=await navigator.mediaDevices.getUserMedia({audio:true});const capture=new MediaRecorder(stream.current),parts:BlobPart[]=[];recorder.current=capture;capture.ondataavailable=e=>{if(e.data.size)parts.push(e.data);};const started=performance.now();capture.onstop=()=>{setRecording(false);stream.current?.getTracks().forEach(track=>track.stop());const blob=new Blob(parts,{type:capture.mimeType});const reader=new FileReader();reader.onload=()=>{setNotice('Transcribing your question…');void api.transcribeStudyAudio(current.id,{audioBase64:String(reader.result).split(',')[1]!,mimeType:blob.type,durationMs:Math.min(60000,Math.max(100,Math.round(performance.now()-started)))}).then(result=>{setQuestion(result.text);setNotice('Check the transcript, then select Ask.');}).catch(()=>setNotice('Speech recognition is unavailable. Type your question instead.'));};reader.readAsDataURL(blob);};capture.start();setRecording(true);setNotice('Recording. Select Stop recording when you finish.');setTimeout(()=>{if(capture.state==='recording')capture.stop();},59000);}catch{setNotice('Microphone unavailable. Type your question instead.');setRecording(false);stream.current?.getTracks().forEach(track=>track.stop());}}
 return <details className="english-reading-assistant" lang="en"><summary>Math Guide · ask about this page</summary><div className="era-content"><p className="era-answer" aria-live="polite">{answer}</p><label className="era-question">Your question<textarea value={question} maxLength={2000} onChange={e=>setQuestion(e.target.value)} placeholder="Why does the derivative measure marginal cost?" disabled={busy}/></label><div className="era-actions"><button onClick={()=>void ask()} disabled={busy||!question.trim()}>{busy?'Thinking…':'Ask'}</button>{busy&&<button onClick={()=>{turn.current?.abort();silence();setBusy(false);setNotice('Answer stopped.');}}>Stop answer</button>}<button onClick={()=>void record()} disabled={busy}>{recording?'Stop recording':'Record question'}</button><label><input type="checkbox" checked={speak} onChange={e=>{setSpeak(e.target.checked);if(e.target.checked){audio.current??=new AudioContext();void audio.current.resume().catch(()=>setNotice('Enable audio in your browser to hear the answer.'));}else silence();}}/>Read answer aloud</label><span role="status">{notice}</span></div></div></details>;
}
