import type {MathematicsLesson} from '../types.js';
import {page,source,text,math,art,plot,table,diagram} from '../authoring.js';
const ref=source('6.1',484,498);
export const lesson13:MathematicsLesson={
 number:13,title:'Antiderivatives: Recovering a Missing Total',filmTitle:'Recover the Missing Total',openingQuestion:'Does a marginal-cost curve determine the whole cost bill?',
 outcomes:['Find basic polynomial antiderivatives and verify them.','Explain the constant of integration.','Recover a total-cost function from marginal cost and an initial value.'],
 vocabulary:[['antiderivative','A function whose derivative equals a given function.'],['indefinite integral','The family of antiderivatives of a function.'],['integration constant','An arbitrary constant accounting for different levels.'],['initial value','A known function value at a specified input.'],['verification','Checking an antiderivative by differentiation.'],['total-cost level','The full cost at a specified output.']],sources:[ref],
 slides:[
 page(13,'01','Recover the missing total','OPENING SCENE',ref,[art('opening',790,230,710,560,'A paper receipt with a missing total and a rising rate curve'),text('The rate is known.\nThe original bill is missing.',80,295,650,160,49),math('MC(q)=20+q',90,595,650,100,64)],{openingFilm:true,publicLabel:'Teaching scenario',question:'Can a rate tell us the total without one starting value?',teachingCue:'暂停视频，让学生寻找缺失的起点信息。',assistantCue:'Do not infer a unique total-cost level from marginal cost alone.'}),
 page(13,'02','Turn differentiation around','REVERSE THE TOOL',ref,[diagram('flow',['Total cost C(q)','Differentiate','Marginal cost 20+q'],100,275,1330,210),text('Now ask for a function whose derivative is 20 + q.',110,660,1300,105,39)],{question:'Which operation moves back from a derivative?',answer:'Finding an antiderivative.',teachingCue:'用逆向箭头连接微分，不说简单除法。',assistantCue:'Describe antidifferentiation as finding a function with the required derivative.'}),
 page(13,'03','A first candidate','CHECK BY DIFFERENTIATION',ref,[math('F(q)=20q+\\frac12q^2',90,295,1390,130,65),math('F^{\\prime}(q)=20+q',100,555,1340,110,68)],{question:'Does this derivative recover the given marginal cost?',answer:'Yes.',teachingCue:'先验证候选后引入积分符号。',assistantCue:'Check term-by-term differentiation.'}),
 page(13,'04','Another candidate also works','A DIFFERENT LEVEL',ref,[math('G(q)=100+20q+\\frac12q^2',90,300,1390,130,57),math('G^{\\prime}(q)=20+q',100,560,1340,100,67)],{question:'Why does the extra 100 disappear?',answer:'A constant has derivative zero.',teachingCue:'强调导数丢失常数信息。',assistantCue:'A different constant shifts the level but not the derivative.'}),
 page(13,'05','Same slopes, different heights','A FAMILY OF CURVES',ref,[plot({xRange:[0,20],yRange:[0,800],xLabel:'Output q',yLabel:'Cost (€)',curves:[{kind:'polynomial',coefficients:[0,20,0.5],color:'blue',label:'F'}, {kind:'polynomial',coefficients:[100,20,0.5],color:'coral',label:'G'}]},70,230,1000,570),text('The vertical gap is €100.\nThe slopes match at every q.',1120,350,380,180,34)],{question:'Does matching marginal cost imply matching total cost?',answer:'No. Total levels can differ by a constant.',teachingCue:'图中两曲线高度差与导数相同对应。',assistantCue:'For connected intervals, equal derivatives imply a constant difference.'}),
 page(13,'06','The integration constant stores the gap','GENERAL ANSWER',ref,[math('\\int(20+q)\\,dq=20q+\\frac12q^2+K',90,300,1390,150,59),text('K is an arbitrary constant.\nAn indefinite integral is a family.',110,635,1300,145,43)],{question:'Why use K rather than another cost function C?',answer:'It keeps the constant distinct from the total-cost symbol C(q).',teachingCue:'全课常数用K避免C函数与C常数混淆。',assistantCue:'Use K for the integration constant in cost examples.'}),
 page(13,'07','Read the integral notation','SYMBOLS',ref,[math('\\int f(x)\\,dx=F(x)+K',90,300,1390,150,75),diagram('flow',['Integrand f(x)','Variable x','Antiderivative family'],100,630,1330,155)],{question:'How can you verify the right-hand side?',answer:'Differentiate it with respect to x.',teachingCue:'符号对应操作，避免把不定积分当面积数。',assistantCue:'An indefinite integral denotes a function family, not a definite area value.'}),
 page(13,'08','Increase the power, then divide','POWER RULE',ref,[math('\\int x^n\\,dx=\\frac{x^{n+1}}{n+1}+K,\\quad n\\ne-1',90,290,1400,160,55),text('Core examples use nonnegative integer powers.',110,670,1300,90,40)],{question:'What makes n=−1 exceptional?',answer:'The denominator n+1 would be zero.',teachingCue:'明确例外，本课主线不含对数积分。',assistantCue:'State n≠−1 and use polynomial powers in the core route.'}),
 page(13,'09','Integrate x squared','WORKED EXAMPLE',ref,[math('\\int x^2\\,dx=\\frac{x^3}{3}+K',90,300,1390,130,74),math('\\frac{d}{dx}\\left(\\frac{x^3}{3}+K\\right)=x^2',100,565,1340,120,60)],{publicLabel:'Worked example',question:'Why divide by three?',answer:'Differentiating x³ multiplies by three, so division reverses it.',teachingCue:'通过求导逆检查法则。',assistantCue:'Explain the coefficient through differentiation rather than memorization alone.'}),
 page(13,'10','Constants integrate to lines','A SIMPLE CASE',ref,[math('\\int 5\\,dx=5x+K',90,300,1390,140,78),text('A constant rate produces a linear change.',110,655,1300,105,42)],{question:'Why is the answer not just 5?',answer:'The derivative of 5 is zero; the derivative of 5x is 5.',teachingCue:'常数项积分易漏x，直接核验。',assistantCue:'Correct the missing variable using derivative verification.'}),
 page(13,'11','Keep constant multipliers','LINEARITY',ref,[math('\\int 6x^2\\,dx=6\\frac{x^3}{3}+K',90,300,1390,130,64),math('=2x^3+K',100,560,1340,100,73)],{question:'What remains unchanged outside the integral?',answer:'The constant multiplier 6.',teachingCue:'常数倍法则与幂规则分步。',assistantCue:'Treat six as a constant multiplier.'}),
 page(13,'12','Integrate a sum term by term','LINEARITY',ref,[math('\\int(6x^2+4x+3)\\,dx',90,285,1390,130,70),math('=2x^3+2x^2+3x+K',100,565,1340,120,67)],{question:'How many arbitrary constants are needed in the final expression?',answer:'One combined arbitrary constant.',teachingCue:'各项常数最终合并为一个K。',assistantCue:'Use one combined constant after term-by-term integration.'}),
 page(13,'13','Verify every term','CHECK THE RESULT',ref,[table(['Antiderivative term','Derivative'],[['2x³','6x²'],['2x²','4x'],['3x','3'],['K','0']],90,250,1400,420)],{question:'Which check catches a missing linear term?',answer:'The derivative would omit the constant term 3.',teachingCue:'表格逐项核验，所有题可用该方法。',assistantCue:'Compare the full derivative with the original integrand.'}),
 page(13,'14','One known value fixes the level','INITIAL CONDITION',ref,[art('case',80,240,510,520,'Receipt with a fixed-cost label and an empty total line'),math('C(0)=100',680,325,830,110,70),text('At zero output, cost is €100.',680,620,800,100,41)],{question:'What information is new compared with MC alone?',answer:'A total-cost level at one specified output.',teachingCue:'初值补回导数丢失的信息。',assistantCue:'Use the given initial condition, not an assumed zero fixed cost.'}),
 page(13,'15','Solve for the constant','RECOVER COST',ref,[math('C(q)=20q+\\frac12q^2+K',90,300,1390,130,65),math('C(0)=K=100',100,565,1340,110,70)],{question:'What total-cost function follows?',answer:'C(q)=100+20q+0.5q².',teachingCue:'代入指定点求K再写完整函数。',assistantCue:'Check both the derivative and the initial value.'}),
 page(13,'16','Now a total can be calculated','USE THE FUNCTION',ref,[math('C(10)=100+200+50=350',90,300,1390,130,62),text('The initial cost is included.\nThe marginal curve alone would omit that level.',110,620,1300,150,40)],{question:'Which part of €350 comes from the initial value?',answer:'€100.',teachingCue:'区分初始总量与后续累计变化。',assistantCue:'Explain the fixed-cost contribution without calling it a marginal cost.'}),
 page(13,'17','A known value need not be at zero','ANOTHER INITIAL CONDITION',ref,[math('MC(q)=20+q,\\quad C(10)=350',90,300,1390,120,57),math('350=200+50+K\\Rightarrow K=100',100,555,1340,120,55)],{question:'Can a cost value at q=10 still determine K?',answer:'Yes. Any one known value in the connected domain can fix the constant.',teachingCue:'初值不一定为零点，代入所在点即可。',assistantCue:'Use the stated q=10 value; do not substitute it as q=0.'}),
 page(13,'18','Recover revenue from its rate','TRANSFER',ref,[math('MR(q)=100-2q',90,300,1390,110,68),math('R(q)=100q-q^2+K',100,555,1340,110,64),text('If R(0)=0, then K=0.',110,735,1300,60,42)],{question:'Which condition makes the revenue constant zero?',answer:'R(0)=0.',teachingCue:'不默认全部积分常数为零，给定条件才消去。',assistantCue:'Derive K=0 from the explicit zero-sales revenue condition.'}),
 page(13,'19','Recover profit carefully','TWO STARTING LEVELS',ref,[math('\\pi^{\\prime}(q)=80-3q',90,300,1390,110,67),math('\\pi(q)=80q-1.5q^2+K',100,550,1340,120,62),text('If π(0)=−100, then K=−100.',110,740,1300,60,40)],{question:'Why is the profit constant negative here?',answer:'The firm incurs a fixed cost of 100 with no revenue at zero output.',teachingCue:'连接上一讲利润截距。',assistantCue:'Use the stated initial profit condition and distinguish profit from cost.'}),
 page(13,'20','A rate alone leaves a question open','INFORMATION CHECK',ref,[text('“MC(q) = 20 + q.\nWhat is total cost at q = 10?”',100,295,890,180,47),math('C(10)=250+K',110,620,870,100,68),art('module',1080,245,420,540,'Module visual: separate strips gathering into accumulated areas')],{question:'Is there enough information for one numerical total?',answer:'No. An initial cost or another total-cost value is needed.',teachingCue:'让信息不足成为可接受答案。',assistantCue:'Do not invent the missing constant.'}),
 page(13,'21','Repair the antiderivative','ERROR DETECTIVE',ref,[table(['Claim','Check by differentiation'],[['∫x² dx = 2x + K','Derivative is 2, not x².'],['∫4 dx = 4 + K','Derivative is 0, not 4.'],['∫(2x+3)dx = x² + K','Derivative omits 3.']],90,255,1410,405)],{question:'How can all three errors be detected without re-integrating?',answer:'Differentiate the proposed answers.',teachingCue:'反向核验作为首选排错。',assistantCue:'Give derivative-based explanations for the specified errors.'}),
 page(13,'22','A fresh cost model','GUIDED PRACTICE',ref,[math('MC(q)=6q+4,\\quad C(0)=80',90,300,1390,125,63),text('Recover C(q), then find C(5).',110,625,1300,105,45)],{question:'What are the function and cost value?',answer:'C(q)=3q²+4q+80; C(5)=175.',teachingCue:'先原函数后代初值，最后计算。',assistantCue:'Offer the polynomial antiderivative as a hint before the full reveal.'}),
 page(13,'23','Explain why one datum matters','COMMUNICATE',ref,[art('case',80,240,500,520,'A missing receipt total restored with an initial-cost tag'),text('“Marginal cost fixes the shape.\nA known total cost fixes the height.”',670,330,830,180,45),text('Both are needed for a unique cost function.',680,650,800,95,36)],{question:'Which operation loses the height information?',answer:'Differentiation removes additive constants.',teachingCue:'用shape和height简洁英文说明。',assistantCue:'Explain additive constants on a connected interval.'}),
 page(13,'24','Reverse, add K, verify, fit','EXIT CHECK',ref,[diagram('steps',['Find an antiderivative','Include K and verify','Use the known value'],100,300,1330,240),text('Never invent the starting level.',110,690,1300,85,45)],{question:'What two checks verify a recovered total function?',answer:'Its derivative matches the rate and its specified value matches the initial condition.',teachingCue:'以双检验收束。',assistantCue:'Check both derivative and initial condition.'}),
 page(13,'25','The exceptional power','OPTIONAL CHALLENGE',ref,[math('\\int\\frac1x\\,dx=\\ln|x|+K,\\quad x\\ne0',90,310,1390,140,60),text('Work on an interval that does not cross zero.',110,670,1300,90,39)],{optionalChallenge:true,question:'Why does the usual power formula fail at n=−1?',answer:'It divides by n+1=0; logarithmic differentiation supplies the replacement.',teachingCue:'作为例外选学，不成为下一讲先修。',assistantCue:'State nonzero domain and interval restriction for ln|x|.'}),
 page(13,'26','An exponential reverses too','OPTIONAL CHALLENGE',ref,[math('\\int e^{2x}\\,dx=\\frac12e^{2x}+K',90,310,1390,140,68),math('\\frac{d}{dx}\\left(\\frac12e^{2x}\\right)=e^{2x}',100,590,1340,120,59)],{optionalChallenge:true,question:'Why is the factor one-half necessary?',answer:'Differentiating e^{2x} introduces a factor of two.',teachingCue:'由链式法则检查系数，复杂代换不展开。',assistantCue:'Explain the constant rate factor using the chain rule.'})
 ],
 exercises:[
 {id:'13-1',question:'Find ∫x³ dx and verify.',answer:'x⁴/4+K.',solution:'The derivative of x⁴/4+K is x³, so it is the full antiderivative family.'},
 {id:'13-2',question:'Find ∫(6x²+4x+3) dx.',answer:'2x³+2x²+3x+K.',solution:'Integrate each term using the power rule. One combined arbitrary constant suffices. Differentiation recovers 6x²+4x+3.'},
 {id:'13-3',question:'Recover C(q) when C′(q)=20+q and C(0)=100.',answer:'100+20q+0.5q².',solution:'An antiderivative is 20q+0.5q²+K. Substituting q=0 gives K=100.'},
 {id:'13-4',question:'Recover C(q) when C′(q)=6q+4 and C(0)=80. Find C(5).',answer:'C=3q²+4q+80; C(5)=175.',solution:'Integrate to 3q²+4q+K. The initial value gives K=80. At 5, cost is 75+20+80=175.'},
 {id:'13-5',question:'If MR(q)=100−2q and R(0)=0, recover revenue.',answer:'R(q)=100q−q².',solution:'Integrating gives 100q−q²+K. The zero-output condition makes K=0.'},
 {id:'13-6',question:'If C′(q)=20+q with no known cost value, can C(10) be determined?',answer:'Only C(10)=250+K can be stated.',solution:'All functions 20q+0.5q²+K have the given derivative. Without a total-cost datum the additive level is unknown.'},
 {id:'13-7',question:'Find ∫e^{2x} dx and verify.',answer:'0.5e^{2x}+K.',solution:'Differentiating 0.5e^{2x} gives 0.5×2e^{2x}=e^{2x}.',optional:true}
 ],
 teacherGuide:'90分钟：开场与原函数20；规则与核验20；常数与初值20；经济应用15；练习出口15。英文话术：“Differentiate to check.” “The derivative loses a constant.” “One known level fixes the family.” 积分常数用K，成本函数用C(q)。不给初值时允许并鼓励信息不足结论。对数、指数积分是选学，不引入繁重代换。',
 film:[
 {from:0,to:15,title:'The missing receipt',narration:'A paper receipt unfolds on a bright desk, but its total has vanished. Beside it, a curve still shows how cost changes with each unit.',caption:'The rate survives. The total is missing.',scene:'A receipt total is erased while a blue marginal-cost curve remains.'},
 {from:15,to:30,title:'Reverse the arrow',narration:'An arrow once pointed from total cost toward marginal cost. It turns around now, asking which whole function could have produced the rate we see.',caption:'Reverse the derivative.',scene:'A diagram arrow rotates from the cost-rate card back toward an empty total-cost card.'},
 {from:30,to:45,title:'More than one answer',narration:'One possible cost curve rises into view. Then another appears above it, following exactly the same slopes while keeping a constant vertical gap everywhere.',caption:'Same slopes. Different levels.',scene:'Two quadratic ribbons align in shape but stay separated by a fixed paper strip.'},
 {from:45,to:60,title:'The hidden constant',narration:'The gap becomes a movable block labelled with a constant. Differentiation removes that block, so the marginal curve cannot tell us its original height.',caption:'A constant leaves no derivative trace.',scene:'A yellow constant block slides between levels and disappears through a derivative machine.'},
 {from:60,to:75,title:'One anchor',narration:'A single known cost value drops onto the screen like an anchor. It selects one curve from the family and fixes the previously missing level.',caption:'One known value fixes the level.',scene:'An initial-value pin fastens one cost ribbon while the others fade into outline.'},
 {from:75,to:90,title:'What is still needed?',narration:'The receipt waits beside the marginal curve and the possible totals. What information must we find before we can recover one complete and reliable bill?',caption:'Can a rate determine the whole bill?',scene:'The blank receipt, curve family, and an unnumbered anchor hold under the final question.'}
 ]
};
