import type {MathematicsLesson} from '../types.js';
import {page,source,text,math,art,plot,table,diagram} from '../authoring.js';
const ref=source('6.2.1–6.2.2',503,505);
export const lesson15:MathematicsLesson={
 number:15,title:'Consumer and Producer Surplus',filmTitle:'Who Gets the Extra Value?',openingQuestion:'How is the extra value from trade shared?',
 outcomes:['Interpret consumer and producer surplus as areas.','Calculate surplus using simple definite integrals.','Distinguish producer surplus from profit when fixed costs exist.'],
 vocabulary:[['willingness to pay','The greatest amount a buyer would pay for a unit.'],['equilibrium','The price and quantity where demand meets supply.'],['consumer surplus','Willingness to pay above what buyers actually pay.'],['producer surplus','Revenue above the variable-cost area in this model.'],['total surplus','Consumer surplus plus producer surplus.'],['variable cost','Cost that changes with output.'],['fixed cost','Cost not included in the variable-cost area.']],sources:[ref],
 slides:[
 page(15,'01','Who gets the extra value?','OPENING SCENE',ref,[art('opening',790,230,710,560,'Paper market stalls with buyer and seller tokens'),text('A buyer pays less than a limit.\nA seller receives more than a unit costs.',80,285,650,190,42),text('Both can gain from the same trade.',90,615,640,115,38)],{openingFilm:true,publicLabel:'Teaching scenario',question:'Which areas represent the gains to buyers and sellers?',teachingCue:'视频停在分配问题，不先公布三角形面积。',assistantCue:'Introduce gains from trade without equating producer surplus with profit.'}),
 page(15,'02','Price on the vertical axis','INVERSE CURVES',ref,[math('D(q)=60-q,\\quad S(q)=20+q',90,300,1390,130,60),text('q: units • price: €/unit • 0 ≤ q ≤ 60\nD is willingness to pay; S is marginal cost here.',110,595,1300,155,37)],{question:'How is this graph different from a Q(P) graph?',answer:'Quantity is horizontal; price is vertical.',teachingCue:'横纵轴换位明确，需求函数用逆形式。',assistantCue:'Use D and S as inverse demand and marginal-cost supply in a simplified competitive model.'}),
 page(15,'03','Find the meeting point','EQUILIBRIUM',ref,[math('60-q=20+q',90,310,1390,120,76),math('q^*=20,\\quad p^*=40',100,555,1340,110,72)],{question:'What quantity clears this market?',answer:'20 units at €40 each.',teachingCue:'解等式得到量后再代价格。',assistantCue:'Keep equilibrium quantity and price distinct.'}),
 page(15,'04','The market graph','TWO SIDES',ref,[plot({xRange:[0,40],yRange:[0,70],xLabel:'Quantity q',yLabel:'Price (€/unit)',curves:[{kind:'polynomial',coefficients:[60,-1],color:'blue',label:'Demand'}, {kind:'polynomial',coefficients:[20,1],color:'green',label:'Supply'}],points:[{x:20,y:40,label:'Equilibrium'}]},70,230,1080,570),text('Demand slopes down.\nSupply slopes up.',1200,360,310,150,32)],{question:'Where does willingness to pay equal marginal cost?',answer:'At the intersection q=20, p=40.',teachingCue:'图上指认两曲线与交点。',assistantCue:'Read the model axes and intersection correctly.'}),
 page(15,'05','A buyer gains on early units','WILLINGNESS TO PAY',ref,[math('D(0)=60,\\quad p^*=40',90,300,1390,120,66),text('The gap between willingness to pay\nand price is a buyer benefit.',110,610,1300,145,42)],{question:'What happens to this gap as q approaches 20?',answer:'It falls to zero at the equilibrium quantity.',teachingCue:'连续曲线首点为边际愿付价，不当一位具体买家报价。',assistantCue:'Treat the demand curve as marginal willingness to pay in this continuous model.'}),
 page(15,'06','Consumer surplus is above the price line','AREA FOR BUYERS',ref,[plot({xRange:[0,40],yRange:[0,70],xLabel:'Quantity q',yLabel:'Price',curves:[{kind:'polynomial',coefficients:[60,-1],color:'blue'},{kind:'polynomial',coefficients:[40],color:'coral'}],area:{curve:0,from:0,to:20,baseline:40}},70,230,980,560),math('CS=\\int_0^{20}[D(q)-40]\\,dq',1100,355,440,160,31)],{question:'Why subtract 40 before integrating?',answer:'Buyers pay €40 for each unit, so only the excess willingness to pay counts as surplus.',teachingCue:'高度是曲线减价格，不是整个曲线下面积。',assistantCue:'Distinguish total willingness to pay from consumer surplus.'}),
 page(15,'07','Calculate the buyer area','DEFINITE INTEGRAL',ref,[math('CS=\\int_0^{20}(20-q)\\,dq',90,290,1390,135,68),math('=[20q-q^2/2]_0^{20}=200',100,555,1340,130,61)],{question:'What is the unit of CS?',answer:'Euros: euros per unit multiplied by units.',teachingCue:'上下限与单位同时核对。',assistantCue:'Use the price-gap integrand and report a currency amount.'}),
 page(15,'08','Geometry checks the integral','A TRIANGLE',ref,[math('CS=\\frac12\\times20\\times20=200',90,310,1390,135,64),diagram('flow',['Base: 20 units','Height: €20/unit','Area: €200'],100,620,1330,160)],{question:'Why does the triangle method work here?',answer:'Demand is linear and meets the horizontal price line at the endpoint.',teachingCue:'几何作独立检查，线性前提明确。',assistantCue:'Do not apply a triangle formula to arbitrary nonlinear curves.'}),
 page(15,'09','A seller gains above marginal cost','THE OTHER SIDE',ref,[art('case',80,240,500,530,'A market seller and two cost-price strips'),math('p^*-S(q)=40-(20+q)',680,315,830,130,45),text('Price exceeds marginal cost\nfor units before q = 20.',690,610,790,150,38)],{question:'Does this gap already subtract fixed cost?',answer:'No. Fixed cost is not part of the marginal-cost gap.',teachingCue:'从首次引入PS就明确固定成本边界。',assistantCue:'Do not identify this per-unit gap or its area as accounting profit.'}),
 page(15,'10','Producer surplus is below price','AREA FOR SELLERS',ref,[plot({xRange:[0,40],yRange:[0,70],xLabel:'Quantity q',yLabel:'Price',curves:[{kind:'polynomial',coefficients:[20,1],color:'green'},{kind:'polynomial',coefficients:[40],color:'coral'}],area:{curve:0,from:0,to:20,baseline:40}},70,230,980,560),math('PS=\\int_0^{20}[40-S(q)]\\,dq',1100,355,440,160,31)],{question:'Which function comes first in the positive PS integrand?',answer:'Price minus marginal-cost supply.',teachingCue:'积分高度为上减下，不把图上的签名积分当PS。',assistantCue:'The shaded gap lies below price and above supply; PS integrates 40−S(q), a positive gap.'}),
 page(15,'11','Calculate the seller area','DEFINITE INTEGRAL',ref,[math('PS=\\int_0^{20}(20-q)\\,dq',90,300,1390,130,68),math('PS=200\\text{ euros}',100,555,1340,100,74)],{question:'Why are CS and PS equal in this example?',answer:'The two linear curves have equal slope magnitudes, creating equal triangles at equilibrium.',teachingCue:'对称性只属于本例，不声称一般均分。',assistantCue:'State that equal surplus is a feature of these particular curves.'}),
 page(15,'12','Revenue is a rectangle','WHAT SELLERS RECEIVE',ref,[math('TR=p^*q^*=40\\times20=800',90,300,1390,130,63),text('All payments from buyers to sellers.\nThis is not the extra value alone.',110,620,1300,145,42)],{question:'Is the €800 revenue equal to producer surplus?',answer:'No. Producer surplus subtracts the variable-cost area.',teachingCue:'矩形支付与剩余面积分开。',assistantCue:'Revenue is a transfer payment amount; PS is revenue minus variable cost under the model.'}),
 page(15,'13','Integrate marginal cost','VARIABLE COST',ref,[math('VC(20)=\\int_0^{20}(20+q)\\,dq',90,300,1390,130,60),math('=400+200=600',100,555,1340,110,71)],{question:'Which assumption makes this the variable-cost level?',answer:'Variable cost is zero at q=0 and S(q) equals marginal cost.',teachingCue:'供应即边际成本与VC零初值同时给出。',assistantCue:'Do not infer this identity without the marginal-cost and initial-value assumptions.'}),
 page(15,'14','Revenue minus variable cost','CHECK PS A SECOND WAY',ref,[math('PS=TR-VC=800-600=200',90,310,1390,130,64),text('A second calculation agrees with the shaded area.',110,655,1300,110,40)],{question:'What has still not been subtracted?',answer:'Fixed cost.',teachingCue:'核验两种方法，提醒未扣固定成本。',assistantCue:'Use PS=TR−VC only within the stated competitive marginal-cost model.'}),
 page(15,'15','Fixed cost changes profit','PS IS NOT PROFIT',ref,[math('FC=50,\\quad TC=600+50=650',90,300,1390,125,59),math('\\pi=800-650=150',100,555,1340,110,68),text('PS = €200 • Profit = €150',110,745,1300,60,43)],{question:'Why is profit lower than producer surplus?',answer:'Profit also subtracts the €50 fixed cost.',teachingCue:'此页核心边界必须完整讲。',assistantCue:'Producer surplus equals profit plus fixed cost in this stated model.'}),
 page(15,'16','Add the two surplus areas','TOTAL SURPLUS',ref,[math('TS=CS+PS=200+200=400',90,305,1390,130,64),text('The buyer and seller gains together.\nPayments are not counted a second time.',110,615,1300,145,41)],{question:'Why not add revenue to total surplus?',answer:'Revenue is the buyers’ payment to sellers and is already accounted for in the two surplus calculations.',teachingCue:'支付转移避免重复计数。',assistantCue:'Keep gains from trade distinct from total payment revenue.'}),
 page(15,'17','The whole gap gives the same total','ONE INTEGRAL',ref,[math('TS=\\int_0^{20}[D(q)-S(q)]\\,dq',90,295,1390,140,59),math('=\\int_0^{20}(40-2q)\\,dq=400',100,555,1340,130,58)],{question:'Why does price disappear from this expression?',answer:'It cancels when buyer and seller surplus integrands are added.',teachingCue:'两高度相加取消价格，不能说价格不重要。',assistantCue:'Price cancels algebraically in the combined surplus integrand for a given allocation.'}),
 page(15,'18','Stop before the crossing','FEWER TRADES',ref,[math('\\int_0^{10}(40-2q)\\,dq=300',90,310,1390,130,63),text('The first ten units create €300 of gross gains.\nSome mutually beneficial units remain.',110,615,1300,150,40)],{question:'How much additional gross surplus do units 10 to 20 create?',answer:'€100.',teachingCue:'仅谈数量分配总增益，不擅自分配CSPS。',assistantCue:'No specific price or rationing rule is given here, so do not allocate this total between buyers and sellers.'}),
 page(15,'19','Beyond the crossing, the gap reverses','TOO MANY UNITS',ref,[math('D(25)=35<45=S(25)',90,310,1390,120,64),text('For this unit, willingness to pay\nis below marginal cost.',110,610,1300,145,44)],{question:'Why does forcing this extra unit reduce gross surplus?',answer:'Its marginal production cost exceeds its marginal willingness to pay.',teachingCue:'单边际单位解释，不加入政策因果断言。',assistantCue:'Use the model gap only; do not claim all real markets achieve efficient equilibrium.'}),
 page(15,'20','Keep the assumptions visible','PUBLIC MODEL LABEL',ref,[text('Competitive teaching model\nSupply represents marginal cost\nNo taxes or external costs included',100,295,1370,230,43),text('These assumptions support the area interpretation.',110,690,1300,85,38)],{question:'Would an external cost require additional information?',answer:'Yes. These curves alone do not measure it.',teachingCue:'短公共模型边界，不展开内部来源说明。',assistantCue:'Do not treat private surplus as complete social welfare with omitted external effects.'}),
 page(15,'21','A new pair of lines','GUIDED PRACTICE',ref,[math('D(q)=50-q,\\quad S(q)=10+q',90,310,1390,125,60),text('Find equilibrium, CS, and PS.',110,630,1300,95,44)],{question:'What are the results?',answer:'q=20, p=30, CS=200, PS=200.',teachingCue:'新数字复用流程，独立求交点后算差。',assistantCue:'Offer equilibrium-equation hints before revealing the surplus values.'}),
 page(15,'22','Add fixed cost to the new case','TRANSFER',ref,[math('TR=30\\times20=600,\\quad VC=400',90,305,1390,125,56),math('FC=80\\Rightarrow\\pi=120',100,565,1340,110,63)],{question:'What is PS in this new case?',answer:'€200, while profit is €120.',teachingCue:'再次区别PS与利润，防止一次解释后遗忘。',assistantCue:'Fixed cost changes profit but not the variable-cost-based producer surplus.'}),
 page(15,'23','Describe the gains precisely','COMMUNICATE',ref,[art('case',80,240,490,520,'A market collage with buyer and seller gain tokens'),text('“Buyers gain €200 above what they pay.\nSellers gain €200 above variable cost.\nProfit is €150 after fixed cost.”',670,310,830,240,39)],{question:'Which statement would be wrong without a fixed-cost assumption?',answer:'The numerical profit statement requires the stated €50 fixed cost.',teachingCue:'解释必须携带固定成本数据。',assistantCue:'Ground each monetary statement in the given assumptions.'}),
 page(15,'24','Find the gap, then integrate','EXIT CHECK',ref,[diagram('steps',['Find q* and p*','CS: demand minus price','PS: price minus supply'],100,280,1330,240),text('Profit also needs fixed cost.',110,690,1300,90,47)],{question:'What is the main difference between PS and profit here?',answer:'Fixed cost is deducted from PS to obtain profit.',teachingCue:'核心三步加利润边界收束。',assistantCue:'Review the area definitions and fixed-cost distinction.'}),
 page(15,'25','Unequal slopes, unequal gains','OPTIONAL CHALLENGE',ref,[math('D(q)=60-2q,\\quad S(q)=20+q',90,295,1390,125,58),math('q^*=40/3,\\quad p^*=100/3',100,540,1340,110,60)],{optionalChallenge:true,question:'Are CS and PS still equal?',answer:'No. CS=1600/9 and PS=800/9 euros.',teachingCue:'以斜率不同说明不一定均分。',assistantCue:'Use triangle heights 80/3 for CS and 40/3 for PS, each with base 40/3.'}),
 page(15,'26','Gross gains and fixed cost','OPTIONAL CHALLENGE',ref,[math('CS+PS=400,\\quad CS+\\pi=350',90,310,1390,120,61),text('A real resource fixed cost of €50\nmust be included when comparing net benefits.',110,610,1300,150,42)],{optionalChallenge:true,question:'Why distinguish gross gains from net benefits?',answer:'The usual demand–marginal-cost area omits fixed cost; net benefit depends on whether that cost is incurred and relevant.',teachingCue:'不将已沉没和新增固定成本混同；只说明需要明确比较基准。',assistantCue:'Treat fixed-cost relevance as dependent on the decision baseline; do not make an unsupported welfare claim.'})
 ],
 exercises:[
 {id:'15-1',question:'For D=60−q and S=20+q, find equilibrium.',answer:'q=20, p=40.',solution:'Set 60−q=20+q. Then 2q=40 and q=20. Both curves give price 40.'},
 {id:'15-2',question:'Calculate consumer surplus.',answer:'€200.',solution:'CS=∫₀²⁰[(60−q)−40]dq=[20q−q²/2]₀²⁰=400−200=200.'},
 {id:'15-3',question:'Calculate producer surplus.',answer:'€200.',solution:'PS=∫₀²⁰[40−(20+q)]dq=[20q−q²/2]₀²⁰=200.'},
 {id:'15-4',question:'Assume S is marginal cost and VC(0)=0. Find VC(20) and revenue.',answer:'VC=€600; revenue=€800.',solution:'VC=∫₀²⁰(20+q)dq=400+200=600. Revenue is equilibrium price times quantity: 40×20=800.'},
 {id:'15-5',question:'With fixed cost €50, find profit and compare it with PS.',answer:'Profit €150; PS €200.',solution:'Total cost is 600+50=650. Profit is 800−650=150. PS=800−600=200, so profit=PS−FC.'},
 {id:'15-6',question:'Calculate total surplus directly.',answer:'€400.',solution:'TS=∫₀²⁰[(60−q)−(20+q)]dq=[40q−q²]₀²⁰=800−400=400, matching CS+PS.'},
 {id:'15-7',question:'For D=60−2q and S=20+q, calculate CS and PS.',answer:'CS=1600/9; PS=800/9.',solution:'Equilibrium q=40/3 and p=100/3. CS triangle height is 60−100/3=80/3; PS height is 100/3−20=40/3. Half base times height gives 1600/9 and 800/9.',optional:true}
 ],
 teacherGuide:'90分钟：开场与逆需求15；均衡10；CS20；PS与VC20；利润边界10；练习出口15。英文话术：“What is the most you would be willing to pay?” “Surplus is the gap, not the whole payment.” “Supply is marginal cost in this model.” “Producer surplus is not profit when fixed cost exists.” 买方愿付价使用willing to pay，不用accept表述支付意愿。定积分上减下。CS与PS相等只因本例曲线对称。外部成本和税不在模型中，禁止把简化总剩余当完整社会福利。',
 film:[
 {from:0,to:15,title:'A market opens',narration:'Paper stalls unfold into a colourful market. Buyers arrive with private spending limits, while sellers bring goods that cost something to produce for each unit.',caption:'Trade has two sides.',scene:'Blue buyer cards and green seller cards gather around a collage stall.'},
 {from:15,to:30,title:'More than the payment',narration:'A buyer pays less than the most they would be willing to pay. The remaining gap glows above the price tag, showing a benefit beyond the payment itself.',caption:'Willingness to pay exceeds price.',scene:'A blue willingness bar stands above a coral price ribbon, leaving a highlighted gap.'},
 {from:30,to:45,title:'The seller gap',narration:'Across the stall, the same price exceeds the cost of producing an early unit. A second gap appears, this time on the seller side of trade.',caption:'Price exceeds marginal cost.',scene:'A green cost bar rests below the price ribbon and the seller gap brightens.'},
 {from:45,to:60,title:'Gaps become areas',narration:'Many small unit gaps gather into two shaded areas. One sits above the price line, while the other sits below it and above marginal cost.',caption:'Small gaps add into surplus.',scene:'Unit strips assemble into two triangles between demand, price, and supply curves.'},
 {from:60,to:75,title:'A separate bill',narration:'A fixed-cost receipt slides beneath the seller area. It reminds us that producer surplus has not yet paid every bill, so profit can be smaller.',caption:'Fixed cost still matters.',scene:'A yellow fixed-cost receipt subtracts from a green producer-surplus block.'},
 {from:75,to:90,title:'Share the gains',narration:'The market pauses where the two curves meet. How much extra value goes to buyers, how much goes to sellers, and which amount represents profit?',caption:'Who gets the extra value?',scene:'The equilibrium and unnumbered surplus areas remain beside the separate fixed-cost receipt.'}
 ]
};
