import type {MathematicsLesson} from '../types.js';
import {page,source,text,math,art,plot,table,diagram} from '../authoring.js';
const ref=source('4.3',290,303);
export const lesson09:MathematicsLesson={
 number:9,title:'Marginal Cost, Revenue, and Local Estimates',filmTitle:'One More Parcel',openingQuestion:'Can an average tell us the cost of the next parcel?',
 outcomes:['Distinguish total, average, and marginal quantities.','Compute marginal cost and marginal revenue as derivatives.','Use a derivative for a local estimate and check its limits.'],
 vocabulary:[['total cost','All cost at a specified output.'],['fixed cost','Cost incurred even at zero output.'],['average cost','Total cost divided by positive output.'],['marginal cost','The derivative of total cost with respect to output.'],['marginal revenue','The derivative of total revenue with respect to output.'],['increment','A finite change in a quantity.'],['local estimate','An approximation using behaviour near a chosen point.']],sources:[ref],
 slides:[
 page(9,'01','One more parcel','OPENING SCENE',ref,[art('opening',780,230,720,560,'Paper-cut parcel conveyor with a single additional box'),text('A warehouse has packed 20 parcels.\nOne more box arrives.',80,285,640,170,44),math('C(q)=100+20q+0.5q^2',80,570,660,100,41)],{openingFilm:true,publicLabel:'Teaching scenario',question:'Does the next box cost the same as the average box?',teachingCue:'播放后区分已有总成本与新增成本。',assistantCue:'Discuss the next parcel without revealing its cost.'}),
 page(9,'02','What does the cost model include?','READ THE MODEL',ref,[diagram('receipt',['Fixed cost','Linear cost','Rising workload'],90,270,1360,250,['100','20q','0.5q²']),text('q: parcels • C: euros • q ≥ 0',110,650,1300,70,38)],{question:'Which term remains when q=0?',answer:'The fixed cost of €100.',teachingCue:'三个项逐个对应单位和情境。',assistantCue:'Treat this as a simplified continuous cost model.'}),
 page(9,'03','Total cost at twenty','ONE OUTPUT LEVEL',ref,[math('C(20)=100+400+200=700',100,290,1310,120,58),art('case',1020,465,440,350,'Warehouse boxes beside a paper receipt'),text('Twenty parcels cost €700 in total.',110,545,830,120,42)],{question:'Does €700 describe one parcel?',answer:'No. It describes all 20 parcels together.',teachingCue:'先确认总量再进入平均量。',assistantCue:'Keep total cost separate from per-unit cost.'}),
 page(9,'04','The average shares all costs','AVERAGE COST',ref,[math('AC(q)=\\frac{C(q)}q,\\quad q>0',100,300,1320,100,57),math('AC(20)=700/20=35',110,540,1280,100,57),text('€35 per parcel includes a share of fixed cost.',110,735,1300,60,35)],{question:'Why is AC undefined at q=0?',answer:'Division by zero is undefined.',teachingCue:'补充平均量定义域；固定成本被分摊。',assistantCue:'Require q>0 for average cost.'}),
 page(9,'05','Calculate the next cost exactly','A FINITE INCREMENT',ref,[math('C(21)=740.5',100,300,1290,110,66),math('C(21)-C(20)=40.5',110,535,1290,110,62)],{question:'What is the exact additional cost of parcel 21?',answer:'€40.50.',teachingCue:'以两个总成本相减得到精确新增量。',assistantCue:'Use the discrete increment, not the derivative, for this exact answer.'}),
 page(9,'06','A slope gives a nearby rate','MARGINAL COST',ref,[math('MC(q)=C^{\\prime}(q)=20+q',90,295,1350,110,58),math('MC(20)=40',100,530,1290,100,64),text('Euros per additional unit at q = 20.',110,720,1300,65,35)],{question:'Is MC(20) a cost level or a rate?',answer:'A local rate of cost change, €40 per unit.',teachingCue:'明确导数的单位与局部意义。',assistantCue:'Define marginal cost as a derivative and distinguish it from a finite increment.'}),
 page(9,'07','The tangent touches the cost curve','LOCAL VIEW',ref,[plot({xRange:[0,40],yRange:[0,1800],xLabel:'Parcels q',yLabel:'Cost (€)',curves:[{kind:'polynomial',coefficients:[100,20,0.5],color:'blue'}],tangent:{curve:0,x:20}},70,230,1000,570),text('At q = 20,\nthe tangent slope is 40.',1130,365,365,170,36)],{question:'What does the tangent predict for a small extra quantity?',answer:'Approximately 40 euros for each extra unit near q=20.',teachingCue:'由图解释切线近似，只说邻近区间。',assistantCue:'Avoid presenting the tangent as the exact cost curve.'}),
 page(9,'08','Three numbers, three meanings','COMPARE',ref,[table(['Quantity at q=20','Value','Meaning'],[['Total cost','€700','All twenty parcels'],['Average cost','€35/unit','Cost shared per parcel'],['Marginal cost','€40/unit','Local rate for additional output']],90,260,1400,390)],{question:'Which value helps estimate a small expansion?',answer:'Marginal cost.',teachingCue:'比较表格中量纲与决策用途。',assistantCue:'Explain all three meanings without treating marginal and average costs as interchangeable.'}),
 page(9,'09','Multiply the rate by the change','LOCAL APPROXIMATION',ref,[math('\\Delta C\\approx C^{\\prime}(q)\\,\\Delta q',90,295,1370,130,64),math('\\Delta C\\approx40\\times1=40',100,560,1300,100,59)],{question:'How far is this estimate from the exact next-parcel cost?',answer:'It is €0.50 below the exact €40.50.',teachingCue:'保留近似符号，比较第5页。',assistantCue:'Use approximately rather than equals for the derivative estimate.'}),
 page(9,'10','The hidden remainder','CHECK THE ERROR',ref,[math('C(20+h)-C(20)=40h+0.5h^2',90,300,1390,120,53),text('Tangent estimate: 40h\nExtra curvature: 0.5h²',110,575,1300,150,42)],{question:'Why does the approximation improve when h shrinks?',answer:'The quadratic remainder shrinks faster than the linear term.',teachingCue:'用展开式展示本例误差，避免抽象误差理论。',assistantCue:'This remainder is exact for this quadratic cost model.'}),
 page(9,'11','Five parcels are a larger step','ESTIMATE VS EXACT',ref,[table(['Extra parcels h','Estimate (€)','Exact increase (€)'],[['1','40','40.5'],['2','80','82'],['5','200','212.5']],100,255,1350,340),text('A local rate needs a local question.',115,730,1290,70,44)],{question:'Which estimate has the largest absolute error?',answer:'The five-parcel estimate, with error €12.50.',teachingCue:'比较误差随步长增大，并指出局部前提。',assistantCue:'Discuss absolute errors and do not claim a universal acceptable step size.'}),
 page(9,'12','Revenue changes too','REVENUE MODEL',ref,[art('case',80,240,510,530,'Warehouse parcels and bright pricing tags'),math('p(q)=100-q',670,295,800,110,57),math('R(q)=q\\,p(q)=100q-q^2',670,525,840,120,49)],{question:'Why can selling more require a lower price?',answer:'This teaching demand model assumes more output is sold only at a lower price.',teachingCue:'标明教学需求假设，不当实际市场数据。',assistantCue:'Use 0≤q≤100 so the model price is nonnegative.'}),
 page(9,'13','Marginal revenue is another derivative','THE SAME TOOL',ref,[math('MR(q)=R^{\\prime}(q)=100-2q',90,300,1380,120,58),math('MR(20)=60',105,550,1300,100,66)],{question:'Why is marginal revenue below the price of €80?',answer:'Selling more in this model lowers the price on all units, not only the additional unit.',teachingCue:'解释收入变化包含已有单位降价效应。',assistantCue:'Explain the all-units price effect in the single-price model.'}),
 page(9,'14','The exact revenue increment','CHECK AGAIN',ref,[math('R(21)-R(20)=59',100,310,1330,110,60),math('MR(20)\\times1=60',110,555,1270,100,60),text('The tangent is €1 above the exact increment.',110,745,1300,60,35)],{question:'Why can a marginal estimate overestimate?',answer:'Revenue is concave here, so its tangent lies above the curve.',teachingCue:'与成本凸曲线作比较，不能只会一种误差方向。',assistantCue:'Limit the concavity explanation to this quadratic revenue function.'}),
 page(9,'15','Subtract costs from revenue','MARGINAL PROFIT',ref,[math('\\pi(q)=R(q)-C(q)',90,300,1360,100,63),math('\\pi^{\\prime}(q)=MR(q)-MC(q)',100,550,1310,110,58)],{question:'What is the local profit rate at q=20?',answer:'60−40=€20 per extra unit.',teachingCue:'先代两种边际率，再相减。',assistantCue:'Describe this as a local profit rate, not an exact next-unit profit.'}),
 page(9,'16','The next parcel adds €18.50','EXACT PROFIT CHANGE',ref,[math('\\Delta\\pi=\\Delta R-\\Delta C',100,300,1330,110,62),math('59-40.5=18.5',110,555,1290,110,65)],{question:'Why is this different from the €20 marginal estimate?',answer:'Both revenue and cost have curvature over the finite one-unit step.',teachingCue:'保持精确增量与导数近似分栏。',assistantCue:'Use exact increments when explaining the €18.50 answer.'}),
 page(9,'17','Fixed cost changes the average','WHAT STAYS THE SAME?',ref,[math('C_1(q)=100+20q+0.5q^2',90,300,900,100,51),math('C_2(q)=200+20q+0.5q^2',100,500,890,100,51),text('Both have marginal cost 20 + q.',110,730,870,60,40),art('module',1080,255,420,520,'Module visual: rates, decisions, and a geometric profit hill')],{question:'Can two firms have equal MC but different AC?',answer:'Yes. Their fixed costs can differ.',teachingCue:'对常数求导与平均成本作对应。',assistantCue:'Keep this conclusion conditional on the same variable-cost function.'}),
 page(9,'18','The model is smooth; parcels are discrete','MODEL BOUNDARY',ref,[diagram('flow',['Continuous curve','Derivative','Estimate for a small step'],100,300,1330,200),text('An indivisible parcel still has an exact increment:\nC(q+1) − C(q).',110,650,1300,150,43)],{question:'Which expression gives the exact extra cost for one indivisible unit?',answer:'C(q+1)−C(q).',teachingCue:'公开说明连续近似边界，保持短句。',assistantCue:'Do not assert that a derivative exactly measures an indivisible unit.'}),
 page(9,'19','Read a marginal-cost statement','UNITS AND LANGUAGE',ref,[text('“At 30 units, marginal cost is €50 per unit.”',100,295,1350,130,46),math('C(30+h)-C(30)\\approx50h',105,580,1330,110,52)],{question:'What does this predict for an extra 0.2 units?',answer:'Approximately €10.',teachingCue:'以可分割数量练习导数乘增量。',assistantCue:'Maintain approximation and euros-per-unit cancellation.'}),
 page(9,'20','Repair the claim','ERROR DETECTIVE',ref,[table(['Claim','What needs repair?'],[['AC(20)=35, so parcel 21 costs €35','Average cost does not give the next increment.'],['MC(20)=40, so C(20)=40','A rate is not a total.'],['MC(20)=C(21)−C(20)','The equality is only approximate here.']],90,250,1410,440)],{question:'Which claim confuses a rate and a level?',answer:'The second claim.',teachingCue:'让学生先指出类型错误再修改数值。',assistantCue:'Correct each specified claim without introducing new business assumptions.'}),
 page(9,'21','A simpler factory','GUIDED PRACTICE',ref,[math('C(q)=80+10q+q^2',100,300,1350,110,63),text('At q = 5, find total cost,\naverage cost, and marginal cost.',110,560,1300,170,43)],{question:'What are the three values?',answer:'C(5)=155; AC(5)=31; MC(5)=20.',teachingCue:'留三栏书写，核对不同单位。',assistantCue:'Provide hints until the teacher reveals the three values.'}),
 page(9,'22','Would a small expansion help?','DECISION',ref,[math('MR(20)=60,\\quad MC(20)=40',90,305,1400,120,57),text('Near 20 units, additional revenue\nexceeds additional cost.',110,585,1300,150,44)],{question:'Does this identify the globally best output?',answer:'No. It only indicates that a small increase near 20 improves profit in this model.',teachingCue:'避免将局部增益立即当最优产量。',assistantCue:'Do not infer a global optimum from one local marginal comparison.'}),
 page(9,'23','Say the conclusion precisely','COMMUNICATE',ref,[art('case',90,240,500,520,'Parcel conveyor illustration'),text('“One more unit near q = 20\nadds about €40 to cost.”',680,320,800,180,46),text('“The exact next-unit cost is €40.50.”',685,625,790,100,38)],{question:'Which word marks the derivative estimate?',answer:'About.',teachingCue:'训练about与exact的英文区分。',assistantCue:'Use about for the derivative and exact for the finite difference.'}),
 page(9,'24','Total, average, marginal','EXIT CHECK',ref,[diagram('steps',['C(q): a level','C(q)/q: a shared cost','C′(q): a local rate'],100,280,1330,230),text('Name the quantity before choosing the formula.',110,680,1310,100,43)],{question:'What is the safest first step in a cost question?',answer:'Identify whether it asks for a total, an average, a derivative, or a finite increment.',teachingCue:'四种提问类型收束，衔接利润最优课。',assistantCue:'Review quantity types and local approximation only.'}),
 page(9,'25','A shrinking change reveals the derivative','OPTIONAL CHALLENGE',ref,[math('\\frac{C(20+h)-C(20)}h=40+0.5h',90,320,1390,130,50),text('As h approaches zero,\nthe average rate approaches 40.',110,610,1310,140,42)],{optionalChallenge:true,question:'Why must h be nonzero in this quotient?',answer:'Division by h is undefined at h=0; the derivative is obtained by a limit.',teachingCue:'区分代零与取极限。',assistantCue:'Use h≠0 in the difference quotient and explain the limit.'}),
 page(9,'26','When the next-unit formula is exact','OPTIONAL CHALLENGE',ref,[math('C(q)=100+20q',100,310,1330,110,65),math('C(q+1)-C(q)=C^{\\prime}(q)=20',105,575,1330,110,55)],{optionalChallenge:true,question:'Why is the derivative exact for this one-unit change?',answer:'The cost function is linear, with no curvature.',teachingCue:'展示线性特殊情形，避免泛化。',assistantCue:'Explain exact equality through linearity rather than the size of one unit.'})
 ],
 exercises:[
 {id:'09-1',question:'For C(q)=100+20q+0.5q², find C(20) and AC(20).',answer:'€700 and €35/unit.',solution:'C(20)=100+400+200=700. AC(20)=700/20=35.'},
 {id:'09-2',question:'Find MC(q) and MC(20).',answer:'20+q; €40/unit.',solution:'Differentiate term by term: 0+20+q=20+q. At q=20 the rate is 40.'},
 {id:'09-3',question:'Calculate the exact cost increase from 20 to 21 parcels.',answer:'€40.50.',solution:'C(21)=100+420+220.5=740.5. Subtract C(20)=700 to obtain 40.5.'},
 {id:'09-4',question:'Use MC(20) to estimate the cost of five extra units. Compare with the exact change.',answer:'Estimate €200; exact €212.50.',solution:'Estimate is 40×5=200. Exact increment is 40×5+0.5×25=212.5. The underestimate is 12.5.'},
 {id:'09-5',question:'For R(q)=100q−q², find MR(20) and the exact revenue increase to q=21.',answer:'€60/unit and €59.',solution:'R′(q)=100−2q, giving 60 at 20. R(20)=1600 and R(21)=1659, so the increment is 59.'},
 {id:'09-6',question:'Using the given revenue and cost models, find the exact profit increase from q=20 to 21.',answer:'€18.50.',solution:'Exact profit increase is ΔR−ΔC=59−40.5=18.5. The derivative estimate 60−40=20 is only approximate.'},
 {id:'09-7',question:'Show the cost increment from q to q+h equals (20+q)h+0.5h².',answer:'Expand and collect terms.',solution:'C(q+h)−C(q)=20h+0.5[(q+h)²−q²]=20h+qh+0.5h²=(20+q)h+0.5h².',optional:true}
 ],
 teacherGuide:'90分钟：开场与三种量20；精确增量和导数20；切线近似15；边际收入与利润15；练习15；出口5。英文话术：“A level is not a rate.” “Average cost shares the bill; marginal cost follows the slope.” “One unit is a finite step.” 核验€40与€40.50的区别，不能称导数为精确下一件成本。连续模型下产量取实数；整数业务只使用有限差分给精确决策。',
 film:[
 {from:0,to:15,title:'A fresh parcel',narration:'A conveyor carries twenty parcels through a bright warehouse. One fresh box slides into view, and a new question interrupts the rhythm of production.',caption:'One more parcel.',scene:'Twenty cut-paper boxes move in a rhythmic grid; a coral box enters alone.'},
 {from:15,to:30,title:'The shared bill',narration:'The warehouse bill includes rent, labour, and a growing workload. Divide that whole bill among existing parcels, and an average cost appears on screen.',caption:'An average shares the whole bill.',scene:'A receipt splits into twenty tiles, with rent depicted as a broad base strip.'},
 {from:30,to:45,title:'A different question',narration:'But the next parcel asks a different question. Some costs already exist, while extra handling may become harder as the conveyor grows more crowded.',caption:'What changes when output changes?',scene:'The base rent strip stays still while handling tokens collect around the new box.'},
 {from:45,to:60,title:'A curve and a touch',narration:'A smooth cost curve rises behind the boxes. A straight line touches one point, showing the nearby rate at which total cost is changing.',caption:'A tangent gives a local rate.',scene:'Boxes morph into points on a blue quadratic curve; a coral tangent pivots into place.'},
 {from:60,to:75,title:'The small gap',narration:'Move one parcel forward along the curve. The tangent gives an estimate, while the curve gives an exact increment, leaving a small visible gap.',caption:'Estimate and exact increment differ.',scene:'A one-unit horizontal move highlights the separation between tangent and quadratic cost.'},
 {from:75,to:90,title:'Which number helps?',narration:'The new parcel waits beside the receipt. Can the average cost predict its extra cost, or should we read a different number from the curve?',caption:'Can an average predict the next cost?',scene:'Average receipt tiles and the unlabeled tangent remain on screen beside the waiting parcel.'}
 ]
};
