import type {MathematicsLesson} from '../types.js';
import {page,source,text,math,art,plot,table,diagram} from '../authoring.js';
const ref=source('4.6',329,347);const prior=source('4.2',279,289);
export const lesson10:MathematicsLesson={
 number:10,title:'Turning Points and Maximum Values',filmTitle:'When the Curve Goes Flat',openingQuestion:'Does a flat tangent always identify a maximum?',
 outcomes:['Use derivative signs to describe increasing and decreasing intervals.','Classify simple stationary points.','Compare stationary points and endpoints on a closed interval.'],
 vocabulary:[['increasing','Values rise as the input rises.'],['decreasing','Values fall as the input rises.'],['stationary point','A point where the derivative is zero.'],['local maximum','A value at least as large as nearby values.'],['local minimum','A value at most as large as nearby values.'],['endpoint','A boundary of the allowed interval.'],['second derivative','The derivative of the first derivative.']],sources:[prior,ref],
 slides:[
 page(10,'01','The curve goes flat','OPENING SCENE',ref,[art('opening',780,230,720,560,'Bright paper hills and a flat tangent ribbon'),text('A climbing path meets a flat step.\nIs this the top?',80,285,650,180,46),math('f^{\\prime}(x)=0',90,590,650,100,70)],{openingFilm:true,question:'What can happen after the slope becomes zero?',teachingCue:'暂停视频，收集继续升、下降、谷底等猜测。',assistantCue:'Do not assume zero derivative implies a maximum.'}),
 page(10,'02','A positive slope rises','DERIVATIVE SIGN',prior,[plot({xRange:[0,4],yRange:[0,10],xLabel:'x',yLabel:'f(x)',curves:[{kind:'polynomial',coefficients:[1,2],color:'blue'}]},70,230,940,550),math('f^{\\prime}(x)=2>0',1060,370,440,120,46),text('Larger x → larger f(x)',1065,610,440,80,32)],{question:'What does the positive derivative tell us?',answer:'The function is increasing on this interval.',teachingCue:'以水平向右读取曲线，配正斜率。',assistantCue:'Use positive derivative on an interval as an increasing-function test.'}),
 page(10,'03','A negative slope falls','DERIVATIVE SIGN',prior,[plot({xRange:[0,4],yRange:[0,10],xLabel:'x',yLabel:'f(x)',curves:[{kind:'polynomial',coefficients:[9,-2],color:'coral'}]},70,230,940,550),math('f^{\\prime}(x)=-2<0',1060,370,440,120,44),text('Larger x → smaller f(x)',1065,610,440,80,32)],{question:'Is a negative derivative a negative function value?',answer:'No. It means the values are decreasing; they can remain positive.',teachingCue:'区分导数符号与函数值符号。',assistantCue:'Do not confuse a negative slope with a negative height.'}),
 page(10,'04','Look on both sides','A HILL',ref,[plot({xRange:[0,4],yRange:[0,5],xLabel:'x',yLabel:'f(x)',curves:[{kind:'polynomial',coefficients:[0,4,-1],color:'blue'}],tangent:{curve:0,x:2}},70,230,970,560),math('f(x)=4x-x^2',1090,335,420,110,43),text('Rise → flat → fall',1090,565,410,110,36)],{question:'Which sign change identifies this local maximum?',answer:'Positive derivative to negative derivative.',teachingCue:'峰前峰后各读一处斜率。',assistantCue:'Classify the point using the derivative sign change.'}),
 page(10,'05','Differentiate, then solve','FIND A CANDIDATE',ref,[math('f^{\\prime}(x)=4-2x',90,310,1330,110,68),math('4-2x=0\\quad\\Rightarrow\\quad x=2',100,555,1330,110,58)],{question:'Does this equation give the maximum value or its location?',answer:'Its location. The value still requires evaluating f(2).',teachingCue:'明确x坐标与f值区别。',assistantCue:'Call x=2 a stationary candidate until classification is completed.'}),
 page(10,'06','A sign table supplies the evidence','FIRST DERIVATIVE TEST',ref,[table(['Region','x<2','x=2','x>2'],[['4−2x','Positive','Zero','Negative'],['Behaviour','Increasing','Stationary','Decreasing']],90,270,1390,290),math('f(2)=4',100,665,1300,100,65)],{question:'Why is the candidate a maximum?',answer:'Values rise before x=2 and fall after x=2.',teachingCue:'先符号表分类，再算高度。',assistantCue:'Use rise-then-fall as the justification.'}),
 page(10,'07','A valley also goes flat','A MINIMUM',ref,[plot({xRange:[0,4],yRange:[0,5],xLabel:'x',yLabel:'g(x)',curves:[{kind:'polynomial',coefficients:[4,-4,1],color:'green'}],tangent:{curve:0,x:2}},70,230,960,560),math('g(x)=(x-2)^2',1080,335,430,100,44),text('Fall → flat → rise',1080,565,420,100,36)],{question:'What sign change occurs at this minimum?',answer:'Negative derivative to positive derivative.',teachingCue:'与峰顶使用同一导数为零但不同分类。',assistantCue:'Distinguish the zero derivative condition from the sign-change classification.'}),
 page(10,'08','Find the valley with algebra','WORKED EXAMPLE',ref,[math('g^{\\prime}(x)=2x-4',90,310,1340,110,68),math('g^{\\prime}(2)=0,\\quad g(2)=0',100,550,1320,110,58),text('The derivative changes from − to +.',110,740,1300,65,38)],{publicLabel:'Worked example',question:'What is the minimum value?',answer:'Zero, attained at x=2.',teachingCue:'位置、函数值、分类三个结果分别说。',assistantCue:'Include location and value in the minimum statement.'}),
 page(10,'09','Flat can still keep climbing','COUNTEREXAMPLE',ref,[plot({xRange:[-2,2],yRange:[-8,8],xLabel:'x',yLabel:'h(x)',curves:[{kind:'polynomial',coefficients:[0,0,0,1],color:'coral'}],tangent:{curve:0,x:0}},70,230,960,560),math('h(x)=x^3',1080,330,430,100,55),math('h^{\\prime}(x)=3x^2',1080,530,430,100,44)],{question:'Is x=0 a maximum or minimum?',answer:'Neither. The function increases through zero.',teachingCue:'此页是核心反例，强调左右同号。',assistantCue:'Describe a stationary point without a local extremum.'}),
 page(10,'10','No sign change, no turn here','READ THE EVIDENCE',ref,[table(['Region','x<0','x=0','x>0'],[['3x²','Positive','Zero','Positive'],['x³','Increasing','Stationary','Increasing']],90,265,1390,310),text('Zero slope is a candidate condition.\nIt is not a classification.',110,665,1300,140,42)],{question:'What evidence rules out a local maximum at zero?',answer:'Positive derivative on both sides.',teachingCue:'回扣开场问题，反例作为判据记忆。',assistantCue:'Use the derivative sign table; do not call every flat point a turning point.'}),
 page(10,'11','The second derivative tracks slope','ANOTHER TEST',ref,[math('f^{\\prime\\prime}(x)=\\frac{d}{dx}f^{\\prime}(x)',90,300,1370,130,64),text('Negative second derivative:\nslopes decrease near the point.',110,600,1300,145,42)],{question:'For f(x)=4x−x², what is f″(x)?',answer:'−2.',teachingCue:'把二阶导数解释为斜率变化。',assistantCue:'Explain second derivative as slope change rather than function height.'}),
 page(10,'12','A quick test needs both conditions','SECOND DERIVATIVE TEST',ref,[table(['At an interior point c','Conclusion'],[['f′(c)=0 and f″(c)<0','Strict local maximum'],['f′(c)=0 and f″(c)>0','Strict local minimum'],['f′(c)=0 and f″(c)=0','This test is inconclusive']],90,260,1400,370),text('Use this test for the smooth functions in this lesson.',110,745,1300,60,34)],{question:'Why is f″(c)<0 alone insufficient to locate a maximum?',answer:'The point must also be stationary; a concave curve can still be rising there.',teachingCue:'两个条件同时核对；本课限平滑多项式。',assistantCue:'Include stationarity and smoothness; zero second derivative gives no conclusion.'}),
 page(10,'13','One candidate, two checks','VERIFY THE HILL',ref,[math('f^{\\prime}(2)=0,\\quad f^{\\prime\\prime}(2)=-2',90,310,1370,120,52),art('case',1050,515,420,285,'Paper hill with a highlighted summit'),text('Sign test: + to −\nSecond derivative test: negative',110,570,860,150,43)],{question:'Do both tests agree?',answer:'Yes. Both classify x=2 as a local maximum.',teachingCue:'相同例子用两种证据建立联系。',assistantCue:'Do not treat local classification alone as a global proof.'}),
 page(10,'14','An inconclusive test is not a failure','RETURN TO THE CUBIC',ref,[math('h(x)=x^3,\\quad h^{\\prime\\prime}(0)=0',90,310,1380,120,57),text('The second derivative test says nothing here.\nThe sign test still works.',110,590,1300,155,42)],{question:'Which earlier evidence resolves this case?',answer:'h′ is positive on both sides, so zero is neither a local maximum nor a local minimum.',teachingCue:'强调无结论不等于无极值或错误。',assistantCue:'Use the first derivative sign test to resolve the cubic example.'}),
 page(10,'15','Allowed values have boundaries','FEASIBLE INTERVAL',ref,[diagram('number-line',['0','Allowed output','3'],100,300,1330,200),math('0\\leq x\\leq3',110,620,1270,100,69)],{question:'Can a boundary be best even if its derivative is not zero?',answer:'Yes. Endpoints must be checked separately.',teachingCue:'将可行范围引入比较，不把驻点条件套端点。',assistantCue:'Explain that interior stationary conditions do not apply to endpoints.'}),
 page(10,'16','Check the candidates and endpoints','GLOBAL COMPARISON',ref,[table(['x','f(x)=4x−x²','Role'],[['0','0','Left endpoint'],['2','4','Stationary point'],['3','3','Right endpoint']],90,255,1400,390),text('On [0,3], the greatest value is 4.',110,740,1300,70,43)],{question:'What is the smallest value on this interval?',answer:'Zero at x=0.',teachingCue:'同一表同时判断全局最大与最小。',assistantCue:'Restrict the global conclusion to the closed interval [0,3].'}),
 page(10,'17','A maximum can be at the edge','NO INTERIOR STOP',ref,[plot({xRange:[0,3],yRange:[0,8],xLabel:'x',yLabel:'k(x)',curves:[{kind:'polynomial',coefficients:[1,2],color:'blue'}]},70,230,970,550),math('k(x)=1+2x',1090,335,410,110,44),text('On [0,3],\nmaximum = 7 at x = 3.',1090,565,420,150,35)],{question:'Why is solving k′(x)=0 unhelpful?',answer:'k′=2 never vanishes, while the maximum occurs at the right endpoint.',teachingCue:'端点反例防止机械解导数为零。',assistantCue:'Use monotonicity and endpoint values.'}),
 page(10,'18','A limited interval can exclude the hilltop','CHANGE THE BOUNDARY',ref,[math('f(x)=4x-x^2,\\quad0\\leq x\\leq1',90,310,1390,120,53),table(['Candidate','Value'],[['x=0','0'],['x=1','3'],['x=2','Outside the interval']],100,550,1300,220)],{question:'Where is the maximum on [0,1]?',answer:'At x=1, with value 3.',teachingCue:'排除不可行驻点，重算允许区间。',assistantCue:'Do not include x=2 as a feasible candidate.'}),
 page(10,'19','A reliable route','OPTIMIZATION STEPS',ref,[diagram('steps',['Write the interval','Solve f′=0 inside it','Compare values and endpoints'],95,280,1350,245),text('For a continuous differentiable function\non the closed interval used here.',110,660,1300,130,37)],{question:'Which step prevents an impossible answer?',answer:'Checking the feasible interval.',teachingCue:'限定本课连续且可微例子，拐角情况选学处理。',assistantCue:'This route applies to the smooth functions on closed bounded intervals in this lesson.'}),
 page(10,'20','A ticket-sales objective','BUSINESS LINK',ref,[art('case',90,240,490,510,'A paper ticket booth on a bright hill'),math('R(q)=12q-q^2,\\quad0\\leq q\\leq10',660,310,840,120,40),text('Revenue rises, then falls.\nFind the best feasible output.',670,590,800,145,42)],{question:'Which derivative locates a candidate?',answer:'R′(q)=12−2q, giving q=6.',teachingCue:'经济情境只练本页数学工具。',assistantCue:'Call q=6 a candidate before checking endpoint revenues.'}),
 page(10,'21','Compare the revenue values','GUIDED PRACTICE',ref,[table(['q','R(q)'],[['0','0'],['6','36'],['10','20']],100,280,1320,340),math('R^{\\prime\\prime}(q)=-2',110,715,1280,90,54)],{question:'What is the best revenue on [0,10]?',answer:'36 at q=6.',teachingCue:'先比较表，再用二阶导数补充局部解释。',assistantCue:'Include both feasible output and maximum value.'}),
 page(10,'22','Repair a tempting shortcut','ERROR DETECTIVE',ref,[text('“The derivative is zero,\nso this must be the maximum.”',100,280,1350,160,49),math('x^3\\text{ at }x=0',110,580,1280,100,60)],{question:'Give one counterexample to the claim.',answer:'x³ has derivative zero at zero but no maximum there.',teachingCue:'要求用具体函数驳斥，不只说不一定。',assistantCue:'Use the cubic counterexample and a sign explanation.'}),
 page(10,'23','Location, value, justification','COMMUNICATE',ref,[text('“On [0,3], the maximum occurs at x = 2.\nIts value is 4. Endpoint values are lower.”',100,310,1370,210,43),diagram('flow',['Location','Value','Evidence'],100,650,1330,150)],{question:'What is missing from “the maximum is 2”?',answer:'It confuses the maximizing location 2 with the maximum value 4.',teachingCue:'训练完整英文最优值陈述。',assistantCue:'Distinguish argmax from maximum value in plain English.'}),
 page(10,'24','Flat is a question, not an answer','EXIT CHECK',ref,[text('Positive → negative: maximum\nNegative → positive: minimum\nNo sign change: inspect further',100,285,1340,230,44),text('Then check the feasible endpoints.',110,685,1300,80,44)],{question:'What three checks follow finding a zero derivative?',answer:'Classify it, check feasibility, and compare relevant endpoint values.',teachingCue:'收束三个检查并衔接下一讲利润。',assistantCue:'Review the candidate, classification, and interval comparison.'}),
 page(10,'25','Zero second derivative can hide a minimum','OPTIONAL CHALLENGE',ref,[math('f(x)=x^4',100,305,1330,100,70),math('f^{\\prime}(0)=f^{\\prime\\prime}(0)=0',110,535,1280,110,61),text('Every nearby nonzero x gives a positive value.',110,735,1300,65,35)],{optionalChallenge:true,question:'Why is zero still a minimum?',answer:'x⁴≥0 for all x and equals zero at x=0, despite the inconclusive second derivative test.',teachingCue:'反例强调二阶为零只是不确定。',assistantCue:'Classify by function values or the first derivative sign test.'}),
 page(10,'26','A sharp corner can be best','OPTIONAL CHALLENGE',ref,[math('f(x)=|x|,\\quad -2\\leq x\\leq2',100,300,1330,120,60),text('The minimum is at zero.\nThe derivative there does not exist.',110,590,1300,160,45)],{optionalChallenge:true,question:'What extra candidate appears when a function is not differentiable?',answer:'An interior point where the derivative does not exist.',teachingCue:'说明主流程光滑假设的边界，不要求复杂非光滑优化。',assistantCue:'Include nondifferentiable interior points when generalizing beyond the smooth core examples.'})
 ],
 exercises:[
 {id:'10-1',question:'For f(x)=4x−x², find stationary points.',answer:'x=2.',solution:'f′(x)=4−2x. Solving 4−2x=0 gives x=2.'},
 {id:'10-2',question:'Classify the stationary point of f(x)=4x−x² using signs.',answer:'A local maximum at x=2.',solution:'f′>0 before 2 and f′<0 after 2. The function rises then falls. Its value is f(2)=4.'},
 {id:'10-3',question:'Classify g(x)=(x−2)².',answer:'A minimum at x=2 with value 0.',solution:'g′=2x−4 vanishes at 2. g″=2>0, so the stationary point is a strict local minimum; g≥0 makes it global.'},
 {id:'10-4',question:'Is zero a maximum of h(x)=x³?',answer:'No.',solution:'h′=3x² is zero at 0 but positive on both sides. The function increases through 0, so there is no local extremum.'},
 {id:'10-5',question:'Find the maximum and minimum of 4x−x² on [0,3].',answer:'Maximum 4 at 2; minimum 0 at 0.',solution:'Compare f(0)=0, f(2)=4, and f(3)=3. These are the endpoints and the sole interior stationary candidate.'},
 {id:'10-6',question:'Find the maximum of 1+2x on [0,3].',answer:'7 at x=3.',solution:'The derivative is 2>0 throughout the interval. The function is increasing, so its right endpoint gives 1+2×3=7.'},
 {id:'10-7',question:'Explain why x⁴ has a minimum at zero although f″(0)=0.',answer:'All values are nonnegative and f(0)=0.',solution:'The second derivative test is inconclusive. Directly, x⁴>0 for every nonzero x while f(0)=0, so zero is a strict global minimum.',optional:true}
 ],
 teacherGuide:'90分钟：开场与导数符号15；峰谷与驻点20；三次函数反例10；二阶导数15；端点比较15；练习出口15。英文话术：“Zero slope gives a candidate.” “Check both sides.” “The best feasible value may be at an edge.” 主课全部采用平滑函数及闭区间。每个最优值同时报位置和数值。x⁴与绝对值只作选学。',
 film:[
 {from:0,to:15,title:'A path climbs',narration:'A paper ribbon climbs across a bright landscape. Its slope becomes gentler until the path appears flat, and a small marker pauses at that point.',caption:'The slope reaches zero.',scene:'A blue ribbon curves upward and a yellow marker settles on a horizontal tangent.'},
 {from:15,to:30,title:'A hill',narration:'The ribbon bends downward after the pause. Now the flat point looks like a summit, because nearby values rise before it and fall after it.',caption:'Rise. Flat. Fall.',scene:'The path completes an inverted parabola with upward and downward arrows on opposite sides.'},
 {from:30,to:45,title:'A valley',narration:'Another ribbon falls into a bowl and then rises again. Its lowest point also has zero slope, but it tells a completely different story.',caption:'Fall. Flat. Rise.',scene:'A green bowl-shaped curve replaces the hill; the tangent remains horizontal at the bottom.'},
 {from:45,to:60,title:'A pause without a turn',narration:'A third path flattens briefly and continues climbing. The marker never reaches a summit or valley, even though the tangent is horizontal at the pause.',caption:'Flat, yet still climbing.',scene:'A coral cubic ribbon passes through its stationary point and continues upward.'},
 {from:60,to:75,title:'The allowed path',narration:'A frame cuts the landscape into an allowed interval. Its edges now matter, because the best available point may sit directly on a boundary.',caption:'Boundaries matter too.',scene:'Two bold vertical borders crop a rising ribbon, highlighting its right endpoint.'},
 {from:75,to:90,title:'What happens next?',narration:'Three flat points remain side by side. Which one is a maximum, which one is a minimum, and which one simply continues its journey?',caption:'Does zero slope mean maximum?',scene:'Hill, valley, and cubic appear as three paper windows, ending on the unresolved question.'}
 ]
};
