import type {MathematicsLesson} from '../types.js';
import {source,page,text,math,art,plot,table,diagram} from '../authoring.js';
const ref=source('4.1',268,278,'Numerical limits and the difference quotient');
const motion={kind:'polynomial' as const,coefficients:[0,0,1],color:'blue' as const,label:'s(t) = t²'};
export const lesson05:MathematicsLesson={
 number:5,title:'Change at One Moment',filmTitle:'The Delivery That Speeds Up',openingQuestion:'How fast is the delivery moving at exactly two seconds?',
 outcomes:['Calculate an average rate with its units.','Use shrinking intervals to estimate an instantaneous rate.','Interpret a derivative as a tangent slope at a stated input.'],
 vocabulary:[['average rate','Output change divided by input change over an interval.'],['secant','A line through two points on a curve.'],['tangent','A line giving the local direction of a smooth curve.'],['limit','The value approached as an input approaches a specified value.'],['derivative','The limiting rate of change at an input.'],['difference quotient','A ratio of changes used to calculate a derivative.']],sources:[ref],
 slides:[
 page(5,'01','THE DELIVERY SPEEDS UP','Watch • track • question',ref,[art('opening',70,230,900,595,'Cut-paper delivery vehicle leaving increasingly spaced marks'),text('Position changes.',1030,310,470,90,46),text('But how fast right now?',1030,475,470,170,43,'blue')],{openingFilm:true,publicLabel:'Teaching scenario',question:'How could we measure speed at one exact moment?',answer:'Estimate rates over shorter intervals, then find the limit.',teachingCue:'视频后区分位置和速度，只提出此刻的测量难题。',assistantCue:'Use the stated teaching model s(t)=t² metres with t in seconds. Explain numerical limits without epsilon-delta proofs. Do not reveal the target speed prematurely.'}),
 page(5,'02','Positions are the evidence','Read the record',ref,[table(['Time t (s)','0','1','2','3','4'],[['Position s (m)','0','1','4','9','16']],70,285,1420,250),text('Equal time steps. Unequal distance steps.',95,650,1360,110,45,'coral')],{publicLabel:'Teaching scenario',question:'How far does the vehicle travel from 2 to 3 seconds?',answer:'9 − 4 = 5 metres.',teachingCue:'单位时间相同先比较相邻位置差，勿将9米当这一秒的路程。'}),
 page(5,'03','A model joins the positions','One variable',ref,[plot({xRange:[0,4],yRange:[0,16],xLabel:'Time t (s)',yLabel:'Position s (m)',curves:[motion],points:[{x:1,y:1},{x:2,y:4},{x:3,y:9}]},70,240,960,580),math(String.raw`s(t)=t^2`,1090,350,390,110,49),text('0 ≤ t ≤ 4',1090,540,390,80,38)],{question:'What position does the model predict at t = 2.5?',answer:'s(2.5) = 6.25 metres.',teachingCue:'说明是简化模型，不是某真实配送记录。'}),
 page(5,'04','One interval, one average','Rate with units',ref,[math(String.raw`\frac{s(3)-s(1)}{3-1}=\frac{9-1}{2}=4`,80,290,1400,140,64),text('4 metres per second across [1, 3]',90,570,1370,120,48,'green')],{question:'Does this average describe every moment in the interval?',answer:'No. It describes the total position change divided by the total time change.',teachingCue:'先算整体平均，明确不保证每时每刻都等于4。'}),
 page(5,'05','Change divided by change','General pattern',ref,[diagram('flow',['Output change','Input change','Average rate'],75,290,1400,260,['Δs','Δt','Δs / Δt']),math(String.raw`\text{Average rate}=\frac{\Delta s}{\Delta t}`,180,670,1190,100,52)],{question:'What unit results from metres divided by seconds?',answer:'Metres per second.',teachingCue:'Delta读作change，不当成新乘数。'}),
 page(5,'06','A line crosses two points','Secant slope',ref,[plot({xRange:[0,4],yRange:[0,17],xLabel:'t (s)',yLabel:'s (m)',curves:[motion],secant:{curve:0,x:1,h:2}},65,240,1000,580),text('Two points determine the secant.',1110,305,380,170,38),math(String.raw`m=4`,1110,590,380,100,58)],{question:'What does the secant slope measure here?',answer:'Average speed from t = 1 to t = 3 seconds.',teachingCue:'指明secant横跨两点；斜率和曲线局部方向不同。'}),
 page(5,'07','The interval matters','Compare two averages',ref,[table(['Interval (s)','Position change (m)','Average (m/s)'],[['[0, 2]','4 − 0','2'],['[2, 4]','16 − 4','6']],75,270,1410,350),text('The vehicle covers more distance in the later interval.',95,695,1370,110,41)],{question:'What evidence supports “speeds up”?',answer:'For equal two-second intervals, the later average speed is larger.',teachingCue:'限于模型，比较同长度区间；不能仅凭纵坐标升高判断加速。'}),
 page(5,'08','Focus on two seconds','The target point',ref,[plot({xRange:[0,4],yRange:[0,16],xLabel:'t (s)',yLabel:'s (m)',curves:[motion],points:[{x:2,y:4,label:'Target'}]},70,245,970,575),text('Position: 4 m',1100,350,390,90,43),text('Speed: still unknown',1100,535,390,130,40,'coral')],{question:'Why does s(2) = 4 not by itself mean the speed is 4 m/s?',answer:'s(2) is a position with units of metres, not a rate with units of metres per second.',teachingCue:'刻意分开函数值和导数值；此例数值巧合但单位不同。'}),
 page(5,'09','Take a smaller step','First local estimate',ref,[math(String.raw`\frac{s(2.5)-s(2)}{0.5}=\frac{6.25-4}{0.5}=4.5`,75,290,1420,150,56),text('A half-second average near the target',90,610,1380,130,45,'blue')],{question:'Which two positions are used?',answer:'The positions at 2 and 2.5 seconds.',teachingCue:'分母是时间差0.5，分子是位置差，不是6.25。'}),
 page(5,'10','The estimates settle down','Numerical approach',ref,[table(['Forward step h (s)','1','0.5','0.1','0.01'],[['Average rate (m/s)','5','4.5','4.1','4.01']],70,275,1420,260),text('The rates approach 4 as the step approaches zero.',90,645,1370,130,47,'green')],{question:'What rate would you expect at h = 0.001?',answer:'4.001 m/s, approaching 4 m/s.',teachingCue:'让学生识别趋近而非四舍五入成定义；保留小数差。'}),
 page(5,'11','Shrink h, keep the target','Difference quotient',ref,[math(String.raw`\frac{s(2+h)-s(2)}{h}`,90,270,1370,160,80),diagram('steps',['Start at 2','Move by h','Divide the position change by h'],90,555,1370,240)],{question:'Why must h be nonzero in this expression?',answer:'The denominator is h, so h = 0 would require division by zero.',teachingCue:'严禁直接代h=0；先用非零步长再取极限。'}),
 page(5,'12','Open the square','Algebra reveals the pattern',ref,[math(String.raw`(2+h)^2=4+4h+h^2`,75,280,1400,110,58),math(String.raw`\frac{(2+h)^2-4}{h}=\frac{4h+h^2}{h}`,75,475,1400,130,58)],{publicLabel:'Worked example',question:'Which constant terms cancel in the numerator?',answer:'The +4 and −4 cancel.',teachingCue:'展开有2×2h项；用h=1核查避免漏中间项。'}),
 page(5,'13','Cancel only a common factor','h remains nonzero',ref,[math(String.raw`\frac{h(4+h)}{h}=4+h\qquad(h\ne0)`,85,325,1360,140,64),text('The simplified expression exposes the approach to 4.',90,600,1370,130,44)],{question:'Is cancelling h the same as substituting h = 0?',answer:'No. Cancellation is valid for nonzero h; the simplified expression can then be used to find a limit.',teachingCue:'把等价范围h≠0写清，区分约分与取极限。'}),
 page(5,'14','A limit is an approached value','The local rate',ref,[math(String.raw`\lim_{h\to0}(4+h)=4`,80,310,1400,150,82),text('Nearby averages approach one number.',85,630,1380,100,49,'blue')],{question:'Must an interval of zero length be measured to find this limit?',answer:'No. The limit is determined by values with nonzero steps approaching zero.',teachingCue:'本讲用数值和图形理解极限，不引入严格epsilon证明。'}),
 page(5,'15','The tangent gives one direction','Geometric meaning',ref,[plot({xRange:[0,4],yRange:[0,16],xLabel:'t (s)',yLabel:'s (m)',curves:[motion],tangent:{curve:0,x:2},points:[{x:2,y:4,label:'Slope 4'}]},70,240,1010,590),text('At t = 2',1110,335,380,90,44),text('Tangent slope: 4',1110,525,380,120,40,'green')],{question:'How many target points does a tangent slope refer to?',answer:'One specified input point, though a tangent line can intersect the curve elsewhere.',teachingCue:'不要把切线定义为只接触一次；强调局部方向。'}),
 page(5,'16','Two notations, one derivative','Read aloud',ref,[math(String.raw`s'(2)=4`,90,295,650,125,76),math(String.raw`\left.\frac{ds}{dt}\right|_{t=2}=4`,805,295,650,135,68),text('“s prime at two”',90,570,650,100,40),text('“the derivative of s with respect to t, at two”',805,570,650,160,37)],{question:'What unit belongs to both derivative values?',answer:'Metres per second.',teachingCue:'口读两种记号；ds/dt此处不是普通两数分式。'}),
 page(5,'17','Any target time a','From a value to a function',ref,[math(String.raw`\frac{(a+h)^2-a^2}{h}=2a+h`,80,290,1400,150,67),math(String.raw`s'(a)=\lim_{h\to0}(2a+h)=2a`,80,555,1400,150,66)],{question:'What is the instantaneous speed at a = 3?',answer:'s′(3) = 6 m/s.',teachingCue:'从2推广到a；学生看到导函数输入时刻输出速率。'}),
 page(5,'18','The derivative is another function','Position and speed',ref,[plot({xRange:[0,4],yRange:[0,8],xLabel:'Time t (s)',yLabel:'Speed (m/s)',curves:[{kind:'polynomial',coefficients:[0,2],color:'green',label:'s′(t) = 2t'}]},70,250,960,565),math(String.raw`s(t)=t^2`,1090,330,400,100,47),math(String.raw`s'(t)=2t`,1090,520,400,100,47,'green')],{question:'What does a horizontal coordinate represent on both graphs?',answer:'Time in seconds. Their vertical coordinates have different meanings and units.',teachingCue:'导函数图不是原图重新命名，纵轴单位有变化。'}),
 page(5,'19','The sign tells a direction','Increasing and decreasing',ref,[table(['Local behaviour','Derivative sign'],[['Output rises as input rises','Positive'],['Output falls as input rises','Negative'],['Horizontal tangent','Zero']],80,270,1400,380),text('A slope describes change, not the height of a point.',90,710,1370,90,42,'coral')],{question:'Can a positive function value have a negative derivative?',answer:'Yes. A curve can be above zero while decreasing.',teachingCue:'用正余额正在减少说明函数值符号与导数符号不同。'}),
 page(5,'20','A straight line keeps one rate','A contrast',ref,[plot({xRange:[0,4],yRange:[0,15],xLabel:'t (s)',yLabel:'s (m)',curves:[{kind:'polynomial',coefficients:[2,3],label:'s = 2 + 3t',color:'coral'}],secant:{curve:0,x:1,h:1}},65,245,1000,575),math(String.raw`s'(t)=3`,1110,370,380,110,54),text('Every nonzero interval gives the same rate.',1110,565,380,170,35)],{question:'What does the initial position 2 change?',answer:'It shifts position upward; it does not change the constant speed of 3 m/s.',teachingCue:'对比线性常速与平方加速，把初始位置和速率拆开。'}),
 page(5,'21','Move the second point','Explore h',ref,[plot({xRange:[0,4],yRange:[0,16],xLabel:'t (s)',yLabel:'s (m)',curves:[motion],secant:{curve:0,x:2,h:1},tangent:{curve:0,x:2}},70,240,1010,585),text('Keep t = 2 fixed.',1130,315,350,125,38),text('Shrink the forward step.',1130,535,350,130,38,'blue')],{interaction:{kind:'parameter',key:'h',label:'Forward time step h (s)',min:.01,max:2,step:.01,initial:1},question:'What happens to the secant as h shrinks?',answer:'Its slope 4 + h approaches the tangent slope 4.',teachingCue:'教师拖动步长，学生描述割线旋向；最小值0.01保持非零。'}),
 page(5,'22','A nearby estimate is an estimate','Finite and instantaneous',ref,[math(String.raw`s'(2)=4\quad\text{but}\quad\frac{s(2.1)-s(2)}{0.1}=4.1`,80,290,1400,160,52),text('A derivative is not automatically an exact finite-step change.',90,610,1370,150,44)],{question:'How large is the model’s exact distance change from 2 to 2.1 seconds?',answer:'4.41 − 4 = 0.41 metres; the local estimate is 4 × 0.1 = 0.40 metres.',teachingCue:'引入局部近似界限，为边际课铺垫，不称导数有限增量精确值。'}),
 page(5,'23','A corner can break the limit','Smoothness matters',ref,[math(String.raw`f(x)=|x|`,90,290,1370,115,72),diagram('flow',['Left slope','At zero','Right slope'],90,485,1370,215,['−1','A corner','+1']),text('Different approaches give different slopes.',90,750,1370,75,39,'coral')],{question:'Is there a single derivative at x = 0?',answer:'No. The left-hand and right-hand difference quotients approach different values.',teachingCue:'只作直观反例，不要求绝对值分段技巧；有连续不必可导。'}),
 page(5,'24','Explain the moment','Exit ticket',ref,[math(String.raw`d(t)=t^2+3\quad\text{metres}`,90,270,1370,120,67),text('At t = 2: find the position, an average over [2, 3], and the instantaneous rate.',90,500,1370,190,46)],{question:'What are the three answers, with units?',answer:'Position: 7 m. Average rate: (12 − 7)/1 = 5 m/s. Instantaneous rate: d′(2) = 4 m/s.',teachingCue:'检查三种量与单位，初始位置3不改变速率。'}),
 page(5,'25','Approach from behind','Optional Challenge',ref,[math(String.raw`\frac{s(2+h)-s(2)}{h}=4+h`,85,300,1370,130,66),table(['h (s)','−0.5','−0.1','−0.01'],[['Rate (m/s)','3.5','3.9','3.99']],80,560,1400,240)],{optionalChallenge:true,question:'Do backward and forward steps approach the same number?',answer:'Yes, both approach 4 m/s for s(t) = t² at t = 2.',teachingCue:'选学双侧趋近，注意负分子除负分母仍为正。'}),
 page(5,'26','A symmetric measurement','Optional Challenge',ref,[math(String.raw`\frac{s(2+h)-s(2-h)}{2h}`,85,290,1370,145,74),text('Use equally spaced measurements before and after the target.',90,540,1370,140,44),text('Try h = 0.5, then simplify algebraically.',90,725,1370,75,39,'green')],{optionalChallenge:true,question:'What rate does this quotient give for s(t) = t²?',answer:'It gives exactly 4 for every nonzero h within the model’s time range: the numerator is 8h.',teachingCue:'选学对称差分；说明本例精确是平方函数的特性，非普遍规则。'})
 ],
 exercises:[
 {id:'05-1',question:'For s(t)=t² metres, find the average speed over [1,3] seconds.',answer:'4 m/s.',solution:'[s(3)−s(1)]/(3−1)=(9−1)/2=4.'},
 {id:'05-2',question:'For s(t)=t², calculate the forward difference quotient at t=2 with h=0.1.',answer:'4.1 m/s.',solution:'[(2.1)²−2²]/0.1=(4.41−4)/0.1=4.1.'},
 {id:'05-3',question:'Simplify [(2+h)²−4]/h for h≠0 and find its limit as h approaches zero.',answer:'4+h; limit 4.',solution:'Expand the numerator to 4h+h², factor out h, cancel it for h≠0, and take the limit.'},
 {id:'05-4',question:'A position is d(t)=2+3t metres. Find the position and instantaneous speed at t=4 seconds.',answer:'14 m and 3 m/s.',solution:'d(4)=2+12=14. The straight line has constant slope 3.'},
 {id:'05-5',question:'For s(t)=t², compare the exact change from 2 to 2.1 seconds with the derivative-based estimate.',answer:'Exact 0.41 m; estimate 0.40 m.',solution:'Exact change=4.41−4=0.41. Estimate=s′(2)×0.1=4×0.1=0.40.'},
 {id:'05-6',question:'A positive balance is decreasing. Must its derivative be positive? Explain.',answer:'No. Its derivative is negative while it is decreasing.',solution:'The function value measures the balance; the derivative measures its direction and rate of change.'},
 {id:'05-7',question:'Optional: simplify [(2+h)²−(2−h)²]/(2h), h≠0.',answer:'4.',solution:'The numerator is 8h, so the quotient is 8h/(2h)=4.',optional:true}
 ],
 teacherGuide:'第5讲90分钟。0–10：视频、位置表与平均速率；10–25：割线和单位；25–45：缩小步长、差商展开与数值极限；45–60：切线、导数记号与导函数；60–73：直线对照与教师操控h；73–83：有限增量界限与角点；83–90：出口题。英文话术：“Position is measured in metres. Speed is measured in metres per second.” “Keep the target fixed; move the second point.” “Approaching zero does not mean dividing by zero.” 小数精度保留到能看出趋势，避免将h=0作为可操作区间；选学可双侧与对称取样。',
 film:[
 {from:0,to:15,title:'The route begins',narration:'A delivery vehicle leaves a paper warehouse. Every second, a new position mark appears. The marks are becoming farther apart along the route.',caption:'Equal seconds. Growing gaps.',scene:'delivery-marks'},
 {from:15,to:30,title:'Positions become a curve',narration:'The positions lift from the road onto a graph. Time runs across the bottom. Distance rises up the side, forming a smooth curve.',caption:'Position is not speed.',scene:'road-to-curve'},
 {from:30,to:45,title:'Two points make a line',narration:'Choose two times and connect their positions. The line measures an average speed across that interval, but the vehicle is changing its speed.',caption:'Two points → average rate',scene:'secant-route'},
 {from:45,to:60,title:'One point stays still',narration:'Hold the two-second position fixed. Move the other time closer. Each new line turns slightly, as the measurement interval becomes shorter and shorter.',caption:'Keep the target. Shrink the step.',scene:'shrinking-interval'},
 {from:60,to:75,title:'The direction settles',narration:'The moving line seems to settle into one direction. Its slope offers a way to describe speed at the target, without measuring zero time.',caption:'A local direction emerges.',scene:'tangent-emerges'},
 {from:75,to:90,title:'The moment is the question',narration:'The delivery reaches exactly two seconds. What is its speed at this moment? Use the nearby position changes to find a convincing mathematical answer.',caption:'How fast at exactly two seconds?',scene:'delivery-question'}
 ]
};
