import type {MathematicsLesson} from '../types.js';
import {page,source,text,math,art,plot,table,diagram} from '../authoring.js';
const ref=source('4.5',314,328);
export const lesson12:MathematicsLesson={
 number:12,title:'Price Elasticity and Revenue',filmTitle:'Same 10%, Different Shock',openingQuestion:'Why can the same price increase create different sales changes?',
 outcomes:['Calculate signed point price elasticity for linear demand.','Interpret elasticity magnitude and its domain.','Connect elasticity with the local direction of revenue change.'],
 vocabulary:[['price elasticity','A local proportional quantity response to a proportional price change.'],['signed elasticity','Elasticity retaining the sign of the demand response.'],['elastic demand','Demand with elasticity magnitude greater than one.'],['inelastic demand','Demand with elasticity magnitude less than one.'],['unit elastic','Demand with elasticity magnitude equal to one.'],['point elasticity','Elasticity evaluated at one price.']],sources:[ref],
 slides:[
 page(12,'01','Same price shock, different impact','OPENING SCENE',ref,[art('opening',790,230,710,560,'Two paper shop windows with contrasting crowds'),text('Two price tags rise by 10%.\nDo sales fall by the same percentage?',80,290,650,190,43),math('Q(P)=100-2P',90,610,660,90,56)],{openingFilm:true,publicLabel:'Teaching scenario',question:'Does a straight demand line have constant elasticity?',teachingCue:'片尾问题保留，先区分数量与百分比变化。',assistantCue:'Do not assume constant slope implies constant elasticity.'}),
 page(12,'02','One familiar demand model','READ THE DOMAIN',ref,[math('Q(P)=100-2P',90,300,1380,110,70),text('0 ≤ P ≤ 50 • P in euros • Q in units\nPoint elasticity is defined only when Q > 0.',110,575,1300,160,39)],{question:'Why does P=50 need special care?',answer:'Demand is zero there, so the elasticity formula divides by zero.',teachingCue:'不使用需求截断区外数据，明确分母条件。',assistantCue:'Use this linear demand on [0,50], with point elasticity only for P<50.'}),
 page(12,'03','Slope measures units per euro','FIRST RESPONSE',ref,[plot({xRange:[0,50],yRange:[0,110],xLabel:'Price P (€)',yLabel:'Quantity Q',curves:[{kind:'polynomial',coefficients:[100,-2],color:'blue'}]},70,230,970,550),math('Q^{\\prime}(P)=-2',1090,335,430,110,51),text('Two fewer units\nper extra euro.',1090,565,420,135,37)],{question:'Does −2 mean a two-percent decline?',answer:'No. It is two units per euro.',teachingCue:'先用量纲反驳百分比误读。',assistantCue:'Explain the dimensional slope before introducing elasticity.'}),
 page(12,'04','Percentage changes need a base','RELATIVE CHANGE',ref,[math('\\text{Relative quantity change}=\\frac{\\Delta Q}{Q}',90,290,1390,120,45),math('\\text{Relative price change}=\\frac{\\Delta P}{P}',100,555,1340,120,45)],{question:'Why can the same drop in units produce different percentages?',answer:'The starting quantities can be different.',teachingCue:'所有百分比均说明起点作分母。',assistantCue:'Use initial values for the finite-change comparisons in this lesson.'}),
 page(12,'05','Compare two starting points','THE BASE EFFECT',ref,[table(['Starting price','Starting Q','+€1 changes Q','Relative Q change'],[['€10','80','−2','−2.5%'],['€40','20','−2','−10%']],85,270,1420,280),text('Same slope. Different proportional response.',110,680,1300,95,41)],{question:'Why is the percentage quantity loss larger at €40?',answer:'Two units are a larger fraction of 20 than of 80.',teachingCue:'只变基数，不需要不同函数。',assistantCue:'Keep absolute and proportional responses separate.'}),
 page(12,'06','The point elasticity formula','SIGNED CONVENTION',ref,[math('E(P)=\\frac{P}{Q(P)}Q^{\\prime}(P)',90,300,1390,130,70),text('This course keeps the negative sign.\nMagnitude: |E|.',110,610,1300,140,43)],{question:'Why is E negative for downward-sloping demand at a positive price?',answer:'Q′ is negative while P and Q are positive.',teachingCue:'公开约定用有符号E，分类时用绝对值。',assistantCue:'Use signed E=(P/Q)Q′; demand classification uses |E|.'}),
 page(12,'07','Substitute the linear model','CALCULATE',ref,[math('E(P)=-\\frac{2P}{100-2P}',90,310,1390,130,71),text('The derivative stays −2.\nThe ratio P/Q changes.',110,610,1300,145,43)],{question:'Which part makes elasticity vary along the line?',answer:'The price-to-quantity ratio P/Q.',teachingCue:'回扣直线斜率恒定但弹性不恒定。',assistantCue:'Do not confuse a constant derivative with a constant elasticity.'}),
 page(12,'08','At a low price','INELASTIC',ref,[math('E(10)=-\\frac{20}{80}=-0.25',90,315,1390,130,66),text('A small 1% price rise predicts\nabout a 0.25% quantity decline.',110,610,1300,150,42)],{question:'Is this demand elastic or inelastic at €10?',answer:'Inelastic because |E|=0.25<1.',teachingCue:'明确预测为局部近似。',assistantCue:'Use small-change and approximately language for point elasticity.'}),
 page(12,'09','At a high price','ELASTIC',ref,[math('E(40)=-\\frac{80}{20}=-4',90,315,1390,130,68),text('A small 1% price rise predicts\nabout a 4% quantity decline.',110,610,1300,150,42)],{question:'Which response is proportionally larger?',answer:'The quantity response; its magnitude is four times the price change.',teachingCue:'负号表示方向，4表示倍数。',assistantCue:'Separate the negative direction from the magnitude four.'}),
 page(12,'10','Three categories use magnitude','CLASSIFY',ref,[table(['Magnitude','Name','Local quantity response'],[['|E|<1','Inelastic','Smaller percentage change'],['|E|=1','Unit elastic','Equal percentage magnitude'],['|E|>1','Elastic','Larger percentage change']],90,260,1400,390)],{question:'How is E=−0.8 classified?',answer:'Inelastic, because its magnitude is 0.8.',teachingCue:'不能把负数直接与正1比较分类。',assistantCue:'Classify with absolute value, never with signed E<1 alone.'}),
 page(12,'11','Where is demand unit elastic?','SOLVE',ref,[math('\\frac{2P}{100-2P}=1',90,295,1390,140,72),math('P=25,\\quad Q=50',100,565,1340,110,70)],{question:'What is the signed elasticity at €25?',answer:'−1.',teachingCue:'求解时保留Q正的定义域。',assistantCue:'Return signed E=−1 and magnitude one.'}),
 page(12,'12','Elasticity changes along one line','COMPARE POINTS',ref,[table(['P','Q','E','Category'],[['10','80','−0.25','Inelastic'],['25','50','−1','Unit elastic'],['40','20','−4','Elastic']],90,270,1390,360)],{question:'Does a straight line mean the same category everywhere?',answer:'No. All three categories occur along this line.',teachingCue:'同一需求曲线跨三类强化基数机制。',assistantCue:'Restrict categories to interior positive-demand points.'}),
 page(12,'13','Revenue multiplies price and demand','A NEW QUESTION',ref,[art('case',80,240,510,530,'A shop receipt and moving price tags'),math('R(P)=P(100-2P)',680,320,830,110,54),text('Does a higher price raise revenue?',680,625,800,110,39)],{question:'What two effects compete?',answer:'Higher revenue per unit and lower quantity sold.',teachingCue:'先口头说两股作用，再求导。',assistantCue:'Keep total revenue distinct from profit.'}),
 page(12,'14','Differentiate revenue','PRODUCT RULE',ref,[math('R^{\\prime}(P)=Q(P)+P Q^{\\prime}(P)',90,295,1390,130,58),math('R^{\\prime}(P)=100-4P',100,555,1340,110,65)],{question:'At P=10, what is the local revenue direction?',answer:'R′(10)=60>0, so a small price rise increases revenue.',teachingCue:'复用乘积法则，含降量效应。',assistantCue:'Describe the derivative as euros of revenue change per euro of price change.'}),
 page(12,'15','The elasticity link','FACTOR THE DERIVATIVE',ref,[math('R^{\\prime}(P)=Q(P)\\,[1+E(P)]',90,310,1390,140,67),text('With Q > 0, the sign of 1 + E\ngives the local revenue direction.',110,615,1300,140,40)],{question:'Why does E=−1 make R′ zero?',answer:'The factor 1+E becomes zero.',teachingCue:'使用有符号公式，避免写成1加绝对值。',assistantCue:'Use signed E in R′=Q(1+E); equivalently Q(1−|E|) for downward demand.'}),
 page(12,'16','Inelastic demand: revenue rises locally','INTERPRET',ref,[math('|E|<1\\quad\\Rightarrow\\quad R^{\\prime}(P)>0',90,315,1390,130,57),text('Near an inelastic point,\na small price rise increases revenue.',110,615,1300,150,43)],{question:'Does this say profit must increase?',answer:'No. Profit also depends on cost.',teachingCue:'严格只谈收入，不能替代利润。',assistantCue:'Do not infer profit or welfare from the revenue sign alone.'}),
 page(12,'17','Elastic demand: revenue falls locally','INTERPRET',ref,[math('|E|>1\\quad\\Rightarrow\\quad R^{\\prime}(P)<0',90,315,1390,130,57),text('Near an elastic point,\na small price rise reduces revenue.',110,615,1300,150,43)],{question:'What happens near P=40 after a small price rise?',answer:'Revenue decreases because E=−4.',teachingCue:'让学生说百分比下降强于价格上升。',assistantCue:'Maintain the local qualification for a point-elasticity statement.'}),
 page(12,'18','Revenue has its own peak','CHECK THE GRAPH',ref,[plot({xRange:[0,50],yRange:[0,1400],xLabel:'Price P (€)',yLabel:'Revenue (€)',curves:[{kind:'polynomial',coefficients:[0,100,-2],color:'green'}],points:[{x:25,y:1250,label:'Unit elastic'}]},70,230,1010,560),math('R(25)=1250',1130,350,360,110,42)],{question:'Is €25 a profit-maximizing price?',answer:'This model establishes only the revenue maximum, not a profit maximum.',teachingCue:'图中的峰标注收入而非利润。',assistantCue:'Use R″=−4 and endpoint revenue zero to justify the revenue maximum only.'}),
 page(12,'19','A 10% rise from ten','FINITE COMPARISON',ref,[table(['','Before','After'],[['Price','10','11'],['Quantity','80','78'],['Revenue','800','858']],90,265,1400,340),text('Quantity falls 2.5%.\nRevenue rises 7.25%.',110,695,1300,110,40)],{question:'Is the revenue percentage simply 10%−2.5%?',answer:'No. The exact result includes the product of the percentage changes.',teachingCue:'乘法交叉项防止百分比机械相减。',assistantCue:'Calculate 858/800−1=0.0725 exactly.'}),
 page(12,'20','A 10% rise from forty','FINITE COMPARISON',ref,[table(['','Before','After'],[['Price','40','44'],['Quantity','20','12'],['Revenue','800','528']],90,265,1400,340),text('Quantity falls 40%.\nRevenue falls 34%.',110,695,1300,110,40)],{question:'Why is the same 10% price rise more disruptive here?',answer:'It is a €4 rise against a small starting quantity of 20.',teachingCue:'同百分比不同绝对提价与数量基数。',assistantCue:'This exact quantity response follows from linearity and the specified initial base.'}),
 page(12,'21','Local statements need care','BOUNDARY OF THE TOOL',ref,[math('\\frac{\\Delta Q}{Q}\\approx E(P)\\frac{\\Delta P}{P}',90,310,1390,130,63),text('For general nonlinear demand,\nlarge moves need the full function.',110,615,1300,145,42)],{question:'Why should a point measure not be used blindly for a large change?',answer:'Elasticity can change along the move.',teachingCue:'本例线性数量比例恰精确，但一般函数仅局部。',assistantCue:'For this linear Q, the initial-base quantity relation is exact; generally it is a local approximation.'}),
 page(12,'22','Fix the sign mistake','ERROR DETECTIVE',ref,[text('“E = −4 is less than 1,\nso demand is inelastic.”',100,300,1370,180,49),math('|-4|=4>1',110,620,1300,100,72)],{question:'What is the correct classification?',answer:'Elastic.',teachingCue:'聚焦符号约定错用。',assistantCue:'Classify with |E| while retaining negative E in the response formula.'}),
 page(12,'23','Calculate at twenty','GUIDED PRACTICE',ref,[math('P=20,\\quad Q=60',90,295,1390,110,72),text('Find E. Classify demand.\nPredict the local revenue direction.',110,595,1300,160,44)],{question:'What are the three conclusions?',answer:'E=−2/3; inelastic; a small price increase raises revenue.',teachingCue:'三步答案分别核对。',assistantCue:'Offer formula substitution hints before revealing all three conclusions.'}),
 page(12,'24','Slope, elasticity, revenue','EXIT CHECK',ref,[diagram('flow',['Units per euro','Percentage response','Local revenue direction'],100,300,1330,240),text('Name the measure. State the point. Keep the sign.',110,685,1300,90,40)],{question:'What changes along this demand line while its slope stays fixed?',answer:'P/Q, elasticity, and the local revenue direction.',teachingCue:'回扣开场问题总结基数变化。',assistantCue:'Review this linear model without adding unmeasured market claims.'}),
 page(12,'25','Near zero demand','OPTIONAL CHALLENGE',ref,[math('E(49)=-49',90,310,1390,110,77),text('A tiny remaining quantity makes\npercentage changes very large.',110,605,1300,155,44)],{optionalChallenge:true,question:'Can E(50) be assigned the finite value −50?',answer:'No. Q(50)=0, so the formula is undefined.',teachingCue:'用49与50区分大数与未定义。',assistantCue:'Avoid treating a limit divergence as a finite endpoint elasticity.'}),
 page(12,'26','Exact revenue percentages','OPTIONAL CHALLENGE',ref,[math('\\frac{R_{new}}{R_{old}}=(1+a)(1+b)',90,315,1390,130,61),math('\\%\\Delta R=100(a+b+ab)',100,575,1340,100,62)],{optionalChallenge:true,question:'If price rises 10% and quantity falls 40%, what is the revenue change?',answer:'(1.1)(0.6)−1=−0.34, or −34%.',teachingCue:'a与b为小数变化率，符号写清。',assistantCue:'Use a=0.10 and b=−0.40; percentages are multiplied through revenue.'})
 ],
 exercises:[
 {id:'12-1',question:'Find signed point elasticity for Q=100−2P.',answer:'E=−2P/(100−2P), for 0≤P<50.',solution:'Q′=−2. Substitute into E=(P/Q)Q′. Demand must be positive.'},
 {id:'12-2',question:'Calculate and classify E(10).',answer:'−0.25; inelastic.',solution:'Q(10)=80. E=(10/80)(−2)=−0.25. Its magnitude is below one.'},
 {id:'12-3',question:'Calculate and classify E(40).',answer:'−4; elastic.',solution:'Q(40)=20. E=(40/20)(−2)=−4. Its magnitude is above one.'},
 {id:'12-4',question:'Find the unit-elastic price.',answer:'€25.',solution:'Set 2P/(100−2P)=1. Then 2P=100−2P, so P=25, Q=50, and E=−1.'},
 {id:'12-5',question:'Find the revenue-maximizing price on [0,50].',answer:'€25, with revenue €1250.',solution:'R=100P−2P²; R′=100−4P=0 at 25. R″=−4<0, and both endpoints give zero.'},
 {id:'12-6',question:'A price rises from 40 to 44. Find the exact quantity and revenue percentage changes.',answer:'−40% and −34%.',solution:'Q falls from 20 to 12: (12−20)/20=−0.4. R falls from 800 to 528: (528−800)/800=−0.34.'},
 {id:'12-7',question:'Why does E become very negative near P=50 but remain undefined at 50?',answer:'Positive Q approaches zero; at zero division is impossible.',solution:'E=−2P/(100−2P). As P approaches 50 from below, the positive denominator approaches zero and the numerator approaches −100. E tends to −∞; E(50) is undefined.',optional:true}
 ],
 teacherGuide:'90分钟：开场与百分比15；斜率和弹性20；分类15；收入连接15；10%两案例15；练习出口10。英文话术：“Slope counts units; elasticity compares percentages.” “Keep the sign; classify the magnitude.” “Revenue is not profit.” 全课使用有符号E，分类用|E|。P=50未定义。需求线性使起点百分比数量关系精确，不能扩展为一般非线性的大变动规则。',
 film:[
 {from:0,to:15,title:'Two tags rise',narration:'Two bright shop windows display the same percentage increase. Both price tags rise by ten percent, but the waiting crowds begin to move differently.',caption:'Same 10% price rise.',scene:'Two collage storefronts raise matching 10% banners while crowd tokens separate.'},
 {from:15,to:30,title:'The starting crowd',narration:'One window starts with many buyers and a low price. The other begins with fewer buyers and a higher price, changing the comparison base.',caption:'Different starting points.',scene:'A large blue crowd and a small coral crowd appear beside contrasting unnumbered tags.'},
 {from:30,to:45,title:'The same straight line',narration:'A single straight demand line connects both windows. Its slope stays constant, yet price and quantity ratios change as the marker moves along it.',caption:'Constant slope. Changing ratio.',scene:'Storefronts morph into two points on one descending line with ratio bars below.'},
 {from:45,to:60,title:'Percentages answer differently',narration:'A small loss of buyers can be a tiny share of one crowd and a large share of another. Elasticity compares these proportional responses.',caption:'How large is the share?',scene:'Equal-sized buyer tokens leave unequal crowds; transparent fraction frames reveal contrasting shares.'},
 {from:60,to:75,title:'Revenue responds',narration:'Price and quantity now form rectangles of revenue. One rectangle grows after the increase, while the other shrinks, despite the matching percentage price changes.',caption:'Revenue can move in opposite directions.',scene:'Blue and coral revenue rectangles resize with opposite area changes.'},
 {from:75,to:90,title:'Measure the response',narration:'The two windows pause beside the demand line. Why does the same ten percent increase cause a different shock, and which measure explains the difference?',caption:'Why do equal price shocks differ?',scene:'The crowds, tags, and linear demand curve hold under the final question without answers.'}
 ]
};
