import type {MathematicsLesson} from '../types.js';
import {page,source,text,math,art,plot,table,diagram} from '../authoring.js';
const ref=source('6.2.3',506,507);const discount=source('6.2.4',508,509);
export const lesson16:MathematicsLesson={
 number:16,title:'Investment Flows and a Complete Decision',filmTitle:'Which Flow Wins?',openingQuestion:'Which investment stream accumulates more over one year?',
 outcomes:['Integrate an investment rate to obtain a cumulative amount.','Compare streams over a specified horizon and identify crossing times.','Connect modeling, derivatives, optimization, and accumulation in one decision.'],
 vocabulary:[['investment flow','Money invested per unit of time.'],['cumulative investment','Total money invested up to a given time.'],['horizon','The endpoint of the comparison period.'],['crossing time','A time when two cumulative amounts are equal.'],['discount factor','A factor converting a future payment to present value.'],['present value','A future amount expressed in current monetary terms.']],sources:[ref,discount],
 slides:[
 page(16,'01','Which flow wins?','OPENING SCENE',ref,[art('opening',790,230,710,560,'Two bright paper money streams entering transparent vessels'),text('One stream starts strong.\nAnother grows during the year.',80,295,650,175,46),text('Compare the full path, not one snapshot.',90,620,660,105,38)],{openingFilm:true,publicLabel:'Teaching scenario',question:'Which stream accumulates more by the end of a year?',teachingCue:'开场保持结果未知，强调比较期限。',assistantCue:'Discuss rate versus total without revealing the winning stream.'}),
 page(16,'02','Two investment rates','READ THE MODELS',ref,[math('A(t)=10000,\\quad B(t)=6000+12000t',90,305,1390,130,52),text('0 ≤ t ≤ 1 year • rates in €/year\nThese are contributions, not investment returns.',110,615,1300,150,38)],{question:'Does integrating these flows measure a return on investment?',answer:'No. It measures the amount contributed.',teachingCue:'投资流投入而非回报，避免财务建议含义。',assistantCue:'Treat both flows as deterministic teaching contribution models, not predicted returns.'}),
 page(16,'03','Which rate is larger now?','INSTANTANEOUS COMPARISON',ref,[plot({xRange:[0,1],yRange:[0,20000],xLabel:'Time (years)',yLabel:'Flow (€/year)',curves:[{kind:'polynomial',coefficients:[10000],color:'blue',label:'A'},{kind:'polynomial',coefficients:[6000,12000],color:'coral',label:'B'}]},70,230,1010,560),text('A begins higher.\nB ends higher.',1130,365,380,150,39)],{question:'When are the instantaneous rates equal?',answer:'At t=1/3 year.',teachingCue:'求率交点，不当累计交点。',assistantCue:'Distinguish equality of flow rates from equality of cumulative amounts.'}),
 page(16,'04','A rate crossing is not a total crossing','FIRST EQUATION',ref,[math('10000=6000+12000t',90,310,1390,125,64),math('t=1/3',100,565,1340,110,83)],{question:'Has B caught up in total contributions at this time?',answer:'No. B has only just caught up in current rate.',teachingCue:'明确B先前落后仍需后期弥补。',assistantCue:'Do not claim cumulative equality at t=1/3.'}),
 page(16,'05','Accumulation is a definite integral','TURN RATE INTO TOTAL',ref,[math('I_A(T)=\\int_0^T A(t)\\,dt',90,285,1390,130,69),math('I_B(T)=\\int_0^T B(t)\\,dt',100,555,1340,130,69)],{question:'What is the unit of I_A and I_B?',answer:'Euros, because €/year is multiplied by years.',teachingCue:'累计下限0对应贡献初始为零。',assistantCue:'Use the stated zero initial cumulative contributions.'}),
 page(16,'06','A builds at a steady pace','INTEGRATE A',ref,[math('I_A(T)=10000T',90,310,1390,125,75),text('At T = 0.5, A has contributed €5000.\nAt T = 1, A has contributed €10000.',110,605,1300,170,43)],{question:'Why is the cumulative graph a straight line?',answer:'Its derivative is the constant flow 10000.',teachingCue:'函数形状和导数联系。',assistantCue:'This straight line is cumulative contribution, not the rate graph.'}),
 page(16,'07','B builds faster as time passes','INTEGRATE B',ref,[math('I_B(T)=6000T+6000T^2',90,310,1390,125,67),text('At T = 0.5, B has contributed €4500.\nAt T = 1, B has contributed €12000.',110,605,1300,170,43)],{question:'Why does B still trail at half a year?',answer:'Its early lower rate has not yet been offset by its later higher rate.',teachingCue:'瞬时流高于A不代表累计已超过。',assistantCue:'Use the cumulative values rather than the current rates for this comparison.'}),
 page(16,'08','Compare amounts at several horizons','THE HORIZON MATTERS',ref,[table(['T (years)','A cumulative (€)','B cumulative (€)'],[['0.25','2500','1875'],['0.5','5000','4500'],['1','10000','12000']],90,260,1400,380)],{question:'Can the answer change when the comparison horizon changes?',answer:'Yes. A leads at half a year; B leads at one year.',teachingCue:'期限必须出现在决策陈述。',assistantCue:'Avoid an unqualified statement that one stream is always larger.'}),
 page(16,'09','Find the cumulative crossing','SECOND EQUATION',ref,[math('10000T=6000T+6000T^2',90,290,1390,130,64),math('T(6000T-4000)=0',100,545,1340,120,63)],{question:'What is the nonzero crossing time?',answer:'T=2/3 year.',teachingCue:'保留T=0平凡解，说明非零追平。',assistantCue:'Return both T=0 and the nonzero crossing 2/3.'}),
 page(16,'10','Rates cross first, totals cross later','TWO EVENTS',ref,[diagram('number-line',['0','Rate crossing: 1/3','Total crossing: 2/3','1'],90,295,1390,230),text('A head start needs time to overcome.',110,680,1300,100,44)],{question:'Why are the two crossing times different?',answer:'Cumulative totals include all earlier rates, not only the current rate.',teachingCue:'用head start帮助国际生理解。',assistantCue:'Explain the accumulated early gap and later catch-up.'}),
 page(16,'11','The cumulative graph tells the decision','TOTALS',ref,[plot({xRange:[0,1],yRange:[0,13000],xLabel:'Horizon T (years)',yLabel:'Contributions (€)',curves:[{kind:'polynomial',coefficients:[0,10000],color:'blue',label:'A'},{kind:'polynomial',coefficients:[0,6000,6000],color:'coral',label:'B'}],points:[{x:2/3,y:20000/3,label:'Catch-up'}]},70,230,1050,570),text('Blue: steady total\nCoral: accelerating total',1170,355,340,150,33)],{question:'Which curve is above after T=2/3?',answer:'B’s cumulative curve.',teachingCue:'当前图纵轴改为欧元，提醒不同于第3页。',assistantCue:'Read the accumulation graph with euros on the vertical axis.'}),
 page(16,'12','Compare by integrating the gap','ONE CALCULATION',ref,[math('I_B(T)-I_A(T)=\\int_0^T[B(t)-A(t)]\\,dt',90,290,1400,150,49),math('=6000T^2-4000T',100,570,1340,110,65)],{question:'What does a positive gap mean?',answer:'B has contributed more in total by horizon T.',teachingCue:'累计差不是流速差，两者名称区分。',assistantCue:'Keep the net cumulative gap distinct from B(T)−A(T).'}),
 page(16,'13','The whole-year difference','A CLEAR RESULT',ref,[math('I_B(1)-I_A(1)=2000',90,310,1390,125,70),art('case',1080,535,400,275,'Two investment vessels with different final fill levels'),text('B contributes €2000 more\nover the full year.',110,580,870,160,45)],{question:'Does this imply B is the better investment product?',answer:'No. These models compare contribution amounts, not returns, risks, or suitability.',teachingCue:'不把投入更多当收益更好。',assistantCue:'Do not infer a financial recommendation from contribution totals.'}),
 page(16,'14','Recover the rate from the total','CHECK BY DIFFERENTIATION',ref,[math('I_A^{\\prime}(T)=10000',90,300,1390,110,68),math('I_B^{\\prime}(T)=6000+12000T',100,550,1340,120,63)],{question:'How can both accumulation formulas be verified?',answer:'Differentiate them and check I_A(0)=I_B(0)=0.',teachingCue:'复用第13讲双检验。',assistantCue:'Check both rate recovery and initial totals.'}),
 page(16,'15','A complete business problem starts with a model','COURSE SYNTHESIS',ref,[diagram('flow',['Quantities and units','Function and domain','Question and objective'],95,280,1350,230),text('A precise question chooses the mathematical tool.',110,680,1300,105,41)],{question:'Which information must come before calculation?',answer:'Variable meaning, units, feasible domain, and the quantity being asked for.',teachingCue:'全课程回顾用具体任务分类。',assistantCue:'Keep this synthesis within single-variable models.'}),
 page(16,'16','Need the current rate? Differentiate.','TOOL SELECTION',ref,[math('C(q)=100+20q+0.5q^2',90,300,1390,125,60),math('MC(20)=C^{\\prime}(20)=40',100,555,1340,110,65)],{question:'Is €40 the exact cost of the twenty-first unit?',answer:'No. It is a marginal rate; the exact increment is €40.50.',teachingCue:'第9讲关键边界再检。',assistantCue:'Distinguish derivative from finite one-unit difference.'}),
 page(16,'17','Need the best output? Compare candidates.','TOOL SELECTION',ref,[math('\\pi(q)=80q-1.5q^2-100',90,300,1390,125,62),text('Find stationary candidates.\nCheck the feasible interval and endpoints.',110,610,1300,160,42)],{question:'Does MR=MC alone finish this task?',answer:'No. Feasibility and maximum verification are still required.',teachingCue:'第11讲候选与决策区分。',assistantCue:'Require interval and endpoint checks; integer output needs value comparisons.'}),
 page(16,'18','Need the accumulated amount? Integrate.','TOOL SELECTION',ref,[math('A(t)=10000\\Rightarrow\\int_0^1A(t)\\,dt=10000',90,300,1390,130,54),text('The horizon and starting level matter.',110,650,1300,105,44)],{question:'Why does the horizon appear in an accumulation question?',answer:'A flow accumulates over a specified interval, so the total depends on its length and location.',teachingCue:'第14讲区间与初值作用再确认。',assistantCue:'Do not report a total without its time interval and unit.'}),
 page(16,'19','Three questions, three tools','COMPARE',ref,[table(['Question','Tool','Main check'],[['What happens nearby?','Derivative','Local vs finite change'],['Which feasible value is best?','Optimization','Candidates and boundaries'],['How much adds up?','Definite integral','Interval, sign, and units']],90,255,1400,395)],{question:'Which tool answers the opening film question?',answer:'Definite integration over the one-year horizon.',teachingCue:'问题决定工具，不从公式找问题。',assistantCue:'Connect the opening question to accumulated contributions.'}),
 page(16,'20','A new pair of streams','GUIDED PRACTICE',ref,[math('U(t)=8000,\\quad V(t)=4000+8000t',90,300,1390,125,55),text('Compare contributions over [0,1].',110,635,1300,100,44)],{question:'Which stream contributes more over one year?',answer:'They tie at €8000 each.',teachingCue:'不是所有增长流一年内更多，保留平局。',assistantCue:'Compute both integrals and allow a tie.'}),
 page(16,'21','The tie hides different timing','INTERPRET',ref,[math('I_U(0.5)=4000,\\quad I_V(0.5)=3000',90,305,1390,125,56),text('Equal annual totals do not mean\nequal contributions at every time.',110,610,1300,155,44)],{question:'Which stream contributes earlier in this example?',answer:'U. Its cumulative contribution exceeds V before year-end.',teachingCue:'年度同总量不等于同时间路径。',assistantCue:'Use I_U−I_V=4000T(1−T)>0 on 0<T<1.'}),
 page(16,'22','Repair the snapshot claim','ERROR DETECTIVE',ref,[text('“B has the larger rate at t = 0.5,\nso it has already contributed more.”',100,290,1370,190,47),math('I_A(0.5)=5000>I_B(0.5)=4500',110,620,1300,110,55)],{question:'What information did the claim ignore?',answer:'All earlier contributions, including A’s head start.',teachingCue:'用反例数值排除瞬时替代累计。',assistantCue:'Differentiate rate comparison from integral comparison.'}),
 page(16,'23','State a bounded conclusion','COMMUNICATE',ref,[art('case',80,240,490,520,'A paper timeline beside two money vessels'),text('“Over the one-year horizon,\nB contributes €12000 and A €10000.\nThis compares amounts, not returns.”',670,305,830,245,39)],{question:'What makes this statement complete?',answer:'It includes the horizon, both totals, units, and what the comparison measures.',teachingCue:'全英文完整决策与证据边界。',assistantCue:'Do not turn contribution comparison into investment advice.'}),
 page(16,'24','Build, differentiate, integrate, decide','COURSE EXIT',ref,[diagram('steps',['Define a useful model','Choose the correct tool','Check and explain the result'],100,285,1330,230),text('Numbers become decisions only with units and context.',110,680,1300,115,40)],{question:'What should every final mathematical answer contain?',answer:'A checked value or function, correct units and domain, and an interpretation tied to the question.',teachingCue:'最终出口检查，允许学生举一例说明。',assistantCue:'Review single-variable tools without requiring the optional discounting material.'}),
 page(16,'25','Future euros can have a present value','OPTIONAL CHALLENGE',discount,[math('PV=\\int_0^1 f(t)e^{-rt}\\,dt',90,300,1390,145,75),text('r = 0.10 per year is a continuous discount rate.\nThe factor weights later contributions less.',110,625,1300,150,39)],{optionalChallenge:true,question:'Is this a 10% effective annual discount rate?',answer:'No. It is a continuous rate; the one-year discount factor is e^{-0.10}.',teachingCue:'连续贴现率与有效年利率区分，作为选学。',assistantCue:'Use a continuous rate, contributions at time t, and present value at time zero.'}),
 page(16,'26','Compare discounted contributions','OPTIONAL CHALLENGE',discount,[table(['Stream','Undiscounted (€)','PV at r=0.10 (€)'],[['A','10000','9516.26'],['B','12000','11324.36']],90,270,1400,300),text('Discounting changes the comparison weights.\nIt does not turn contributions into returns.',110,675,1300,125,40)],{optionalChallenge:true,question:'What extra assumption was needed for this comparison?',answer:'A specified continuous discount rate and valuation time.',teachingCue:'数值可用计算器验积分，不能把PV当实现收益。',assistantCue:'Treat the values as discounted contribution amounts, not profit, return, or a recommendation.'})
 ],
 exercises:[
 {id:'16-1',question:'Find cumulative contributions for A(t)=10000 and B(t)=6000+12000t, starting at zero.',answer:'I_A(T)=10000T; I_B(T)=6000T+6000T².',solution:'Integrate each rate from 0 to T. Both initial totals are zero and their derivatives recover their rates.'},
 {id:'16-2',question:'Compare the amounts at T=0.5.',answer:'A=€5000; B=€4500.',solution:'10000×0.5=5000. For B, 6000×0.5+6000×0.25=4500. A leads by €500.'},
 {id:'16-3',question:'Compare the amounts at T=1.',answer:'A=€10000; B=€12000.',solution:'Substitute T=1 into the cumulative functions. B contributes €2000 more over the year.'},
 {id:'16-4',question:'Find the nonzero cumulative crossing time.',answer:'2/3 year.',solution:'Set 10000T=6000T+6000T². Factor T(6000T−4000)=0. Apart from T=0, equality occurs at T=2/3.'},
 {id:'16-5',question:'Find the rate crossing and explain why it differs from the cumulative crossing.',answer:'1/3 year.',solution:'10000=6000+12000t gives t=1/3. At that point the rates match, but B still has an earlier cumulative shortfall. It catches up only at 2/3.'},
 {id:'16-6',question:'For U=8000 and V=4000+8000t, compare annual amounts and half-year amounts.',answer:'Annual tie €8000; half-year U=€4000, V=€3000.',solution:'I_U=8000T and I_V=4000T+4000T². Substitution at T=1 gives 8000 each; at 0.5 gives 4000 and 3000.'},
 {id:'16-7',question:'At continuous discount rate r=0.10, calculate the present values of A and B over one year.',answer:'A≈€9516.26; B≈€11324.36.',solution:'PV_A=10000(1−e^{-r})/r. For B, PV_B=6000(1−e^{-r})/r+12000[1−(1+r)e^{-r}]/r². Substitute r=0.10. These are contribution present values, not returns.',optional:true}
 ],
 teacherGuide:'90分钟：开场与流量15；累计积分20；两种交点15；图与期限10；课程综合15；练习出口15。英文话术：“A snapshot is not the whole path.” “Rates cross before totals catch up.” “State the horizon.” 所有投资流是贡献率而非投资收益，不据此推荐金融产品。第25、26页连续贴现选学，主线可以完整跳过。核心综合再次核验边际率、端点最优、积分单位。',
 film:[
 {from:0,to:15,title:'Two streams begin',narration:'Two paper money streams enter transparent vessels. One begins with a strong steady flow, while the other starts more slowly and gathers speed over time.',caption:'Two paths. One year.',scene:'A blue constant stream and a coral growing stream enter separate paper-glass vessels.'},
 {from:15,to:30,title:'A strong start',narration:'The steady stream builds an early lead. Its vessel fills faster at first, showing why a strong beginning can matter even when another flow grows.',caption:'An early lead accumulates.',scene:'The blue vessel fills above the coral vessel during the early timeline.'},
 {from:30,to:45,title:'The rates meet',narration:'The growing stream reaches the same current rate, then becomes faster. Yet its vessel remains behind, because its earlier contributions were smaller than the steady stream.',caption:'Equal rates do not mean equal totals.',scene:'Stream widths match, then coral grows wider while its vessel remains lower.'},
 {from:45,to:60,title:'The totals catch up',narration:'Later, the accumulated amounts finally meet. The past shortfall has been recovered, and the growing stream can now move ahead over the remaining comparison period.',caption:'Totals catch up later.',scene:'Vessel levels align after the rate-crossing marker, then the coral level begins to exceed blue.'},
 {from:60,to:75,title:'Choose the horizon',narration:'A movable timeline selects the comparison date. Earlier and later horizons reveal different leaders, so the answer must include the period over which contributions are measured.',caption:'The horizon changes the answer.',scene:'A slider moves between early and late timeline points, with unnumbered vessel levels changing.'},
 {from:75,to:90,title:'Find the total',narration:'The two vessels pause at the end of the year. Which stream has contributed more, and what calculation compares the complete paths rather than one instant?',caption:'Which flow wins over one year?',scene:'The vessels and rate curves freeze without totals under the final question.'}
 ]
};
