import type {MathematicsLesson} from '../types.js';
import {page,source,text,math,art,plot,table,diagram,shape} from '../authoring.js';
const ref=source('6.2',499,512,'Riemann sums and the Fundamental Theorem of Calculus: supplementary explanation');
export const lesson14:MathematicsLesson={
 number:14,title:'Definite Integrals: Adding a Changing Flow',filmTitle:'A Staircase Becomes an Area',openingQuestion:'How much water arrives when the flow keeps changing?',
 outcomes:['Estimate an accumulated quantity using rectangles.','Evaluate a definite integral using an antiderivative.','Interpret signed area and attach correct units.'],
 vocabulary:[['flow rate','Amount passing per unit of time.'],['accumulation','A total built by adding small contributions.'],['partition','A division of an interval into smaller intervals.'],['Riemann sum','A sum of height times width for chosen sample points.'],['definite integral','The limit of suitable sums over an interval.'],['signed area','Area above an axis counted positively and below negatively.'],['Fundamental Theorem','A link between accumulation and antiderivatives.']],sources:[ref],
 slides:[
 page(14,'01','A tank fills. The rate changes.','OPENING SCENE',ref,[art('opening',760,225,740,570,'Paper-cut water tank with a rising stream'),text('A meter shows litres per minute.\nThe tank records litres.',80,270,630,180,44),math('r(t)=2+t',80,520,630,80,60),text('0 ≤ t ≤ 4 minutes',80,665,630,60,32)],{openingFilm:true,publicLabel:'Teaching scenario',question:'How can a changing rate become one total?',teachingCue:'播放开场片；停在问题处，区分流速单位与累计水量。',assistantCue:'Discuss rate in litres per minute and volume in litres. Do not reveal the final volume.'}),
 page(14,'02','A constant rate is a rectangle','A FAMILIAR START',ref,[plot({xRange:[0,4],yRange:[0,7],xLabel:'Time (min)',yLabel:'Rate (L/min)',curves:[{kind:'polynomial',coefficients:[3],color:'blue'}],area:{curve:0,from:0,to:4}},70,230,840,540),math('3\\times4=12\\text{ L}',980,350,500,100,48),text('Height × width\nRate × time',980,540,500,150,38)],{question:'Which unit disappears when rate is multiplied by time?',answer:'Minutes cancel, leaving litres.',teachingCue:'先读矩形两边的单位，再说明面积的物理意义。',assistantCue:'Explain dimensional cancellation using a constant rate only.'}),
 page(14,'03','Four readings, four small totals','LEFT ENDPOINTS',ref,[table(['Interval (min)','Left rate (L/min)','Volume (L)'],[['0–1','2','2'],['1–2','3','3'],['2–3','4','4'],['3–4','5','5']],80,245,920,430),math('L_4=2+3+4+5',1050,330,450,130,40),text('Every strip is one minute wide.',100,730,1280,60,36)],{question:'Why does the left reading underestimate this increasing flow?',answer:'The rate increases during each interval, so the left reading is its lowest value.',teachingCue:'逐个区间对应水量；结论先由增加趋势解释。',assistantCue:'Keep the distinction between a rate reading and a volume contribution explicit.'}),
 page(14,'04','The staircase sits below the curve','RECTANGLE ESTIMATE',ref,[plot({xRange:[0,4],yRange:[0,7],xLabel:'Time (min)',yLabel:'Rate (L/min)',curves:[{kind:'polynomial',coefficients:[2,1],color:'blue'}],rectangles:{curve:0,from:0,to:4,n:4}},70,225,970,580),math('L_4=14\\text{ L}',1100,365,380,100,42),text('An estimate,\nnot an exact total.',1100,540,380,140,34)],{question:'Where is the missing volume visible?',answer:'In the thin regions between each rectangle top and the curve.',teachingCue:'用图中矩形与曲线的缝隙指认误差，不只宣布答案。',assistantCue:'Describe the missing strips without implying all left sums underestimate every function.'}),
 page(14,'05','A right reading gives another estimate','SAME WIDTH, NEW HEIGHT',ref,[table(['Interval','Right rate','Volume'],[['0–1','3','3'],['1–2','4','4'],['2–3','5','5'],['3–4','6','6']],90,240,870,440),math('R_4=18\\text{ L}',1030,365,460,100,44),text('For this increasing rate:\n14 L ≤ true volume ≤ 18 L',1030,530,460,170,34)],{question:'What can be known before exact integration?',answer:'The total lies between 14 and 18 litres.',teachingCue:'强调上下界依赖此例单调递增的性质。',assistantCue:'State the bound for this increasing linear flow; do not generalize to arbitrary functions.'}),
 page(14,'06','Make the strips thinner','MORE OBSERVATIONS',ref,[plot({xRange:[0,4],yRange:[0,7],xLabel:'Time (min)',yLabel:'Rate (L/min)',curves:[{kind:'polynomial',coefficients:[2,1],color:'blue'}],rectangles:{curve:0,from:0,to:4,n:8}},70,230,970,550),math('\\Delta t=\\frac4n',1110,345,380,90,46),text('Move the rectangle count.\nWatch the gaps shrink.',1110,505,380,180,32)],{interaction:{kind:'parameter',key:'n',label:'Rectangle count',min:2,max:40,step:2,initial:8},question:'Does more rectangles mean a different tank or a better estimate?',answer:'A better estimate of the same accumulated volume.',teachingCue:'拖动矩形数，提醒曲线和时间区间始终不变。',assistantCue:'Treat n as the number of rectangles, not a physical change in the flow.'}),
 page(14,'07','A pattern in the estimates','CONVERGENCE',ref,[table(['n','Left sum (L)','Right sum (L)'],[['2','12','20'],['4','14','18'],['8','15','17'],['16','15.5','16.5']],95,240,930,460),math('L_n=16-\\frac8n',1080,310,420,100,39),math('R_n=16+\\frac8n',1080,470,420,100,39),text('Both approach the same total.',105,755,1320,55,34)],{question:'What number do both columns approach?',answer:'16 litres.',teachingCue:'允许先观察小数列，再读表达式中随n缩小的项。',assistantCue:'Use these formulas only for r(t)=2+t on [0,4].'}),
 page(14,'08','The integral names that limit','NOTATION',ref,[math('\\int_0^4 (2+t)\\,dt',100,285,950,170,78),diagram('flow',['Lower limit: 0','Rate: 2 + t','Upper limit: 4'],100,570,1340,170),text('Add rate × tiny time widths.',1090,335,420,160,34)],{question:'What does dt remind us to measure?',answer:'The width of each small time interval.',teachingCue:'把每个符号对应到前面的矩形，不把dt当独立数字。',assistantCue:'Explain dt through small interval widths; avoid unsupported infinitesimal algebra.'}),
 page(14,'09','An antiderivative saves the work','REVERSE A DERIVATIVE',ref,[math('F(t)=2t+\\frac12t^2',90,275,980,100,64),math('F\\prime(t)=2+t',90,445,980,100,64),art('case',1120,235,370,410,'A collage of a tank and a clock'),text('One formula describes cumulative change.',100,720,1340,65,34)],{question:'How can you check that F is an antiderivative?',answer:'Differentiate F and recover 2+t.',teachingCue:'现场求导核验，连接上一讲的不定积分。',assistantCue:'Verify the derivative of the proposed antiderivative before evaluating limits.'}),
 page(14,'10','Subtract the two endpoint values','FUNDAMENTAL THEOREM',ref,[math('\\int_a^b f(t)\\,dt=F(b)-F(a)',100,280,1380,140,64),text('If f is continuous on [a,b]\nand F′ = f on that interval.',115,540,1310,150,40),shape('yellow',90,750,1360,12)],{question:'Why do we subtract F(a)?',answer:'To remove accumulation before the starting point a.',teachingCue:'说明本课连续函数条件，端点相减而非只代上限。',assistantCue:'State the continuous-function version of the Fundamental Theorem accurately.'}),
 page(14,'11','The tank receives sixteen litres','WORKED EXAMPLE',ref,[math('\\left[2t+\\frac12t^2\\right]_0^4',90,270,910,150,64),math('(8+8)-0=16\\text{ L}',90,500,910,120,56),diagram('receipt',['Rate','Duration','Accumulated volume'],1070,250,420,420,['2+t L/min','4 min','16 L'])],{publicLabel:'Worked example',question:'Does the exact result agree with both earlier bounds?',answer:'Yes. 14 ≤ 16 ≤ 18.',teachingCue:'完整写上下限，最后与估计区间进行交叉检查。',assistantCue:'Show endpoint subtraction and the litres unit; distinguish exact total from earlier estimates.'}),
 page(14,'12','The starting time matters','A NEW INTERVAL',ref,[plot({xRange:[0,4],yRange:[0,7],xLabel:'Time (min)',yLabel:'Rate (L/min)',curves:[{kind:'polynomial',coefficients:[2,1],color:'blue'}],area:{curve:0,from:1,to:3}},70,230,910,560),math('\\int_1^3(2+t)\\,dt',1050,315,440,110,43),math('F(3)-F(1)=8',1050,530,440,100,39)],{question:'Why is this total smaller than the four-minute total?',answer:'It includes only the two-minute interval from 1 to 3.',teachingCue:'先读阴影左右边界，再计算；避免把上限误当时长。',assistantCue:'Clarify that the duration is 3−1 minutes, not three minutes.'}),
 page(14,'13','An integral can be negative','SIGNED ACCUMULATION',ref,[plot({xRange:[0,3],yRange:[-4,4],xLabel:'Time',yLabel:'Net flow',curves:[{kind:'polynomial',coefficients:[-2,1],color:'coral'}],area:{curve:0,from:0,to:3}},70,230,940,560),text('Below zero:\nwater leaves the tank.',1070,290,420,150,38),math('\\int_0^3(t-2)\\,dt=-\\frac32',1040,555,490,110,35)],{question:'Does a negative integral mean negative physical water?',answer:'No. It means a net loss of 1.5 units over the interval.',teachingCue:'把负号解释为净流出，而非负的存量。',assistantCue:'Distinguish a negative change in volume from an impossible negative volume level.'}),
 page(14,'14','Net change differs from total movement','TWO QUESTIONS',ref,[table(['Quantity','Meaning','Result'],[['Net flow','Inflow minus outflow','−1.5'],['Total movement','Inflow plus outflow','2.5']],100,275,1300,250),math('\\int_0^3 |t-2|\\,dt=2+0.5',100,595,1320,100,52),text('Split at t = 2, where the rate changes sign.',110,750,1300,55,32)],{question:'Why does total movement need an absolute value?',answer:'It counts both directions positively.',teachingCue:'用0到2的三角形与2到3的小三角形解释绝对值积分。',assistantCue:'Use signed area for net change and absolute rate for total movement.'}),
 page(14,'15','A definite integral has no free constant','CONSTANTS CANCEL',ref,[math('[F(t)+C]_a^b',90,275,1260,110,64),math('F(b)+C-F(a)-C',90,475,1260,110,60),text('A fixed interval fixes the accumulated change.',100,705,1330,80,36)],{question:'Where did the constant C go?',answer:'It cancels when the two endpoint values are subtracted.',teachingCue:'承接上一讲积分常数，区分函数族与确定区间上的数值。',assistantCue:'Explain cancellation; do not append +C to the final definite-integral value.'}),
 page(14,'16','Accumulation can be a function','A MOVING ENDPOINT',ref,[plot({xRange:[0,4],yRange:[0,7],xLabel:'Time',yLabel:'Rate',curves:[{kind:'polynomial',coefficients:[2,1],color:'blue'}],area:{curve:0,from:0,to:2}},70,230,950,540),math('A(x)=\\int_0^x(2+t)\\,dt',1070,320,440,120,35),math('A\\prime(x)=2+x',1070,560,440,90,39)],{interaction:{kind:'parameter',key:'x',label:'End time (min)',min:0,max:4,step:0.25,initial:2},question:'What rate describes the change in accumulated volume at x?',answer:'The current flow rate 2+x.',teachingCue:'拖动右端点，用增加的薄条解释累计函数的导数。',assistantCue:'Distinguish integration variable t from moving endpoint x.'}),
 page(14,'17','Read the units before integrating','DIMENSION CHECK',ref,[diagram('flow',['L/min × min','€/unit × units','people/hour × hours'],100,290,1340,260,['Litres','Euros','People']),text('The vertical unit × the horizontal unit\nis the unit of accumulated change.',130,655,1270,140,42)],{question:'What does integrating marginal cost over quantity produce?',answer:'A change in total cost, measured in currency.',teachingCue:'让三种单位依次消去；与第九讲边际概念相连。',assistantCue:'Integrating marginal cost gives cost change; initial or fixed cost is needed for total cost level.'}),
 page(14,'18','A decreasing rate still accumulates','POSITIVE HEIGHTS',ref,[plot({xRange:[0,4],yRange:[0,7],xLabel:'Time (h)',yLabel:'Rate (units/h)',curves:[{kind:'polynomial',coefficients:[6,-1],color:'green'}],area:{curve:0,from:0,to:4}},70,230,950,550),math('\\int_0^4(6-t)\\,dt=16',1070,360,450,120,39),text('Falling rate.\nGrowing total.',1070,555,410,145,40)],{question:'Is the accumulated total falling because the rate falls?',answer:'No. The rate remains positive, so the total continues to grow.',teachingCue:'区分流速下降与累计量下降，这是常见概念误区。',assistantCue:'A positive decreasing rate produces an increasing accumulation at a slowing pace.'}),
 page(14,'19','Estimate before you calculate','A SANITY CHECK',ref,[art('case',70,235,470,510,'Bright tank illustration with time markers'),text('On [0,4], the rate stays\nbetween 2 and 6 L/min.',630,265,870,140,43),math('8\\leq\\int_0^4r(t)\\,dt\\leq24',630,525,870,120,46),text('An answer of 40 L fails this check.',640,725,850,55,33)],{question:'What simple bounds use only the smallest and largest rates?',answer:'2×4=8 litres and 6×4=24 litres.',teachingCue:'计算前先做粗界限，帮助发现代数失误。',assistantCue:'Apply min-rate and max-rate bounds only over the stated interval.'}),
 page(14,'20','Three errors, three repairs','ERROR DETECTIVE',ref,[table(['Claim','Repair'],[['∫₀⁴(2+t) dt = 2+4','Find an antiderivative, then subtract endpoints.'],['The answer is 16 L/min','The integrated unit is litres.'],['A negative integral is impossible','A signed integral can describe net outflow.']],90,250,1420,430),text('Check method, units, and meaning.',110,745,1300,60,40)],{question:'Which error changes the meaning without changing the number?',answer:'Reporting L/min instead of L changes volume into a rate.',teachingCue:'三条分别检查运算、量纲和符号，不能只修数字。',assistantCue:'Correct these three specific errors with concise English explanations.'}),
 page(14,'21','Try a different flow','GUIDED PRACTICE',ref,[math('r(t)=3+2t,\\quad0\\leq t\\leq2',100,290,1330,110,60),diagram('steps',['Find F(t)','Evaluate F(2) and F(0)','Subtract and attach units'],100,560,1330,170)],{question:'How many litres arrive over these two minutes?',answer:'[3t+t²]₀²=6+4=10 litres.',teachingCue:'留出独立书写时间，揭示后检查端点和单位。',assistantCue:'Offer a first-step hint unless the teacher has revealed the solution.'}),
 page(14,'22','Choose the correct operation','DECISION CHECK',ref,[table(['Information','Question','Operation'],[['Volume function V(t)','Current flow rate?','Differentiate V.'],['Flow rate r(t)','Net added volume?','Integrate r over time.'],['Flow rate r(t), initial V₀','Final volume?','Add V₀ to the integral.']],90,250,1410,430)],{question:'A tank starts with 5 L and receives 16 L. What is its final volume?',answer:'21 litres, provided no other inflow or outflow occurs.',teachingCue:'明确初始水量不由流速函数自动给出。',assistantCue:'State the no-other-flow assumption when converting accumulated inflow into final volume.'}),
 page(14,'23','Explain the result to a manager','FROM SYMBOLS TO WORDS',ref,[math('\\int_0^4(2+t)\\,dt=16',90,285,950,130,64),text('“The tank receives 16 litres\nin the first four minutes.”',95,525,940,170,43),art('case',1120,250,380,460,'A water storage case illustration')],{question:'What must a useful interpretation include?',answer:'The quantity, the interval, and the unit.',teachingCue:'训练一句完整英文解释，避免只读出积分号。',assistantCue:'Require quantity, time interval, and unit in the explanation.'}),
 page(14,'24','Rate → strips → total','EXIT CHECK',ref,[diagram('flow',['Changing rate','Rectangle estimates','Definite integral'],100,275,1330,190),text('1. What does a rectangle contribute?\n2. Why subtract endpoint values?\n3. When can net change be negative?',115,580,1300,210,38)],{question:'What connects differentiation and accumulation?',answer:'An antiderivative evaluates a definite integral, and the derivative of accumulation recovers a continuous rate.',teachingCue:'用三个短问确认概念与量纲，不引入新的技术。',assistantCue:'Review only rectangles, endpoint subtraction, signed accumulation, and the continuous-function theorem.'}),
 page(14,'25','Midpoints can do better','OPTIONAL CHALLENGE',ref,[plot({xRange:[0,4],yRange:[0,7],xLabel:'Time',yLabel:'Rate',curves:[{kind:'polynomial',coefficients:[2,1],color:'blue'}]},70,230,910,550),math('M_4=2.5+3.5+4.5+5.5',1040,315,480,130,31),text('Here, M₄ = 16 exactly.\nThe rate is linear.',1050,575,450,140,34)],{optionalChallenge:true,question:'Is a midpoint sum always exact?',answer:'No. It is exact for this linear function but generally only an approximation.',teachingCue:'展示线性函数中误差对称抵消，禁止推广成一般精确规则。',assistantCue:'Explain why linearity makes this midpoint sum exact and why nonlinear functions need not share that property.'}),
 page(14,'26','Reverse the journey','OPTIONAL CHALLENGE',ref,[math('\\int_b^a f(t)\\,dt=-\\int_a^b f(t)\\,dt',100,300,1380,130,57),math('\\int_4^0(2+t)\\,dt=-16',105,580,1300,100,55)],{optionalChallenge:true,question:'Does reversing the limits change the flow law?',answer:'No. It changes the orientation of accumulation and therefore its sign.',teachingCue:'用端点差反转证明符号，不赋予负时间的物理解释。',assistantCue:'Explain oriented accumulation using F(a)−F(b), without implying a negative physical duration.'})
 ],
 exercises:[
 {id:'14-1',question:'A constant rate is 5 L/min for 3 minutes. Find the added volume.',answer:'15 L.',solution:'Volume = rate × duration = 5 L/min × 3 min = 15 L.'},
 {id:'14-2',question:'For r(t)=2+t on [0,4], calculate a left sum with four equal intervals.',answer:'14 L.',solution:'Each width is 1 min. Left rates are 2, 3, 4, and 5 L/min. The sum is (2+3+4+5)×1=14 L.'},
 {id:'14-3',question:'Evaluate ∫₁³(2+t) dt.',answer:'8.',solution:'F(t)=2t+t²/2. F(3)=10.5 and F(1)=2.5. Their difference is 8.'},
 {id:'14-4',question:'Find the net change for r(t)=t−2 on [0,3].',answer:'−1.5 units.',solution:'[t²/2−2t]₀³=4.5−6=−1.5. The negative result indicates net outflow.'},
 {id:'14-5',question:'A tank begins with 5 L. Its only flow is r(t)=3+2t L/min on [0,2]. Find its final volume.',answer:'15 L.',solution:'Added volume is [3t+t²]₀²=10 L. Final volume is initial 5 L + 10 L = 15 L.'},
 {id:'14-6',question:'If A(x)=∫₀ˣ(6−t) dt for 0≤x≤4, find A′(x) and explain its sign.',answer:'A′(x)=6−x>0.',solution:'The Fundamental Theorem gives A′(x)=6−x. This rate is at least 2 on [0,4], so accumulation is increasing even though its rate falls.'},
 {id:'14-7',question:'Find the total movement for r(t)=t−2 on [0,3].',answer:'2.5 units.',solution:'Split at t=2. Total movement is ∫₀²(2−t)dt+∫₂³(t−2)dt=2+0.5=2.5.',optional:true}
 ],
 teacherGuide:'90分钟：开场与单位10；矩形估计20；极限与定积分10；基本定理和上下限15；符号与初值15；练习与出口检查20。英文话术：“A rate is not a total.” “Each strip adds height times width.” “Subtract the starting accumulation.” 核心顺序为矩形→极限→原函数，不直接跳到公式。负积分页区分净变化、总移动与存量。第25、26页选学，主路线可跳过。',
 film:[
 {from:0,to:15,title:'The meter wakes',narration:'A tap opens above a bright water tank. The meter begins to rise, but its number describes a flow rate, not the water collected.',caption:'A rate is not a total.',scene:'Cut-paper tank appears; a coral stream unfolds beside a blue rate meter.'},
 {from:15,to:30,title:'Time makes a strip',narration:'Freeze the flow for one short minute. A rectangle appears, with time along its base and litres per minute standing along its height.',caption:'Rate × time = volume.',scene:'The stream morphs into one translucent rectangular strip with unit labels.'},
 {from:30,to:45,title:'The stairs arrive',narration:'Now the flow changes. Four readings build four steps across the screen. Their heights differ, and thin empty wedges remain above each step.',caption:'Four readings. Four estimates.',scene:'Four blue rectangles rise in sequence below a diagonal coral rate curve.'},
 {from:45,to:60,title:'Smaller gaps',narration:'Split each minute into smaller pieces. The staircase becomes finer, and the empty gaps shrink. The tank itself has not changed at all.',caption:'More strips. Smaller gaps.',scene:'Rectangles subdivide deterministically from four to eight to sixteen beneath the fixed curve.'},
 {from:60,to:75,title:'One continuous shape',narration:'The tiny contributions gather into one shaded shape. Its area represents accumulated water, because a rate multiplied by time gives a volume again.',caption:'Accumulation becomes an area.',scene:'The staircase smooths visually into shaded area while unit tokens combine into litres.'},
 {from:75,to:90,title:'Leave the question open',narration:'The meter still moves, and the tank still fills. How much water arrives during these four minutes? Find a total from a changing rate.',caption:'How much water arrives?',scene:'The tank and unnumbered shaded curve pause; the question fills the open paper background.'}
 ]
};
