import type {MathematicsLesson} from '../types.js';
import {page,source,text,math,art,plot,table,diagram} from '../authoring.js';
const ref=source('4.6–4.7',329,360);
export const lesson11:MathematicsLesson={
 number:11,title:'Profit Optimization with Feasible Limits',filmTitle:'Should We Make One More?',openingQuestion:'When should a firm stop expanding output?',
 outcomes:['Build profit from revenue and cost.','Find and verify a feasible profit-maximizing output.','Distinguish an interior condition from boundary and integer decisions.'],
 vocabulary:[['profit','Revenue minus total cost.'],['feasible output','An output allowed by the stated constraints.'],['capacity','The greatest output the firm can produce.'],['candidate','A point to be checked before choosing the optimum.'],['interior optimum','A best point strictly inside the feasible interval.'],['marginal profit','The derivative of profit with respect to output.']],sources:[ref],
 slides:[
 page(11,'01','Should we make one more?','OPENING SCENE',ref,[art('opening',790,230,710,560,'Paper factory with a growing row of products'),text('More output brings revenue.\nIt also brings cost.',80,290,650,170,46),math('\\pi=R-C',90,590,650,100,78)],{openingFilm:true,publicLabel:'Teaching scenario',question:'What evidence tells a firm when to stop?',teachingCue:'开场暂停后收集收益与成本两边信息。',assistantCue:'Keep the business case hypothetical and do not reveal optimal output.'}),
 page(11,'02','A price that depends on output','DEMAND MODEL',ref,[math('p(q)=100-q',90,310,1330,110,69),text('To sell more, this firm reduces its single price.\nCore feasible interval: 0 ≤ q ≤ 40.',110,585,1310,155,40)],{question:'Why state a feasible interval before optimizing?',answer:'It rules out outputs that the firm cannot choose.',teachingCue:'单一定价假设与容量40明确。',assistantCue:'Use the continuous model on [0,40]; do not imply observed demand.'}),
 page(11,'03','Revenue is price times output','BUILD REVENUE',ref,[math('R(q)=q(100-q)=100q-q^2',90,300,1390,130,59),diagram('flow',['Output q','Price 100−q','Revenue'],100,605,1330,160)],{question:'Does maximizing output necessarily maximize revenue?',answer:'No. Falling price can offset additional sales.',teachingCue:'价与量同时变化，复用第七讲乘积结构。',assistantCue:'Explain the tradeoff within this single-price demand model.'}),
 page(11,'04','The cost side','BUILD COST',ref,[art('case',70,240,520,530,'A factory cost receipt in bright collage style'),math('C(q)=100+20q+0.5q^2',680,320,820,120,45),text('Fixed cost + variable cost',680,625,800,90,39)],{question:'What is the cost at zero output?',answer:'€100.',teachingCue:'说明本例固定成本停产时仍发生。',assistantCue:'The stated cost function includes €100 even at q=0.'}),
 page(11,'05','Put both sides together','PROFIT FUNCTION',ref,[math('\\pi(q)=R(q)-C(q)',90,290,1390,110,65),math('\\pi(q)=80q-1.5q^2-100',100,545,1330,120,60)],{question:'What does π(0)=−100 mean?',answer:'With no sales, the firm still pays its €100 fixed cost.',teachingCue:'逐项相减，成本平方项符号要核对。',assistantCue:'Distinguish negative profit from negative revenue.'}),
 page(11,'06','See the profit hill','VISUAL MODEL',ref,[plot({xRange:[0,40],yRange:[-150,1100],xLabel:'Output q',yLabel:'Profit (€)',curves:[{kind:'polynomial',coefficients:[-100,80,-1.5],color:'blue'}]},70,230,1020,570),text('A rise followed by a fall.\nThe graph suggests a candidate.',1140,340,370,185,34)],{question:'Can the graph alone justify a precise optimum?',answer:'It suggests where to look; algebra and feasibility checks provide the precise result.',teachingCue:'图作观察，数字由导数和比较确认。',assistantCue:'Do not treat a visual estimate as the exact solution.'}),
 page(11,'07','Profit changes at MR minus MC','DIFFERENTIATE',ref,[math('\\pi^{\\prime}(q)=80-3q',90,305,1360,110,68),math('MR(q)=100-2q,\\quad MC(q)=20+q',100,555,1340,110,50)],{question:'What is marginal profit at q=20?',answer:'80−60=€20 per unit.',teachingCue:'边际收入减边际成本对照第九讲。',assistantCue:'Describe marginal profit as a local rate.'}),
 page(11,'08','A positive marginal profit','BEFORE THE PEAK',ref,[math('\\pi^{\\prime}(20)=20>0',90,310,1370,110,69),text('A small feasible expansion near 20\nincreases profit in this model.',110,580,1300,155,43)],{question:'Should the firm conclude that output 20 is best?',answer:'No. Positive derivative indicates nearby higher outputs improve profit.',teachingCue:'局部方向与最佳产量分开。',assistantCue:'Limit this statement to small feasible changes.'}),
 page(11,'09','A negative marginal profit','AFTER THE PEAK',ref,[math('\\pi^{\\prime}(30)=-10<0',90,310,1370,110,68),text('Near 30 units, more output\nreduces profit.',110,590,1300,155,44)],{question:'What nearby direction improves profit at q=30?',answer:'A small reduction in output.',teachingCue:'沿导数符号判断方向。',assistantCue:'Use local monotonicity without skipping the global comparison.'}),
 page(11,'10','Solve the interior condition','CANDIDATE',ref,[math('80-3q=0',90,305,1380,110,77),math('q^*=\\frac{80}{3}\\approx26.67',100,545,1320,120,67)],{question:'Is 80/3 inside the core feasible interval?',answer:'Yes. It lies strictly between 0 and 40.',teachingCue:'候选解后立即检查区间。',assistantCue:'Call this an interior candidate until verified.'}),
 page(11,'11','MR equals MC at this candidate','EQUIVALENT CONDITION',ref,[math('100-2q=20+q',90,310,1380,110,68),math('MR(80/3)=MC(80/3)=140/3',100,555,1330,120,55)],{question:'Is MR=MC sufficient in every optimization problem?',answer:'No. It is an interior candidate condition; classification and boundaries still matter.',teachingCue:'防止等式被写成万能决策。',assistantCue:'MR=MC is a necessary interior condition under differentiability, not a universal sufficient rule.'}),
 page(11,'12','Check the shape','SECOND DERIVATIVE',ref,[math('\\pi^{\\prime\\prime}(q)=-3<0',90,310,1380,120,70),text('The profit function is strictly concave.\nIts stationary point is its unique peak.',110,580,1300,160,42)],{question:'What does strict concavity contribute here?',answer:'It verifies that the stationary candidate is a maximum, not a minimum.',teachingCue:'本例全区间二阶负支持全局峰值。',assistantCue:'Use strict concavity on the interval, not merely one isolated second-derivative value, for uniqueness.'}),
 page(11,'13','Check both endpoints anyway','VALUE COMPARISON',ref,[table(['Output','Profit (€)','Role'],[['0','−100','Left endpoint'],['80/3','2900/3 ≈ 966.67','Interior candidate'],['40','700','Right endpoint']],90,260,1390,380)],{question:'Which feasible value is greatest?',answer:'2900/3 euros at q=80/3.',teachingCue:'核验峰值2900/3，位置与高度同时报。',assistantCue:'Use exact fractions before decimal rounding.'}),
 page(11,'14','Report a complete decision','CONTINUOUS MODEL',ref,[math('q^*=80/3,\\quad p^*=220/3',90,305,1390,110,61),text('Produce about 26.67 units.\nCharge about €73.33 per unit.\nMaximum profit is about €966.67.',110,560,1300,230,41)],{question:'Why is the price not the maximum profit?',answer:'Price is revenue per unit; profit is total revenue minus total cost.',teachingCue:'最优量价利润三个量不混。',assistantCue:'These are continuous-model values, not an exact integer production plan.'}),
 page(11,'15','A smaller capacity changes the answer','BOUNDARY OPTIMUM',ref,[math('0\\leq q\\leq20',90,310,1390,110,73),text('The candidate 26.67 is infeasible.\nProfit rises throughout [0,20].',110,575,1300,160,43)],{question:'Where is the constrained maximum now?',answer:'At q=20, with profit €900.',teachingCue:'容量变化后不能沿用原解。',assistantCue:'At a boundary optimum MR can exceed MC; equality is not required.'}),
 page(11,'16','At capacity, MR can exceed MC','INTERPRET THE BOUNDARY',ref,[math('MR(20)=60>40=MC(20)',90,310,1390,120,62),art('case',1100,520,370,280,'Factory capacity gate blocking extra boxes'),text('Expansion would help,\nbut capacity prevents it.',110,565,890,155,43)],{question:'Does MR>MC mean the constrained decision is wrong?',answer:'No. The feasible maximum is at capacity.',teachingCue:'约束解释最优点未必满足边际相等。',assistantCue:'Distinguish feasible optimum from the unconstrained preferred output.'}),
 page(11,'17','Whole products need a discrete check','INTEGER OUTPUT',ref,[table(['Integer output','Profit (€)'],[['26','966'],['27','966.5'],['28','964']],100,270,1350,345),text('For whole units, compare nearby integers.',110,740,1300,70,39)],{question:'Which integer output is best on {0,…,40}?',answer:'27 units, with profit €966.50.',teachingCue:'凹二次峰附近比较，不能只按普通四舍五入宣称正确。',assistantCue:'Use exact profit comparison at neighbouring integers and concavity to justify the discrete choice.'}),
 page(11,'18','Revenue is not profit','COMPARE OBJECTIVES',ref,[math('R^{\\prime}(q)=100-2q=0\\Rightarrow q=50',90,300,1390,120,48),text('Revenue prefers 50 in its larger domain.\nProfit prefers about 26.67.\nThe core capacity remains 40.',110,570,1300,220,40)],{question:'Why can the revenue optimum differ?',answer:'Revenue ignores production costs.',teachingCue:'50不在核心容量，标清是更大定义域下比较。',assistantCue:'Keep q=50 outside the [0,40] core problem and explain objective differences.'}),
 page(11,'19','Changing fixed cost shifts the hill','SENSITIVITY',ref,[math('\\pi_F(q)=80q-1.5q^2-F',90,300,1390,120,59),text('A different fixed cost changes profit levels.\nIt does not change the derivative 80 − 3q.',110,575,1300,160,40)],{question:'Does a larger fixed cost change this interior candidate?',answer:'No, if the same cost is incurred for every feasible output and other terms stay unchanged.',teachingCue:'附带固定成本发生方式条件，不能泛化停产决策。',assistantCue:'This holds with fixed cost incurred at q=0 too; avoid claims about shutdown when costs are avoidable.'}),
 page(11,'20','Write the constraint first','A DECISION CHECKLIST',ref,[diagram('steps',['Objective and units','Feasible interval','Candidates and endpoint values'],95,285,1350,240),text('Then state the output, value, and assumptions.',110,680,1300,90,41)],{question:'Which step is missing from “solve MR=MC”?',answer:'Feasibility, classification, and endpoint comparison.',teachingCue:'多步过程压缩成三个行为检查。',assistantCue:'Keep the checklist tied to the smooth one-variable objective.'}),
 page(11,'21','A simpler profit function','GUIDED PRACTICE',ref,[math('\\pi(q)=12q-q^2-20,\\quad0\\leq q\\leq8',90,310,1390,130,51),text('Find a candidate.\nCompare it with both endpoints.',110,610,1300,150,43)],{question:'What is the maximum?',answer:'Profit 16 at q=6; endpoint profits are −20 and 12.',teachingCue:'独立练习留候选与比较时间。',assistantCue:'Offer derivative and endpoint hints before the reveal.'}),
 page(11,'22','Now limit capacity to four','TRANSFER',ref,[math('\\pi(q)=12q-q^2-20,\\quad0\\leq q\\leq4',90,310,1390,130,51),text('The same function.\nA different feasible decision.',110,610,1300,140,43)],{question:'What is the constrained maximum?',answer:'Profit 12 at q=4.',teachingCue:'只改变约束，观察答案变化。',assistantCue:'Reject q=6 as infeasible and use increasing profit on [0,4].'}),
 page(11,'23','A responsible recommendation','COMMUNICATE',ref,[text('“Under the stated demand and cost model,\n27 whole units give the highest profit\nwithin the capacity of 40.”',100,300,1370,230,42),art('case',1100,570,380,250,'A factory production recommendation collage')],{question:'Which phrase marks the evidence boundary?',answer:'Under the stated model.',teachingCue:'结论含整数、容量、模型边界。',assistantCue:'Do not present a teaching model as an empirically validated business recommendation.'}),
 page(11,'24','The stopping rule needs a check','EXIT CHECK',ref,[text('MR − MC gives direction.\nMR = MC gives an interior candidate.\nFeasibility and comparison give the decision.',100,300,1370,230,43)],{question:'When can MR=MC fail to describe the best feasible choice?',answer:'At a boundary or with indivisible output, and when a stationary point is not a maximum.',teachingCue:'三条区分方向、候选和最终决策。',assistantCue:'Summarize the interior, boundary, and integer distinctions.'}),
 page(11,'25','Complete the square','OPTIONAL CHALLENGE',ref,[math('\\pi(q)=\\frac{2900}{3}-\\frac32\\left(q-\\frac{80}{3}\\right)^2',90,320,1400,180,50),text('Subtracting a nonnegative square\nmakes the peak visible.',110,645,1300,140,42)],{optionalChallenge:true,question:'How does this expression prove the maximum?',answer:'The subtracted square is at least zero and equals zero only at q=80/3.',teachingCue:'以另一代数证据检查导数结论。',assistantCue:'Apply the square identity exactly and keep feasibility separate.'}),
 page(11,'26','A minimum also satisfies MR=MC','OPTIONAL CHALLENGE',ref,[math('R(q)=q^2,\\quad C(q)=2q',90,300,1390,120,63),math('\\pi(q)=q^2-2q,\\quad\\pi^{\\prime}(1)=0',100,550,1330,120,55)],{optionalChallenge:true,question:'On [0,3], is q=1 the profit maximum?',answer:'No. It is a minimum; the maximum is 3 at q=3.',teachingCue:'给等式不充分的具体反例。',assistantCue:'π″=2>0 classifies the stationary point as a minimum; compare endpoints for the maximum.'})
 ],
 exercises:[
 {id:'11-1',question:'Form profit from R=100q−q² and C=100+20q+0.5q².',answer:'80q−1.5q²−100.',solution:'Subtract every cost term: 100q−q²−100−20q−0.5q²=80q−1.5q²−100.'},
 {id:'11-2',question:'Find the interior stationary output.',answer:'80/3.',solution:'π′=80−3q. Set this equal to zero: q=80/3.'},
 {id:'11-3',question:'Verify the maximum on [0,40].',answer:'2900/3 euros at q=80/3.',solution:'π″=−3<0. Compare π(0)=−100, π(80/3)=2900/3, π(40)=700. The candidate has the greatest value.'},
 {id:'11-4',question:'Find the maximum if capacity is only 20.',answer:'€900 at q=20.',solution:'The stationary point is infeasible. π′=80−3q≥20>0 on [0,20], so the maximum is π(20)=1600−600−100=900.'},
 {id:'11-5',question:'Choose the best whole-number output with capacity 40.',answer:'27 units; €966.50.',solution:'The concave peak lies between 26 and 27. π(26)=966 and π(27)=966.5. Outputs further from the peak have lower profit, so 27 is best.'},
 {id:'11-6',question:'For π=12q−q²−20 on [0,8], find the maximum.',answer:'16 at q=6.',solution:'π′=12−2q gives 6; π″=−2. Compare −20 at 0, 16 at 6, and 12 at 8.'},
 {id:'11-7',question:'For π=q²−2q on [0,3], explain why π′=0 does not identify the maximum.',answer:'q=1 is a minimum; maximum 3 at q=3.',solution:'π′=2q−2 vanishes at 1 but π″=2>0. Compare π(0)=0, π(1)=−1, π(3)=3.',optional:true}
 ],
 teacherGuide:'90分钟：建模20；边际方向15；候选与凹性15；端点与容量15；整数比较10；练习出口15。英文话术：“A candidate is not yet a decision.” “The constraint comes first.” “Compare the actual profit values.” 固定成本在零产量也发生；不加入沉没成本或停产扩展。连续最优26.67与整数最优27区分，容量20时MR不等MC仍可最优。',
 film:[
 {from:0,to:15,title:'Production begins',narration:'A bright factory unfolds from paper shapes. Each new product carries a revenue token, but a second stream of cost tokens follows close behind.',caption:'Every extra unit brings two changes.',scene:'A factory assembles itself; blue revenue and coral cost tokens accompany each box.'},
 {from:15,to:30,title:'A widening gap',narration:'At first, revenue grows faster than cost. The space between the two streams widens, suggesting that a small increase in output can improve profit.',caption:'Revenue change exceeds cost change.',scene:'Token streams separate and reveal a green profit strip between them.'},
 {from:30,to:45,title:'The gap slows',narration:'More products require a lower selling price and a heavier workload. The profit strip still grows, but each new addition becomes smaller than before.',caption:'The next addition becomes smaller.',scene:'Product rows expand while price tags shorten and handling stacks grow.'},
 {from:45,to:60,title:'Two rates meet',narration:'A pair of moving bars approaches equal height. They represent marginal revenue and marginal cost, creating an interior candidate where the profit slope becomes zero.',caption:'Equal rates identify a candidate.',scene:'Blue MR and coral MC bars meet beside an unlabeled concave profit curve.'},
 {from:60,to:75,title:'A gate appears',narration:'A capacity gate cuts across the production line. Even a promising extra unit may be impossible, so the best allowed decision can sit at that boundary.',caption:'Capacity changes the decision.',scene:'A yellow gate stops the next box before the unconstrained peak is reached.'},
 {from:75,to:90,title:'Choose and justify',narration:'The factory waits with its curves and limits visible. Should it make one more unit, stop here, or move backward? Give a decision with evidence.',caption:'Should we make one more?',scene:'The gate, two marginal bars, and profit curve freeze around the unanswered decision.'}
 ]
};
