import type {MathematicsLesson} from '../types.js';
import {source,page,text,math,art,plot,table,diagram} from '../authoring.js';
const ref=source('4.8',361,372);
export const lesson08:MathematicsLesson={
 number:8,title:'Rates for Exponentials and Logarithms',filmTitle:'Different Kinds of Growth',openingQuestion:'Why does the next increase depend on where you are on the curve?',
 outcomes:['Differentiate eˣ and ln x with valid domains.','Use the chain rule for simple exponential and logarithmic compositions.','Interpret increasing exponential rates and diminishing logarithmic rates.'],
 vocabulary:[['exponential rate','A change rate proportional to the current amount in an exponential model.'],['natural base','The number e, approximately 2.71828.'],['natural logarithm','The inverse of eˣ, defined for positive inputs.'],['proportional','Related by multiplication by a constant.'],['decay','A decrease over time in a stated model.'],['domain restriction','A condition limiting allowed inputs.']],sources:[ref],
 slides:[
 page(8,'01','DIFFERENT KINDS OF GROWTH','Watch • compare • ask',ref,[art('opening',70,235,900,585,'Bright experimental collage of an expanding exponential tower and flattening logarithmic paper steps'),text('One curve speeds up.',1040,305,450,140,45,'blue'),text('One curve flattens.',1040,545,450,140,45,'coral')],{openingFilm:true,question:'Why is the next increase different on each curve?',answer:'The exponential derivative grows with its value; the logarithmic derivative 1/x decreases for positive x.',teachingCue:'先读视觉趋势，学生用near与rate描述，不先背导数。',assistantCue:'Teach e^x and ln x in English. Require positive logarithm inputs and distinguish continuous relative rates from discrete percentage growth.'}),
 page(8,'02','Remember the two functions','Powers and their inverse',ref,[math(String.raw`y=e^x\quad\Longleftrightarrow\quad x=\ln y`,75,300,1410,160,75),text('eˣ gives a positive output for every real x.',90,610,1370,90,43),text('ln x requires x>0.',90,760,1370,70,42,'coral')],{question:'What are e⁰ and ln1?',answer:'e⁰=1 and ln1=0.',teachingCue:'先复习第4讲，后导数公式；指数可负而输出正。'}),
 page(8,'03','The exponential rises faster','Observe eˣ',ref,[plot({xRange:[-2,2],yRange:[0,8],xLabel:'x',yLabel:'eˣ',curves:[{kind:'exponential',color:'blue',label:'eˣ'}],points:[{x:0,y:1},{x:1,y:Math.E}]},70,245,990,575),text('Positive everywhere.',1110,320,380,125,41),text('Steeper to the right.',1110,550,380,140,41,'blue')],{question:'Can eˣ equal zero at a finite real x?',answer:'No. It remains strictly positive.',teachingCue:'图区间有限但结论来自函数性质，左侧靠近0不等于达到0。'}),
 page(8,'04','Its slope matches its height','Exponential derivative',ref,[math(String.raw`\frac{d}{dx}e^x=e^x`,80,300,1400,165,94),table(['x','0','1','2'],[['Value eˣ','1','≈2.718','≈7.389'],['Derivative','1','≈2.718','≈7.389']],80,590,1400,240)],{question:'What is the tangent slope at x=0?',answer:'1.',teachingCue:'只有底数e的基本指数函数导数等于自身，不能泛化到任意底数。'}),
 page(8,'05','A multiplier remains outside','Scale the exponential',ref,[math(String.raw`f(x)=5e^x`,80,285,1400,135,94),math(String.raw`f'(x)=5e^x`,80,560,1400,135,94)],{question:'What is f′(0)?',answer:'5.',teachingCue:'复用常数倍规则，导数不额外乘5两次。'}),
 page(8,'06','Time inside the exponent has a rate','Chain rule',ref,[diagram('nested',['t','u=0.1t','eᵘ'],80,265,1400,240),math(String.raw`\frac{d}{dt}e^{0.1t}=0.1e^{0.1t}`,80,625,1400,155,77)],{question:'Which factor comes from the inner rule?',answer:'0.1, the derivative of 0.1t.',teachingCue:'线性内层对应上一讲，经济单位需要t时间单位固定。'}),
 page(8,'07','A growing group has a growing rate','A stated model',ref,[art('case',80,280,550,465,'Paper group of user tokens growing across a blue ribbon'),math(String.raw`N(t)=100e^{0.1t}`,750,330,740,140,73),math(String.raw`N'(t)=10e^{0.1t}`,750,600,740,125,71)],{publicLabel:'Teaching scenario',question:'What is the growth rate at t=0 days?',answer:'10 users per day in the continuous model.',teachingCue:'人数按模型规模理解，不将10视为次日精确新增。'}),
 page(8,'08','The absolute rate rises with the group','Evaluate and compare',ref,[table(['t (days)','0','10'],[['N(t) (users)','100','≈271.83'],['N′(t) (users/day)','10','≈27.18']],80,280,1400,330),text('A larger current group gives a larger absolute rate.',90,700,1370,110,44)],{question:'Does N′(10) mean the exact increase from day 10 to day 11?',answer:'No. It is the instantaneous rate at day 10.',teachingCue:'对照速率与有限增量，保留approximately与instantaneous。'}),
 page(8,'09','The relative rate stays constant','Divide rate by level',ref,[math(String.raw`\frac{N'(t)}{N(t)}=\frac{10e^{0.1t}}{100e^{0.1t}}=0.1`,80,300,1400,170,70),text('0.1 per day: a continuous relative growth rate.',90,610,1370,150,45,'green')],{question:'Is the exact one-day growth percentage 10%?',answer:'No. The one-day multiplier is e^0.1, giving about 10.52% growth.',teachingCue:'连续相对率与离散比例区分是本讲重要边界。'}),
 page(8,'10','A negative exponent gives decay','Chain sign',ref,[math(String.raw`V(t)=100e^{-0.2t}`,80,285,1400,140,83),math(String.raw`V'(t)=-20e^{-0.2t}`,80,560,1400,140,79)],{publicLabel:'Teaching scenario',question:'What is the derivative sign for every real t?',answer:'Negative, because the exponential factor is positive and the multiplier is −20.',teachingCue:'负速率来自负内层，不来自指数函数取负值。'}),
 page(8,'11','The value stays positive while falling','Decay graph',ref,[plot({xRange:[0,10],yRange:[0,110],xLabel:'t (periods)',yLabel:'Model value',curves:[{kind:'exponential',scale:100,rate:-.2,color:'coral',label:'100e^(−0.2t)'}],tangent:{curve:0,x:2}},70,245,990,575),text('Positive value.',1110,315,380,115,42),text('Negative slope.',1110,550,380,115,42,'coral')],{question:'As time grows, does the decrease per period become larger in absolute size?',answer:'No. The absolute instantaneous decrease 20e^(−0.2t) becomes smaller.',teachingCue:'水平趋近零但有限时不为零，负斜率绝对值减小。'}),
 page(8,'12','The logarithm rises more slowly','Observe ln x',ref,[plot({xRange:[.1,5],yRange:[-2.5,2],xLabel:'Positive input x',yLabel:'ln x',curves:[{kind:'logarithm',color:'blue',label:'ln x'}],points:[{x:1,y:0},{x:Math.E,y:1}]},70,245,990,575),text('Increasing.',1110,320,380,115,44,'blue'),text('Flattening.',1110,550,380,115,44)],{question:'Does a negative value ln(0.5) imply a negative slope?',answer:'No. The logarithm is increasing on its positive-input domain.',teachingCue:'值负导数正再一次分开，为弹性对数解释准备。'}),
 page(8,'13','The slope is the reciprocal of input','Logarithm derivative',ref,[math(String.raw`\frac{d}{dx}\ln x=\frac1x\qquad x>0`,80,300,1400,175,90),text('Larger positive inputs give smaller positive slopes.',90,635,1370,150,45)],{question:'What are the slopes at x=1 and x=4?',answer:'1 and 1/4.',teachingCue:'真数大斜率小，是边际递减直观而非收益总量下降。'}),
 page(8,'14','The rate has its own graph','Reciprocal slope',ref,[plot({xRange:[.25,5],yRange:[0,4.3],xLabel:'Positive input x',yLabel:'Derivative 1/x',curves:[{kind:'power',power:-1,color:'green',label:'1/x'}]},70,245,990,575),text('Always positive.',1110,320,380,115,41),text('Falls as x grows.',1110,550,380,140,41,'green')],{question:'What happens to the slope as x approaches zero from the right?',answer:'It grows without bound.',teachingCue:'图区间不包括0；不把导数1/0写为某个有限数。'}),
 page(8,'15','Scale the logarithmic response','A model index',ref,[math(String.raw`B(x)=3\ln x\qquad x>0`,80,280,1400,145,80),math(String.raw`B'(x)=\frac3x`,80,560,1400,155,93)],{publicLabel:'Teaching scenario',question:'Compare B′(1) and B′(3).',answer:'They are 3 and 1; the local response becomes smaller.',teachingCue:'B为教学指数，无量纲或给定评分单位，不称实测效用。'}),
 page(8,'16','A line can sit inside a logarithm','Chain rule again',ref,[math(String.raw`f(x)=\ln(2x+1)`,80,280,1400,140,88),math(String.raw`f'(x)=\frac2{2x+1}\qquad x>-\frac12`,80,550,1400,160,76)],{question:'Why is x>−1/2 required?',answer:'The logarithm input 2x+1 must be positive.',teachingCue:'先解内层正，不只是分母不等于0；x<−.5分母非零也无实ln。'}),
 page(8,'17','Check the domain before a value','Evaluate a log derivative',ref,[table(['x','0','1','−1'],[['2x+1','1','3','−1'],['Allowed for ln?','Yes','Yes','No']],80,270,1400,320),math(String.raw`f'(1)=\frac23`,80,680,1400,125,77)],{question:'Can the formula 2/(2x+1) justify f′(−1)=−2?',answer:'No. The original logarithm is not defined at x=−1.',teachingCue:'导数公式沿原函数实定义域，不因有代数值就允许扩域。'}),
 page(8,'18','The inner scale can cancel','A useful check',ref,[math(String.raw`g(x)=\ln(3x)\qquad x>0`,80,285,1400,140,80),math(String.raw`g'(x)=\frac3{3x}=\frac1x`,80,560,1400,145,82)],{question:'Why does this agree with ln(3x)=ln3+lnx?',answer:'ln3 is a constant and has derivative zero, leaving 1/x.',teachingCue:'用对数法则作独立核验，3并非任何情况都取消。'}),
 page(8,'19','Added terms stay separate','Combine familiar rules',ref,[math(String.raw`f(x)=2e^x+3\ln x\qquad x>0`,75,280,1410,145,73),math(String.raw`f'(x)=2e^x+\frac3x`,80,555,1400,145,84)],{question:'What is f′(1)?',answer:'2e+3≈8.437.',teachingCue:'定义域由log项限制，指数项自身全实域不能解除限制。'}),
 page(8,'20','A product can contain an exponential','Product rule',ref,[math(String.raw`f(x)=xe^x`,80,280,1400,135,96),math(String.raw`f'(x)=1\cdot e^x+x e^x=e^x(1+x)`,80,550,1400,155,70)],{question:'What is the derivative at x=0?',answer:'1.',teachingCue:'先识别乘积，两项都有e^x；不将导数写成e^x。'}),
 page(8,'21','Move along the logarithm','Explore the local response',ref,[plot({xRange:[.25,5],yRange:[-1.5,2],xLabel:'Positive input x',yLabel:'ln x',curves:[{kind:'logarithm',color:'blue',label:'ln x'}],tangent:{curve:0,x:1}},70,240,1000,590),math(String.raw`f'(x)=1/x`,1100,355,390,110,50),text('The curve rises while its slope gets smaller.',1110,565,380,180,38)],{interaction:{kind:'parameter',key:'x',label:'Positive input x',min:.25,max:5,step:.25,initial:1},question:'At x=4, what does the tangent slope equal?',answer:'1/4.',teachingCue:'滑块始终正值，要求先预测再拖动。'}),
 page(8,'22','Two familiar mistakes','Error clinic',ref,[math(String.raw`\frac{d}{dx}e^{2x}\;\color{red}{\ne}\;e^{2x}`,80,275,1400,145,72),math(String.raw`\frac{d}{dx}\ln x\;\color{red}{\ne}\;\ln x`,80,555,1400,145,73)],{question:'Repair both derivatives.',answer:'2e^(2x) and 1/x for x>0.',teachingCue:'指数漏内层2、对数误以为自身分别说明，不把两公式类比记错。'}),
 page(8,'23','One interval gives a finite increase','Rate and realised change',ref,[math(String.raw`N(t)=100e^{0.1t}\quad N'(0)=10`,80,280,1400,145,70),math(String.raw`N(1)-N(0)=100(e^{0.1}-1)\approx10.517`,80,555,1400,155,60)],{question:'Why is the one-day change greater than 10?',answer:'The instantaneous rate rises during the day, so the initial local rate understates that finite change.',teachingCue:'核心解释无需积分，数字复核10.517，不说正好10%。'}),
 page(8,'24','Choose a rule and a valid input','Exit ticket',ref,[math(String.raw`A(t)=50e^{0.2t}\qquad B(x)=\ln(x+2)`,75,280,1410,145,71),text('Find A′(0), B′(0), and the domain of B.',90,575,1370,155,49)],{question:'What are the derivative values and domain?',answer:'A′(0)=10; B′(0)=1/2; B is defined for x>−2.',teachingCue:'出口题结合指数链、对数链和定义域，不能只报两个数。'}),
 page(8,'25','A different exponential base','Optional Challenge',ref,[math(String.raw`b^x=e^{x\ln b}\qquad b>0`,80,285,1400,150,81),math(String.raw`\frac{d}{dx}b^x=(\ln b)b^x`,80,565,1400,150,81)],{optionalChallenge:true,question:'What is the derivative of 2ˣ?',answer:'(ln2)·2ˣ.',teachingCue:'选学一般底数转换，b=1也给0但普通log底数规则另有≠1。'}),
 page(8,'26','One product, two rates','Optional Challenge',ref,[math(String.raw`G(t)=(10+2t)e^{0.1t}`,80,285,1400,145,79),text('Differentiate each factor in turn and combine.',90,585,1370,150,47)],{optionalChallenge:true,question:'Find G′(t), then G′(0).',answer:'G′(t)=e^(0.1t)(3+0.2t); G′(0)=3.',teachingCue:'选学乘积加线性内层链，不展开不必要的指数近似。'})
 ],
 exercises:[
 {id:'08-1',question:'Differentiate f(x)=5eˣ and calculate f′(0).',answer:'f′(x)=5eˣ; f′(0)=5.',solution:'Apply the constant-multiple rule and use e⁰=1.'},
 {id:'08-2',question:'N(t)=100e^(0.1t). Find N′(t) and N′(0).',answer:'N′(t)=10e^(0.1t); N′(0)=10.',solution:'The chain rule multiplies by the derivative 0.1 of the exponent.'},
 {id:'08-3',question:'Differentiate V(t)=100e^(−0.2t) and state its derivative sign.',answer:'V′(t)=−20e^(−0.2t), always negative.',solution:'The exponential factor is positive; the chain multiplier is −0.2.'},
 {id:'08-4',question:'Differentiate ln(2x+1) and state the real domain.',answer:'2/(2x+1), for x>−1/2.',solution:'Require 2x+1>0, then multiply the outer reciprocal by inner derivative 2.'},
 {id:'08-5',question:'Differentiate f(x)=xeˣ and evaluate f′(0).',answer:'eˣ(1+x); at 0 the value is 1.',solution:'Product rule gives 1·eˣ+x·eˣ. Factor out eˣ and substitute 0.'},
 {id:'08-6',question:'For N(t)=100e^(0.1t), compare N′(0) with the exact one-period increase.',answer:'10 versus about 10.517.',solution:'The finite increase is 100(e^0.1−1). A continuous relative rate 0.1 is not an exact discrete increase of 10%.'},
 {id:'08-7',question:'Optional: differentiate 2ˣ.',answer:'(ln2)2ˣ.',solution:'Write 2ˣ=e^(x ln2), then apply the chain rule.',optional:true}
 ],
 teacherGuide:'第8讲90分钟。0–12指数对数回顾与图；12–32e^x、常数倍与线性内层；32–47模型绝对率、相对率与衰减；47–65ln图、1/x及定义域；65–78对数链、和与乘积、交互；78–90错误诊断与出口题。英文话术：“The exponential stays positive; its derivative may carry a negative multiplier.” “A logarithm needs a positive input.” “Increasing does not mean an increasing slope.” 用前几讲规则组合，但核心不出现复杂多层内函数。连续相对率与整期百分比必须公开区分。',
 film:[
 {from:0,to:15,title:'Two growth objects rise',narration:'Two paper structures rise from a bright tabletop. Both become taller, but one accelerates upward while the other begins to flatten as it grows.',caption:'Both rise. Their rates differ.',scene:'growth-structures'},
 {from:15,to:30,title:'The exponential expands',narration:'The first structure follows an exponential model. A larger current amount produces a larger instantaneous increase, so its steps become taller along the path.',caption:'A larger level, a larger rate',scene:'exponential-steps'},
 {from:30,to:45,title:'The logarithm flattens',narration:'The second structure follows a logarithmic curve. Its level keeps rising, but equal input steps add less and less height as the input increases.',caption:'Rising level. Smaller slope.',scene:'logarithm-steps'},
 {from:45,to:60,title:'Tangents reveal the difference',narration:'Small tangent ribbons touch the two curves. Their directions reveal local rates, giving a precise way to compare changes that the eye only notices.',caption:'Tangents make the rates visible.',scene:'growth-tangents'},
 {from:60,to:75,title:'Inputs need boundaries',narration:'A logarithm door admits only positive inputs. An exponential door accepts any real input. The derivative rule must respect the function behind that door.',caption:'Check the input first.',scene:'domain-doors'},
 {from:75,to:90,title:'Compare the next increase',narration:'Choose a point on each curve. Why is the next small increase different? Find their derivative rules and explain the rate at your chosen input.',caption:'How fast is each curve changing?',scene:'growth-rates-question'}
 ]
};
