import { practice01 } from './lesson-01.js';
import { practice02 } from './lesson-02.js';
import { practice03 } from './lesson-03.js';
import { practice04 } from './lesson-04.js';
import { practice05 } from './lesson-05.js';
import { practice06 } from './lesson-06.js';
import { practice07 } from './lesson-07.js';
import { practice08 } from './lesson-08.js';
import { practice09 } from './lesson-09.js';
import { practice10 } from './lesson-10.js';
import { practice11 } from './lesson-11.js';
import { practice12 } from './lesson-12.js';
import { practice13 } from './lesson-13.js';
import { practice14 } from './lesson-14.js';
import { practice15 } from './lesson-15.js';
import { practice16 } from './lesson-16.js';
export { publicPack, publicQuestion } from './authoring.js';
export type { PrivatePracticePack, PrivatePracticeQuestion } from './authoring.js';
export const rankedPracticePacks = [practice01,practice02,practice03,practice04,practice05,practice06,practice07,practice08,practice09,practice10,practice11,practice12,practice13,practice14,practice15,practice16];
export const getRankedPracticePack = (course: string, lesson: number) => rankedPracticePacks.find(p => p.courseId === course && p.lesson === lesson);
