import { pack, question as q, source as s } from './authoring.js';
const general = 'A firm has demand $P=aQ+b$ ($a<0$, $b>0$), fixed costs $c$ and variable costs $d$ per unit. ';
export const practice11 = pack(11, 'Profit optimisation and feasible decisions', [
 q(11,1,general+'Write down a general expression for total revenue.',['$aQ+b$','$aQ^2+bQ$','$aQ^2+b$','$c+dQ$'],1,'Total revenue is price times output: $TR=(aQ+b)Q=aQ^2+bQ$.',['This is price.','Correct: multiply price by quantity.','The intercept term must also be multiplied by quantity.','This is total cost.'],s('4.7','Exercise 4.7*','1(a), TR',359),'expand((a*Q+b)*Q)',['a*Q+b','a*Q**2+b*Q','a*Q**2+b','c+d*Q']),
 q(11,2,general+'Write down a general expression for total cost.',['$c+d$','$cQ+d$','$c+dQ$','$dQ$'],2,'Fixed cost is $c$ and total variable cost is $dQ$. Therefore $TC=c+dQ$.',['Variable cost per unit must be multiplied by output.','Fixed cost is not charged separately for each unit.','Correct: add fixed cost to variable cost times output.','This omits fixed cost.'],s('4.7','Exercise 4.7*','1(a), TC',359),'c+d*Q',['c+d','c*Q+d','c+d*Q','d*Q']),
 q(11,3,general+'Deduce the marginal cost.',['$c$','$c+d$','$dQ$','$d$'],3,'Differentiate $TC=c+dQ$ with respect to $Q$. Fixed cost disappears and $MC=d$.',['Fixed cost has zero derivative.','Fixed cost does not contribute to marginal cost.','This is total variable cost.','Correct: constant variable cost per unit equals marginal cost.'],s('4.7','Exercise 4.7*','1(b), MC',359),'diff(c+d*Q,Q)',['c','c+d','d*Q','d']),
 q(11,4,general+'Deduce the marginal revenue.',['$2aQ+b$','$aQ+b$','$2a+b$','$aQ^2+bQ$'],0,'Differentiate $TR=aQ^2+bQ$: $MR=2aQ+b$.',['Correct: apply the power rule.','This is price rather than marginal revenue.','The first derivative still depends on quantity.','This is total revenue.'],s('4.7','Exercise 4.7*','1(b), MR',359),'diff(a*Q**2+b*Q,Q)',['2*a*Q+b','a*Q+b','2*a+b','a*Q**2+b*Q']),
 q(11,5,general+'Assume also $b>d\\ge0$ and $c\\ge0$. Find the non-negative output which maximises profit.',['$\\frac{b-d}{2a}$','$\\frac{d-b}{2a}$','$\\frac{d-b}{a}$','$\\frac{-b}{2a}$'],1,'Profit is $aQ^2+(b-d)Q-c$. Set its derivative $2aQ+b-d$ to zero: $Q=(d-b)/(2a)>0$. Since $2a<0$, this is a maximum. It lies below the non-negative-price endpoint $-b/a$. If $b\\le d$, the feasible optimum would instead be $Q=0$.',['This gives negative output under the stated assumptions.','Correct: solve $MR=MC$ and verify feasibility and concavity.','This omits the factor 2.','This maximises revenue rather than profit when marginal cost is positive.'],s('4.7','Exercise 4.7*','1(c)',359,'Model retained; conditions b>d≥0, c≥0 and non-negative output added to ensure an interior feasible maximum.'),'solve(2*a*Q+b-d,Q)[0]',['(b-d)/(2*a)','(d-b)/(2*a)','(d-b)/a','-b/(2*a)']),
 q(11,6,'A firm has $TC=Q^2+50Q+10$ and demand $P=200-4Q$. Find the level of output needed to maximise profit.',['$25$','$30$','$15$','$50$'],2,'$TR=200Q-4Q^2$ and $\\pi=150Q-5Q^2-10$. Its derivative is $150-10Q$, giving $Q=15$. The second derivative is -10. On $0\\le Q\\le50$, compare the vertex with the endpoints.',['This is the output maximising revenue.','This loses the factor 2 on the quadratic profit term.','Correct: maximise revenue minus total cost.','This gives zero demand price, not maximum profit.'],s('4.6','Exercise 4.6*','6(a)',347),'solve(diff(150*Q-5*Q**2-10,Q),Q)[0]',['25','30','15','50']),
 q(11,7,'A firm has demand $P=60-0.5Q$, fixed costs 10 and variable costs $Q+3$ per unit. Find the maximum profit.',['$541.5$','$531.5$','$1083$','$19$'],1,'$TC=10+Q(Q+3)$, giving $\\pi=57Q-1.5Q^2-10$. The vertex is $Q=19$, inside $0\\le Q\\le120$. Profit is $57(19)-1.5(19^2)-10=531.5$. The second derivative is -3; endpoint profits are lower.',['This omits fixed cost.','Correct: evaluate profit at its feasible maximum.','This counts only the linear term in profit.','This is the optimal output, not the maximum profit.'],s('4.6','Exercise 4.6*','1',347),'(57*Q-Rational(3,2)*Q**2-10).subs(Q,19)',['Rational(1083,2)','Rational(1063,2)','1083','19']),
 q(11,8,'The average cost per person of hiring a tour guide for a week’s river cruise is $AC=3Q^2-192Q+3500$, where $0<Q\\le30$. Find the minimum average cost for the trip.',['$428$','$3500$','$32$','$440$'],3,'$AC\u2032=6Q-192$ is negative throughout $0<Q\\le30$. The unconstrained vertex at 32 is outside the maximum party size. Thus choose $Q=30$, giving $AC=2700-5760+3500=440$.',['428 is the value at infeasible output 32.','This is the limiting cost near zero party size.','This is an infeasible party size rather than a cost.','Correct: the feasible minimum occurs at the endpoint 30.'],s('4.6','Exercise 4.6','9',346),'(3*Q**2-192*Q+3500).subs(Q,30)',['428','3500','32','440']),
 q(11,9,'A firm has production $Q=3\\sqrt L$, sells everything at USD 50 per unit, and pays USD 10 per unit of labour. Ignore other costs. Find the value of $L$ which maximises profit, treating labour as continuous.',['$56.25$','$7.5$','$225$','$0$'],0,'$\\pi(L)=150\\sqrt L-10L$, for $L\\ge0$. For $L>0$, $\\pi\u2032=75/\\sqrt L-10=0$ gives $\\sqrt L=7.5$, so $L=56.25$. Concavity is negative and profit there exceeds the endpoint value at 0.',['Correct: square 7.5 to obtain the labour input.','This is the square root of optimal labour.','This uses the wrong revenue derivative coefficient.','Zero labour gives zero profit, below the interior maximum.'],s('4.6','Exercise 4.6','8',346,'Original production, prices and assumptions retained; dollar notation written as USD and continuous-labour interpretation made explicit.'),'(Rational(75,10))**2',['Rational(225,4)','Rational(15,2)','225','0']),
 q(11,10,'A firm has $TC=Q^2+50Q+10$ and $P=200-4Q$. A tax of $t$ dollars per good is added to its costs. For $0\\le t<150$, the firm continues to maximise profit. By how much does the price increase?',['$t$','$t/5$','$2t/5$','$3t/5$'],2,'Taxed profit is $(150-t)Q-5Q^2-10$. Thus $Q^*=(150-t)/10$ and $P^*=200-4Q^*=140+2t/5$. The increase from the untaxed price 140 is $2t/5$. The condition ensures positive optimal output.',['Full pass-through does not follow from this demand and cost model.','This understates the price increase by a factor of 2.','Correct: substitute the taxed optimum into demand.','This is not the price change implied by the optimal quantity.'],s('4.6','Exercise 4.6*','6(b)',347,'Models repeated; “show that” changed to a choice question and 0≤t<150 added for a positive interior optimum.'),'expand(200-4*(150-t)/10-140)',['t','t/5','2*t/5','3*t/5']),
]);
