import {pack,question as q,source as s} from './authoring.js';
const r=(part:string,adaptation?:string)=>s('4.8','Exercise 4.8',part,370,adaptation);
const bank='If USD 4000 is saved in an account offering a return of 4% compounded continuously, the future value, $S$, after $t$ years is given by $S=4000e^{0.04t}$.';
export const practice08=pack(8,'Derivatives of exponentials and logarithms',[
 q(8,1,'Write down the derivative of $y=e^{6x}$.',['$e^{6x}$','$6e^x$','$6e^{6x}$','$e^{6x}/6$'],2,'The exponential remains $e^{6x}$; the chain rule multiplies it by 6.',['The inner derivative is missing.','The exponent must remain $6x$.','Correct chain rule.','The inner derivative multiplies rather than divides.'],r('1(a)'),'diff(exp(6*x),x)',['exp(6*x)','6*exp(x)','6*exp(6*x)','exp(6*x)/6']),
 q(8,2,'Write down the derivative of $y=e^{-342x}$.',['$342e^{-342x}$','$e^{-342x}$','$-342e^x$','$-342e^{-342x}$'],3,'The inner derivative is $-342$, so $dy/dx=-342e^{-342x}$.',['The sign of the inner derivative is negative.','The inner derivative is missing.','The original exponent must remain unchanged.','Correct; the derivative is negative.'],r('1(b)'),'diff(exp(-342*x),x)',['342*exp(-342*x)','exp(-342*x)','-342*exp(x)','-342*exp(-342*x)']),
 q(8,3,'Write down the derivative of $y=\\ln(3x)$, where $x>0$.',['$1/x$','$3/x$','$1/(3x)$','$\\ln3$'],0,'$dy/dx=(1/(3x))(3)=1/x$. The domain ensures a positive logarithm argument.',['Correct: the factor 3 cancels.','The inner factor was included twice.','The inner derivative 3 is missing.','The logarithm does not differentiate to a constant.'],r('3(a)'),'diff(log(3*x),x)',['1/x','3/x','1/(3*x)','log(3)']),
 q(8,4,'Write down the derivative of $y=2e^{-x}+4e^x$.',['$2e^{-x}+4e^x$','$-2e^{-x}+4e^x$','$-2e^{-x}-4e^x$','$-e^{-x}+e^x$'],1,'Differentiate each term. The derivative of $e^{-x}$ introduces a negative sign, giving $-2e^{-x}+4e^x$.',['The derivative of $-x$ is missing.','Correct sum and chain rules.','The increasing exponential has a positive derivative.','The constant multipliers must be retained.'],r('1(c)'),'diff(2*exp(-x)+4*exp(x),x)',['2*exp(-x)+4*exp(x)','-2*exp(-x)+4*exp(x)','-2*exp(-x)-4*exp(x)','-exp(-x)+exp(x)']),
 q(8,5,'Write down the derivative of $y=10e^{4x}-2x^2+7$.',['$10e^{4x}-4x$','$40e^{4x}-4x+7$','$40e^{4x}-4x$','$40e^x-4x$'],2,'The chain rule gives $40e^{4x}$; the polynomial gives $-4x$; the constant gives zero.',['The inner derivative 4 is missing.','The constant 7 contributes zero.','Correct derivative of every term.','The exponential must retain the exponent $4x$.'],r('1(d)'),'diff(10*exp(4*x)-2*x**2+7,x)',['10*exp(4*x)-4*x','40*exp(4*x)-4*x+7','40*exp(4*x)-4*x','40*exp(x)-4*x']),
 q(8,6,'Write down the derivative of $y=\\ln(-13x)$, where $x<0$.',['$-13/x$','$-1/x$','$1/(-13x)$','$1/x$'],3,'$dy/dx=(-13)/(-13x)=1/x$. This is negative on the stated domain $x<0$.',['The inner coefficient cancels rather than remains.','The two minus signs in the chain rule cancel.','The inner derivative is missing.','Correct expression and domain.'],r('3(b)'),'diff(log(-13*x),x)',['-13/x','-1/x','1/(-13*x)','1/x']),
 q(8,7,`${bank} Write down an expression for $dS/dt$ and hence find the exact value of the rate of growth after five years.`,['$160e^{0.2}$','$4000e^{0.2}$','$0.04e^{0.2}$','$160e^{0.04}$'],0,'$dS/dt=160e^{0.04t}$. At $t=5$, the instantaneous rate is $160e^{0.2}\\approx195.42$ dollars/year.',['Correct instantaneous rate in dollars per year.','This is the balance, not its rate.','The principal 4000 was omitted.','The time 5 was not substituted into the exponent.'],r('2(2)','Question introduction repeated with dollar notation written as USD; exact requested quantity selected.'),'diff(4000*exp(Rational(1,25)*t),t).subs(t,5)',['160*exp(Rational(1,5))','4000*exp(Rational(1,5))','Rational(1,25)*exp(Rational(1,5))','160*exp(Rational(1,25))']),
 q(8,8,`${bank} Calculate $S$ at $t=5$ and $t=5.01$ and hence estimate the rate of growth at $t=5$. Use unrounded intermediate balances; round the rate to two decimal places.`,['$1.95$','$195.46$','$195.42$','$4885.61$'],1,'The finite-interval estimate is $[4000e^{0.04(5.01)}-4000e^{0.04(5)}]/0.01\\approx195.46$ dollars/year. This differs slightly from the tangent rate 195.42.',['This is approximately the balance increment, not its rate.','Correct finite difference using unrounded balances.','This is the instantaneous derivative, not the finite-interval estimate.','This is the initial balance, not a rate.'],r('2(1)(a)–(b) and hence','Introduction and times retained; dollar notation written as USD; unrounded intermediate-value convention added to avoid premature-rounding error.'),'round((4000*exp(Rational(1,25)*Rational(501,100))-4000*exp(Rational(1,25)*5))/Rational(1,100),2)',['1.95','195.46','195.42','4885.61']),
 q(8,9,'Use the product rule to differentiate $y=x\\ln x$. Assume $x>0$.',['$1$','$x+\\ln x$','$\\ln x+1$','$\\ln x+1/x$'],2,'The derivative is $(1)(\\ln x)+x(1/x)=\\ln x+1$, for $x>0$.',['This multiplies the derivatives rather than applying the product rule.','The derivative of $\\ln x$ is $1/x$.','Correct; both product-rule terms are included.','The second term must also include the factor $x$.'],r('5(b)','Positive-domain condition made explicit.'),'diff(x*log(x),x)',['1','x+log(x)','log(x)+1','log(x)+1/x']),
 q(8,10,'Use the chain rule to differentiate $y=\\ln(x^4+3x^2)$. Assume $x\\ne0$.',['$1/(x^4+3x^2)$','$4x^3+6x$','$1/x$','$\\frac{4x^3+6x}{x^4+3x^2}$'],3,'Differentiate the inner polynomial and divide by its value: $(4x^3+6x)/(x^4+3x^2)$. Since $x^2(x^2+3)>0$ exactly when $x\\ne0$, this is the real domain.',['The inner derivative is missing.','The outer logarithm derivative is missing.','The inner expression is not simply a constant times $x$.','Correct chain rule and domain.'],r('4(b)','Real logarithm domain made explicit.'),'diff(log(x**4+3*x**2),x)',['1/(x**4+3*x**2)','4*x**3+6*x','1/x','(4*x**3+6*x)/(x**4+3*x**2)']),
]);
