import { pack, question as q, source as s } from './authoring.js';
export const practice14 = pack(14, 'Definite integrals, area and accumulation', [
 q(14,1,'Evaluate the definite integral $\\int_0^2 x^3\\,dx$.',['$4$','$8$','$16$','$0$'],0,'An antiderivative is $x^4/4$. Evaluate the endpoints: $(2^4-0^4)/4=4$.',['Correct: integrate and subtract endpoint values.','This is the function value at the upper endpoint.','The factor $1/4$ is missing.','The lower endpoint contributes zero, but the upper endpoint does not.'],s('6.2','Exercise 6.2','3(a)',509),'integrate(x**3,(x,0,2))',['4','8','16','0']),
 q(14,2,'Evaluate the definite integral $\\int_{-2}^2 x^3\\,dx$.',['$8$','$0$','$4$','$-8$'],1,'$[x^4/4]_{-2}^2=4-4=0$. The negative and positive signed contributions cancel.',['This is geometric area, not signed integral.','Correct: symmetry gives cancellation.','This counts only the positive half.','The signed contributions cancel rather than add negatively.'],s('6.2','Exercise 6.2','3(b)',509),'integrate(x**3,(x,-2,2))',['8','0','4','-8']),
 q(14,3,'Find the exact area under the curve $y=(x-2)^2$ between $x=2$ and $x=3$.',['$1$','$3$','$\\frac13$','$0$'],2,'$y\\ge0$ on this interval. The area is $[(x-2)^3/3]_2^3=1/3$.',['This is a unit-width rectangle at the maximum height.','The power-rule divisor is applied incorrectly.','Correct: use the antiderivative and both endpoints.','Only the lower endpoint has zero height.'],s('6.2','Exercise 6.2','2(b)',509),'integrate((x-2)**2,(x,2,3))',['1','3','1/3','0']),
 q(14,4,'Evaluate the integral $\\int_1^3 4x^2\\,dx$.',['$36$','$108$','$\\frac{26}{3}$','$\\frac{104}{3}$'],3,'$[4x^3/3]_1^3=(4/3)(27-1)=104/3$.',['This is the integrand at 3.','This omits the power-rule divisor and the lower endpoint contribution.','This omits the coefficient 4.','Correct: subtract both endpoint values of the antiderivative.'],s('6.2','Exercise 6.2','1(a)',509),'integrate(4*x**2,(x,1,3))',['36','108','26/3','104/3']),
 q(14,5,'Evaluate the integral $\\int_1^2 (4x^3-3x^2+4x+2)\\,dx$.',['$16$','$20$','$12$','$-16$'],0,'An antiderivative is $F(x)=x^4-x^3+2x^2+2x$. Since $F(2)=20$ and $F(1)=4$, the integral is 16.',['Correct: $20-4=16$.','This omits the lower endpoint.','The linear and constant terms were not integrated correctly.','The endpoint order was reversed.'],s('6.2','Exercise 6.2','1(d)',509),'integrate(4*x**3-3*x**2+4*x+2,(x,1,2))',['16','20','12','-16']),
 q(14,6,'Evaluate the integral $\\int_{-1}^2 (5x^2-4x+6)\\,dx$.',['$\\frac{23}{3}$','$27$','$\\frac{52}{3}$','$-27$'],1,'$F(x)=5x^3/3-2x^2+6x$. Then $F(2)=52/3$ and $F(-1)=-29/3$, giving $81/3=27$.',['This adds the endpoint values instead of subtracting.','Correct: subtracting the negative lower value increases the result.','This ignores the lower endpoint.','The limits were reversed.'],s('6.2','Exercise 6.2*','1(a)',510),'integrate(5*x**2-4*x+6,(x,-1,2))',['23/3','27','52/3','-27']),
 q(14,7,'Find the exact area under the curve $y=2x^2+x+3$ between $x=1$ and $x=5$.',['$\\frac{320}{3}$','$\\frac{334}{3}$','$\\frac{248}{3}$','$53$'],0,'Integrate each term: $F(x)=2x^3/3+x^2/2+3x$. The difference is $248/3+12+12=320/3$. The curve is positive throughout.',['Correct: all three terms and both endpoints are included.','The lower endpoint was not subtracted correctly.','This integrates only the quadratic term.','This is the upper endpoint height, not an area.'],s('6.2','Exercise 6.2','2(a)',509),'integrate(2*x**2+x+3,(x,1,5))',['320/3','334/3','248/3','53']),
 q(14,8,'Write down an expression for $g\u2032(x)$ when $g(x)=\\int_2^x(5t^2-2t)\\,dt$.',['$10x-2$','$5x^2-2x-16$','$5x^2-2x$','$\\frac53x^3-x^2$'],2,'The fundamental theorem gives $g\u2032(x)=5x^2-2x$. The fixed lower endpoint contributes a constant whose derivative is zero.',['This differentiates the integrand instead of the accumulated function.','The lower endpoint constant should disappear on differentiation.','Correct: evaluate the integrand at the upper variable endpoint.','This is an antiderivative rather than the requested derivative.'],s('6.2','Exercise 6.2*','10',511),'5*x**2-2*x',['10*x-2','5*x**2-2*x-16','5*x**2-2*x','Rational(5,3)*x**3-x**2']),
 q(14,9,'What is the actual area between the x axis and the graph of $y=x^3$, over the range $-2\\le x\\le2$?',['$0$','$4$','$-8$','$8$'],3,'Geometric area counts both halves positively: $-\\int_{-2}^0x^3dx+\\int_0^2x^3dx=4+4=8$.',['This is the signed integral, not the geometric area.','This counts only one half.','Geometric area cannot be negative.','Correct: add the two positive areas.'],s('6.2','Exercise 6.2','3, final follow-up',509,'Original follow-up retained; explicit range replaces “over this range” from the preceding part.'),'integrate(-x**3,(x,-2,0))+integrate(x**3,(x,0,2))',['0','4','-8','8'],{coefficients:[0,0,0,1],xMin:-2,xMax:2,yMin:-8,yMax:8,xLabel:'x',yLabel:'y',caption:'Redrawn graph of y = x³ on [−2, 2].'}),
 q(14,10,'Evaluate the integral $\\int_2^3\\frac{2}{x^3}\\,dx$.',['$-\\frac{5}{36}$','$\\frac{1}{9}$','$\\frac{5}{36}$','$\\frac{19}{2}$'],2,'Write the integrand as $2x^{-3}$. Its antiderivative is $-x^{-2}$. Evaluate $-1/9-(-1/4)=5/36$; the interval avoids $x=0$.',['The endpoint order was reversed.','This uses only one endpoint and loses the sign.','Correct: subtract both values of $-x^{-2}$.','This integrates a different positive power.'],s('6.2','Exercise 6.2','1(b)',509),'integrate(2/x**3,(x,2,3))',['-5/36','1/9','5/36','19/2']),
]);
