import { pack, question as q, source as s } from './authoring.js';
export const practice13 = pack(13, 'Antiderivatives and recovering totals', [
 q(13,1,'Find $\\int6x^5\\,dx$.',['$6x^6+C$','$x^6+C$','$30x^4+C$','$x^5+C$'],1,'The power rule gives $6x^6/6+C=x^6+C$. Differentiate the result to check it.',['The new exponent must also divide the coefficient.','Correct: the factor 6 cancels the new exponent.','This differentiates instead of integrating.','The exponent must increase by 1.'],s('6.1','Exercise 6.1','1(a)',496),'integrate(6*x**5,x)',['6*x**6','x**6','30*x**4','x**5']),
 q(13,2,'Find $\\int x^4\\,dx$.',['$4x^3+C$','$x^5+C$','$x^5/5+C$','$x^4/4+C$'],2,'Increase the exponent to 5 and divide by 5. The constant $C$ represents all antiderivatives.',['This differentiates rather than integrates.','This omits division by the new exponent.','Correct: differentiating $x^5/5$ gives $x^4$.','The exponent was not increased.'],s('6.1','Exercise 6.1','1(b)',496),'integrate(x**4,x)',['4*x**3','x**5','x**5/5','x**4/4']),
 q(13,3,'Find $\\int(2x^3-6x)\\,dx$.',['$2x^4-6x^2+C$','$6x^2-6+C$','$x^4/2-6x^2+C$','$x^4/2-3x^2+C$'],3,'Integrate each term: $2x^4/4-6x^2/2+C=x^4/2-3x^2+C$.',['Both new exponents need to divide their coefficients.','This is the derivative of the integrand.','The second term must be divided by 2.','Correct: integrate both terms and include one constant.'],s('6.1','Exercise 6.1','1(f)',496),'integrate(2*x**3-6*x,x)',['2*x**4-6*x**2','6*x**2-6','x**4/2-6*x**2','x**4/2-3*x**2']),
 q(13,4,'Find $\\int(x^2-8x+3)\\,dx$.',['$x^3/3-4x^2+3x+C$','$x^3-8x^2+3x+C$','$x^3/3-4x^2+3+C$','$2x-8+C$'],0,'Integrate term by term: $x^3/3-8x^2/2+3x+C$. A constant integrand contributes a linear term.',['Correct: all three terms are integrated.','The first two new exponent divisors are missing.','The constant integrand 3 integrates to $3x$.','This differentiates the original expression.'],s('6.1','Exercise 6.1','1(g)',496),'integrate(x**2-8*x+3,x)',['x**3/3-4*x**2+3*x','x**3-8*x**2+3*x','x**3/3-4*x**2+3','2*x-8']),
 q(13,5,'Find $\\int(ax+b)\\,dx$, where $a$ and $b$ are constants.',['$ax^2+bx+C$','$ax^2/2+bx+C$','$ax^2/2+b+C$','$a+C$'],1,'Treat $a$ and $b$ as constants. The result is $ax^2/2+bx+C$. Differentiating gives $ax+b$.',['The quadratic term needs a divisor 2.','Correct: integrate the linear and constant terms separately.','The constant term integrates to $bx$.','This differentiates the integrand.'],s('6.1','Exercise 6.1','1(h)',496),'integrate(a*x+b,x)',['a*x**2+b*x','a*x**2/2+b*x','a*x**2/2+b','a']),
 q(13,6,'Find total cost if marginal cost is $MC=Q+5$ and fixed costs are 20.',['$Q+25$','$Q^2/2+5Q$','$Q^2/2+5Q+20$','$Q^2+5Q+20$'],2,'Integrate $MC$: $TC=Q^2/2+5Q+C$. Fixed cost gives $TC(0)=C=20$.',['This has not integrated marginal cost.','This leaves out fixed cost.','Correct: recover the total and use the initial condition.','The quadratic term needs a divisor 2.'],s('6.1','Exercise 6.1','2(a)',496),'integrate(Q+5,Q)+20',['Q+25','Q**2/2+5*Q','Q**2/2+5*Q+20','Q**2+5*Q+20']),
 q(13,7,'Marginal cost is $MC=2Q+6$. Total cost is 212 when $Q=8$. Find total cost when $Q=14$.',['$280$','$416$','$28$','$380$'],3,'$TC=Q^2+6Q+C$. At 8, $64+48+C=212$, so $C=100$. At 14, total cost is $196+84+100=380$.',['This omits the constant determined by the initial condition.','This adds 212 to the indefinite integral without adjusting for its value at 8.','This is the quadratic contribution to the derivative at 14, not total cost.','Correct: recover the constant before evaluating the new output.'],s('6.1','Exercise 6.1','3',496),'(Q**2+6*Q+(212-(8**2+6*8))).subs(Q,14)',['280','416','28','380']),
 q(13,8,'Find the total revenue and demand functions corresponding to $MR=20-2Q$. Use $TR(0)=0$ and $Q>0$ for the demand function. Choose $(TR,P)$.',['$(20Q-Q^2,20-Q)$','$(20Q-Q^2,20-2Q)$','$(20-2Q,20/Q-2)$','$(20Q-2Q^2,20-2Q)$'],0,'Integrate: $TR=20Q-Q^2+C$. Zero sales imply zero revenue, so $C=0$. Divide by positive output: $P=TR/Q=20-Q$. For non-negative price, restrict to $0<Q\\le20$.',['Correct: integrate marginal revenue then divide by output.','The price is average revenue, not marginal revenue.','The marginal revenue was not integrated.','The quadratic integral coefficient is wrong.'],s('6.1','Exercise 6.1','4(a)',496,'Original MR retained; zero-sales revenue condition, positive-output domain and ordered-pair instruction made explicit.'),'Tuple(integrate(20-2*Q,Q),simplify(integrate(20-2*Q,Q)/Q))',['Tuple(20*Q-Q**2,20-Q)','Tuple(20*Q-Q**2,20-2*Q)','Tuple(20-2*Q,20/Q-2)','Tuple(20*Q-2*Q**2,20-2*Q)']),
 q(13,9,'Find the consumption function if the marginal propensity to consume is 0.6 and consumption is 10 when income is 5. Deduce the savings function. Choose $(C(Y),S(Y))$.',['$(0.6Y+10,0.4Y-10)$','$(0.6Y+7,0.4Y-7)$','$(0.6Y+7,0.4Y+7)$','$(0.6Y,0.4Y)$'],1,'$C(Y)=0.6Y+k$. From $C(5)=10$, $k=7$. Savings are $Y-C(Y)=0.4Y-7$. Negative savings at low income represent dissaving in this model.',['The observed consumption is not the integration constant.','Correct: use the observation and then subtract consumption from income.','The consumption constant must be subtracted in savings.','This omits the nonzero intercept required by the observation.'],s('6.1','Exercise 6.1','5',496,'Original data retained; ordered-pair instruction added.'),'Tuple(Rational(3,5)*Y+10-Rational(3,5)*5,Y-(Rational(3,5)*Y+10-Rational(3,5)*5))',['Tuple(Rational(3,5)*Y+10,Rational(2,5)*Y-10)','Tuple(Rational(3,5)*Y+7,Rational(2,5)*Y-7)','Tuple(Rational(3,5)*Y+7,Rational(2,5)*Y+7)','Tuple(Rational(3,5)*Y,Rational(2,5)*Y)']),
 q(13,10,'Differentiate $F(x)=(2x+1)^5$. Hence find $\\int(2x+1)^4\\,dx$.',['$(2x+1)^5/5+C$','$2(2x+1)^5/5+C$','$(2x+1)^5/10+C$','$8(2x+1)^3+C$'],2,'$F\u2032(x)=10(2x+1)^4$ by the chain rule. Therefore the antiderivative is $F(x)/10+C$. Check by differentiation.',['This omits the inner derivative factor 2.','The inner factor should divide the antiderivative, not multiply it.','Correct: divide by the full derivative coefficient 10.','This differentiates the integrand instead of integrating.'],s('6.1','Exercise 6.1','8(1)',496),'diff((2*x+1)**5/10,x)',['diff((2*x+1)**5/5,x)','diff(2*(2*x+1)**5/5,x)','diff((2*x+1)**5/10,x)','diff(8*(2*x+1)**3,x)']),
]);
