import {pack,question as q,source as s} from './authoring.js';
const r=(part:string,adaptation?:string)=>s('4.2','Exercise 4.2',part,286,adaptation);
export const practice06=pack(6,'Power, constant, sum and difference rules',[
 q(6,1,'Differentiate $y=5x^2$.',['$5x$','$10x^2$','$10x$','$x^2$'],2,'$dy/dx=5(2x)=10x$.',['The power-rule factor 2 is missing.','The power was not reduced.','Correct constant multiple and power rules.','Neither the coefficient nor the power was differentiated.'],r('1(a)'),'diff(5*x**2,x)',['5*x','10*x**2','10*x','x**2']),
 q(6,2,'Differentiate $y=2x+3$.',['$2x$','$5$','$3$','$2$'],3,'The derivative of $2x$ is 2; the derivative of the constant 3 is zero.',['The derivative of $x$ is 1.','The constant term contributes no derivative.','This is the intercept, not the slope.','Correct constant slope.'],r('1(c)'),'diff(2*x+3,x)',['2*x','5','3','2']),
 q(6,3,'Differentiate $y=ax+b$, treating $a$ and $b$ as constants.',['$a$','$b$','$a+b$','$ax$'],0,'$dy/dx=a(1)+0=a$.',['Correct: the coefficient of $x$ is the derivative.','This is the intercept.','The constant $b$ differentiates to zero.','The variable $x$ should disappear.'],r('1(h)','Constant-parameter condition made explicit.'),'diff(a*x+b,x)',['a','b','a+b','a*x']),
 q(6,4,'Differentiate $y=x^2+x+1$.',['$2x+2$','$2x+1$','$x+1$','$2x$'],1,'Apply the sum rule: $dy/dx=2x+1+0$.',['The constant 1 was incorrectly differentiated to 1.','Correct derivative of each term.','The power-rule multiplier 2 is missing.','The derivative of the linear term is missing.'],r('1(d)'),'diff(x**2+x+1,x)',['2*x+2','2*x+1','x+1','2*x']),
 q(6,5,'Differentiate $y=x^2-3x+2$.',['$2x+3$','$2x-1$','$2x-3$','$x^2-3$'],2,'$dy/dx=2x-3$. The constant 2 contributes zero.',['The subtraction sign was lost.','The constant was incorrectly retained as a derivative.','Correct sum and difference rules.','The quadratic term has not been differentiated.'],r('1(e)'),'diff(x**2-3*x+2,x)',['2*x+3','2*x-1','2*x-3','x**2-3']),
 q(6,6,'Differentiate $y=2x^3-6x^2+49x-54$.',['$6x^2-6x+49$','$6x^2-12x-5$','$2x^2-6x+49$','$6x^2-12x+49$'],3,'Differentiate term by term: $6x^2-12x+49-0$.',['The factor 2 from the quadratic term is missing.','The constant $-54$ should contribute zero.','Power-rule coefficients are missing.','Correct derivative of all four terms.'],r('1(g)'),'diff(2*x**3-6*x**2+49*x-54,x)',['6*x**2-6*x+49','6*x**2-12*x-5','2*x**2-6*x+49','6*x**2-12*x+49']),
 q(6,7,'Evaluate $f\u2032(x)$ for $f(x)=3x^9$ at $x=1$.',['$27$','$3$','$9$','$0$'],0,'$f\u2032(x)=27x^8$, so the tangent slope at $x=1$ is 27.',['Correct: evaluate the derivative, not the function.','This is $f(1)$, not $f\u2032(1)$.','The constant coefficient 3 was omitted.','The graph is not horizontal at this point.'],r('2(a)'),'diff(3*x**9,x).subs(x,1)',['27','3','9','0']),
 q(6,8,'Evaluate $f\u2032(x)$ for $f(x)=x^2-2x$ at $x=3$.',['$3$','$4$','$6$','$-4$'],1,'$f\u2032(x)=2x-2$, giving a positive tangent slope of 4 at $x=3$.',['This is $f(3)$, not its slope.','Correct: the graph is rising at this point.','The derivative of $-2x$ was omitted.','The decreasing direction is incorrect here.'],r('2(b)'),'diff(x**2-2*x,x).subs(x,3)',['3','4','6','-4'],{coefficients:[0,-2,1],xMin:0,xMax:4,yMin:-2,yMax:9,xLabel:'x',yLabel:'f(x)',caption:'Redrawn graph of f(x) = x² − 2x.'}),
 q(6,9,'Evaluate $f\u2032(x)$ for $f(x)=x^3-4x^2+2x-8$ at $x=0$.',['$-8$','$0$','$2$','$-6$'],2,'$f\u2032(x)=3x^2-8x+2$. At $x=0$, the tangent slope is 2, though the function value is $-8$.',['This is the graph’s height at 0.','A zero input need not give a zero slope.','Correct: only the derivative’s constant term remains.','The original constant should disappear during differentiation.'],r('2(c)'),'diff(x**3-4*x**2+2*x-8,x).subs(x,0)',['-8','0','2','-6']),
 q(6,10,'Evaluate $f\u2032(x)$ for $f(x)=\\sqrt{x}-\\frac2x$ at $x=4$.',['$\\frac18$','$\\frac12$','$\\frac32$','$\\frac38$'],3,'For $x>0$, $f\u2032(x)=1/(2\\sqrt{x})+2/x^2$. At 4 this is $1/4+1/8=3/8$.',['The reciprocal term has the wrong sign.','The square-root derivative has an incorrect coefficient.','This is the function value $f(4)$, not the derivative.','Correct: both power-rule derivatives are included.'],r('2(e)'),'diff(sqrt(x)-2/x,x).subs(x,4)',['1/8','1/2','3/2','3/8']),
]);
