import {pack,question as q,source as s} from './authoring.js';
const r=(section:string,part:string,page:number,adaptation?:string)=>s(section,`Exercise ${section}`,part,page,adaptation);
export const practice02=pack(2,'Functions, lines and market equilibrium',[
 q(2,1,'If $f(x)=3x+15$, evaluate $f(2)$.',['$6$','$17$','$21$','$36$'],2,'$f(2)=3(2)+15=21$.',['The intercept 15 is missing.','This adds 2 to 15 without multiplying by 3.','Correct substitution.','This doubles the whole expression $3+15$.'],r('1.5','1(a)',80,'The relevant function is selected from the shared introduction; numerical values retained.'),'3*2+15',['6','17','21','36']),
 q(2,2,'If $f(x)=3x+15$, evaluate $f(0)$.',['$0$','$3$','$18$','$15$'],3,'At $x=0$, $f(0)=3(0)+15=15$, the vertical intercept.',['A zero input does not require a zero output.','This is the slope, not the intercept.','This substitutes 1 instead of 0.','Correct: only the constant term remains.'],r('1.5','1(c)',80,'The relevant function is selected from the shared introduction; numerical values retained.'),'3*0+15',['0','3','18','15']),
 q(2,3,'For the supply function $P=\\frac13Q+7$, determine $P$ when $Q=12$.',['$11$','$4$','$43$','$19$'],0,'$P=12/3+7=11$.',['Correct substitution.','This omits the intercept 7.','This uses a slope of 3 rather than $1/3$.','This uses a slope of 1.'],r('1.5','2(a)',80,'Supply function repeated from the question introduction; sketch instruction omitted.'),'12/3+7',['11','4','43','19']),
 q(2,4,'State the value of the slope and y intercept for the line $y=5x+9$.',['Slope 9; intercept 5','Slope 5; intercept 9','Slope −5; intercept 9','Slope 5; intercept −9'],1,'In $y=mx+b$, the coefficient of $x$ is the slope and the constant is the intercept: $(m,b)=(5,9)$.',['The two roles were reversed.','Correct slope–intercept reading.','The slope has the wrong sign.','The intercept has the wrong sign.'],r('1.3','7(a)',52),'Tuple(5,9)',['Tuple(9,5)','Tuple(5,9)','Tuple(-5,9)','Tuple(5,-9)']),
 q(2,5,'For the line $3x-5y=8$, find the value of $x$ when $y=2$.',['$-\\frac23$','$\\frac83$','$6$','$18$'],2,'$3x-10=8$, so $3x=18$ and $x=6$.',['This moves $-10$ with the wrong sign.','This ignores the specified value of $y$.','Correct: solve after substitution.','This stops at $3x=18$.'],r('1.3','4(a)',52),'(8+5*2)/3',['-2/3','8/3','6','18']),
 q(2,6,'A taxi firm charges a fixed cost of USD 4 plus a charge of USD 2.50 a mile. Write down a formula for the cost, $C$, of a journey of $x$ miles.',['$C=6.5x$','$C=4x+2.5$','$C=2.5x$','$C=4+2.5x$'],3,'The fixed charge is paid once; the distance charge is $2.5x$. Thus $C=4+2.5x$ dollars, for $x\\ge0$.',['This multiplies the fixed charge by every mile.','The fixed and per-mile charges have been interchanged.','The fixed charge is missing.','Correct: fixed plus variable cost.'],r('1.3','9(a)',52,'Question introduction repeated; dollar notation written as USD.'),'4+Rational(5,2)*x',['Rational(13,2)*x','4*x+Rational(5,2)','Rational(5,2)*x','4+Rational(5,2)*x']),
 q(2,7,'An airline charges USD 300 for a flight of 2000 km and USD 700 for a flight of 4000 km. Assuming a linear model, estimate the cost of a flight of 3200 km.',['$480$','$640$','$540$','$500$'],2,'Slope $=(700-300)/(4000-2000)=0.2$ dollars/km. Cost $=300+0.2(3200-2000)=540$ dollars.',['This assumes proportional pricing using only the first fare.','This omits the negative intercept.','Correct linear interpolation.','This takes the midpoint fare although 3200 is not the midpoint distance.'],r('1.3','2(b)(i)',52,'Question introduction repeated; dollar notation written as USD; selected subpart retained.'),'300+(700-300)/(4000-2000)*(3200-2000)',['480','640','540','500']),
 q(2,8,'A taxi firm charges a fixed cost of USD 4 plus a charge of USD 2.50 a mile. Hence, or otherwise, work out the distance of a journey which costs USD 24.',['8 miles','9.6 miles','10 miles','11.2 miles'],0,'Solve $4+2.5x=24$: $x=(24-4)/2.5=8$ miles.',['Correct: remove the fixed charge before dividing.','This treats all $24 as a distance charge.','This divides by 2 rather than 2.50.','This adds the fixed charge rather than subtracting it.'],r('1.3','9(c)',52,'Question introduction repeated; dollar notation written as USD; distance context from part (a) is implicit.'),'(24-4)/Rational(5,2)',['8','Rational(48,5)','10','Rational(56,5)']),
 q(2,9,'If the supply function is $Q=4P-25$, determine the lowest possible price that could be charged.',['$25$','$0$','$\\frac{25}{4}$','$\\frac4{25}$'],2,'Feasible quantity requires $Q\\ge0$. Thus $4P-25\\ge0$ and $P\\ge25/4$. The boundary price is $6.25$.',['This ignores the coefficient of $P$.','This gives a negative supplied quantity.','Correct: the minimum feasible price gives $Q=0$.','The division is reversed.'],s('1.5','Chapter 1 multiple choice','Question 3',112,'Stem retained; nonnegative supplied quantity is the textbook economic convention.','Original options A–D retained; original E omitted.'),'25/4',['25','0','25/4','4/25']),
 q(2,10,'The demand and supply functions of a good are given by $P=-3Q_D+75$ and $P=2Q_S+15$. Determine the equilibrium price.',['$39$','$12$','$60$','$15$'],0,'At equilibrium $Q_D=Q_S=Q$. Then $-3Q+75=2Q+15$, giving $Q=12$ and $P=39$.',['Correct: substitute the equilibrium quantity into either price equation.','This is the quantity, not the price.','This is the difference between intercepts.','This is the supply intercept, not the equilibrium.'],s('1.4–1.5','Chapter 1 multiple choice','Question 6',113,'Stem and values retained.','Original A–D retained; original E omitted.'),'2*(75-15)/(3+2)+15',['39','12','60','15']),
]);
