import {pack,question as q,source as s} from './authoring.js';
const r=(section:string,part:string,page:number,adaptation?:string)=>s(section,`Exercise ${section}`,part,page,adaptation);
export const practice04=pack(4,'Powers, logarithms and exponential growth',[
 q(4,1,'Without using your calculator, evaluate $8^2$.',['$16$','$64$','$10$','$256$'],1,'$8^2=8\\times8=64$.',['The exponent is not a multiplier.','Correct square.','The exponent is not an addend.','This uses $8^2$ incorrectly as $16^2$.'],r('2.3','1(1)(a)',168),'8**2',['16','64','10','256']),
 q(4,2,'Without using your calculator, evaluate $3^{-1}$.',['$-3$','$3$','$\\frac13$','$-\\frac13$'],2,'A negative exponent takes a reciprocal: $3^{-1}=1/3$.',['A negative exponent does not negate the base.','The reciprocal operation is missing.','Correct reciprocal.','The exponent does not introduce a minus sign into the value.'],r('2.3','1(1)(c)',168),'3**(-1)',['-3','3','1/3','-1/3']),
 q(4,3,'Without using your calculator, evaluate $36^{1/2}$.',['$18$','$72$','$1296$','$6$'],3,'The exponent $1/2$ gives the principal square root: $\\sqrt{36}=6$.',['This multiplies by $1/2$.','This doubles the base.','This squares rather than square-roots.','Correct principal square root.'],r('2.3','1(1)(f)',168),'sqrt(36)',['18','72','1296','6']),
 q(4,4,'Use the rules of indices to simplify $a^3\\times a^8$.',['$a^{11}$','$a^{24}$','$2a^{11}$','$a^5$'],0,'For a common base, multiply powers by adding exponents: $a^{3+8}=a^{11}$.',['Correct product rule for powers.','Exponents are multiplied when a power is raised to a power.','There is no extra coefficient 2.','Subtracting exponents would correspond to division.'],r('2.3','2(a)',168),'a**3*a**8',['a**11','a**24','2*a**11','a**5']),
 q(4,5,'Use the rules of logs to expand $\\ln(xy)$. Assume $x>0$ and $y>0$.',['$\\ln x\\,\\ln y$','$\\ln x+\\ln y$','$\\ln x-\\ln y$','$x+y$'],1,'For positive factors, $\\ln(xy)=\\ln x+\\ln y$.',['A log of a product becomes a sum, not a product of logs.','Correct logarithm rule.','A difference applies to a quotient.','The logarithms cannot be discarded.'],r('2.4','2(a)',183,'Positive-domain conditions added; textbook expression retained.'),'log(x)+log(y)',['log(x)*log(y)','log(x)+log(y)','log(x)-log(y)','x+y']),
 q(4,6,'Solve $e^x=5.9$. Round your answer to two decimal places.',['$5.90$','$0.59$','$1.77$','$-1.77$'],2,'Take natural logs: $x=\\ln5.9\\approx1.77495$, which rounds to 1.77.',['The right-hand side is not the exponent.','This divides rather than applies a logarithm.','Correct rounded logarithm.','Because 5.9 exceeds 1, the exponent is positive.'],r('2.4','4(a)',183),'round(log(Rational(59,10)),2)',['5.9','.59','1.77','-1.77']),
 q(4,7,'The number of items, $N$, produced each day by an assembly-line worker, $t$ days after an initial training period, is modelled by $N=100-100e^{-0.4t}$. Calculate the number of items produced daily 1 day after the training period. Choose the value to two decimal places.',['$67.03$','$100$','$40.00$','$32.97$'],3,'At $t=1$, $N=100(1-e^{-0.4})\\approx32.97$ items/day.',['This is the remaining gap to the limiting output.','The limiting output is not reached after one day.','This uses a linear approximation as an exact calculation.','Correct substitution and rounding.'],r('2.4','1(1)(a)',182,'Introduction repeated verbatim; two-decimal-place option convention added.'),'round(100-100*exp(-Rational(2,5)),2)',['67.03','100','40','32.97']),
 q(4,8,'For the worker model $N=100-100e^{-0.4t}$, what is the worker’s daily production in the long run?',['100 items/day','0 items/day','40 items/day','Unlimited growth'],0,'As $t\\to\\infty$, $e^{-0.4t}\\to0$, so $N\\to100$ items/day. The curve approaches this bound.',['Correct limiting production.','The exponential term vanishes, not the entire expression.','The rate parameter is not the output limit.','The model has a finite asymptote.'],r('2.4','1(2)',183,'Model from the introduction on printed p.182 / PDF p.199 repeated; original question retained.'),'100',['100','0','40','oo']),
 q(4,9,'Solve $\\ln x=0$. Which x intercept does this give for $y=\\ln x$?',['$x=0$','$x=1$','$x=e$','$x=-1$'],1,'Exponentiate: $x=e^0=1$. The logarithm requires $x>0$, and its graph crosses the x axis at $(1,0)$.',['The logarithm of zero is undefined.','Correct positive solution and x intercept.','$\\ln e=1$, not 0.','The real logarithm is undefined for a negative input.'],r('2.4','6(b)',183,'Original equation retained; equivalent x-intercept interpretation added.'),'exp(0)',['0','1','E','-1']),
 q(4,10,'Future sales of two products A and B are given by $S_A=5e^{0.01t}$ and $S_B=2e^{0.02t}$. Find the time, $t$, when sales of the two products are the same.',['$\\ln(2.5)$','$100\\ln(0.4)$','$100\\ln(2.5)$','$50\\ln(2.5)$'],2,'Divide by $2e^{0.01t}$: $2.5=e^{0.01t}$. Thus $t=100\\ln2.5\\approx91.63$, in the time units used by the model.',['This omits division by the growth-rate difference 0.01.','The ratio is reversed, giving a negative time.','Correct: use the difference between growth rates.','This uses the larger rate instead of the rate difference.'],r('2.4','7',183),'log(Rational(5,2))/Rational(1,100)',['log(Rational(5,2))','100*log(Rational(2,5))','100*log(Rational(5,2))','50*log(Rational(5,2))']),
]);
