import { pack, question as q, source as s } from './authoring.js';
export const practice05 = pack(5, 'From average slope to the derivative', [
 q(5,1,'Find the slope of the straight line passing through $(2,5)$ and $(4,9)$.',['$\\frac12$','$2$','$4$','$-2$'],1,'Slope $=(9-5)/(4-2)=4/2=2$.',['Rise and run were reversed.','Correct: vertical change divided by horizontal change.','This is the rise alone.','Only one subtraction was reversed.'],s('4.1','Exercise 4.1','1(a)',277),'(9-5)/(4-2)',['1/2','2','4','-2']),
 q(5,2,'Find the slope of the straight line passing through $(3,-1)$ and $(7,-5)$.',['$1$','$-4$','$-1$','$4$'],2,'Slope $=(-5-(-1))/(7-3)=-4/4=-1$.',['The decreasing direction was lost.','This is the vertical change alone.','Correct: the line falls by 4 as $x$ increases by 4.','This ignores the run and the negative direction.'],s('4.1','Exercise 4.1','1(b)',277),'(-5-(-1))/(7-3)',['1','-4','-1','4']),
 q(5,3,'Find the slope of the straight line passing through $(7,19)$ and $(4,19)$.',['Undefined','$-3$','$19$','$0$'],3,'Both points have the same height: $(19-19)/(4-7)=0/(-3)=0$.',['A zero rise is allowed; only a zero run makes the slope undefined.','This is the horizontal change alone.','A function value is not a slope.','Correct: the line is horizontal.'],s('4.1','Exercise 4.1','1(c)',277),'0',['oo','-3','19','0']),
 q(5,4,'Differentiate the function $f(x)=x^7$.',['$7x^6$','$x^6$','$7x^7$','$x^8/8$'],0,'The power rule gives $f\u2032(x)=7x^{7-1}=7x^6$.',['Correct: multiply by 7 and reduce the power by 1.','The factor 7 is missing.','The exponent was not reduced.','This is an antiderivative, not the derivative.'],s('4.1','Exercise 4.1','4, first instruction',277),'diff(x**7,x)',['7*x**6','x**6','7*x**7','x**8/8']),
 q(5,5,'Differentiate $y=x^8$.',['$8x^8$','$8x^7$','$x^7$','$x^9/9$'],1,'$dy/dx=8x^{8-1}=8x^7$.',['The exponent was not reduced.','Correct application of the power rule.','The multiplier 8 is missing.','This integrates instead of differentiating.'],s('4.1','Exercise 4.1','5(a)',277),'diff(x**8,x)',['8*x**8','8*x**7','x**7','x**9/9']),
 q(5,6,'Sketch the graph of the function $f(x)=5$. Explain why it follows from this that $f\u2032(x)=0$. Choose the explanation.',['The graph is vertical.','Its height is zero.','The graph is horizontal, so every tangent has zero slope.','Its slope is 5.'],2,'The graph has constant height 5; a change in $x$ produces no change in $f(x)$. Every tangent is horizontal.',['The graph of a constant function is horizontal.','Its height is 5; its slope, rather than its height, is zero.','Correct: the derivative measures slope, not height.','The function value 5 is not its derivative.'],s('4.1','Exercise 4.1','3',277,'Textbook instructions retained; “Choose the explanation” added for single-choice response.'),'2',['0','1','2','3'],{coefficients:[5],xMin:-2,xMax:2,yMin:0,yMax:7,xLabel:'x',yLabel:'f(x)',caption:'Redrawn graph of f(x) = 5.'}),
 q(5,7,'Differentiate the function $f(x)=x^7$. Hence calculate the slope of the graph of $y=x^7$ at the point $x=2$.',['$128$','$896$','$14$','$448$'],3,'$f\u2032(x)=7x^6$, so $f\u2032(2)=7(2^6)=448$.',['This is the function value $f(2)$, not its slope.','This uses $7(2^7)$ and fails to reduce the power.','This multiplies the coefficient by $x$ without evaluating $x^6$.','Correct: evaluate the derived function at 2.'],s('4.1','Exercise 4.1','4, hence instruction',277),'7*2**6',['128','896','14','448']),
 q(5,8,'For the function $f(x)=x^2-2x$, sketch the graph and, by measuring the slope of the tangents, estimate $f\u2032(1)$.',['$0$','$-1$','$2$','$1$'],0,'The tangent at the vertex $x=1$ is horizontal. Equivalently $f\u2032(1)=2(1)-2=0$.',['Correct: the tangent at the vertex is horizontal.','This is the function value $f(1)$, not its slope.','The derivative of $-2x$ was omitted.','This is the $x$ coordinate, not the tangent slope.'],s('4.1','Exercise 4.1','7(b)',277,'Function repeated from the question introduction; table-completion instruction omitted; graph redrawn.'),'2*1-2',['0','-1','2','1'],{coefficients:[0,-2,1],xMin:-1,xMax:3,yMin:-2,yMax:4,xLabel:'x',yLabel:'f(x)',caption:'Redrawn graph of f(x) = x² − 2x.'}),
 q(5,9,'For the graph $y=\\sqrt{x}$, A is the point where $x=4$, and B is the point where $x=4.1$. Find the gradient of the chord AB.',['$\\frac14$','$\\frac{\\sqrt{4.1}-2}{4.1}$','$\\frac{\\sqrt{4.1}-2}{0.1}$','$\\sqrt{0.1}$'],2,'The chord slope is the finite difference $(\\sqrt{4.1}-\\sqrt4)/(4.1-4)=(\\sqrt{4.1}-2)/0.1\\approx0.24846$. The tangent slope at A is 0.25; they are different.',['This is the tangent slope at A, not the chord slope.','The denominator must be the change in $x$, not the final $x$.','Correct: use both coordinate differences.','In general $\\sqrt b-\\sqrt a$ is not $\\sqrt{b-a}$.'],s('4.1','Exercise 4.1*','3(a)(ii)',278,'Selected graph and subpart; point definitions repeated verbatim from the shared introduction.'),'(sqrt(Rational(41,10))-2)/Rational(1,10)',['1/4','(sqrt(Rational(41,10))-2)/Rational(41,10)','(sqrt(Rational(41,10))-2)/Rational(1,10)','sqrt(Rational(1,10))']),
 q(5,10,'Find the coordinates of the point(s) at which the curve $y=x^5$ has gradient $405$.',['$(3,243)$ only','$(3,243)$ and $(-3,-243)$','$(81,81^5)$ only','$(3,405)$ and $(-3,405)$'],1,'$dy/dx=5x^4=405$, so $x^4=81$ and $x=\\pm3$. Substituting into $y=x^5$ gives $(3,243)$ and $(-3,-243)$.',['The negative solution also has positive gradient 405.','Correct: both real roots give valid points.','This does not take the fourth root of 81.','The gradient is not the $y$ coordinate.'],s('4.1','Exercise 4.1*','4(b)',278),'Tuple(Tuple(3,243),Tuple(-3,-243))',['Tuple(Tuple(3,243))','Tuple(Tuple(3,243),Tuple(-3,-243))','Tuple(Tuple(81,81**5))','Tuple(Tuple(3,405),Tuple(-3,405))']),
]);
