import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import katex from '../apps/teacher-web/node_modules/katex/dist/katex.mjs';
import {INTERNATIONAL_MATHEMATICS_DEFINITIONS as lessons,INTERNATIONAL_MATHEMATICS_SLIDES as slides,INTERNATIONAL_MATHEMATICS_V1_PAGE_MAP as migration,resolveInternationalMathematicsSavedPosition as restore} from '../packages/course-content/src/international-mathematics/index.js';
import {CORE_TARGETS} from '../packages/course-content/src/international-mathematics/v2/index.js';
const pilot=process.argv.includes('--pilot'),selected=pilot?lessons.filter(l=>[1,5,14].includes(l.number)):lessons;let formulas=0;
for(const l of selected){const core=l.slides.filter(s=>!s.optionalChallenge);assert.equal(core.length,CORE_TARGETS[l.number-1],l.title);assert.equal(l.slides.filter(s=>s.optionalChallenge).length,2);assert.equal(l.hours?.length,2);
 const sequences=new Map<string,number>();for(const s of core){if(s.pedagogy?.sequence)sequences.set(s.pedagogy.sequence,(sequences.get(s.pedagogy.sequence)??0)+1);}assert.ok([...sequences.values()].filter(n=>n>=3).length>=3,`Lesson ${l.number} needs three developed examples`);
 assert.ok(core.filter(s=>s.pedagogy?.role==='checkpoint').length>=4,`Lesson ${l.number}: checkpoints`);assert.ok(core.filter(s=>s.pedagogy?.role==='misconception').length>=2,`Lesson ${l.number}: misconceptions`);assert.ok(core.some(s=>s.pedagogy?.role==='exit'),`Lesson ${l.number}: exit`);
 for(const h of l.hours!){const block=core.filter(s=>s.pedagogy?.hour===h.number);assert.equal(block.length,CORE_TARGETS[l.number-1]!/2);assert.equal(block.reduce((n,s)=>n+s.pedagogy!.seconds!,0),2700);assert.ok(block.length>=36&&block.length<=45);}
 for(const s of l.slides){for(const e of s.elements){assert.ok(e.x>=0&&e.y>=0&&e.x+e.w<=1600&&e.y+e.h<=850,`${s.slideKey} bounds`);if(e.kind==='math'){katex.renderToString(e.tex,{throwOnError:true,strict:'ignore'});formulas++;} const publicText=e.kind==='text'?e.text:e.kind==='table'?[...e.columns,...e.rows.flat()].join(' '):e.kind==='diagram'?e.labels.join(' '):'';assert.ok(!/[\u4e00-\u9fff]/.test(publicText),`${s.slideKey} non-English`);}assert.equal(s.source.pdfPages[0],s.source.printedPages[0]+17);}
}
assert.equal(new Set(slides.map(s=>s.slideKey)).size,slides.length);assert.equal(new Set(slides.map(s=>s.compositionId)).size,slides.length);assert.equal(migration.length,416);for(const p of migration){assert.equal(restore('release-international-mathematics-jacques-v1',p.v1Index)?.slideKey,p.slideKey);assert.equal(restore('release-international-mathematics-jacques-v1',p.v1Index,p.slideKey)?.index,p.v2Index);}
if(!pilot){assert.equal(slides.length,1312);assert.equal(slides.filter(s=>!s.optionalChallenge).length,1280);assert.equal(lessons.reduce((n,l)=>n+l.exercises.filter(e=>!e.optional).length,0),96);}
const output=path.resolve(process.env.IM_OUTPUT_ROOT||'output/international-mathematics/v2/qa');fs.mkdirSync(output,{recursive:true});const report={status:'passed',pilot,lessons:selected.map(l=>({number:l.number,pages:l.slides.length,hours:l.hours?.map(h=>({number:h.number,pages:h.coreSlides,first:l.slides[h.localStart-1]!.title,last:l.slides[h.localEnd-1]!.title}))})),formulas,legacyMappings:migration.length,studentMetadata:'Teacher planning fields are kept in source only.'};fs.writeFileSync(path.join(output,pilot?'pilot-content.json':'content-validation.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
