import assert from 'node:assert/strict';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { createCapacityRun, advanceCapacityRun, capacityView, serializeCapacityRun, restoreCapacityRun, PORT_CAPACITY_PLANS, type PortCapacityPlan } from '../packages/port-simulation-core/src/port-capacity.js';

const root = new URL('../', import.meta.url), out = new URL('output/port-lesson-five-evidence/', root);
await mkdir(out, {recursive:true});
const evidence = {} as Record<PortCapacityPlan, ReturnType<typeof capacityView>>;
const manifests=[];
const sourceFiles=await Promise.all(['packages/port-simulation-core/src/port-capacity.ts','packages/port-simulation-core/src/port-course.ts','packages/port-simulation-core/src/port-operations-engine.ts','packages/port-simulation-core/src/port-operations-model.ts'].map(async path=>({path,sha256:createHash('sha256').update(await readFile(new URL(path,root))).digest('hex')})));
for (const plan of Object.keys(PORT_CAPACITY_PLANS) as PortCapacityPlan[]) {
  const run=createCapacityRun(plan);
  advanceCapacityRun(run,86400);
  assert.ok(run.complete,plan);
  const raw=serializeCapacityRun(run), view=capacityView(run);
  assert.deepEqual(capacityView(restoreCapacityRun(raw)),view);
  evidence[plan]=view;
  await writeFile(new URL(`${plan}.json`,out),raw);
  manifests.push({plan,elapsed:view.elapsed,sha256:createHash('sha256').update(raw).digest('hex')});
}
assert.deepEqual(Object.values(evidence).map(v=>v.elapsed),[46130,46900,23628,14550,14550]);
const compact=Object.fromEntries(Object.entries(evidence).map(([id,v])=>[id,{...v,samples:v.samples.filter(s=>s.elapsed%300===0||[3600,7200,14400,v.elapsed].includes(s.elapsed))}]));
await writeFile(new URL('packages/course-content/src/port-lesson-five-evidence.ts',root),`// Generated by scripts/port-lesson-five-evidence.mts; do not hand-edit.\nexport const PORT_LESSON_FIVE_EVIDENCE = ${JSON.stringify(compact)} as const;\n`);
await writeFile(new URL('manifest.json',out),JSON.stringify({version:'port-capacity/1.0',engine:'port-operations/3.1',seed:20260932,startSecond:9209,sourceFiles,manifests},null,2));
console.log(JSON.stringify(manifests,null,2));
