import {writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {PORT_EXPANSION_SLIDES as pages,PORT_EXPANSION_SOURCES as sources,expansionTiming,EXPANSION_TITLES} from '../packages/course-content/src/port-expansion.js';
const folder=fileURLToPath(new URL('../docs/course/',import.meta.url));await mkdir(folder,{recursive:true});
for(const lesson of [7,8] as const){let minutes=0;const timing=expansionTiming(lesson);const lines=[`# 港口管理概论 · 第${lesson}讲教师讲稿`,``,`主题：${EXPANSION_TITLES[lesson]}。48页，90分钟，45＋45分钟。第24页后课间。`,``,`教师主导逐步展开与情境比较，个人口头或纸面判断，无分组和个人仿真提交。`,``,`## 节奏`,``,`| 时间 | 页码 | 内容 |`,`|---|---|---|`,...timing.map(t=>{const start=minutes;minutes+=t.minutes;return `| ${start}—${minutes}分钟 | ${t.slideStart-(lesson===7?293:341)}—${t.slideEnd-(lesson===7?293:341)} | ${t.label} |`;}),``];
 for(const p of pages.filter(p=>p.lesson===lesson))lines.push(`## ${String(p.localPage).padStart(2,'0')}　${p.title}`,``,p.lead,``,`**本页讲授与操作**`, ``,p.teachingCue,``,`**投影要点**`, ``,...p.points.map(t=>`- ${t}`),``,...(p.options?[`**演示选项：** ${p.options.join('；')}`,``]:[]),...(p.reveal?[`**教师参考解析（受控揭示）：** ${p.reveal}`,``]:[]),`**来源：** [${sources[p.source].label}](${sources[p.source].url}) · ${sources[p.source].date}`,``,`**助手边界：** ${p.assistantCue}`,``);
 await writeFile(folder+`port-management-lesson-${lesson===7?'seven':'eight'}-teacher.md`,lines.join('\n'));
}
const lines=['# 第7—8讲来源台账','','访问复核日期：2026-09-21。以下“用于”由本课程归纳，不能扩大来源的证明范围。','','| 编号 | 来源 | 日期 | 用于页面 | 证据边界 |','|---|---|---|---|---|',...Object.entries(sources).map(([id,s])=>`| ${id} | [${s.label}](${s.url}) | ${s.date} | ${pages.filter(p=>p.source===id).map(p=>`${p.lesson}-${p.localPage}`).join('、')} | ${s.boundary} |`),'','## 素材边界','','场景图复用现有 `course-assets/port-management` 教学复原素材；新SVG由课程代码绘制。素材呈现环境与关系，不作为某港现场、当前设备状态或施工完成证据。课堂算例由本课程独立编制，未宣称来自公开港口统计。','','## 图形与数量口径','','- 散货串联能力：输入均为同货种吨/小时，忽略波动和新增缓冲，只求固定串联系统持续能力。','- 冷藏箱：空位与可用插座为同一时点，20只箱每箱需独立插座，其他条件固定满足。','- 规划规模：使用同货种万实体吨/年，需求、有效能力和实际产出分别解释。','- 分期比较：两期各一年；费用为教学资金单位，不贴现，不计收益和运营成本；扩建时间简化在第8讲第40页明确修正。','- 地图：候选区位及旧仓库全部为虚构空间，不按比例，不表达真实地块许可。','- 代际：PEMP整理的研究框架，不作为国家标准、认证或排行。',''];
await writeFile(folder+'port-management-lessons-seven-eight-sources.md',lines.join('\n'));console.log('Authored teacher notes and source ledger exported.');
